ROX-16734: Reconcile Central Audit log notifier configuration
stackrox/acs-fleet-manager pull request #1041
Opened 2023-05-19 20:33 UTC by rhybrillou

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-05-19 20:34 UTC, rhybrillou commented
Current dependencies on/for this PR:
* main
  * **PR #1040** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1040" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1041** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1041" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1041?utm_source=stack-comment).

2023-07-06 11:32 UTC, rhybrillou commented
/test all

2023-07-07 07:42 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	"gopkg.in/yaml.v2"
IDE autocompletion. Other files in the repo import v2.
I'll upgrade to v3.

2023-07-12 07:45 UTC, SimonBaeumer requested changes
Can you add automated tests please?

2023-07-17 06:21 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	envVars = ensureDeclarativeConfigurationEnabled(envVars)
Since we are now using 4.1, you can skip explicitly setting the environment variable since it will be true by default.

2023-07-17 14:37 UTC, dhaus67 reviewed
Would definitely be good to enhance the existing unit tests for the reconciler and think about whether it's possible to enhance the E2E tests to include verifying the creation of the notifier within the Central.

2023-07-17 14:37 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			for _, configObj := range configurations {
nit: theoretically we could skip this part of iterating through the configurations given that we only store a single configuration here, but we can leave it as well.

2023-07-17 14:37 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			}
Personally would handle this in the beginning of the function before accessing the `secret.Data` to ensure that we don't mistakenly forget it in some cases.

2023-07-17 14:37 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) reconcileCentralAuditLogNotifier(ctx context.Context, remoteCentral *private.ManagedCentral) error {
Right now this function creates the secret and that's essentially it.

Since declarative config only uses config map and no CRs where a status could be populated, it's quite hard to know whether the config was successfully applied or not.
In the case of auth providers it's somewhat easier since the auth providers are exposed on an unauthenticated route on the Central's API and one can use that to verify the auth provider has been created successfully.

Do we have any ideas in mind on how to alert on this in case the creation fails, i.e. providing the wrong configuration? I'd be more comfortable if there was a part within the E2E tests that would verify that the notifier is created, if that's even possible with the current setup.

2023-07-17 14:37 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
Given that this will be invoked when the reconciliation is in "deletion" phase, why bother explicitly checking the secret's data and only conditionally deleting the secret?

Since this secret is solely used by the reconciler, we might as well just generically delete the complete secret here, irrespective of the specific configuration type of declarative configuration, i.e. that this both applies for auth provider as well as notifiers (and whatever else we might introduce in the future).

2023-07-17 14:37 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	actualName string,
Those parameter namings were a tad confusing to me.

`nameForErrors` in my opinion is not required at all, the pattern we have within the reconciler to log errors for K8S objects is to specify the object's name and namespace as such:
```go
fmt.Errorf("updating secret %s/%s: %w", actualName, remoteCentralNamespace, err)
```

I'd just drop the `nameForErrors` in favor of logging the explicit name + namespace combination.

2023-07-19 08:42 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) reconcileCentralAuditLogNotifier(ctx context.Context, remoteCentral *private.ManagedCentral) error {
Tests are indeed required. I'll see how I can test that.

2023-07-19 08:42 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			for _, configObj := range configurations {
I did not want to make assumptions on what was in the secret or not. I think this leaves the door open for later changes without having to go back to adjust that part because the initial assumption is not valid anymore.

2023-07-19 08:42 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
Here again, I avoided making assumptions. At the end of the flow, the secret should be removed. Nevertheless, if a later step fails, the secret is scrubbed (and possibly removed).

2023-07-20 15:17 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
We can make the changes either within this PR or within the PR that introduces the declarative config for authn+z, but it's simpler in those cases to just remove the complete secret. I don't think there's any real use-case where you'd want to keep either one of those entries within the secret.

2023-07-24 05:15 UTC, dhaus67 requested changes

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	for dataKey, expectedVal := range expectedSecret.Data {
I _think_ (but you probably have to double check) you should be able to just do `assert.Equal` here.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	return false
Couldn't this be:
```suggestion
	targetString := fmt.Sprintf("%s:%d", targetHost, targetPort)
	assert.Contains(t, strings.Split(envValue, ","), targetString)
```

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	for _, auditLogConfig := range []config.AuditLogging{defaultAuditLogConfig, vectorAuditLogConfig} {
Probably a table test with separate `t.Run` and then using `require` where applicable to skip returns makes this easier to extend and more readable.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	}
Use `require` here.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	}
Use `require` here.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	}
Use `require` here.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	}
Use `require` here.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	}
Use `require` here.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	}
Use `assert.Contains(t, centralCRDeclarativeConfig.Secret, sensibleDeclarativeConfigSecretName)`.

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +		preexistingSecret       bool
```suggestion
		preExistingSecret       bool
```

2023-07-24 05:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +				assert.NoError(t, fakeClient.Create(ctx, secret))
Also probably a `require` is better in this case, since this is somewhat a test setup.

2023-07-25 17:08 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/proxy.go
> +		noProxyEndPoint := fmt.Sprintf("%s:%s", noProxyURL.Hostname(), noProxyURL.Port())
super nit: alternatively could just use `noProxyURL.Host` which will get you `host:port`.

2023-07-25 17:08 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	declarativeConfigurationFeatureFlagName = "ROX_DECLARATIVE_CONFIGURATION"
Once we remove the env variable check we can remove this as well.

2023-07-25 17:08 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	envVars = ensureDeclarativeConfigurationEnabled(envVars)
I think we can now just remove it, with the latest release we are now at 4.1.

2023-07-26 08:45 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	"gopkg.in/yaml.v3"
https://issues.redhat.com/browse/ROX-18693

2023-07-26 08:49 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			SkipTLSVerify:       true,
During the last e2e tests, it was not ready.
Made this parameter configurable through environment variables.

2023-07-26 08:56 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	secretModifyFunc := func(secret *v1.Secret) (bool, error) {
As far as I can tell, the "core" logic is tested in `TestGetAuditLogNotifierConfig`, `TestShouldUpdateAuditLogNotifierSecret` and `TestReconcileCentralAuditLogNotifier`

2023-07-27 08:22 UTC, SimonBaeumer requested changes

2023-07-27 08:22 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func shouldUpdateAuditLogNotifierSecret(
Is this logic worth the overhead of code?
I am questioning this because the reconciler is only executed when fleetshard-sync restarts or the Central changed, thus I would argue that the Secret object can just be optimistically updated when it already exists unconditionally.
This reduces testing efforts and makes the code easier to read.

2023-07-27 08:22 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			Host: r.auditLogging.Endpoint(),
The no proxy URL can be added unconditionally. There no risk in adding it to the no-proxy, when the host does not exist in the namespace Central just can't reach it.

2023-07-27 08:22 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			}
This check be removed if done unconditionally.

2023-07-27 08:22 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			if secret.Data == nil {
When called unconditionally the notifier config can always overwrite this field and initialize the field while updating:

```
secret.Data = map[string][]byte{
  auditLogNotifierKey: encodedNotifierConfig,
}
```

2023-07-27 08:22 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		}
Is there a reason to update the secret conditionally?

2023-07-27 09:22 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func shouldUpdateAuditLogNotifierSecret(
There are more parts than just the Audit Log Notifier that will be configured through declarative configuration and the associated secret (see PR #1156 for the auth provider part).
The point to consider here is whether we'd like to open the declarative configuration part for cloud service users. If so, I think focusing on the part of the `declarative configuration secret` and not overwriting the user-provided configuration part of the secret would be the way to go.

2023-07-27 09:26 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			}
Do we want to re-push the secret on every fleetshard-sync run even if it did not change ?

2023-07-27 11:15 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			}
I expect the update calls to be in a range of 5-10 in 4 weeks. So, in this case it is okay to update it on every reconcile. Additionally, in an operator it is considered best-pracitce to have an idempotent reconciler which does not cache states between reconcile runs.
We cache the Central changes to "mimikry" an event driven system in a polling-based mechanism.

2023-07-27 11:17 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			Host: r.auditLogging.Endpoint(),
> the target endpoint configuration can be expected to not be valid.

There is a default configured. How could this be not there? Could it be a simple unit test which verifies that the host is added unconditionally?
Reducing N-path complexity improves code readability, maintenance and testing.

2023-07-27 13:29 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		}
I think it's better not to write back the secret when its content has not changed.
Otherwise, the secrets would be potentially re-written on each fleetshard-sync reconciliation run.

2023-07-28 08:28 UTC, rhybrillou commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			Endpoint:            fmt.Sprintf("https://%s", auditLoggingConfig.Endpoint()),
it's used in one location without, and here with. I can change that, though.

2023-07-28 12:45 UTC, dhaus67 approved these changes

2023-07-28 12:45 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
super nit: can be simplified to
```suggestion
	if err != nil || exists {
		return err
	}
```

2023-07-28 14:30 UTC, SimonBaeumer approved these changes

2023-07-28 14:30 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			r.configureAuditLogNotifier(secret, namespace)
Should the error be returned here?

2023-07-31 07:52 UTC, merged