Remove unused central operator version API fields
stackrox/acs-fleet-manager pull request #1116
Opened 2023-06-21 12:22 UTC by SimonBaeumer

## Description

Remove unused central operator version API fields

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

 - CI

2023-06-21 12:27 UTC, johannes94 approved these changes

2023-06-21 12:39 UTC, johannes94 requested changes
CI seems to be broken, waiting with approval until it's green.

2023-06-23 15:38 UTC, kurlov approved these changes
🔨

2023-06-27 09:25 UTC, johannes94 approved these changes

2023-06-27 09:28 UTC, merged