ROX-17987: Add delete Operator deployment
stackrox/acs-fleet-manager pull request #1118
Opened 2023-06-21 15:15 UTC by kurlov

## Description

Add Operator deletion method based on version. This method will be used in operator version reconciliation.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

```
# To run tests locally run:
make deploy/dev-fast
```

2023-06-22 08:51 UTC, SimonBaeumer requested changes

2023-06-22 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +func (u *ACSOperatorManager) DeleteOperator(ctx context.Context, version string) error {
Where is this function executed and controller versions passed?

2023-06-22 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +	depName := operatorDeploymentPrefix + "-" + version
I've expected a function which will receive all expected operator versions, list all installed deployments and tries to delete all deployments which are not used anymore. 
Similar to a garbage collector.

Additionally the computation of the name does not match the computation of the helm chart (i.e. the chart truncates the deployment name). 
To keep the logic in one place please move the name computation to Go instead of the Helm template and reuse the function.

2023-06-22 13:36 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +func (u *ACSOperatorManager) DeleteOperator(ctx context.Context, version string) error {
It will be executed here https://github.com/stackrox/acs-fleet-manager/pull/1091/files#diff-4a5f912092e037464fef8f19fd9a883a0587f4c5dedc2d15c40b5a4109551addR40-R41 

#1091 depends on this method

2023-06-23 08:47 UTC, SimonBaeumer requested changes
Changes look good overall, only some nit-picks.

2023-06-23 08:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +		depName := generateDeploymentName(tag)
```suggestion
		deploymentName := generateDeploymentName(tag)
```

dep == dependency

2023-06-23 08:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +	for _, dep := range deployments.Items {
```suggestion
	for _, deployment := range deployments.Items {
```

2023-06-23 08:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +		dep := &appsv1.Deployment{}
```suggestion
		deployment := &appsv1.Deployment{}
```

2023-06-23 08:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +	for _, depName := range deleteDeps {
```suggestion
	for _, deploymentName := range deleteDeployments {
```

2023-06-23 08:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade_test.go
> +	require.NoError(t, err)
Can you assert the operators were installed? 
Imho it is not always necessary to execute `InstallOrUpgrade`, you can also directly pass Deployment object to the fake client.

2023-06-23 12:35 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +		depName := generateDeploymentName(tag)
I've changed it from IDE to skip compilation error

2023-06-23 12:37 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade_test.go
> +	require.NoError(t, err)
I really like your suggestion about passing Deployment object to the fake client. 
I also added small check that only deployment is delete (e.g. serviceAccount still persists)

2023-06-26 10:47 UTC, SimonBaeumer requested changes

2023-06-26 10:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +	var deleteDeps []string
```suggestion
	var deleteDeployments []string
```

2023-06-26 10:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +				deleteDeps = append(deleteDeps, deployment.Name)
I think you can assume that all deployments are operator deployments because you've selected them by using the label `rhacs-operator`.
To check whether an operator should be garbage collected you can re-compute the name instead of using the images to track an unused deployment.
Alternateviley you could also maintain a data structure internally which maps deployment names to images before the Helm chart is applied, like a cache. 

WDYTH about these approaches?

2023-06-28 13:06 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +				deleteDeps = append(deleteDeps, deployment.Name)
I've change the method so now it cleans up unused operators. Although, I still stick to use images for checking what to delete because parsing deployment names introduces new potentials error to check.
Do you think it's better to call `parseOperatorImages`?

2023-06-29 07:18 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +				deleteDeps = append(deleteDeps, deployment.Name)
> Do you think it's better to call parseOperatorImages?

What do you mean? 🤔 

>  Although, I still stick to use images for checking what to delete because parsing deployment names introduces new potentials error to check.

Sounds good!

2023-06-29 07:21 UTC, SimonBaeumer approved these changes

2023-06-29 07:21 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +// RemoveUnusedOperators removes unused operator deployments from the cluster
```suggestion
// RemoveUnusedOperators removes unused operator deployments from the cluster. It receives a list of operator images which should be present in the cluster and removes all deployments which do not deploy any of the desired images.
```

2023-06-29 07:21 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +func (u *ACSOperatorManager) RemoveUnusedOperators(ctx context.Context, desiredImages []string) error {
curiosity: What was the reason for you to not go with `GarbageCollectOperators` or similar?

2023-06-29 08:55 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +func (u *ACSOperatorManager) RemoveUnusedOperators(ctx context.Context, desiredImages []string) error {
I didn't want to put Garbage next to the Operator.
Seriously though, `garbage collect` sounds like it's about interacting with memory, having cycles/references/generations. But we just deleting deployment(s) and letting k8s do the rest for us

2023-06-29 09:20 UTC, merged