ROX-17712 prevent unnecessary central updates
stackrox/acs-fleet-manager pull request #1122
Opened 2023-06-23 13:37 UTC by ludydoo

This PR adds some logic to prevent fleetshard from updating Centrals if there are no changes, which prevent unnecessary opreator reconciliation loops.

2023-06-26 10:40 UTC, SimonBaeumer requested changes

2023-06-26 10:40 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		desiredCentral.Spec = *central.Spec.DeepCopy()
What happens if an annotation was updated? It looks to me that changes on the metadata are not updated anymore.

2023-06-26 10:40 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func printCentralDiff(desired, actual *v1alpha1.Central) {
Do you think the log verbosity could be problem?
When ~50 Centrals are reconciled, during an upgrade this log could get very verbose when it logs all Centrals which do not have any errors.
Could the diff be more conditional to not always print it?

2023-06-26 12:52 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func printCentralDiff(desired, actual *v1alpha1.Central) {
Hey, yes I've added a feature flag for enabling the diffs. 
As for the central annotations and labels, I think those are also currently completely ignored. 
The current logic ignores them completely, and just takes the labels and annotations from the existing central:
```
existingCentral.Spec = central.Spec
if err := r.client.Update(ctx, &existingCentral); err != nil {
			return errors.Wrapf(err, "updating central %s/%s", central.GetNamespace(), central.GetName())
```

2023-06-26 13:00 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		desiredCentral.Spec = *central.Spec.DeepCopy()
The current logic ignores them completely, and just takes the labels and annotations from the existing central:
```
existingCentral.Spec = central.Spec
if err := r.client.Update(ctx, &existingCentral); err != nil {
			return errors.Wrapf(err, "updating central %s/%s", central.GetNamespace(), central.GetName())
```

2023-06-26 13:43 UTC, SimonBaeumer requested changes

2023-06-26 13:43 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		updatedCentral.Spec = *central.Spec.DeepCopy()
Would it be possible to build a hash over the labels/annotations + spec and use the computed hash to detect if an update is necessary?
Not useful for printing a diff though.

2023-06-26 13:51 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		// This would apply the defaults and the mutating webhooks without actually updating the object.
The dry run will run the update through the api server, setting all default fields, applying (if any) mutating/validating webhooks, etc, without storing the update. The object returned will be as if it was actually updated. Then only is it safe to compare the desired state (after a "would-be" update) with the current state. 

The problem with the central hash is that it contains fields that don't affect the actual Central CR, such as the status. So the fleetshard will still update the Central CR even if it didn't actually needs to change. 

Also, everytime fleetshard does so, it increments a "revision" annotation. But it turns out that in 95% of cases, the only thing that fleetshard updates is the "revision", without modifying any other field on the CR. This creates a lot of traffic for the operator. This is especially visible in the first minutes of deploying a Central, where there could be as many as 20-40 unnecessary reconciliation loops (without actual changes to the CR) triggered due to this. 

So basically this logic is to check whether or not the Central will change as a result of the update or not. And the dry-run is to mitigate any side effects that could be somehow applied either on the apiserver, or through webhooks.

2023-06-26 13:53 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		// This would apply the defaults and the mutating webhooks without actually updating the object.
https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/#kubectl-diff

2023-06-26 13:55 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		// This would apply the defaults and the mutating webhooks without actually updating the object.
This is also how the helm operator detects if resources are changed or not, and if an upgrade needs to be performed or not. https://github.com/operator-framework/helm-operator-plugins/blob/c16a400954f7e43bb987b196e8ecf2f4d2d4ab0f/pkg/reconciler/reconciler.go#L720

2023-06-27 07:26 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		updatedCentral.Spec = *central.Spec.DeepCopy()
Why is it less robust? 🤔

2023-06-27 07:26 UTC, SimonBaeumer approved these changes

2023-06-27 07:34 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		updatedCentral.Spec = *central.Spec.DeepCopy()
My take on it is that the apiserver must be thought as some sort of black box. It might have various webhooks, and other defaulting strategies that are impossible to account for. So the `existingCentral` might differ from the `central` because of apiserver side effects. By using a dry-run, those side effects are accounted for

2023-06-27 12:08 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		updatedCentral.Spec = *central.Spec.DeepCopy()
Are you suggesting that instead of `DeepCompare`, we would compare the hash of the `would be` central and the `existing` central ? What would be the advantage ?

2023-06-28 10:27 UTC, SimonBaeumer approved these changes

2023-06-29 14:01 UTC, merged