Add egress diagram to docs
stackrox/acs-fleet-manager pull request #1130
Opened 2023-06-27 14:56 UTC by SimonBaeumer

## Description
Add egress diagram to docs

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-06-28 08:49 UTC, johannes94 requested changes
Except the one comment the diagram looks good.

2023-06-28 08:49 UTC, johannes94 commented on docs/architecture/images/egress_diagram.md
> +            acs1egress[egress]
If I understand correctly this is the egress-proxy? I would change the names in this diagram so it matches the names of k8s resources e.g egress -> egress-proxy

2023-06-28 12:46 UTC, ebensh submitted a review, later dismissed

2023-07-04 07:44 UTC, SimonBaeumer commented on docs/architecture/images/egress_diagram.md
> +            acs1egress[egress]
Updated

2023-07-04 07:47 UTC, SimonBaeumer commented on docs/architecture/images/egress_diagram.md
> +        acs1central-->acs1egress
Good catch, Scanner uses the egress-proxy too. Fixed the diagram

2023-07-04 08:02 UTC, johannes94 commented
@SimonBaeumer was adding the values.yaml file intentional?

2023-07-04 11:32 UTC, SimonBaeumer commented
> @SimonBaeumer was adding the values.yaml file intentional?

@johannes94 Fixed

2023-07-04 11:53 UTC, johannes94 requested changes

2023-07-04 11:53 UTC, johannes94 commented on docs/architecture/images/egress_diagram.md
> +        acs1central-->acs1egress
In the current diagram scanner is pointing to the internet without going through the egress-proxy first.

2023-07-20 08:37 UTC, SimonBaeumer commented on docs/architecture/images/egress_diagram.md
> +        acs1central-->acs1egress
Fixed!

2023-07-21 07:07 UTC, johannes94 approved these changes

2023-09-14 11:53 UTC, SimonBaeumer commented
/override ci/prow/e2e

2023-09-14 11:53 UTC, merged