Add operator configuration in fleetshard-sync
stackrox/acs-fleet-manager pull request #1157
Opened 2023-07-17 09:25 UTC by SimonBaeumer

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-07-20 09:23 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> -              cpu: 2
Can you put those under `operator.resources...`? Because we might want to also configure the `rbac-proxy` (e.g. `rbac-proxy.resources...`)

2023-07-20 09:25 UTC, ludydoo commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-config.yaml
> +---
Will this be the git-ops config map as well ?

2023-07-20 09:36 UTC, ludydoo commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-config.yaml
> +    rhacs_operator:
should this be rather
```
operators:
- image: ...
   operator:
     resources: ...
     rbacProxy: ...
```

2023-07-21 08:48 UTC, SimonBaeumer commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-config.yaml
> +    rhacs_operator:
Yes

2023-07-21 08:48 UTC, SimonBaeumer commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-config.yaml
> +---
Nope, this will be removed

2023-07-21 08:48 UTC, SimonBaeumer commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> -              cpu: 2
Yes, good point

2023-07-21 08:49 UTC, SimonBaeumer commented
@ludydoo The PR is out of date with the recent design changes we discussed.

2023-07-24 09:10 UTC, ludydoo commented on internal/dinosaur/pkg/services/rhacsoperator/config.go
> +	HelmValues string `yaml:"helmValues,omitempty"`
using `json` should work too

2023-08-08 07:48 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/rhacsoperator/config.go
> +  helmValues: |
I've not found a way to define an unstructured object to the OpenAPI spec.

2023-08-08 12:16 UTC, kurlov requested changes

2023-08-08 12:16 UTC, kurlov commented on fleetshard/config/config.go
> +	DefaultBaseCrdURL    string        `env:"DEFAULT_BASE_CRD_URL" envDefault:"https://raw.githubusercontent.com/stackrox/stackrox/%s/operator/bundle/manifests/"`
Should we uppercase `CRD`? It will be kinda ugly(`CRDURL` sounds like a demon name or something)  but 
It's suggested to have consistent case for [initialisms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2023-08-08 12:16 UTC, kurlov commented on fleetshard/pkg/central/operator/config.go
> +		if len(config.GitRef) > 63 {
it's better to use [IsValidLabelValue](https://github.com/kubernetes/apimachinery/blob/8071e5f05ff19f8d66a4f35426e3c636be1e50f8/pkg/util/validation/validation.go#L167) method. It checks not only length but also char set

2023-08-08 12:16 UTC, kurlov commented on fleetshard/pkg/central/operator/config.go
> +	manifests, err := manager.RenderChart(configs)
`RenderChart` also validates `OperatorConfigs` under the hood. I think we should have only one validation method which returns errors or manifests which can be used for operators deployment

2023-08-08 12:16 UTC, kurlov commented on internal/dinosaur/pkg/api/private/model_managed_central_list.go
> +	RhacsOperators RhacsOperatorConfigs `json:"rhacs_operators,omitempty"`
It should be `RHACS`

2023-08-08 14:05 UTC, SimonBaeumer commented on fleetshard/config/config.go
> +	DefaultBaseCrdURL    string        `env:"DEFAULT_BASE_CRD_URL" envDefault:"https://raw.githubusercontent.com/stackrox/stackrox/%s/operator/bundle/manifests/"`
Agree and changed

2023-08-08 14:06 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/config.go
> +		if len(config.GitRef) > 63 {
Done

2023-08-08 14:08 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/model_managed_central_list.go
> +	RhacsOperators RhacsOperatorConfigs `json:"rhacs_operators,omitempty"`
I think it is not possible becuase it is generated code. In the open API spec it is upper case:
https://github.com/stackrox/acs-fleet-manager/blob/684ddb81e75f9a07256a625eb39974c9673dda5e/openapi/fleet-manager-private.yaml#L346-L359

2023-08-08 14:14 UTC, kurlov commented on internal/dinosaur/pkg/api/private/model_managed_central_list.go
> +	RhacsOperators RhacsOperatorConfigs `json:"rhacs_operators,omitempty"`
Oh, it was generated. Sorry

2023-08-08 14:16 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/model_managed_central_list.go
> +	RhacsOperators RhacsOperatorConfigs `json:"rhacs_operators,omitempty"`
> Sorry

Thanks for the feedback 👊

2023-08-09 08:23 UTC, kurlov commented on fleetshard/pkg/runtime/runtime.go
> +	//err = r.operatorManager.InstallOrUpgrade(ctx, operator.FromAPIResponse(list.RhacsOperators))
Please, remove it

2023-08-09 08:24 UTC, kurlov approved these changes
Looking great!

2023-08-09 08:27 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +	//err = r.operatorManager.InstallOrUpgrade(ctx, operator.FromAPIResponse(list.RhacsOperators))
This line is used after Fleet-Manager implementation is finished and the API response has content. I've added a comment to clarify the intention of the comment.

2023-08-09 09:01 UTC, SimonBaeumer commented
/retest

2023-08-09 09:55 UTC, ludydoo commented on fleetshard/config/config.go
> +	DefaultBaseCRDURL    string        `env:"DEFAULT_BASE_CRD_URL" envDefault:"https://raw.githubusercontent.com/stackrox/stackrox/%s/operator/bundle/manifests/"`
Consider something like:
```suggestion
	CentralCRDURLTemplate    string        `env:"CENTRAL_CRD_URL_TEMPLATE" envDefault:"https://raw.githubusercontent.com/stackrox/stackrox/{{ .GitRef }} /operator/bundle/manifests/platform.stackrox.io_centrals.yaml"`
		SecuredClusterCRDURLTemplate    string        `env:"SECURED_CLUSTER_CRD_URL_TEMPLATE" envDefault:"https://raw.githubusercontent.com/stackrox/stackrox/{{ .GitRef }} /operator/bundle/manifests/platform.stackrox.io_securedclusters.yaml"`
```

2023-08-09 09:56 UTC, ludydoo commented on fleetshard/pkg/central/operator/config.go
> +		DefaultBaseCRDURL: "https://raw.githubusercontent.com/stackrox/stackrox/%s/operator/bundle/manifests/",
Why is this duplicated there ?

2023-08-11 07:29 UTC, merged

2023-08-11 07:30 UTC, SimonBaeumer commented on fleetshard/config/config.go
> +	DefaultBaseCRDURL    string        `env:"DEFAULT_BASE_CRD_URL" envDefault:"https://raw.githubusercontent.com/stackrox/stackrox/%s/operator/bundle/manifests/"`
Removed the variable and replaced it with a constant. We can overwrite the default via GitOps, there is no need for a config as an env variable, it would be duplicated.

2023-08-11 07:30 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/config.go
> +		DefaultBaseCRDURL: "https://raw.githubusercontent.com/stackrox/stackrox/%s/operator/bundle/manifests/",
Removed it and replaced with a constant