set logger for controller-runtime in fleetshard
stackrox/acs-fleet-manager pull request #116
Opened 2022-06-10 14:00 UTC by johannes94

## Description
I was facing an issue where fleetshard-sync component was exiting with code 1 without any appropriate log msg. During debugging I found out that the problem was an error in my kubeconfig and that the `os.Exit(1)` was called by k8s controller-runtime lib when creating k8s client :
```
func GetConfigOrDie() *rest.Config {
	config, err := GetConfig()
	if err != nil {
		log.Error(err, "unable to get kubeconfig")
		os.Exit(1)
	}
	return config
}
```
We don't set a logger for the controller-runtime dependency, that's why the log of the failing GetConfig was not visible. See [this comment](https://github.com/kubernetes-sigs/controller-runtime/issues/1475#issuecomment-822887715) on controller-runtime  repo.

In this PR, I added a Line in `main.go` to set the logger for controller-runtime with default configuration.

Log before change:

```
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450182       1 main.go:41] Starting application
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450337       1 main.go:42] FleetManagerEndpoint: http://fleet-manager:8000
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450368       1 main.go:43] ClusterID: 1234567890abcdef1234567890abcdef
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450392       1 main.go:44] RuntimePollPeriod: 5s
docker-compose-fleetshard-sync-1 exited with code 1
```

Log after change:

```
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450182       1 main.go:41] Starting application
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450337       1 main.go:42] FleetManagerEndpoint: http://fleet-manager:8000
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450368       1 main.go:43] ClusterID: 1234567890abcdef1234567890abcdef
docker-compose-fleetshard-sync-1     | I0610 13:55:31.450392       1 main.go:44] RuntimePollPeriod: 5s
docker-compose-fleetshard-sync-1     | {"level":"error","ts":1654869331.466284,"logger":"controller-runtime.client.config","msg":"unable to get kubeconfig","error":"invalid configuration: [unable to read client-cert /Users/johannes/.minikube/profiles/minikube/client.crt for minikube due to open /Users/johannes/.minikube/profiles/minikube/client.crt: no such file or directory, unable to read client-key /Users/johannes/.minikube/profiles/minikube/client.key for minikube due to open /Users/johannes/.minikube/profiles/minikube/client.key: no such file or directory, unable to read certificate-authority /Users/johannes/.minikube/ca.crt for minikube due to open /Users/johannes/.minikube/ca.crt: no such file or directory]","errorCauses":[{"error":"unable to read client-cert /Users/johannes/.minikube/profiles/minikube/client.crt for minikube due to open /Users/johannes/.minikube/profiles/minikube/client.crt: no such file or directory"},{"error":"unable to read client-key /Users/johannes/.minikube/profiles/minikube/client.key for minikube due to open /Users/johannes/.minikube/profiles/minikube/client.key: no such file or directory"},{"error":"unable to read certificate-authority /Users/johannes/.minikube/ca.crt for minikube due to open /Users/johannes/.minikube/ca.crt: no such file or directory"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/client/config.GetConfigOrDie\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/client/config/config.go:153\ngithub.com/stackrox/acs-fleet-manager/fleetshard/pkg/k8s.CreateClientOrDie\n\t/workspace/fleetshard/pkg/k8s/client.go:18\nmain.main\n\t/workspace/fleetshard/main.go:46\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
docker-compose-fleetshard-sync-1 exited with code 1
```

## Checklist (Definition of Done)
- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

- Start fleetshard-sync without any kubeconfig

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-13 20:18 UTC, SimonBaeumer requested changes
Nice catch, thanks!

2022-06-13 20:18 UTC, SimonBaeumer commented on fleetshard/main.go
> +	ctrl.SetLogger(zap.New())
Can we set `glog` here instead to avoid another dependency?

2022-06-14 05:20 UTC, johannes94 commented on fleetshard/main.go
> +	ctrl.SetLogger(zap.New())
Wanted to do that, but we would need to implement a wrapper for glog to implement logr.LogSink interface in order to use it as logr.Logger. Went with the zap logger instead because I've seen it being used in other parts of the project (stackrox operator). Do you think we should implement the wrapper?

2022-06-14 13:51 UTC, SimonBaeumer commented on fleetshard/main.go
> +	ctrl.SetLogger(zap.New())
> Do you think we should implement the wrapper?

I don't think so, seems a bit much effort for one error message we get by creating the client. 
Changing the call in `CreateClientOrDie()` to `CreateClient()` and exiting on the error should fix it without the necessity adding a logger to the client.

2022-06-15 15:28 UTC, merged