Add prod and stage check in dev scripts
stackrox/acs-fleet-manager pull request #1163
Opened 2023-07-18 08:56 UTC by SimonBaeumer

## Description
Add prod and stage check in dev scripts

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

 - Executing script against kubernetes endpoint on prod or staging URLs

2023-07-18 08:57 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
Do we deploy any cluster on `openshiftapps` URLs which is provisioned by `make deploy/bootstrap`?

2023-07-18 09:01 UTC, ludydoo commented on dev/env/scripts/lib.sh
> +        echo "Executing against prod or staging not allowed. Please check your kubectl conetxt."
Typo. 
Side comment: Will errors to execute kubectl cluster-info always be due to a permission error (`not allowed`) ? 
```suggestion
        echo "Executing against prod or staging not allowed. Please check your kubectl context."
```

2023-07-18 09:04 UTC, ludydoo commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
I think this will prevent targeting clusters deployed with infractl, but maybe that's ok ?

2023-07-18 09:07 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
Checked it, infra deploys domains like `https://console-openshift-console.apps.mm-07-18-test123.openshift.infra.rox.systems/` and does not use `openshiftapps`.

2023-07-18 09:07 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +        echo "Executing against prod or staging not allowed. Please check your kubectl conetxt."
Fixed

2023-07-18 09:08 UTC, ludydoo commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
ah yes sorry, my mistake

2023-07-18 09:08 UTC, ludydoo approved these changes

2023-07-18 09:13 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
@SimonBaeumer pls check openshift CI too

2023-07-18 09:20 UTC, kovayur commented on dev/env/scripts/lib.sh
> +        exit 1
```suggestion
        die "Error: Executing against prod or staging not allowed. Please check your kubectl context."
```

2023-07-18 09:20 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
```suggestion
    try_kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
```

2023-07-18 09:34 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
Seems fine, but overall `openshiftapps` looks error prone as the address may change in the future.

> INFO[2023-07-18T09:05:49Z] Using namespace https://console.build02.ci.openshift.org/k8s/cluster/projects/ci-op-qhcfm4gr

2023-07-18 09:35 UTC, kovayur requested changes
I believe that `try_kubectl` is crucial for Openshift CI.

2023-07-18 09:50 UTC, kurlov commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
openshift e2e failed though. I am not sure it's a or not flake because haven't seen this error before

2023-07-20 08:41 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +        exit 1
done

2023-07-20 08:42 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +    kubectl cluster-info  | grep -E "stage|prod|openshiftapps"
done

2023-08-11 07:35 UTC, SimonBaeumer commented
/retest

2023-09-14 08:35 UTC, SimonBaeumer commented
/retest

2024-01-15 13:35 UTC, closed without merging