ROX-18427: tag DB clusters and instances with ACS insntace ID
stackrox/acs-fleet-manager pull request #1169
Opened 2023-07-19 10:20 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-07-20 07:11 UTC, johannes94 requested changes

2023-07-20 07:11 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +func newCreateCentralDBClusterInput(clusterID, acsInstanceID, dbPassword, securityGroup, subnetGroup, dataplaneClusterName string, isTestInstance bool) *rds.CreateDBClusterInput {
Input variables are getting a lot in these newCreateCentralDB*Input functions. What to you think about changing it to a method of RDS struct. This way we don't have to pass so many vars.

2023-07-20 07:11 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +func newCreateCentralDBInstanceInput(clusterID, instanceID, acsInstanceID, dataplaneClusterName string, performanceInsights bool, isTestInstance bool) *rds.CreateDBInstanceInput {
Same here.

2023-07-21 07:49 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +func newCreateCentralDBClusterInput(clusterID, acsInstanceID, dbPassword, securityGroup, subnetGroup, dataplaneClusterName string, isTestInstance bool) *rds.CreateDBClusterInput {
Done.

2023-07-21 07:49 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +func newCreateCentralDBInstanceInput(clusterID, instanceID, acsInstanceID, dataplaneClusterName string, performanceInsights bool, isTestInstance bool) *rds.CreateDBInstanceInput {
Done.

2023-07-21 08:58 UTC, merged