Use unique namespace names for central deployments
stackrox/acs-fleet-manager pull request #117
Opened 2022-06-10 16:03 UTC by kovayur

## Description
Use unique namespace names for central deployments.

## Checklist (Definition of Done)

- [x] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual
1. Add yourself in the `quota-management-list-configuration.yaml`
2. Create a few instances using public API
3. Make sure that unique namespaces were created by the fleetshard

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-13 19:41 UTC, SimonBaeumer requested changes

2022-06-13 19:41 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/util.go
> +const dns1123LabelErrMsg string = "a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character"
nit: Use instead
```
const (
   ...
)
```

2022-06-13 19:41 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/util.go
> +		return "", fmt.Errorf("invalid namespace %s: %s", text, validation.RegexError(dns1123LabelErrMsg, dns1123LabelFmt, "my-name", "123-abc"))
Are `my-name` and `123-abc` placeholders?

2022-06-13 19:41 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/util_test.go
> +		error     bool
I prefer being explicit with properties in test. In this case for example not obvious which of these properties is the expected result.

```suggestion
		expectError     bool
```

2022-06-13 19:41 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/util.go
> +var dns1123LabelRegexp = regexp.MustCompile("^" + dns1123LabelFmt + "$")
nit:
```
var (
  ...
)
```

2022-06-13 19:41 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/util.go
> +	truncatedNamespace := truncateString("rhacs-"+text, validation.LabelValueMaxLength)
WDYTH about adding actual instance or customer names to namespaces for easier navigation?
(More detailed data of could be added to the namespace labels anyway)

2022-06-14 12:42 UTC, kovayur commented on internal/dinosaur/pkg/services/util.go
> +const dns1123LabelErrMsg string = "a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character"
Fixed.

2022-06-14 12:43 UTC, kovayur commented on internal/dinosaur/pkg/services/util.go
> +		return "", fmt.Errorf("invalid namespace %s: %s", text, validation.RegexError(dns1123LabelErrMsg, dns1123LabelFmt, "my-name", "123-abc"))
These are examples of the correct format

2022-06-14 12:43 UTC, kovayur commented on internal/dinosaur/pkg/services/util_test.go
> +		error     bool
Renamed as suggested.

2022-06-15 07:00 UTC, merged