ROX-18428: report secret data to fleet-manager
stackrox/acs-fleet-manager pull request #1185
Opened 2023-08-01 14:40 UTC by johannes94

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-08-04 06:29 UTC, johannes94 commented
/retest

2023-08-08 08:53 UTC, johannes94 commented on openapi/fleet-manager-private.yaml
> +                secretsStored:
I only report secrets as a list of secret names, because the secrets data itself is at ~10KB per tenant. To save network traffic and costs I'll implement lazy loading of secret data in the follow up PR for secret restore in fleetshard-sync.

2023-08-15 21:20 UTC, vladbologa requested changes
Looks good, I had a few comments here and there.

2023-08-15 21:20 UTC, vladbologa commented on fleetshard/pkg/k8s/secret.go
> +// This servise is specific to ACS Managed Services and provides methods work on specific secrets
```suggestion
// SecretService is responsible with reading specified secrets from a Kubernetes namespace
```

There's no writing as of yet, I guess you plan to add it in the future, but for now it's misleading. Also the name SecretService sounds a bit funny, maybe we can come up with another name?

2023-08-15 21:20 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	// from the cluster state.
```suggestion
	// Only report secrets if Central is ready, to ensure we're not trying to get secrets before they are created
	// Also, only report secrets once, to not overwrite initial secrets with possibly corrupted secrets
	// from the cluster state.
```

2023-08-15 21:20 UTC, vladbologa commented on internal/dinosaur/pkg/services/data_plane_dinosaur.go
> +			e = d.persistCentralValues(dinosaur, ks, cluster)
Please update the comment above.

2023-08-16 10:56 UTC, johannes94 commented on internal/dinosaur/pkg/services/data_plane_dinosaur.go
> +			e = d.persistCentralValues(dinosaur, ks, cluster)
Done.

2023-08-16 10:56 UTC, johannes94 commented on fleetshard/pkg/k8s/secret.go
> +	centralDBPasswordSecretName,
While I see that this solution is simple to implement introducing edge cases for specific secrets might be harder to maintain. Consider we now have:
- central-tls
- db-password

We would need to document as SOPS and test (perhaps automatically) 2 different approaches to restore/regenerate those secrets. Lets say we add a KMS key, now we have to ask ourselfes, can we easily regenerate it, should we backup it? Is there a potential 3rd solution to recover. We would need to go through SOPs and add it everywhere and need to write a new one if we implement something different.

That's why I'd like to handle both generated secrets the same for now. WDYTH? IMO we can also defer the decision to the point where we implement db password rotation.

2023-08-16 11:46 UTC, vladbologa commented on fleetshard/pkg/k8s/secret.go
> +	centralDBPasswordSecretName,
I'm ok with deferring the decision until we implement db password rotation.

But to continue the discussion a bit. When dealing with secrets created and managed by `fleetshard-sync` (currently only the db-password falls into this category afaik), if they are missing, fleetshard-sync could and should be capable of regenerating them and recover on its own. So we wouldn't even need to mention them in SOPs.

2023-08-16 11:57 UTC, vladbologa commented on internal/dinosaur/pkg/migrations/20230802000000_add_secrets_field_to_central_request.go
> +		OperatorImage                 string     `json:"operator_image"`
Yes, looks like in some migrations we do, in others we don't.

I remember first seeing a comment about this here: https://github.com/stackrox/acs-fleet-manager/pull/904#discussion_r1147656127

After that I also brought it up on other occasions. What I don't know is, does it bring any benefits to have the full model? If not,  I think having less code is generally better.

2023-08-16 13:29 UTC, johannes94 commented on internal/dinosaur/pkg/migrations/20230802000000_add_secrets_field_to_central_request.go
> +		OperatorImage                 string     `json:"operator_image"`
I've reduced it to only the secrets field

2023-08-16 14:15 UTC, vladbologa approved these changes

2023-08-17 12:27 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	secretService    *k8s.SecretBackup
```suggestion
	secretBackup    *k8s.SecretBackup
```

2023-08-29 07:44 UTC, johannes94 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	secretService    *k8s.SecretBackup
Done.

2023-08-29 08:24 UTC, merged