ROX-16090: Start data plane CD on integration environment.
stackrox/acs-fleet-manager pull request #1190
Opened 2023-08-04 07:43 UTC by porridge

## Description

This change also splits the idp setup script to resolve some dependency loops between it and the terraform config.

## Checklist (Definition of Done)

- [ ] ~Unit and integration tests added~
- [ ] ~Added test description under `Test manual`~
- [x] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~
- [x] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] ~RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~
- [ ] ~Check AWS limits are reasonable for changes provisioning new resources~

## Test manual

CI should suffice.

2023-08-04 09:34 UTC, ebensh requested changes
I like the cleanup for sure :) Thank you for splitting it out.

2023-08-04 09:34 UTC, ebensh commented on .github/workflows/deploy-integration.yaml
> +      deploy_clusters: "acs-int-us-01"
What happened to the plan to update the naming scheme?

2023-08-04 09:34 UTC, ebensh commented on docs/development/setup-osd-cluster-idp.md
> +Based on the environment, you have to choose between `rhacs-managed-service-stage`, `rhacs-managed-service-integration` or `rhacs-managed-service-prod` account.
This may be a nit but I thought the logical ordering was:
int -> stage -> prod
It would make sense to put integration first then for consistency. If I'm wrong and it is:
stage -> int -> prod
And "int" is "pre-prod" then it makes sense.

If this change is made, please reflect that below as well (stage|integration|prod -> integration|stage|prod)

2023-08-04 09:34 UTC, ebensh commented on dp-terraform/cd-robot-account-setup.sh
> +    echo "Cluster typically looks like: acs-{environment}-dp-01"
This is no longer true, but we can leave it there for consistency until the naming scheme is updated

2023-08-04 09:34 UTC, ebensh commented on dp-terraform/cd-robot-account-setup.sh
> +    EXPECT_OCM_ID="2QVFzUvsbMGheHhoUDjtG0tpJ08"
This does not match the value in https://docs.engineering.redhat.com/pages/viewpage.action?pageId=288990393#Environments(Dev,Int,Stg,Prd)-ACSManagedServiceEnvironments , which is `2NgB6hzFyCWU2EvO2Ro3MX4jEfF`. Which value is correct? Are both from OCM's production environment and for the correct organization?

2023-08-04 09:34 UTC, ebensh commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    FM_ENDPOINT="https://qj3layty4dynlnz.api.integration.openshift.com"
Please add this to https://docs.engineering.redhat.com/pages/viewpage.action?pageId=288990393#Environments(Dev,Int,Stg,Prd)-ACSManagedServiceEnvironments

2023-08-04 09:34 UTC, ebensh commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
Will this be a problem using the Observatorium stage environment? Will Stage and Int environments clobber each other?

2023-08-04 09:34 UTC, ebensh commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    SECURED_CLUSTER_ENABLED="true"
Is this going to work correctly when reporting values to the Dogfood instance?

2023-08-04 09:34 UTC, ebensh commented on dp-terraform/osd-cluster-idp-setup.sh
> +    EXPECT_OCM_ID="2QVFzUvsbMGheHhoUDjtG0tpJ08"
Same q here

2023-08-07 06:12 UTC, porridge commented on dp-terraform/cd-robot-account-setup.sh
> +    EXPECT_OCM_ID="2QVFzUvsbMGheHhoUDjtG0tpJ08"
Both are correct. `2Ng...` is the org id. `2QVF...` is the account id :-)

2023-08-07 06:13 UTC, porridge commented on .github/workflows/deploy-integration.yaml
> +      deploy_clusters: "acs-int-us-01"
As it ran deeper and deeper I decided to not block the cluster creation on the decision. It was dragging for far too long already.

2023-08-07 06:19 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    FM_ENDPOINT="https://qj3layty4dynlnz.api.integration.openshift.com"
I will once it's actually up.

2023-08-07 06:38 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
Excellent point!
Some time ago @stehessel mentioned we could use the stage observatorium for this environment, but I guess we should first disambiguate the metrics. Taking a quick look at the config, the `tenant` helm value looks tempting, but I doubt we can just set it to something like `rhacs-int` in this case without some external setup first?

I guess the same concern applies to the `logging`, `cloudwatch` and perhaps `audit-logs` subcharts?

2023-08-07 06:43 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    SECURED_CLUSTER_ENABLED="true"
Just another secured cluster, no? But OK, let's make baby steps and set this to false for now...

2023-08-07 06:46 UTC, porridge commented on dp-terraform/osd-cluster-idp-setup.sh
> +    EXPECT_OCM_ID="2QVFzUvsbMGheHhoUDjtG0tpJ08"
Same answer :-)

2023-08-07 08:39 UTC, ebensh commented on dp-terraform/cd-robot-account-setup.sh
> +    EXPECT_OCM_ID="2QVFzUvsbMGheHhoUDjtG0tpJ08"
Ah dangit - good catch, thank you

2023-08-07 08:39 UTC, ebensh commented on dp-terraform/osd-cluster-idp-setup.sh
> +    EXPECT_OCM_ID="2QVFzUvsbMGheHhoUDjtG0tpJ08"
:D

2023-08-07 10:06 UTC, stehessel commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
Prometheus metrics have `clusterName` as an external label, so I don't see an issue with using the stage observatorium tenant. `cloudwatch` subchart should also be fine to re-use, just need to adapt the environment and cluster name.

2023-08-21 06:38 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
@stehessel can you please clarify what you mean by

> just need to adapt the environment and cluster name

Is this something I need to do beforehand?
:sweat_smile:

Also, what about the `logging` and `audit-logs` subcharts? Are you familiar with them?

2023-08-21 10:03 UTC, stehessel commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
Cluster name and environment are setup via https://github.com/stackrox/acs-fleet-manager/blob/main/dp-terraform/helm/rhacs-terraform/terraform_cluster.sh#L18-L19. For `logging` and `audit-logs` I'd suggest to take a look at the current Helm values for stage. You need to adapt a few parameters from `stage-dp-02` to `integration-...`.

2023-08-22 12:00 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
I'm still at a loss at where I should be looking for "the current Helm values for stage". AFAICT the helm values are being set dynamically by the shell script you pointed at, so as long as `deploy_clusters` parameter in the GHA workflow file is set correctly (and it is) I don't need to change anything in the charts :thinking:

I had a closer look and determined the following w.r.t. to the child charts:

## audit-logs

Seems to configure feeding k8s (?) audit logs into AWS cloudwatch service in the configured account. Since `integration` uses a separate account, there should be no clash with `staging`.

BTW helm is called with`  --set audit-logs.annotations.rhacs\\.redhat\\.com/cluster-name="${CLUSTER_NAME}" \` but it's not clear whether this affects the streamed logs in any way.

## cloudwatch

Watches AWS resources and exports metrics for prometheus to scrape, so does not directly touch anything related to other environments.

## logging

This one is a bit mysterious to me since the README assumes knowledge of OCP technologies that I'm unfamiliar with. Either way, the log forwarder output configuration has `groupPrefix: {{ .Values.groupPrefix | quote }}` which we set as `  --set logging.groupPrefix="${CLUSTER_NAME}" \` when calling helm. So while it's not clear to me where these logs end up, I think this should ensure the results are not mixed with other clusters.

## observability

As discussed above, `clusterId` label is being set based on `  --set observability.clusterName="${CLUSTER_NAME}" \`

2023-08-22 12:01 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
@ebensh can you please approve?

2023-08-22 12:15 UTC, stehessel commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    OBSERVABILITY_OBSERVATORIUM_GATEWAY="https://observatorium-mst.api.stage.openshift.com"
I meant that there is probably nobody who knows all the charts and their values. So you could look at the generated Helm values for stage, note anything that is tied to the cluster name / env / AWS account, and either confirm that they are dynamically generated or set them manually. Which it looks like is what you did, so all good from my POV.

> So while it's not clear to me where these logs end up, I think this should ensure the results are not mixed with other clusters.

The logs should end up in CloudWatch. In the secrets manager there should be AWS credentials for this.

2023-08-23 08:46 UTC, ebensh approved these changes

2023-08-24 05:23 UTC, merged