ROX-18914: Add E2E tests for Canary Upgrade
stackrox/acs-fleet-manager pull request #1196
Opened 2023-08-10 06:55 UTC by kurlov

## Description

Adds E2E tests to cover:
- Run ACS Operator from Fleetshard-sync service
- Run multiple ACS Operators
- Create Central with Canary Upgrade Feature turned on
- Upgrade Cenral

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-08-10 10:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +var _ = Describe("Fleetshard-sync Canary Upgrade", func() {
nit: confusion before, this would be targeted, canary would be the implementation on the gradual rollout logic.
WDYTH?

```suggestion
var _ = Describe("Fleetshard-sync Targeted Upgrade", func() {
```

2023-08-10 10:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +		It("should run only the latest operator", func() {
AFAIK, this test removes one operator
```suggestion
		It("should delete the removed operator", func() {
```

2023-08-10 10:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +			twoOperatorVersionConfig := `
imho it is sufficient because the context is clear and not multiple variables are used
```suggestion
			operatorConfig := `
```

2023-08-10 10:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +func updateOperatorConfig(ctx context.Context, configYAML string) error {
Here passing the operator config structs and marshalling the YAML in this function.
- expected input is clear which config should be passed because of strong typing
- usage search is not working when using the unstructured approach. If someone modifies the data structure they will be notified likely only by CI that these tests failed

2023-08-10 10:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +	err := k8sClient.Get(ctx, centralKey, deployment)
Is it possible to remove the `if err != nil` cases with an assertion? 
Or return `return deployment, err`? I think it is okay in a test to not 100% align with best pracitces but prefer an idomatic approach which reduces complexity in the code flow.

2023-08-10 10:20 UTC, SimonBaeumer commented on pkg/features/list.go
> +	UseOperatorsConfigMap = registerFeature("Use ACS Operators configuration from ConfigMap", "RHACS_USE_OPERATORS_CONFIGMAP", false)
nit: Keeping the name a bit more general to debug mode gives more flexibility later, i.e. to use to mock fleet-manager API responses.

```suggestion
	UseOperatorsConfigMap = registerFeature("Use ACS Operators configuration from ConfigMap", "RHACS_DEBUG_MODE", false)
```

2023-09-01 14:20 UTC, SimonBaeumer requested changes

2023-09-01 14:20 UTC, SimonBaeumer commented on dev/env/manifests/rhacs-operator/03-operators-config.yaml
> +      image: quay.io/rhacs-eng/stackrox-operator:4.1.1
`gitRef` and image tag are different, this would act as a bad example. Can you adjust the values to match each other?

```suggestion
    - gitRef: 4.1.1
      image: quay.io/rhacs-eng/stackrox-operator:4.1.1
```

2023-09-01 14:20 UTC, SimonBaeumer commented on pkg/features/list.go
> +	UseOperatorsConfigMap = registerFeature("Use ACS Operators configuration from ConfigMap", "RHACS_USE_OPERATORS_CONFIGMAP", false)
I think you not had the time since our sync, commenting here for visibility to change the name.

2023-09-01 14:20 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +		}
Imho can be logged unconditionally.

```suggestion

        glog.Infof("Reading operator config map, extracted %d operators from configmap", len(configMapOperators))

```

2023-09-01 14:20 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +		}}
Adding this as a default operator might cause confusion. If I start fleetshard without it, the operator is created by default, but as soon as I create the configmap the operator is deleted and the other config is active.
This would remove the default operator unintentionally.

2023-09-01 14:20 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +func (u *ACSOperatorManager) ReadOperatorConfigurationFromConfigMap(ctx context.Context) ([]OperatorConfig, error) {
nit:
```suggestion
func (u *ACSOperatorManager) ReadOperatorConfigFromConfigMap(ctx context.Context) ([]OperatorConfig, error) {
```

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +func validateOperatorDeployment(ctx context.Context, GitRef string, image string) error {
```suggestion
func validateOperatorDeployment(ctx context.Context, gitRef string, image string) error {
```

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +		if !runCanaryUpgradeTests {
Can you use the feature flag for this if-case? If we enable the feature-flag the tests automatically are re-activated and stop us from merging broken states accidentially.

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +		It("should deploy two operators", func() {
```suggestion
		It("should deploy two operators with different versions", func() {
```

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +			Eventually(validateOperatorDeployment(ctx, "4.1.1", "quay.io/rhacs-eng/stackrox-operator:4.1.1")).
Can you wrap this with `It` func blocks to provide more info in test failures?

Like:

```
It(`should reconcile operator via label selector 4.1.1`) {}
```

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +			Eventually(validateOperatorDeployment(ctx, "4.1.2", "quay.io/rhacs-eng/stackrox-operator:4.1.2")).
Add `It` func block

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +		It("should delete the removed operator", func() {
👍

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +			Skip("Skipping canary upgrade test")
Add feature flag check

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +		It("create central", func() {
Does this have more expectations? for example, creating Central in a specific version?

```suggestion
		It("creates central", func() {
```

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +				Image:  "quay.io/rhacs-eng/stackrox-operator:4.1.1",
This gives users a bad example on how `gitRef` and image tag should be used, if you want to have different values use the commit hash the tag is referring to.

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +				if centralCR.Labels["rhacs.redhat.com/version-selector"] != "4.0.0" {
Getter instead of direct access?

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +					return fmt.Errorf("wrong version-selector")
What was expected? Does a user get enough information to debug the test failures easily?

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_suite_test.go
> +	runCanaryUpgradeTests bool
Use feature flag instead

2023-09-01 14:20 UTC, SimonBaeumer commented on e2e/e2e_suite_test.go
> +	runCentralTests       bool
This should be defaulted to `true`

2023-09-04 09:22 UTC, kurlov commented on e2e/e2e_suite_test.go
> +	runCanaryUpgradeTests bool
Mapped value reading to feature flag

2023-09-04 09:31 UTC, kurlov commented on fleetshard/pkg/runtime/runtime.go
> +		}}
I am not sure what would be the best approach here. It looks we need some sort of default version for local development until canary is roll out.I think it is explicitly expected that default operator is deleted if some custom config is used

2023-09-08 09:08 UTC, SimonBaeumer requested changes

2023-09-08 09:08 UTC, SimonBaeumer commented on e2e/e2e_canary_upgrade_test.go
> +		if !runCanaryUpgradeTests || !features.StandaloneMode.Enabled() {
The test can run always when the targeted upgrades feature is enabled, at least in the e2e test suite. 

```suggestion
		if feature.TargetedUpgrades.Enabled() || !features.StandaloneMode.Enabled() {
```

2023-09-08 09:08 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +    export RHACS_STANDALONE_MODE=${RHACS_STANDALONE_MODE:-$RHACS_STANDALONE_MODE_DEFAULT}
What is the difference between `RHACS_USE_OPERATORS_CONFIGMAP` and `RHACS_STANDALONE_MODE`? I would prefer to have one environmental variable (`RHACS_STANDALONE_MODE`) for simplicity.

2023-09-11 13:07 UTC, kurlov commented on dev/env/scripts/lib.sh
> +    export RHACS_STANDALONE_MODE=${RHACS_STANDALONE_MODE:-$RHACS_STANDALONE_MODE_DEFAULT}
There is no `RHACS_USE_OPERATORS_CONFIGMAP` anymore

2023-09-11 15:27 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +    export RHACS_STANDALONE_MODE=${RHACS_STANDALONE_MODE:-$RHACS_STANDALONE_MODE_DEFAULT}
Than I found some dead code :skull: 

https://github.com/stackrox/acs-fleet-manager/pull/1196/files#diff-03ca885f8fbb44cbdf5d57ecccdefe690f69d32d4cf79db86a78f34723e07986R59-R62

2023-09-14 11:25 UTC, merged