ROX-19013: Add gitops to fleetshard
stackrox/acs-fleet-manager pull request #1234
Opened 2023-09-04 07:51 UTC by ludydoo

## Description
Uses the `centralYAML` from the gitops config to reconcile the centrals. 

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [x] Added test description under `Test manual`
- [ ] ~~Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
- [ ] CI and all relevant tests are passing
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~
- [ ] ~~Add secret to app-interface Vault or Secrets Manager if necessary~~
- [ ] ~~RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~~
- [ ] ~~Check AWS limits are reasonable for changes provisioning new resources~~

## Test manual

- Use a hardcoded gitops config
- Add an override patch to modify the central instance
- Verify that the patch is applied to Centraly lint binary test test/integration

2023-09-05 07:58 UTC, SimonBaeumer requested changes
Please add an automated test for the gitops config when it is enabled.

2023-09-14 15:54 UTC, SimonBaeumer approved these changes

2023-09-14 15:54 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if features.GitOpsCentrals.Enabled() {
In case GitOps config is enabled, but the response is empty it should fallback on the legacy version.
With the following release we can remove the backward-compatibility switch. By doing that we support older fleet-manager verisons in case of a rollback.

2023-09-14 16:00 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if features.GitOpsCentrals.Enabled() {
When `getInstanceConfigWithGitops` returns an error would be more accurate, empty could a valid state

2023-09-14 16:16 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if features.GitOpsCentrals.Enabled() {
Resolving the conversation after private meeting

2023-09-15 05:12 UTC, merged