WIP: RHSSO dynamic clients rotation API
stackrox/acs-fleet-manager pull request #1236
Opened 2023-09-04 11:15 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-09-08 12:47 UTC, johannes94 requested changes
Please also update the API [documentation](./openapi/fleet-manager-private-admin.yaml).

2023-09-08 12:47 UTC, johannes94 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +func (h adminCentralHandler) RotateSecrets(w http.ResponseWriter, r *http.Request) {
The name of this handler could be ambiguous. We also store other secrets within a central request of FM DB which are not rotated by this operation. I'd suggest to make it more specific like you did in the service, something like `RotateCentralRHSSOClient'.

2023-09-08 12:47 UTC, johannes94 commented on internal/dinosaur/pkg/routes/route_loader.go
> +	adminCentralsRouter.HandleFunc("/{id}/rotate-secrets", adminCentralHandler.RotateSecrets).
See comment about the handler name, the route should also reflect that.

2023-09-08 12:47 UTC, johannes94 commented on internal/dinosaur/pkg/routes/route_loader.go
> +		Methods(http.MethodPatch)
I'd prefer http.MethodPost at this point. For me `PATCH` indicates that I partially update the resource with the resource body I send. Which doesn't match to what the endpoint is doing.

2023-09-08 17:40 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/routes/route_loader.go
> +		Methods(http.MethodPatch)
I think `POST` does not apply here because `POST` indicates the creation of a new resource, while `PATCH` indicates partial modification of an existing resource. 

I agree with you that having `PATCH` without a body is weird as well(although If I read correctly does not go against [RFC](https://www.rfc-editor.org/rfc/rfc5789#section-2). IMHO out of all 3 potential methods(`POST`, `PUT`, `PATCH`) I think `PATCH` comes the closest to the standard.

2023-09-08 17:42 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +func (h adminCentralHandler) RotateSecrets(w http.ResponseWriter, r *http.Request) {
My original idea was that we might want to extend this endpoint with more secret rotation in the future, however, there's no indication it will ever be the case. I'll rename the handler 👍

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +			centralRequest, svcErr := h.service.Get(ctx, id)
Let's keep it simple and refer to it as `err`, there's no shadowing here which would require another name for the error.

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/rhsso/augment.go
> +	name := stringutils.Truncate(fmt.Sprintf("acsms-%s", r.Name), dynamicClientsNameMaxLength)
With the other name change PR you had, shall we also change the name to `acscs` here?

Shouldn't really make a difference since they are anways referred to by client ID.

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/routes/route_loader.go
> +		Methods(http.MethodPatch)
What we're doing here isn't really REST since it's not necessarily related to `CRUD` (you don't really create a resource, or update it per-se, but rather trigger an action).

Looking at the overall industry, `POST` seems to be the common standard to use when triggering actions like revoking things, let's use it instead of `PATCH`.

Both are also open for extending it, like we said in case we want to rotate _more_ secrets than just the sso.r.c dynamic client.

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/routes/route_loader.go
> +	adminCentralsRouter.HandleFunc("/{id}/rotate-secrets", adminCentralHandler.RotateSecrets).
Hmm, I think we have two ways to go here:
- Either keep this one "generic" and leave it open for extending it.
- Create "RPC-style" API which has options like `rotate/dynamic-client`, `rotate/dns` or whatever else we might want to rotate for an existing instance in the future.

Having the extensibility in mind, I wouldn't mind keeping it "unspecific" and have the option to extend it further down the road.

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +	RotateCentralRHSSOClient(ctx context.Context, centralRequest *dbapi.CentralRequest) *errors.ServiceError
Maybe as a follow-up, let's use this opportunity to get rid of the `dinosaurRequest` naming within this file.

2023-09-08 20:49 UTC, dhaus67 commented on pkg/errors/errors.go
> +	ErrorClientRotationNotConfiguredReason string           = "RHSSO client rotation is not configured"
Is it really `ClientRotationNotConfigured` or rather `DynamicClientNotConfigured`?

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +		glog.Errorf("Created new RHSSO dynamic client, but failed to update central record, client ID is %s", centralRequest.AuthConfig.ClientID)
Maybe use `rotated` here so it's easier searchable?

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +		return errors.NewWithCause(errors.ErrorClientRotationFailed, err, "failed to delete previous OIDC client")
```suggestion
		return errors.NewWithCause(errors.ErrorClientRotationFailed, err, "failed to delete previous RHSSO dynamic client")
```

2023-09-08 20:49 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +		glog.Errorf("Failed to delete RHSSO dynamic client, client ID is %s", centralRequest.AuthConfig.ClientID)
(not related to this PR): wonder whether it'd be better to create metrics for this and alerts?

Feels like this is definitely something we want to have and persist it, would also help make life easier in terms of a) discovering it and b) investigating it.

But, probably more of a follow-up thing instead of this PR.

2023-09-11 17:28 UTC, ivan-degtiarenko commented on pkg/errors/errors.go
> +	ErrorClientRotationNotConfiguredReason string           = "RHSSO client rotation is not configured"
It's possible for client rotation not to be configured but dynamic clients to be configured, because in code we give preference to static configuration if it's configured

2023-09-12 07:11 UTC, johannes94 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +func (h adminCentralHandler) RotateSecrets(w http.ResponseWriter, r *http.Request) {
No need to rename, see comment below.

2023-09-12 12:04 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/routes/route_loader.go
> +		Methods(http.MethodPatch)
`POST` it is

2023-09-12 12:05 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +	RotateCentralRHSSOClient(ctx context.Context, centralRequest *dbapi.CentralRequest) *errors.ServiceError
I'll create a follow-up PR 👍

2023-09-12 12:05 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +		glog.Errorf("Created new RHSSO dynamic client, but failed to update central record, client ID is %s", centralRequest.AuthConfig.ClientID)
Reworked the error message

2023-09-12 12:09 UTC, dhaus67 commented on pkg/errors/errors.go
> +	ErrorClientRotationNotConfiguredReason string           = "RHSSO client rotation is not configured"
Should we call it `DynamicClientNotUsed` then? My point is we don't have a configuration for client rotation, and if anyone other than the two of us reads the error message they might be confused as to what is going on / why it isn't working; and which configuration option to set 😅

2023-09-12 12:09 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +		glog.Errorf("Failed to delete RHSSO dynamic client, client ID is %s", centralRequest.AuthConfig.ClientID)
For me, the path for discovery and investigation is pretty straightforward:
1. Discovery - ACSCS operator sends request to rotate secrets, gets status code other than `2xx`
2. Investigation - ACSCS operator goes into fleet-manager logs and finds the reason for that failure

Metrics and alerts I think would be needed in case we decide to automate client rotation in the future.

2023-09-12 12:11 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +		glog.Errorf("Failed to delete RHSSO dynamic client, client ID is %s", centralRequest.AuthConfig.ClientID)
Yeah fair, my thinking is more or less that we extend this to _all_ delete operations and also cover stale clients during instance cleanup (which isn't really something we know currently _unless_ there's an issue, and stuff is quite hard to track back).

For the API, I agree it's pretty straight forward and not required, so feel free to skip this comment for now.

2023-09-12 21:16 UTC, dhaus67 approved these changes

2023-09-12 21:16 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +		return errors.New(errors.ErrorDynamicClientsNotUsed, "RHSSO dynamic configuration is not present")
```suggestion
		return errors.New(errors.ErrorDynamicClientsNotUsed, "RHSSO dynamic client configuration is not present")
```

2023-09-12 21:16 UTC, dhaus67 commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +	"github.com/stackrox/acs-fleet-manager/internal/dinosaur/pkg/rhsso"
Let's format this properly and put it below to the non-standard packages.

2023-09-13 07:34 UTC, johannes94 approved these changes
LGTM

2023-09-13 17:54 UTC, merged