ROX-19558: Mount gitops config to Fleet Manager
stackrox/acs-fleet-manager pull request #1241
Opened 2023-09-06 09:20 UTC by kurlov

## Description

Add `gitops-config-file` which later can be used to parse  gitops config in fleet manager. This file represents configmap from gitops repository

## Checklist (Definition of Done)

~~- [ ] Unit and integration tests added~~
~~- [ ] Added test description under `Test manual`~~
~~- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
~~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~
~- [ ] Add secret to app-interface Vault or Secrets Manager if necessary~~
~~- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~~
~~- [ ] Check AWS limits are reasonable for changes provisioning new resources~~

## Test manual

N/A

2023-09-06 10:19 UTC, ludydoo commented on templates/service-template.yml
> +              subPath: gitops-config
Should this be `stage/prod.yaml` ?

2023-09-07 09:28 UTC, kurlov commented on templates/service-template.yml
> +              subPath: gitops-config
No, it's already mapped correctly to the clusters ( e.g. stage config passed to stage and  prod config passed to the prod cluster)

2023-09-08 09:40 UTC, SimonBaeumer requested changes

2023-09-08 09:40 UTC, SimonBaeumer commented on templates/service-template.yml
> +            - name: gitops-config
What is being mounted? The volume is missing which references the ConfigMap, see lines 1002-1065.

2023-09-08 09:40 UTC, SimonBaeumer commented on templates/service-template.yml
> +            - --gitops-config-file=/config/gitops-config
This argument does not exist, the gitops-config can be a hardcoded mount location, there is no need for 
 a dynamic path configuration.

2023-09-11 13:36 UTC, SimonBaeumer requested changes

2023-09-11 13:36 UTC, SimonBaeumer commented on templates/service-template.yml
> +            configMap:
Please mark it as [optional](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#optional-references), otherwise fleet-manager can't start when the ConfigMap can't be mounted.

2023-09-12 14:23 UTC, SimonBaeumer approved these changes

2023-09-13 15:14 UTC, merged