michael/ROX-19507-expiration-worker
stackrox/acs-fleet-manager pull request #1248
Opened 2023-09-08 14:32 UTC by 0x656b694d

2023-09-08 14:32 UTC, 0x656b694d commented
Current dependencies on/for this PR:

  * main
    * **PR #1240**
    * **PR #1248** 👈

2023-09-11 17:14 UTC, 0x656b694d commented
/test e2e

2023-09-12 03:13 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
I'm afraid we have to go down to the cloud account ID level here. So if the billing model is one of the cloud marketplaces, we need `Consumed() <= Allowed() && cloud_account_id in cloud_accounts`. Where `cloud_accounts` is the list of of active cloud accounts returned by `/quota_cost?fetchCloudAccounts=true`.

2023-09-12 08:47 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
Are you saying that quota cost can have `allowed == 0`, but still have entitlement if cloud account is active?

2023-09-12 09:46 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
Or, is it that we also need to check if the account is active in addition to `allowed == 0`?

2023-09-12 11:06 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
No what I'm saying is that an instance can be expired even if `allowed > 0`, because `cloud_account_id` is no longer part of `cloud_accounts`. This happens if the cloud account that initially registered the instance has unsubscribed, but another account still provides quota.

2023-09-12 11:22 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
Basically we need:
* For `billing_model=standard`: `consumed <= allowed`
* For `billing_model=marketplace_*`: `consumed <= allowed && cloud_account_id in cloud_accounts`.

`allowed==0` would fail the first condition if any instance is still alive.

2023-09-12 11:48 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
Kafka thinks quota is entitled even if overconsumed. So the reaction could be different between `allowed=0 && consumed>0` and `allowed==1 && consumed==2`.

2023-09-12 14:18 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			// When an SKU entitlement expires in AMS, the allowed value for that quota cost is set back to 0.
Please take a look at the updated logic:
* it maps the allowed quota costs to cloud and standard models, for convenience;
* for cloud accounts: checks it is present in the list of quota cloud accounts;
* for standard accounts: checks if there is some allowed quota in the list.

2023-09-12 14:31 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/quota_management_list_service.go
> +
empty line

2023-09-12 14:31 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		active, ok := subscriptionStatusByOrg[central.OrganisationID]
let's rename `ok` to `exists` or `isPresent`

2023-09-12 15:35 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		if arrays.Contains(constants.GetDeletingStatuses(), central.Status) {
Indeed.

2023-09-12 15:35 UTC, 0x656b694d commented on internal/dinosaur/constants/central.go
> +func GetDeletingStatuses() []string {
Requires future refactoring.

2023-09-12 15:54 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/dinosaur.go
> +func (k *dinosaurService) IsQuotaEntitlementActive(centralRequest *dbapi.CentralRequest) (bool, error) {
Thanks. Moved the code to the `grace_period_mgr`.

2023-09-13 21:44 UTC, 0x656b694d commented
/test e2e

2023-09-14 16:13 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +	centrals, svcErr := k.dinosaurService.ListByStatus(constants.GetDeletingStatuses()...)
Brilliant! Fixed.

2023-09-19 08:23 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +func (q amsQuotaService) IsQuotaEntitlementActive(central *dbapi.CentralRequest) (bool, error) {
```suggestion
func (q *amsQuotaService) IsQuotaEntitlementActive(central *dbapi.CentralRequest) (bool, error) {
```

2023-09-19 08:23 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	isCloudAccount := central.CloudAccountID != "" && central.CloudProvider == awsCloudProvider
I think just `central.CloudAccountID != ""` is enough

2023-09-19 08:29 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
> +		dinosaurConfig:  dinosaurConfig,
Let's not add more dinosaurs

2023-09-19 08:35 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr_test.go
> +		gpm := NewGracePeriodManager(dinoSvc, quotaFactory, defaultCfg)
nit: let's rename to something more telling, even just `mgr`

2023-09-19 09:51 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +func (q amsQuotaService) IsQuotaEntitlementActive(central *dbapi.CentralRequest) (bool, error) {
TODO for future refactoring: all other methods need to be changed.

2023-09-19 09:59 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	isCloudAccount := central.CloudAccountID != "" && central.CloudProvider == awsCloudProvider
Ok.

2023-09-19 10:03 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
> +		dinosaurConfig:  dinosaurConfig,
TODO for future refactoring: rename dinosaur to central.

2023-09-19 10:04 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		dinosaurConfig:      dinosaur,
TODO for future codebase-wide refactoring.

2023-09-19 10:05 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr_test.go
> +		gpm := NewGracePeriodManager(dinoSvc, quotaFactory, defaultCfg)
ok

2023-09-19 21:54 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	var foundUnsupportedBillingModel string
Why store only the last one? Wouldn't it be more practical to just return the list of unsupported billing models?

2023-09-19 22:05 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		!isCloudAccount && len(quotasMap[amsv1.BillingModelStandard]) > 0 ||
Maybe extract the first condition into a separate variable for readability?

2023-09-19 22:09 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		!isCloudAccount && len(quotasMap[amsv1.BillingModelStandard]) > 0 ||
Technically there is also the possibility that quota exists, but `allowed < consumed`. I.e. consider the case that 2 subscriptions gave quota for 20 instances, and 15 instances are created. Then one subscription expires, and there is only quota for 10 instances. The customer would then be 5 over the limit.

Note that this is an edge case, and in general we don't care much about the number of Centrals as long as the number is not unreasonably big. So I would be fine with ignoring this check here, and only enforce it on instance creation. Just wanted to point it out so it's a conscious decision to do so.

2023-09-19 22:17 UTC, stehessel commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		dinosaurConfig:      dinosaur,
I'd encourage boy scout rules. Maybe a follow up PR to do the renaming so we actually do it?

2023-09-19 22:24 UTC, stehessel commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		active, exists := subscriptionStatusByOrg[central.OrganisationID]
What if an organisation has some Centrals that are expired and some that are entitled? I think we have to check it for every Central individually.

2023-09-19 22:26 UTC, stehessel commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +	glog.Infof("no grace_from changes needed for central %q, skipping update", central.ID)
Not sure we need this log, could create some spam.

2023-09-21 12:49 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +	glog.Infof("no grace_from changes needed for central %q, skipping update", central.ID)
ok

2023-09-21 13:39 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		active, exists := subscriptionStatusByOrg[central.OrganisationID]
The code was taken from the Kafka implementation. But your argument is valid for our case.
Here we call OMS to query for `quotacost(orgID)`. I'll introduce a cache to not abuse the OMS service.

2023-09-21 13:41 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	var foundUnsupportedBillingModel string
Dumb copy-paste. Fixed.

2023-09-21 13:45 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		!isCloudAccount && len(quotasMap[amsv1.BillingModelStandard]) > 0 ||
I had such a check in the commit history, which would only log a message, that nobody would probably read. It had been suggested to remove the logging.

2023-09-21 13:56 UTC, 0x656b694d commented on internal/dinosaur/pkg/migrations/20230911090600_add_grace_from_to_central_request.go
> +		GraceFrom *time.Time `json:"grace_from"`
Yes. I'm not sure I'll implement migration testing in this or in a parallel PR.

2023-09-21 19:49 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +			WorkerType: "grace_period_worker",
There could be various reasons why instances may run in grace period. All cases will be covered by this worker.

2023-09-22 06:36 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +			WorkerType: "grace_period_worker",
@0x656b694d what could be the reasons?

2023-09-22 06:41 UTC, ivan-degtiarenko commented on pkg/client/ocm/cache.go
> +	for k, ts := range c.ts {
nit: right now average, best and worst write complexity of this cache is `O(n)`.  Perhaps we could introduce a minimal time that needs to pass between two cleanups?

2023-09-22 06:46 UTC, ivan-degtiarenko commented on pkg/client/ocm/cache.go
> +	data map[K]V
nit: by uniting `V` and `time.Time` in a single struct we could reduce amount of map lookups

2023-09-22 06:59 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		active, err := quotaService.CheckIfQuotaIsDefinedForInstanceType(central, types.DinosaurInstanceType(central.InstanceType))
1. Why do we check that quota is defined, but return whether quota is active? AFAIU quota can be defined but be inactive(`consumed` > `allowed`).
2. Since `CheckIfQuotaIsDefinedForInstanceType` is called in `DetectInstanceType` which is called [before](https://github.com/stackrox/acs-fleet-manager/blob/d48925a3f952a067c83b2fa68eac82f66e500c7b/internal/dinosaur/pkg/services/dinosaur.go#L264-L264) `reserveQuota`, new hack that we introduced won't work as it is executed within `reserveQuota`

2023-09-22 10:51 UTC, ivan-degtiarenko commented on pkg/client/ocm/cache.go
> +	Add(key K, value V) V
I don't see big practical reason to return value here

2023-09-22 10:51 UTC, ivan-degtiarenko commented on pkg/client/ocm/cache.go
> +	return rec.value, ok
is it possible to make generic accept only pointer types and return `nil` here?

2023-09-22 10:51 UTC, ivan-degtiarenko commented on pkg/client/ocm/client.go
> +		qcl, err := quotaCostClient.List().Parameter("fetchRelatedResources", true).Parameter("fetchCloudAccounts", true).Send()
I don't see under which conditions this value will be different from `quotaCostList`

2023-09-22 13:14 UTC, 0x656b694d commented on pkg/client/ocm/cache.go
> +	return rec.value, ok
Generic could operate with a pointer to the generic parameter. But why?

2023-09-22 13:18 UTC, 0x656b694d commented on pkg/client/ocm/cache.go
> +	Add(key K, value V) V
Syntactic sugar, see the use: https://github.com/stackrox/acs-fleet-manager/blob/54f591b36233fb837def3aea0e800015d05cbcdc/pkg/client/ocm/client.go#L726

2023-09-22 13:18 UTC, 0x656b694d commented on pkg/client/ocm/client.go
> +		qcl, err := quotaCostClient.List().Parameter("fetchRelatedResources", true).Parameter("fetchCloudAccounts", true).Send()
Do you mean it could be
```go
var err error
quotaCostList, err = quotaCostClient.List()...
```
?

2023-09-25 10:30 UTC, ivan-degtiarenko commented on pkg/client/ocm/cache.go
> +	return rec.value, ok
Right now it's possible to return something like `<outdated value>, false` which assumes that the caller must check `ok` flag.

2023-09-25 10:37 UTC, ivan-degtiarenko commented on pkg/client/ocm/client.go
> +		qcl, err := quotaCostClient.List().Parameter("fetchRelatedResources", true).Parameter("fetchCloudAccounts", true).Send()
Yes

2023-09-25 10:39 UTC, ivan-degtiarenko commented on pkg/client/ocm/client.go
> +		quotaCostList = c.quotaCostCache.Add(organizationID, qcl)
Github does not let me comment on unmodified lines, but I think here
https://github.com/stackrox/acs-fleet-manager/pull/1248/files#diff-8bc7204e8ebade976e69f40acf5a0b8ad416e9d4bd53050bfcf5104217330c0aR733
we don't have to append the same quota cost multiple times if `resourceName` and `product` matches

2023-09-25 10:44 UTC, ivan-degtiarenko commented on pkg/client/ocm/cache.go
> +func NewCache[K comparable, V any](age time.Duration) *cacheImpl[K, V] {
My IDE tells me:
```
Exported function with the unexported return type
```

2023-09-25 10:53 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		// If the allowed value is 0 and consumed is greater than this, that denotes that the SKU entitlement
We don't check that `consumed > 0` here

2023-09-25 10:58 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	if len(costsMap) == 0 && len(foundUnsupportedBillingModels) > 0 {
Why do we fail if we find an unsupported billing model? Can we just ignore them? I think that would be more error-proof approach considering quota configuration is external to `fleet-manager`

2023-09-25 11:10 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	standardAccountIsActive := !isCloudAccount && len(quotasMap[amsv1.BillingModelStandard]) > 0
What will happen if org has several subscriptions with billing model standard and one of them expires? Since we only check that `len(quotasMap[amsv1.BillingModelStandard]) > 0`, would that mean that customer will be able to have more instances that current subscriptions allow them?

Same question applies to non-standard billing model case.

2023-09-25 11:11 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	quotasMap, err := mapAllowedQuotaCosts(quotaCosts)
`quotasMap` does not really tell what is the key and what is the value in this map

2023-09-25 12:56 UTC, 0x656b694d commented on pkg/client/ocm/client.go
> +		qcl, err := quotaCostClient.List().Parameter("fetchRelatedResources", true).Parameter("fetchCloudAccounts", true).Send()
Ok!

2023-09-25 21:10 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		// If the allowed value is 0 and consumed is greater than this, that denotes that the SKU entitlement
Yup. Not sure what would be the difference if we checked.

2023-09-25 21:14 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	if len(costsMap) == 0 && len(foundUnsupportedBillingModels) > 0 {
We fail because there's no supported model. We decide on entitlement based on that, so I'd rather not swallow errors.

2023-09-29 10:21 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	if len(costsMap) == 0 && len(foundUnsupportedBillingModels) > 0 {
So the error then is not that there is unsupported billing model, but rather that there are no supported billing models with active SKU entitlement. Let's make error message reflect that

2023-10-03 14:24 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +			WorkerType: "grace_period_worker",
Contract expiration, subscription expiration, overconsumption due to quota change, account deleted, etc?

2023-10-05 11:50 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	quotasMap, err := mapAllowedQuotaCosts(quotaCosts)
Still named the same

2023-10-05 11:52 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	if len(costsMap) == 0 && len(foundUnsupportedBillingModels) > 0 {
Not addressed

2023-10-05 12:31 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return false, errors.InsufficientQuotaError("%v: error getting quotas for product %q", err, quotaType.GetProduct())
Why is this an insufficient quota error and not general error?

2023-10-05 12:31 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/quota_management_list_service.go
> +		userIsRegistered = org.GetMaxAllowedInstances() > 0
Let's not hide another condition under `userIsRegistred` variable

2023-10-05 12:31 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +	centrals, svcErr := k.centralService.ListByStatus(
Consider situation where another state would be added - how would the person who adds it know that it should be added here as well? Let's create some method that will return these statuses in `internal/dinosaur/constants/central.go`

2023-10-05 12:31 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +			defined, svcErr = quotaService.CheckIfQuotaIsDefinedForInstanceType(central, types.DinosaurInstanceType(central.InstanceType))
The naming is confusing - the method is called `CheckIfQuotaIsDefinedForInstanceType` and returns `defined` variable, but what it **actually** returns is `isQuotaEntitlementActive`. Why don't we rename the method accordingly?

2023-10-05 12:31 UTC, ivan-degtiarenko commented on pkg/client/ocm/client.go
> +	const pageSize = 100
let's move `const` to the top of the file

2023-10-09 12:19 UTC, 0x656b694d commented on pkg/client/ocm/cache.go
> +	return rec.value, ok
The code has been removed.

2023-11-14 09:36 UTC, 0x656b694d commented
/retest

2023-11-14 16:33 UTC, 0x656b694d commented
/retest

2023-11-14 20:42 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +			standard_active, err := quotaService.IsQuotaActive(dinosaur, types.STANDARD)
Let's not name variables with `_`

2023-11-14 20:42 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +func Test_amsQuotaService_CheckQuotaEntitlement(t *testing.T) {
```suggestion
func Test_amsQuotaService_IsQuotaActive(t *testing.T) {
```

2023-11-15 10:05 UTC, 0x656b694d commented on internal/dinosaur/constants/central.go
> +	for status, ordinal := range ordinals {
Not sure we want to list statuses explicitely, as we may miss a later added status. Moreover, not sure we even want to limit the list of statuses for which we set the `expired_at`.

2023-11-15 10:21 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			"failed to get assigned quota of type %q for organization with external id %q and id %q",
Won't hurt showing both either, I guess.

2023-11-15 10:25 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +			string(quotaType), central.OrganisationID, org.ID()))
It would, indeed.

2023-11-15 10:47 UTC, 0x656b694d commented on pkg/client/ocm/client.go
> +			return nil, fmt.Errorf("retrieving relatedResources from the QuotaCosts service: %w", err)
`fmt.Errorf` is closer above, that's why.

2023-11-16 13:24 UTC, ivan-degtiarenko commented on pkg/client/ocm/client.go
> +			return nil, fmt.Errorf("retrieving calling QuotaCosts service: %w", err)
I think you meant something else here

2023-11-16 13:55 UTC, ivan-degtiarenko commented on internal/dinosaur/constants/central.go
> +	for status, ordinal := range ordinals {
Listing statuses implicitly does not work here:
1. It does not work now, because in the only non-test usage we have to append another status that has too big of an ordinal. The only usage of this function already has to adjust the result.
2. It won't work in the future, because there's no guarantee our state machine will be sequential. What if we add status `Paused` - would it go before or after `Ready`/`Deprovision`? I think the question whether we expire `paused` instances would better be handled explicitly and not accidentally by choosing the wrong(or right) ordinal

> Moreover, not sure we even want to limit the list of statuses for which we set the `expired_at`.

Setting/unsetting (remember we do both depending on quota allowance) `expired_at` for instances in `Deprovision`/`Deleting` state would not change anything for them at best, at worst - create a confusing record in the database of central request that was deleted due to lack of quota allowance but has no `expired_at` set.
Let's work only with instances we can actually delete in expiration manager.

2023-11-16 13:56 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		// If the allowed value is 0 and consumed is greater than this, that denotes that the SKU entitlement
In that case let's remove the part about consumed

2023-11-16 14:03 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +	const not_allowed = 0
let's not name variables or constants with `_`

2023-11-16 14:04 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +func makeOrganizationFromExtID(externalId string) (*v1.Organization, error) {
```suggestion
func makeOrganizationFromExternalID(externalId string) (*v1.Organization, error) {
```

We can allow ourselves 5 more letters 😉

2023-11-16 14:05 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +func makeStandardTestQuotaCost(resourceName string, organizationID string, allowed int, consumed int, t *testing.T) *v1.QuotaCost {
```suggestion
func makeStandardTestQuotaCost(resourceName, organizationID string, allowed, consumed int, t *testing.T) *v1.QuotaCost {
```

2023-11-16 19:03 UTC, 0x656b694d commented on pkg/client/ocm/client.go
> +	for page := 1; ; page++ {
I temporarily set page size to 2 and added logging to the item processing functor in my local binary:
```go
		items++
		glog.V(10).Infof("fetched item %d", items)
```
And observed the following in the log, ensuring we're fetching all pages:
```console
$ kubectl logs fleet-manager-66d8fcd4df-ldnhd| grep fetched
Defaulted container "fleet-manager" out of: fleet-manager, db-migrate (init)
I1116 18:56:06.737468      13 client.go:641] fetched item 1
I1116 18:56:06.738223      13 client.go:641] fetched item 2
I1116 18:56:06.875013      13 client.go:641] fetched item 3
I1116 18:56:06.875026      13 client.go:641] fetched item 4
I1116 18:56:07.001512      13 client.go:641] fetched item 5
I1116 18:56:07.001549      13 client.go:641] fetched item 6
I1116 18:56:07.129293      13 client.go:641] fetched item 7
I1116 18:56:07.129342      13 client.go:641] fetched item 8
I1116 18:56:07.255719      13 client.go:641] fetched item 9
I1116 18:56:07.255738      13 client.go:641] fetched item 10
I1116 18:56:07.393687      13 client.go:641] fetched item 11
I1116 18:56:07.393729      13 client.go:641] fetched item 12
...
```
We may notice that the log timestamps are close in groups of 2 records, which is the size of the page.

2023-11-17 08:48 UTC, 0x656b694d commented on internal/dinosaur/constants/central.go
> +	for status, ordinal := range ordinals {
Ok.

2023-11-17 08:53 UTC, 0x656b694d commented on internal/dinosaur/constants/central.go
> +	for status, ordinal := range ordinals {
FTR. The statuses have ordinals exactly for the purpose of ordering. So if we pause a ready instance, it would be "Paused Ready" status, I guess. In this case iterating over statuses by ordinals have full sense.
The Failed status is an exceptional state, so handled exceptionally.

2023-11-17 09:03 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +	const not_allowed = 0
O_k.

2023-11-17 09:05 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +func makeStandardTestQuotaCost(resourceName string, organizationID string, allowed int, consumed int, t *testing.T) *v1.QuotaCost {
I remember receiving a request to do the opposite. So I keep types for each parameter since. Sorry.

2023-11-17 09:06 UTC, 0x656b694d commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +func makeCloudTestQuotaCost(resourceName string, organizationID string, allowed int, consumed int, t *testing.T) *v1.QuotaCost {
Same.

2023-11-21 12:50 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/grace_period_mgr.go
> +		dinosaurConfig:      dinosaur,
Renamed dinosaurs in the file.

2023-11-21 13:27 UTC, SimonBaeumer requested changes

2023-11-21 13:27 UTC, SimonBaeumer commented on internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
> +package dinosaurmgrs
This could a service/manager which provides these function and being reconciled in the ready dinosaur manager. By doing this the ready worker finally gets a purpose and we don't need to introduce a new worker for a single field.

2023-11-23 11:51 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +
empty line

2023-11-23 11:51 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +		if page == maxPages {
I would rather put this check at the beginning of the cycle and replace with `page == maxPages + 1` so we would not break on the `maxPage` if it has `pageSize` elements

2023-11-23 12:31 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +
Right, to separate function parameters from the body.

2023-11-23 12:55 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +		if page == maxPages {
`page` will never be equal to `maxPages+1` inside the loop.
Having this check here gives a chance to break normally in case the `page[maxPages]` is the last page.

2023-11-23 13:53 UTC, 0x656b694d commented on internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
> +package dinosaurmgrs
As agreed, let's refactor the worker as a separate effort.

2023-11-24 13:14 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +
Why this function is different from others that it requires such separation?

2023-11-24 13:14 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +	}
I think I need to correct my suggestion. I think it is still correct **not to fail** when `maxPages` page has `pageSize` elements.

```suggestion
	for page := 1; page <= maxPages + 1; page++ {
		response, err := req.Page(page).Send()
		if err != nil {
			return pkgerrors.Wrapf(err, "error retrieving page %d", page)
		}
		keepGoing := true
		response.Items().Each(func(data Data) bool {
			keepGoing = f(data)
			return keepGoing
		})
		if !keepGoing || response.Size() < pageSize {
			break
		}
		if page == maxPages + 1 &&  response.Size() > 0 {
			return pkgerrors.New("too many pages")
		}
	}
```

2023-11-24 18:26 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +	}
While `response.Size() == pageSize` the result is considered incomplete. The logic of `maxPages` is to query not more than `maxPages`. Therefore, the function doesn't fetch `maxPages+1` page in the hope that last page was the last one.
Anyway, the `maxPages` feature is there mostly to prevent endless fetching, so there's no big difference if we set it to 1000 or 1001 in the real usecase.
I refactored the function to better indicate the error condition.

2023-11-24 18:27 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +
Too long signature.

2023-11-24 18:43 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +
I meant body from function parameters. I don't think we usually do that

2023-11-24 18:56 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +// fetchPages calls OCM API with size and page request parameters, allowing for
If function is generic, the description should be generic as well

2023-11-24 18:56 UTC, ivan-degtiarenko commented on pkg/client/ocm/paginated_request.go
> +// Iteration stops when all or maxPages pages are retrieved, or f returns false.
That does not explain the error logic

2023-11-24 20:57 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +// fetchPages calls OCM API with size and page request parameters, allowing for
Agree. Updated.

2023-11-24 20:57 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +
The code is less readable without this empty line. We usually should do that in such cases.

2023-11-24 20:57 UTC, 0x656b694d commented on pkg/client/ocm/paginated_request.go
> +// Iteration stops when all or maxPages pages are retrieved, or f returns false.
Fixed.

2023-11-27 10:10 UTC, 0x656b694d commented
/retest

2023-11-27 10:57 UTC, merged