Remove multi target build
stackrox/acs-fleet-manager pull request #1259
Opened 2023-09-13 14:31 UTC by SimonBaeumer

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-09-18 09:15 UTC, kovayur approved these changes

2023-09-18 10:03 UTC, vladbologa requested changes
This PR seems to break `make deploy/dev` builds on my arm64 mac, please don't merge until I figure out what the problem is.

2023-09-18 17:01 UTC, vladbologa requested changes
There is a small error in `docker.sh` and the regular build is made even if `ARCH==arm64.

If I fix that, I still run into this problem that I haven't yet fixed:
```
2023-09-18T18:53:11,N:z Applying resource from '/dev/env/manifests/fleet-manager/01-fleet-manager-secrets.yaml'
secret/fleet-manager created
2023-09-18T18:53:11,N:z Applying resource from '/dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml'
deployment.apps/fleet-manager created
2023-09-18T18:53:12,N:z Applying resource from '/dev/env/manifests/fleet-manager/03-fleet-manager-service.yaml'
service/fleet-manager created
deployment.apps/fleet-manager env updated
deployment.apps/fleet-manager env updated
deployment.apps/fleet-manager env updated
deployment.apps/fleet-manager env updated
deployment.apps/fleet-manager env updated
2023-09-18T18:53:12,N:z Waiting for container fleet-manager within pod application=fleet-manager in namespace acsms to appear...
2023-09-18T18:55:22,N:z Timed out waiting for container fleet-manager to appear for pod application=fleet-manager in namespace acsms
make: *** [deploy/dev] Error 1
```

If I switch to the main branch, the deployment works fine.

2023-09-19 09:27 UTC, vladbologa requested changes
I'm still having problems running the scripts. Can you please check that `make deploy/dev` works for you?

For me it times out waiting for fleet-manager to start:
```
2023-09-19T11:20:58,N:z Waiting for container fleet-manager within pod application=fleet-manager in namespace acsms to appear...
2023-09-19T11:23:08,N:z Timed out waiting for container fleet-manager to appear for pod application=fleet-manager in namespace acsms
make: *** [deploy/dev] Error 1
```

2023-09-19 09:27 UTC, vladbologa commented on Makefile
>  deploy/dev-fast: image/build deploy/dev-fast/fleet-manager deploy/dev-fast/fleetshard-sync
`make deploy/dev` now uses `image/build/local`
`make deploy/dev-fast` uses `image/build`

Is that intentional?

2023-09-19 09:27 UTC, vladbologa commented on dev/env/scripts/docker.sh
>                          log "Building standard image..."
```suggestion
                        log "Building local image..."
```

2023-09-19 15:00 UTC, vladbologa requested changes

2023-09-21 13:28 UTC, SimonBaeumer commented on dev/env/scripts/docker.sh
> +                    if [[ $"ARCH" == "arm64" ]]; then
done

2023-09-21 13:28 UTC, SimonBaeumer commented on dev/env/scripts/docker.sh
>                          log "Building standard image..."
done

2023-09-21 13:28 UTC, SimonBaeumer commented on Makefile
> +image/build/local: DOCKERFILE="Dockerfile.local"
done

2023-09-21 14:51 UTC, vladbologa requested changes

2023-09-21 14:51 UTC, vladbologa commented on Makefile
>  deploy/dev-fast: image/build deploy/dev-fast/fleet-manager deploy/dev-fast/fleetshard-sync
```suggestion
deploy/dev-fast: deploy/dev-fast/fleet-manager deploy/dev-fast/fleetshard-sync
```

There was still one instance left. 😅

2023-09-22 08:09 UTC, SimonBaeumer commented on Makefile
>  deploy/dev-fast: image/build deploy/dev-fast/fleet-manager deploy/dev-fast/fleetshard-sync
:tada: fixed

2023-09-22 08:46 UTC, vladbologa approved these changes

2023-09-22 09:14 UTC, merged