ROX-11407: Configurable resource limits for Central and Scanner
stackrox/acs-fleet-manager pull request #128
Opened 2022-06-20 08:44 UTC by mtesseract

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-20 08:58 UTC, mtesseract commented
Regarding the test failures:

I thought using `MustParse` from `"k8s.io/apimachinery/pkg/api/resource"` would be the canonical way for validating resource quantities. But apparently it is not quite providing the desired semantics: It doesn't capture the fact that plain numbers like "0.5" could also be provided for CPU resources instead of something like "500m", which would be validated correctly.

Hints regarding the correct validation logic welcome!

2022-06-21 07:08 UTC, mtesseract commented
Regarding your offline remark, @SimonBaeumer: As a quick way to proceed here we could add a runtime switch (e.g. an environment variable `ALLOW_CUSTOM_CENTRAL_RESOURCES`) for enabling support for custom resource settings. Defaulting to `false`.

2022-06-21 08:32 UTC, johannes94 requested changes

2022-06-21 08:32 UTC, johannes94 commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	centralResources, err := convertPrivateResourceRequirementsToCoreV1(&remoteCentral.Spec.Central.Resources)
nit: add additional function to create complete central spec, would make it easier for me to focus on reconcile logic instead of conversion logic

2022-06-21 08:32 UTC, johannes94 commented on internal/dinosaur/pkg/migrations/20220114114500_add_centrals.go
> +		Central                       api.JSON   `json:"central"`
We have to be careful with schema changes like this. This change would not be applied to the DB for the deployment in staging SRE cluster. If we want it to be applied we either have to again rollback and reapply migrations in the DB (what I did when I was merging the dinosaur change of this Model) or we would have to create another migration file, that adds the additional columns to the already existing table.

2022-06-21 08:32 UTC, johannes94 commented on openapi/fleet-manager-private.yaml
> +  "/api/rhacs/v1/agent-clusters/{id}/status":
Looks like a lot of quote changes here, do we default to single or double quotes in yaml files?

2022-06-21 08:32 UTC, johannes94 commented on openapi/fleet-manager.yaml
> +                $ref: "#/components/schemas/VersionMetadata"
again a lot of quote changes.

2022-06-21 08:32 UTC, johannes94 commented on internal/dinosaur/pkg/presenters/dinosaur.go
> +		// TODO: Add error propagation.
Just want to make sure, you are still aware of the TODO's added.

2022-06-21 08:38 UTC, mtesseract commented on openapi/fleet-manager-private.yaml
> +  "/api/rhacs/v1/agent-clusters/{id}/status":
Yeah, that was annoying... It is what VSCode did without asking me. :-(

2022-06-21 08:39 UTC, mtesseract commented on internal/dinosaur/pkg/presenters/dinosaur.go
> +		// TODO: Add error propagation.
Yes, thank you. Before fleshing this out, I'd suggest to first discuss the approach to take from a timeline perspective.

2022-06-21 08:40 UTC, mtesseract commented on internal/dinosaur/pkg/migrations/20220114114500_add_centrals.go
> +		Central                       api.JSON   `json:"central"`
Ah, yes, adding another migration file seems like the way to go for changes like this, I assume.

2022-06-21 08:40 UTC, mtesseract commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	centralResources, err := convertPrivateResourceRequirementsToCoreV1(&remoteCentral.Spec.Central.Resources)
good point, thanks.

2022-06-23 14:25 UTC, closed without merging