ROX-19718: Add flag for fleetmanager gitops
stackrox/acs-fleet-manager pull request #1283
Opened 2023-09-18 15:34 UTC by ludydoo

## Description

This PR exposes a new flag on fleet-manager to specify the path to the gitops configuration file. 
If the flag is not specified in the command-line args, it is assumed that no gitops configuration is used.

It also enables gitops by default on for development environments.   

## Checklist (Definition of Done)

- [ ] ~~Unit and integration tests added~~
- [ ] ~~Added test description under `Test manual`~~
- [ ] ~~Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
- [ ] CI and all relevant tests are passing~~
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~
- [ ] ~~Add secret to app-interface Vault or Secrets Manager if necessary~~
- [ ] ~~RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~~
- [ ] ~~Check AWS limits are reasonable for changes provisioning new resources~~

## Test manual

1. Run as usual using `make deploy/dev`
2. Change the gitops configmap in dev/env/manifests/fleet-manager/04-gitops-config.yaml
3. Run `make deploy/dev/update-gitops-config` to update the configMap on k8s
4. Observe that the centrals are patched according to the config

2023-09-18 17:03 UTC, ludydoo commented
/retest

2023-09-18 17:59 UTC, ludydoo commented
/retest

2023-09-19 07:49 UTC, SimonBaeumer requested changes

2023-09-19 07:49 UTC, SimonBaeumer commented on dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
> +            - mountPath: /gitops-config
Mount should be optional as in production fleet-manager templates

2023-09-19 07:49 UTC, SimonBaeumer commented on internal/dinosaur/pkg/gitops/module.go
> +func (s *Module) AddFlags(fs *pflag.FlagSet) {
Why using a flag here for adding the mount path which is hardcoded in the Deployments? Do you expect the path to change, if yes, why? :thinking: 
imho a const for the path would be sufficient in this case.

2023-09-19 09:02 UTC, ludydoo commented on dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
> +            - mountPath: /gitops-config
Done

2023-09-19 09:09 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/module.go
> +func (s *Module) AddFlags(fs *pflag.FlagSet) {
It's from experience, I'm used to have the ability to specify the path to a config file from a flag or environment variable. Like `nginx -c /my/nginx-config.conf` or `PGDATA=/my/postgres/files postgres`.

The value is different (currently) between dev environment/ci and stage/prod. It is defined on dev/ci and not defined on stage/prod because we are not yet using gitops on stage/prod. 

Is it a blocker?

2023-09-19 09:13 UTC, SimonBaeumer commented on internal/dinosaur/pkg/gitops/module.go
> +func (s *Module) AddFlags(fs *pflag.FlagSet) {
> Is it a blocker?

No, it's not a blocker

2023-09-19 09:14 UTC, SimonBaeumer approved these changes

2023-09-19 09:24 UTC, kurlov approved these changes

2023-09-19 11:23 UTC, merged