Add Central deletion e2e test
stackrox/acs-fleet-manager pull request #141
Opened 2022-06-23 15:32 UTC by SimonBaeumer

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-24 05:21 UTC, johannes94 requested changes
LGTM except the one comment.

2022-06-24 05:21 UTC, johannes94 commented on e2e/e2e_test.go
> +				err = client.DeleteCentral(createdCentral.Id)
I'm not familiar with ginkgo, but it looks to me that this would send the DeleteCentral requests more than once (every polling cycle). If so, shouldn't we test that one call to delete should be sufficient to get to deprovisioning state?

2022-06-24 06:54 UTC, SimonBaeumer commented on e2e/e2e_test.go
> +				err = client.DeleteCentral(createdCentral.Id)
Good catch! Fixed it, the delete request is now send before the `Eventually` function call.

2022-06-24 07:39 UTC, johannes94 approved these changes
Looks good.

2022-06-27 07:24 UTC, kovayur approved these changes
LGTM

2022-06-27 10:58 UTC, SimonBaeumer commented
/retest

2022-06-27 11:49 UTC, kovayur approved these changes
Looks good.

2022-06-27 11:49 UTC, kovayur commented on e2e/e2e_test.go
> +
nit: extra blank line

2022-06-27 12:34 UTC, merged