ROX-21070: Add fleetshard addon installation status to private api
stackrox/acs-fleet-manager pull request #1503
Opened 2023-11-23 16:26 UTC by kovayur

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-11-23 16:26 UTC, kovayur commented
Current dependencies on/for this PR:
* main
  * **PR #1503** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1503?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1503?utm_source=stack-comment).

2023-12-18 13:07 UTC, ebensh requested changes
LGTM, thanks for the cleanups as well

2023-12-18 13:07 UTC, ebensh commented on internal/dinosaur/pkg/services/data_plane_cluster.go
> +func (d *dataPlaneClusterService) UpdateDataPlaneClusterStatus(clusterID string, status dbapi.DataPlaneClusterStatus) *errors.ServiceError {
I was surprised to see that ctx could just be removed here - digging down it looks like the clusterService in clusters.go doesn't use gorm's support for context (https://gorm.io/docs/context.html), so piping it down doesn't make sense. But do you know, is there a reason why there's no use of the context down at the database level? Is that best practice to not try to interrupt database calls with context / maybe there's some bad interaction between them?

2023-12-18 13:34 UTC, ebensh approved these changes

2023-12-19 10:04 UTC, merged