Add OCM refresh token authentication within fleetshard sync.
stackrox/acs-fleet-manager pull request #151
Opened 2022-06-28 11:41 UTC by dhaus67

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-28 11:41 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #151** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/151" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #152** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/152" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #153** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/153" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/151?utm_source=stack-comment).

2022-06-28 14:40 UTC, kovayur commented on fleetshard/pkg/fleetmanager/static-token
> +eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6InNpZyIsImtpZCI6ImwzLTU2VmdRTFBCY3NkNERKdHBiYVQ5QllJeDFTeEtXOElsS0FTUHdvQlEiLCJhbGciOiJSUzI1NiIsIm4iOiIzNXAwbGp3cmYxNkQycFN6VTdQX3I2bWgwUkpJSXZTdEJjNjJ5ZlhMRkp
Is it ok to commit this token?

2022-06-28 21:41 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +	if req.Header.Get("Authorization") == "" {
So, right now theoretically only the caller could do that (for whatever reason). Added it to be more defensive about it, but I also don't mind simply removing it to avoid potential confusion.

2022-06-28 23:07 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/static-token
> +eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6InNpZyIsImtpZCI6ImwzLTU2VmdRTFBCY3NkNERKdHBiYVQ5QllJeDFTeEtXOElsS0FTUHdvQlEiLCJhbGciOiJSUzI1NiIsIm4iOiIzNXAwbGp3cmYxNkQycFN6VTdQX3I2bWgwUkpJSXZTdEJjNjJ5ZlhMRkp
Removed it.

2022-06-29 07:12 UTC, mtodor approved these changes
Fantastic work!

2022-06-29 16:56 UTC, ivan-degtiarenko commented on fleetshard/pkg/fleetmanager/client.go
>  	ocmToken              string
Why do we need `ocmToken` field now?

2022-06-29 16:56 UTC, ivan-degtiarenko commented on fleetshard/pkg/fleetmanager/auth.go
> +type noAuth struct{}
would it make sense to move it to the test section since that's the only place it's used?

2022-06-29 16:56 UTC, ivan-degtiarenko commented on fleetshard/pkg/fleetmanager/auth_ocm.go
> +		Client("cloud-services", "").
maybe extract it to `const`?

2022-06-29 20:55 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/client.go
>  	ocmToken              string
Removed it.

2022-06-30 13:34 UTC, SimonBaeumer requested changes

2022-06-30 13:34 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/auth.go
> +package fleetmanager
Could this file be seen as a registry or factory of auth providers?
(If you agree, it is okay for me to rename in a following PR to avoid rebases)

2022-06-30 13:56 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +	OCMTokenAuthType AuthType = iota
The constants need to be definied within a common place due to the `iota` usage, otherwise we would have to manually track and set the integers accordingly to keep the enumeration correct. Seems non-idiomatic to define them separately and manually set the integer instead of using `iota` at a common place.

2022-06-30 13:56 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +package fleetmanager
Theoretically yes, although I've decided against defining the whole abstraction of factory (although it very well could be done). What's your suggestion, renaming it to `auth_factory`, even though there's no such concept of a factory?

2022-06-30 13:57 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +	return [...]string{
The `[...]string` is called an `Array literal`, where the length of the array will be equal to the number of elements given (in our case `OCM`).  We are not initializing a string but rather a string array with the length of the given elements.
Afterwards, its just a simple access to the array, not sure what's so special about that 😅

2022-06-30 13:57 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +// found, the issue will be logged and StaticTokenAuthType will be used as default.
Think there's two things: by default should be `OCMTokenAuthType`, but we can also change it to return an error and only allow valid authentication types, I don't have a strong opinion on it.

2022-07-01 07:11 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/auth.go
> +// found, the issue will be logged and StaticTokenAuthType will be used as default.
Not defaulting to OCM is more clean. The API has unexpected behaviour because I provide an AuthType, but instead of getting an error if I provide an invalid just one random will be returned.

2022-07-01 07:15 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/auth.go
> +	return [...]string{
The challenging part here is to understand that `AuthType` is a `iota` representing the index of the string array and the auth types string representation.
In this case the string array's index is depended on the value of the `AuthType`.
I would expect `AuthType` a struct and not an int, like discussed with `GetName()` func.

2022-07-01 07:20 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/auth.go
> +	OCMTokenAuthType AuthType = iota
This breaks the abstraction, no?
On one side every AuthProvider has its own file, on the other name and ID are defined in another file. 
The AuthProvider can know its name themselves, thus leaking less implementation details to the registry which only knows the interface types.

2022-07-01 07:21 UTC, SimonBaeumer approved these changes
/approve

2022-07-04 13:13 UTC, ebensh commented on dev/config/dataplane-cluster-configuration-minikube.yaml
> + - name: rancher-desktop  # Uncomment if using minikube
Please don't change this file, it's intended specifically for minikube. If you are using rancher-desktop either modify the copy or create a new one for your environment

2022-07-04 15:29 UTC, merged