Add RH SSO authentication within fleetshard sync.
stackrox/acs-fleet-manager pull request #152
Opened 2022-06-28 11:41 UTC by dhaus67

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-28 11:41 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #151** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/151" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #152** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/152" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #153** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/153" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/152?utm_source=stack-comment).

2022-06-28 17:19 UTC, mtodor commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +          - mountPath: /run/secrets/rhsso
nitpick: I would suggest using the same name in `mountPath` as we have in `name` - i.e. `/run/secrets/rhsso-token`. I know that in some cases it will redundant - `/rhsso-token/token`. But it's still easier to track what volume is related to that.

2022-06-28 17:22 UTC, mtodor commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +        image: {{ .Values.fleetshardSync.tokenRefresher.image.name }}:{{ .Values.fleetshardSync.tokenRefresher.image.tag }}
nitpick: I would suggest just using a string property for the image. i.e. `.Values.fleetshardSync.tokenRefresher.image`

2022-06-28 17:27 UTC, mtodor commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +            value: https://sso.redhat.com/auth/realms/redhat-external
I can't remember this, but is the issuer the same for production and staging RedHat SSO? If they are different, then I would suggest moving this value to Helm values. If they are the same, we can keep them as it is.

EDIT: Looks like you have already planned that. 😄 As I see, there is already `.Values.fleetshardSync.tokenRefresher.issuerUrl`.

2022-06-28 17:40 UTC, mtodor commented on fleetshard/pkg/fleetmanager/auth.go
> +		return newRHSSOAuth(tokenPath)
I would suggest using a similar interface for factory functions. Maybe we can call them without params.

For example:
```
newRHSSOAuth()
newOcmAuth()
```

And then inside the function, we are using constant or `os.Getenv("OCM_TOKEN")` in the case of `newOcmAuth`.

If we apply a suggestion to split implementations of Auth types into separate files from the first PR, then this change will also get nicely together.

2022-06-28 17:43 UTC, mtodor commented on fleetshard/pkg/fleetmanager/auth.go
> +	tokenPath = "/run/secrets/rhsso/token"
Should we consider providing this value via some command option or environment variable?

2022-06-28 17:46 UTC, mtodor commented on fleetshard/pkg/fleetmanager/auth.go
> +	setBearer(req, string(contents))
nit-nitpick: Let's call it a token.
```suggestion
	token, err := os.ReadFile(r.tokenFilePath)
	if err != nil {
		return err
	}

	setBearer(req, string(token))
```

2022-06-28 22:05 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +	tokenPath = "/run/secrets/rhsso/token"
Yeah, was thinking about this as well.
I've changed the config to be a singleton and re-use it within here, as we have the ability to provide sane defaults (like the default mount path we have in the deployment). I don't particularly like how it's currently handled with i.e. the `OCM_TOKEN` environment variable, would rather have it in a single place, so changed it to the singleton.

2022-06-28 22:05 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +		return newRHSSOAuth(tokenPath)
Fine with aligning the function signatures, albeit I won't go for the stretch and define an interface for auth type factories, i.e.
```go
type authFactory interface {
    Create() (Auth, error)
}
```
If we grow the numbers of authentication types, I think it's worthwhile to have it, but right now don't see the need to overcomplicate things.

2022-06-28 22:05 UTC, dhaus67 commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +        image: fleetsync:latest
Yeah, that wasn't planned on being pushed, my bad.

I'd vote to do the changes in a separate PR regarding defining this in Helm values, since it's impact will be a bit more broad.

2022-06-28 22:10 UTC, dhaus67 commented
@mtodor I've thought about using the RH SSO client, but ultimately decided against it due to the additionally required configuration options (i.e. realm, token endpoint URI). Instead, I followed the pattern that's already existing for the observatorium tokens. I know it'll increase complexity for the deployment / helm template, but at the very least keeps the config options to a minimum within the fleetshard sync (functionality wise, there's no difference between the token-refresher and the `GetToken()`, both will yield the required access token and handle creating a new one before expiration.

2022-06-29 08:08 UTC, mtodor approved these changes
It looks great. I have added just two small tweaks, nothing crucial.

2022-06-29 08:08 UTC, mtodor commented on fleetshard/pkg/fleetmanager/auth_rhsso.go
> +	contents, err := os.ReadFile(r.tokenFilePath)
nit-nitpick. I see that you have marked a suggestion to change this into `token` with 👍 . Probably because of refactoring, that change has been lost.

2022-06-29 21:05 UTC, dhaus67 commented on fleetshard/config/config.go
> +	RHSSOTokenFilePath   string        `env:"RHSSO_TOKEN_FILE" envDefault:"/run/secrets/rhsso-token/token"`
It can be done, I'll add some more documentation within #153 , as I've added additional docs within there.

2022-06-29 21:36 UTC, dhaus67 commented on fleetshard/config/config.go
> +		cfgErr = errors.Wrapf(err, "Unable to parse runtime configuration from environment")
Sure thing, I'll use `errorhelpers.ErrorList` since we already have the dependency within the rpeo. I also decided to short-circuit on the parsing error, since it doesn't really make sense to go through the different environment variables.

2022-06-30 13:43 UTC, SimonBaeumer requested changes

2022-06-30 13:43 UTC, SimonBaeumer commented on fleetshard/README.md
> +- OCM refresh token
I think I missed some of the conversations around SSO.
Can you refresh my memory why we support two different auth types in fleet-shard synchronizer?
(I thought OCM is for inter-service auth and RHSSO for customer auth into Central)

2022-06-30 13:43 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/auth.go
> +		"RHSSO",
Ahhhh now I understood the code 🎉 
https://github.com/stackrox/acs-fleet-manager/pull/151#discussion_r911025015

2022-06-30 13:43 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/auth.go
> +	RHSSOAuthType
Instead of having all auth types as a constant I would prefer using an `init()` func which automatically registers all auth types here by here name.
Each `AuthType` has an interface which fulfills the function `GetName() string` and returns just the static name.
The registry has a map indexed by AuthType's name `map[string]AuthType` and can access the auth type by the index.

2022-06-30 14:04 UTC, dhaus67 commented on fleetshard/README.md
> +- OCM refresh token
The reason for OCM auth type is to have the possibility to use personal tokens when using the fleetshard synchronizer locally instead of requiring everyone to use the service account's client_id / client_secret. It's merely there for enhancing the development experience.
In production, we shall always use RH SSO auth type, using the client_credentials grant.

I don't understand the comment about `inter-service auth and RHSSO for customer auth into central`.
When you obtain an OCM token, you obtain a token issued by `sso.redhat.com`. The difference is _the way of obtaining the token_. The token obtained via `ocm token` will use the `refresh_token` grant, and cannot be used by service accounts. To use service accounts and non-personalized tokens, you have to use a service account with the `client_credentials` grant.

We still are using RH SSO for log in to central as an auth provider, but this is something unrelated, as there an OAuth client is used, which is something completely different.

2022-06-30 14:04 UTC, dhaus67 commented on fleetshard/pkg/fleetmanager/auth.go
> +	RHSSOAuthType
I guess we can go that route if you want to, I just wanted to keep it simple initially since we don't plan to add anything additional, but 🤷 .

I'll do it in a follow-up PR to change all three implementations at once, to not make this one bigger.

2022-07-01 07:06 UTC, SimonBaeumer commented on fleetshard/README.md
> +- OCM refresh token
Thanks for clarifying @dhaus67.
Do you have a good doc, article or video at hand to educate myself more on these differences?

2022-07-01 07:10 UTC, merged