ROX-20479: leader election
stackrox/acs-fleet-manager pull request #1520
Opened 2023-12-08 10:11 UTC by ludydoo

2023-12-11 09:51 UTC, SimonBaeumer requested changes
The approach and code looking good to me, but it introduces a second leader election to the existing in [leader_election_mgr.go](https://github.com/stackrox/acs-fleet-manager/blob/ac4af1502d2dee370156557c21d2746da2970bf1/pkg/workers/leader_election_mgr.go).
The env variable `RHACS_LEADER_ELECTION_ENABLED` introduces a new configuration which increases adds a new variable which diverges between environments like testing/dev/prod.

2023-12-11 09:51 UTC, SimonBaeumer commented on pkg/serviceregistration/leader.go
> +			_, err = l.client.CoreV1().Pods(l.namespaceName).Patch(ctx, l.podName, types.StrategicMergePatchType, []byte(patch), metav1.PatchOptions{})
Use `.Pods(namespace).Update()` instead of a formatted patch string?

```
glog.Infof("[serviceregistration] updating pod %s/%s labels: %s=%s", l.namespaceName, l.podName, activeLabel, isActive)
pod.Labels[activeLabel] = isActive
_, err = l.client.CoreV1().Pods(l.namespaceName).Update(ctx, pod, metav1.UpdateOptions{})
```

2024-01-09 10:10 UTC, SimonBaeumer approved these changes
:fire: :fire: :fire: :ship:

2024-01-09 10:10 UTC, SimonBaeumer commented on pkg/workers/leader_election_mgr.go
> -package workers
:fire: :fire: :fire: :fire: :fire:

2024-01-09 10:10 UTC, SimonBaeumer commented on pkg/workers/leader_election_mgr_test.go
> -package workers
:fire: :fire: :fire: :fire: :fire: :fire:

2024-01-09 10:10 UTC, SimonBaeumer commented on .github/workflows/ci.yaml
> +      E2E: "true"
This looks a bit like an accident. Is this change correct?

2024-01-09 10:12 UTC, ludydoo commented on .github/workflows/ci.yaml
> +      E2E: "true"
Thanks for the review! This is required, because during those tests there are no kubernetes clusters available, and we have to mock the kubernetes apiserver. Check pkg/serviceregistration/service.go, there's a switch to create a fake vs real client during those tests

2024-01-09 11:15 UTC, merged