Pass auth config to fleetshard
stackrox/acs-fleet-manager pull request #154
Opened 2022-06-28 12:20 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-30 01:11 UTC, dhaus67 commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +	OwnerUserid    string `json:"owner_userid"`
Would propose to use `owner_user_id` to keep the same naming scheme. Same applies to the migration.

2022-06-30 01:11 UTC, dhaus67 commented on internal/dinosaur/pkg/handlers/validation.go
> +		dinosaurRequest.OwnerUserid, _ = claims.GetSub()
Got the naming a bit confused, with the whole `sub == owner_user_id`. Would it make sense to just use `claims.GetUserId()` instead, to make it more clear for callers?

2022-06-30 01:11 UTC, dhaus67 commented on pkg/auth/context_config.go
> +	subClaim                     string = "sub"
nit, to keep it in sync with the current naming of claims:
```suggestion
	tenantSubClaim                     string = "sub"
```

2022-06-30 01:11 UTC, dhaus67 commented on internal/dinosaur/pkg/services/dinosaur.go
> +				// TODO: make part of dinosaurConfig
Do you have a ticket for that, or will this be done within this PR?

2022-06-30 04:44 UTC, johannes94 requested changes

2022-06-30 04:44 UTC, johannes94 commented on internal/dinosaur/pkg/migrations/20220114114500_add_centrals.go
> +		OwnerUserid                   string     `json:"owner_userid"`
We can not change existing migration this easy anymore, because a migration file is applied to DB only once and we have a long running instance of fleet manager within staging AppSRE environment. It uses a Database provisioned by AppSRE, which we can't access from our Dev Machines to rollback migrations manually. We have to options:

1. Use proper migration i.e add a new migration that changes the DB model
2. Rollback migration in AppSRE DB by temporary changing deployments init container to run `fleet-manager migrate rollback-all` like we did in #114 to prepare for #82

2022-06-30 20:39 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +	OwnerUserid    string `json:"owner_userid"`
Migration automatically generates `owner_userid` name for the column. We could probably use `RenameColumn` to change to `owner_user_id`, but is it really worth it? 

Alternatively, we could rename the field to "OwnerUserId", then it will be `owner_user_id` column name.

2022-06-30 20:41 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/migrations/20220114114500_add_centrals.go
> +		OwnerUserid                   string     `json:"owner_userid"`
Let's do it a proper way and create a new migration 👍

2022-06-30 20:54 UTC, dhaus67 commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +	OwnerUserid    string `json:"owner_userid"`
Well, then let's rename it to `UwnerUserId`, this also fits better to `OwnerAccountId, SubscriptionId etc...`.

2022-06-30 21:44 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +				// TODO: make part of dinosaurConfig
Created a ticket

2022-06-30 22:39 UTC, dhaus67 approved these changes
Looks good to me 🚀 
Probably would be best to await a review from Draconians before merging tho.

2022-07-01 04:38 UTC, johannes94 approved these changes
LGTM

2022-07-01 04:44 UTC, merged