ROX-21701: add PATCH for Central name
stackrox/acs-fleet-manager pull request #1569
Opened 2024-01-15 14:31 UTC by stehessel

## Description

Add PATCH path for changing the Central name of a tenant.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2024-01-15 16:37 UTC, stehessel commented
/test all

2024-01-15 22:58 UTC, stehessel commented
/test all

2024-01-15 23:57 UTC, stehessel commented
/test all

2024-01-16 00:02 UTC, stehessel commented
/test all

2024-01-16 01:11 UTC, stehessel commented
/test all

2024-01-16 01:56 UTC, stehessel commented
/test all

2024-01-16 12:37 UTC, dhaus67 commented on e2e/e2e_suite_test.go
> +			return fmt.Errorf("expected centralRequest name %s, got %s", name, centralRequest.Name)
super nit: on the formatting, since this is request / response data we print out, `%q` might be more obvious to detect e.g. empty return values.

2024-01-16 12:37 UTC, dhaus67 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +			glog.Warningf("Setting name to %q for central %q: %s", updateNameRequest.Name, id, updateNameRequest.Reason)
Why is this a "warn" log instead of just informational?

2024-01-16 12:37 UTC, dhaus67 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +			}
Given that we seem to duplicate this logic of reading the body and unmarshalling the contents into a given struct, let's factor this out and create a helper for this.

2024-01-16 12:51 UTC, johannes94 requested changes
Did you test that against an actual running fleetshard-sync / k8s cluster?

The reason why I'm asking is that, if I recall correctly the name of the tenant is used as the name of the central custom resource created by fleetshard-sync.

The problem about that:

If the name of the tenant changes, fleetshard-sync reconciler would pick up the tenant and query the namespace for a central CR having that name. Since it wouldn't find the old CR after the name change it would create a new one. Now we would have 2 CRs in one namespace, which will cause operator reconciliation conflicts.

2024-01-16 14:28 UTC, johannes94 approved these changes
We've addressed my previous comment in a private conversation. We think we can work around the concerns by:
- pause reconciling before changing the name
- rename through API
- delete the namespace
- unpause reconcile
- let fleetshard-sync restore the NS from backup

We can test that process on the integration environment.

I'm fine with merging if the e2e test is green.

2024-01-16 16:39 UTC, kurlov approved these changes

2024-01-16 23:50 UTC, merged