Specify additional tenant's auth via gitops
stackrox/acs-fleet-manager pull request #1714
Opened 2024-03-18 11:23 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-03-19 07:41 UTC, ludydoo commented on openapi/fleet-manager-private.yaml
> +                additionalAuth:
Could this be renamed to `additionalAuthProvider`?

2024-03-19 07:41 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +type ClaimMapping struct {
Could this be renamed to `AuthProviderClaimMapping` ?

2024-03-19 07:41 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +type Group struct {
Could this be renamed to `AuthProviderGroup` ?

2024-03-19 07:41 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +type OIDCConfig struct {
Could this be renamed to `AuthProviderOIDCConfig` ?

2024-03-19 07:41 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +type RequiredAttribute struct {
Could this be renamed to `AuthProviderRequiredAttribute` ?

2024-03-19 07:41 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	InstanceID   string        `json:"instanceId"`
Are AuthProviders always bound to a single central instance ? (1-1 mapping?)
If not (1-n mapping), then perhaps the authProviders could be in the `CentralOverride` struct

2024-03-19 14:17 UTC, ivan-degtiarenko commented
/retest

2024-03-19 14:26 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/gitops/config.go
> +	InstanceID   string        `json:"instanceId"`
Yes, the auth provider is inherently a single central resource.

2024-03-22 15:40 UTC, kovayur submitted a review, later dismissed
LGTM. I think it would be cleaner and more flexible if we moved the default authentication provider to the gitops configuration too, allowing it to be changed at runtime if needed. It kinda makes the word "additional" redundant :)

2024-03-28 13:36 UTC, ludydoo requested changes

2024-03-28 13:36 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	authProviderConfig := getAdditionalAuthProvider(central)
Please rename to `findAdditionalAuthProvider` - it's better to indicate that the result may be nil

2024-03-28 13:36 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +		errs = append(errs, field.Required(path.Child("instanceID"), "instance ID is required"))
```suggestion
		errs = append(errs, field.Required(path.Child("instanceId"), "instance ID is required"))
```

2024-03-28 13:36 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	authProviderPath := path.Child("authProvider")
Can you move the various validations to dedicated functions? It's much easier to read when there is one validation function for each struct / struct array. For example
- `validateAuthProvider`
- `validateAuthProviderName`
- `validateAuthProviderGroups`
- `validateAuthProviderGroup`
- `validateAuthProviderRequiredAttributes`
- `validateAuthProviderRequiredAttribute`
- ...

2024-03-28 13:36 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +		errs = append(errs, field.Required(authProviderPath, "name is required"))
```suggestion
		errs = append(errs, field.Required(authProviderPath.Child("name"), "name is required"))
```

2024-03-28 13:36 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	ClientID     string `json:"clientID,omitempty"`
Should the json tag be `clientId` rather than `clientID`?
```suggestion
	ClientID     string `json:"clientId,omitempty"`
```

2024-03-28 13:36 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	for i, additionalProvider := range providers {
Can there be more than 1 auth provider for 1 central instance? If not we should check that there are at most 1 additional auth provider per central instance

2024-03-28 13:36 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	for i, group := range provider.AuthProvider.Groups {
Do we need to perform some "duplicate" checks here for those lists? In other words, do some of those need to be unique in any way in those lists ? (e.g. no two groups with the same name, etc.)
- `groups`
- `requiredAttributes`
- `claimMapping`

2024-03-28 13:43 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	MinimumRoleName    string                          `json:"minimumRole,omitempty"`
Can we use the same name for the struct field and the json tag ? 
- `MinimumRoleName` -> `minimumRoleName`
- `OidcConfig` -> `oidcConfig`

2024-03-28 13:43 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	AttributeKey   string `json:"key,omitempty"`
Same comment for consistency between struct field and json tag

2024-03-28 13:43 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	AttributeKey   string `json:"key,omitempty"`
Same comment for consistency between struct field and json tag

2024-03-28 13:45 UTC, ludydoo requested changes

2024-03-28 13:45 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	RoleName       string `json:"role,omitempty"`
```suggestion
	Key   string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
	Role       string `json:"role,omitempty"`
```

2024-03-28 13:45 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	AttributeValue string `json:"value,omitempty"`
```suggestion
	Key   string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
```

2024-03-28 13:45 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	OIDCConfig         *AuthProviderOIDCConfig         `json:"oidc,omitempty"`
```suggestion
	Name               string                          `json:"name,omitempty"`
	MinimumRole    string                          `json:"minimumRole,omitempty"`
	Groups             []AuthProviderGroup             `json:"groups,omitempty"`
	RequiredAttributes []AuthProviderRequiredAttribute `json:"requiredAttributes,omitempty"`
	ClaimMappings      []AuthProviderClaimMapping      `json:"claimMappings,omitempty"`
	OIDCConfig         *AuthProviderOIDCConfig         `json:"oidcConfig,omitempty"`
```

2024-03-28 13:45 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	CallbackMode string `json:"mode,omitempty"`
```suggestion
	CallbackMode string `json:"callbackMode,omitempty"`
```

2024-03-28 13:46 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	RoleName       string `json:"role,omitempty"`
Can be either way, make a field named like its json tag, or the other way around

2024-03-28 13:46 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	AttributeValue string `json:"value,omitempty"`
Can be either way, make a field named like its json tag, or the other way around

2024-03-28 13:46 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	OIDCConfig         *AuthProviderOIDCConfig         `json:"oidc,omitempty"`
Can be either way, make a field named like its json tag, or the other way around

2024-03-28 13:46 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +	CallbackMode string `json:"mode,omitempty"`
Can be either way, make a field named like its json tag, or the other way around

2024-04-02 15:41 UTC, ludydoo commented on internal/dinosaur/pkg/gitops/config.go
> +}
instead of a N^2 approach to finding duplicates, you can maintain a list of "seen groups"

```suggestion
func validateAuthProviderGroups(path *field.Path, groups []AuthProviderGroup) field.ErrorList {
	var errs field.ErrorList
	var seenGroups = make(map[AuthProviderGroup]struct{}, 0, len(groups))
	for i, group := range groups {
	    groupPath := path.Index(i)
	    if _, ok := seenGroups[group]; ok {
	        errs = append(errs, field.Duplicate(groupPath, fmt.Sprintf("duplicate group %v", group)))
	        continue
	     }
	     seenGroups[group] = {}
	     errs = append(errs, validateAuthProviderGroup(groupPath, group)...)
	}
	return errs
}
```

2024-04-02 15:43 UTC, ludydoo commented on internal/dinosaur/pkg/presenters/managedcentral.go
> +	authProvider := findAdditionalAuthProvider(gitopsConfig, from)
If multiple auth providers can be attached to a central (1:N), should this method rather be `findCentralAdditionalAuthProviders` ?

2024-04-02 16:50 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/presenters/managedcentral.go
> +	authProvider := findAdditionalAuthProvider(gitopsConfig, from)
Ok, I stand corrected: even though **theoretically** there can be multiple additional auth providers, for now we only need one and implement it that way

2024-04-02 17:28 UTC, ludydoo requested changes
Could you add some tests for the validation and various methods added in this PR ?

2024-04-10 10:02 UTC, ivan-degtiarenko commented
@ludydoo do you think the tests that I added are enough, or do you have more cases in mind?

2024-04-11 19:07 UTC, ludydoo reviewed
The PR looks really good! Do you think you could add some tests to make sure the validation works as expected? The validation runs in CI before the gitops config is applied, so it allows us to catch any misconfigurations before they make their way to production

I think the yaml-based tests are harder to write. You could write tests that call the validateAdditionalAuthProvider directly.

If you think that those tests are not necessary, I'll approve the PR

2024-04-12 17:44 UTC, ludydoo approved these changes

2024-04-13 10:03 UTC, ivan-degtiarenko commented
/retest

2024-04-14 14:07 UTC, ivan-degtiarenko commented
/override ci/prow/e2e

2024-04-15 10:45 UTC, ivan-degtiarenko commented
/retest

2024-04-15 11:30 UTC, ivan-degtiarenko commented
Tested code locally and it builds/works. Merging the PR.

2024-04-15 11:30 UTC, merged