add base for email sender service
stackrox/acs-fleet-manager pull request #1754
Opened 2024-04-10 02:30 UTC by kurlov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-04-10 02:30 UTC, kurlov commented
* **#1756** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1756?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1755** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1755?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1754** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1754?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kurlov and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-10 08:40 UTC, kurlov commented
/retest

2024-04-10 10:23 UTC, kurlov commented
/retest

2024-04-16 20:18 UTC, johannes94 requested changes
Looks good, just some minor things to simplify.

Also could you add makefile targets for this service, or will that be part of a future PR?

2024-04-16 20:18 UTC, johannes94 commented on emailsender/cmd/app/main.go
> +		}
I think this could be simpler.

Why are you filtering the error for http.ErrServerClosed?
If that's important you could also add it add the if for the log in my suggestion.

```suggestion
		var err error
		if cfg.EnableHTTPS {
			err := server.ListenAndServeTLS(cfg.HTTPSCertFile, cfg.HTTPSKeyFile)
		} else {
			err := server.ListenAndServe()
		}
		glog.Fatalf("ListenAndServer error: %v", err)
```

2024-04-16 20:18 UTC, johannes94 commented on emailsender/cmd/app/main.go
> +	if err := server.Shutdown(ctx); err != nil {
As stated above I this ctx will in usual circumstances allways be Done() because the timer starts at the beginning of the process.

2024-04-16 20:18 UTC, johannes94 commented on emailsender/cmd/app/main.go
> +	glog.Infof("Application started. Will shut down gracefully on %s.", notifySignals)
```suggestion
	glog.Infof("Application started. Will shut down gracefully on OS signals: %s.", notifySignals)
```

2024-04-16 20:18 UTC, johannes94 commented on emailsender/config/config.go
> +		return nil, errors.Wrap(cfgErr, "unexpected configuration settings")
```suggestion
		return nil, errors.Wrap(cfgErr, "invalid configuration settings")
```

2024-04-16 20:18 UTC, johannes94 commented on emailsender/config/config.go
> +			configErrors.AddError(errors.New("ENABLE_HTTPS is set but unspecified required HTTPS_CERT_FILE and HTTPS_KEY_FILE"))
```suggestion
			configErrors.AddError(errors.New("ENABLE_HTTPS is true but required variables HTTPS_CERT_FILE or HTTPS_KEY_FILE are empty"))
```

2024-04-17 21:45 UTC, kurlov commented on emailsender/cmd/app/main.go
> +		}
I've applied your suggestion but returned `ErrServerClosed` filter. The reason is that closing server by interrupt signal is expected and normal shut down so such flow should not throw a error. Anything else which stops the server should be handled as an error

2024-04-17 22:05 UTC, kurlov commented on emailsender/cmd/app/main.go
> +	ctx, cancel := context.WithTimeout(context.Background(), cfg.StartupTimeout)
I had an impression that we can use it later but it's so small so we can add it if needed

2024-04-17 22:08 UTC, kurlov commented on emailsender/cmd/app/main.go
> +	if err := server.Shutdown(ctx); err != nil {
Dropped timeout

2024-04-17 23:08 UTC, kurlov commented
/retest

2024-04-19 07:01 UTC, merged