part 2: add metrics
stackrox/acs-fleet-manager pull request #1755
Opened 2024-04-10 02:30 UTC by kurlov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-04-10 02:30 UTC, kurlov commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1755?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1756** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1756?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1755** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1755?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1754** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1754?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kurlov and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-22 08:54 UTC, johannes94 requested changes

2024-04-22 08:54 UTC, johannes94 commented on emailsender/pkg/metrics/server.go
> +func ListenAndServe(server *http.Server) {
It looks like this function is defined but never used.

If you change that I'd prefer to delete this func instead of using it. Because `utils.Should` is using the `zapcore` logging defined for stackrox components, which is fine if we want to share it everywhere. But all ACSCS components including this one currently use `glog` and by using this utils functions we kind of have both which can make it more complicated to integrate future changes to the overall logging.

2024-04-22 08:54 UTC, johannes94 commented on emailsender/pkg/metrics/server.go
> +func CloseMetricsServer(server *http.Server) {
Same as above.

2024-04-22 08:54 UTC, johannes94 commented on emailsender/pkg/metrics/metrics.go
> +func NewInstance() *Metrics {
I would remove the "New" prefix here, because it implies that this will always create a New Instance which it will not.
```suggestion
func NewInstance() *Metrics {
```

2024-04-22 08:54 UTC, johannes94 commented on emailsender/pkg/metrics/server_test.go
> +	require.Equal(t, http.StatusOK, rec.Code, "status code should be OK")
Same here Listen was never called, so there's nothing to close we only use the internal Handler, which is kind of "simulating" the server without ever actually opening a network connection.
```suggestion
	server := newMetricsServer(":9999", registry)
	server.Handler.ServeHTTP(rec, req)
	require.Equal(t, http.StatusOK, rec.Code, "status code should be OK")
```

2024-04-22 08:57 UTC, johannes94 commented on emailsender/pkg/metrics/server.go
> +func NewMetricsServer(config *config.Config) *http.Server {
We could also just give the actuall address string here, makes the interface more clear because it communicates that we only use this single parameter of the config.

2024-04-23 12:50 UTC, kurlov commented on emailsender/cmd/app/main.go
> +		if err := metricServer.ListenAndServe(); !errors.Is(err, http.ErrServerClosed) {
Also added error filtering to avoid logging error on graceful shutdown like this one:
```
1 main.go:68] metrics server error: http: Server closed
```

2024-04-24 06:12 UTC, johannes94 approved these changes
LGTM 👍

2024-04-24 07:51 UTC, merged