part 3: add local deployment
stackrox/acs-fleet-manager pull request #1756
Opened 2024-04-10 02:30 UTC by kurlov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-04-10 02:30 UTC, kurlov commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1756?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1756** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1756?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1755** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1755?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1754** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/1754?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kurlov and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-24 06:53 UTC, johannes94 requested changes

2024-04-24 06:53 UTC, johannes94 commented on Makefile
> +.PHONY: email-sender
I'd use the wording without the dash everywhere to stay consistent with naming. Could you change that throughout this file?

```suggestion
emailsender:
	GOOS="$(GOOS)" GOARCH="$(GOARCH)" CGO_ENABLED=0  $(GO) build $(GOARGS) -o emailsender/bin/emailsender ./emailsender/cmd/app
.PHONY: emailsender
```

2024-04-24 06:53 UTC, johannes94 commented on Makefile
> +EMAIL_SENDER_IMAGE = email-sender
```suggestion
EMAIL_SENDER_IMAGE = emailsender
```

2024-04-24 06:53 UTC, johannes94 commented on emailsender/Dockerfile
> +EXPOSE 8000
I think the default for this service was 8080. 

You might also want to add the default metrics port. But the EXPOSE is anyways only something like a label for the image. We could still expose any port we want during runtime.
```suggestion
EXPOSE 8080
```

2024-04-24 06:53 UTC, johannes94 commented on emailsender/Dockerfile
> +RUN make email-sender
Also note the naming inconsistency here.
```suggestion
RUN make emailsender
```

2024-04-24 06:53 UTC, johannes94 commented on emailsender/Dockerfile
> +RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@v1.20.1
I'm not sure why we need that.

The only scenario that comes to mind is if we had this in the image to be able to run a Go debugger against this container. But as this is only part of the `build` stage and not of the `standard` stage we can't do that.

Maybe I'm missing something here.

2024-04-24 12:42 UTC, kurlov commented on Makefile
> +.PHONY: email-sender
We use `fleet-manager` or `fleetshard-sync` names as well in the makefile. But there is also `acsfleetctl` 😕

2024-04-24 12:45 UTC, kurlov commented on emailsender/Dockerfile
> +RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@v1.20.1
Dropped it, It's copy-pasted

2024-04-24 12:57 UTC, johannes94 approved these changes
Only nits, since we already started to call everything emailsender

2024-04-24 14:45 UTC, merged