Add NetworkPolicy and EgressFirewall to Tenant Helm chart
stackrox/acs-fleet-manager pull request #1767
Opened 2024-04-16 22:02 UTC by ebensh

## Description
Add NetworkPolicy's and EgressFirewall to the Fleetshard Sync Tenant Helm chart.

These effectively replace and improve the ACS Operator's default NetworkPolicy's.

Document discussing the changes: https://docs.google.com/document/d/15-rlsU_wDsv6TX_2hKHNFir82W1T9Ov1SOnRSha1VUY/edit

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-04-17 17:28 UTC, kylape reviewed
Did you ever find out if we can disable network policy creation in the operator?  Also, do we need scanner v4 network policies, too?

I'll try to applly these network policies later today and see if I can test them out.

2024-04-17 17:28 UTC, kylape commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +      cidr: 10.1.0.0/16
this should be indented once to be under the `ipBlock` section.

2024-04-17 17:28 UTC, kylape commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +      cidr: 0.0.0.0/0
same indentation comment

2024-04-17 17:28 UTC, kylape commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +  - to:  # Allow egress to Scanner-db
does scanner v2 reach out to central for updated definitions?

2024-04-17 17:28 UTC, kylape commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +      cidr: 10.1.0.0/16
It might be worth a comment here to note that the `EgressFirewall` blocks this CIDR block except for the specific IP that resolves from the tenant's RDS hostname.

2024-04-18 13:53 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +      cidr: 0.0.0.0/0
Done

2024-04-18 13:56 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +  - to:  # Allow egress to Scanner-db
Asked @RTann for clarity on this one. It's a good point - before Central is open to any ingress on port 8443, but I didn't check what other jobs could be calling out to it. Thanks!

2024-04-18 21:05 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +  - to:  # Allow egress to Scanner-db
Yes, it does. Added in the newest commit. Marking this one as done.

2024-04-18 22:21 UTC, ebensh commented
> Did you ever find out if we can disable network policy creation in the operator?

Yes I checked, no we can't, but as discussed in sync call there's a way to roll out a GitOps override while we add the flag (not blocked by ACS release).

> Also, do we need scanner v4 network policies, too?

I was going to add them in a future PR but have rolled them in here too. PTAL.

> I'll try to applly these network policies later today and see if I can test them out.

Sounds good.

2024-04-19 14:38 UTC, ebensh commented
/retest

2024-04-19 14:44 UTC, kovayur approved these changes

2024-04-22 11:38 UTC, vladbologa requested changes
In addition to my other comments, I think that at:

https://github.com/stackrox/acs-fleet-manager/blob/68166244938ba8b8e2f5d7c678cb158a396103b2/fleetshard/pkg/central/reconciler/reconciler.go#L313

We should have something like:
```golang
if !r.secureTenantNetwork {
    r.applyProxyConfig(central)
}
```

This applies if this PR is merged before https://github.com/stackrox/acs-fleet-manager/pull/1768. Else Central traffic will go through the egress-proxy, which is not allowed by these network policies.

It's also not clear to me what happens if `secureTenantNetwork` is enabled while the operator still deploys its own NetworkPolicies.

2024-04-22 11:38 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +          app: scanner
Are you sure that it doesn't need egress to scanner-v4 components?

2024-04-22 11:38 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +  egress:
I think we also need to allow egress to:
- k8s API (kubernetes.default.svc.cluster.local.:443)
- audit logging, the URL is configurable, see https://github.com/stackrox/acs-fleet-manager/blob/76f1b5e69be1feb11350d6c2b4c89352a01e7cde/fleetshard/config/config.go#L64

2024-04-24 07:49 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +          app: scanner
Done.

2024-04-24 11:47 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +          app: scanner
Added

2024-04-24 11:48 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +  egress:
Added audit logging to central egress (port 8888).

Having troubles with the k8s API - it looks like the IPs there are not stable. We could add open its *range* (if it's clear) and then block in the EgressFirewall, as an option.

See e.g. https://pauldally.medium.com/accessing-kubernetes-api-server-when-there-is-an-egress-networkpolicy-af4435e005f9

2024-04-24 13:20 UTC, ebensh commented
> In addition to my other comments, I think that at:
> 
> https://github.com/stackrox/acs-fleet-manager/blob/68166244938ba8b8e2f5d7c678cb158a396103b2/fleetshard/pkg/central/reconciler/reconciler.go#L313
> 
> We should have something like:
> 
> ```go
> if !r.secureTenantNetwork {
>     r.applyProxyConfig(central)
> }
> ```
> 
> This applies if this PR is merged before #1768. Else Central traffic will go through the egress-proxy, which is not allowed by these new network policies.

Good point; added in latest commit.

> It's also not clear to me what happens if `secureTenantNetwork` is enabled while the operator still deploys its own NetworkPolicies.

The policies are strictly additive. The main concern is that the ACS Operator doesn't deploy *any* egress policies. This means that once the Fleetshard Sync starts writing its policies, all egress *not* explicitly specified will be denied.

I have other PRs to:
1. Use gitops to effectively null out the ACS Operator's NetworkPolicy spec's, which will help confirm our policies here are sufficient, and
2. Add the secureTenantNetwork flag to the OCM Addon flags for the Addons. This will let us control the rollout of the secureTenantNetwork by environment, so we can test the interactions in ACSCS Integration before it hits stage/prod. (Separated code behavior and config push)
3.

2024-04-24 14:10 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +        cidr: 10.1.0.0/16
This is the CIDR of the VPC where we keep the tenant RDS databases. It's peered to the VPC of the OpenShift cluster.

2024-04-24 18:57 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +  egress:
@knobunc We're having trouble figuring out how to allow access to the k8s API, can you please help?

2024-04-25 09:50 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +# If zero NetworkPolicy's exist for Ingress or Egress, then all traffic is by
Thank you for the clearer explanation - I've applied your suggestion and moved the text into the conditional template.

2024-04-25 09:51 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +# TODO: Double check this allows KubeDNS, OpenShift Internal DNS, OpenShift External DNS
Thanks for clarifying this. Simplified the text and removed the TODO.

2024-04-25 10:08 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +        {{- include "localNetworkCidrRanges" . | nindent 8 }}
> Is this an attempt to prevent access to pods?

Yes. Part of Central's functionality is its integrations - we want it to be able to make outgoing connections to external services. At the same time, we don't want Central (via malicious configuration of integrations, for example) to be able to connect to our own internal network.

I was hoping there was a way to represent a "network egress" similar to the network ingress and create a network policy allowing only that, but I couldn't find one. This attempts to invert and allow everything except internal access.

> We may need to think this through a little more because people could set the cluster up on their own ip space and not use a reserved one.

To be clear the customer cannot set up *this* cluster, we own and operate it. Given that, is this still a concern?

> Or want to talk to something in their corporate network in a reserved network.

Is this possible? How would they have an IP address in those ranges registered with DNS?

2024-04-25 10:21 UTC, ebensh commented
To be explicit I'm waiting on @vladbologa and @knobunc approval before merging :)

Looking at the CI to try to figure out if it's just flakes or a test I missed updating now.

2024-04-25 14:17 UTC, vladbologa requested changes

2024-04-25 14:17 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +            app=audit-logs-aggregator
```suggestion
            app: audit-logs-aggregator
```

2024-04-25 15:07 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +            app=audit-logs-aggregator
Applied

2024-04-25 16:10 UTC, vladbologa approved these changes
LGTM!

One more thing, what do you think about surrounding `fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml`
with
`
{{- if not .Values.secureTenantNetwork }}
{{ end }}
`
so that we don't even install the egress-proxy and its network policies when `secureTenantNetwork` is enabled?

2024-04-26 08:48 UTC, vladbologa requested changes

2024-04-26 08:48 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +        protocol: TCP
Are these rules OK? Without a namespace selector, I think that it would allow traffic to `audit-logs-aggregator` and `openshift-kube-apiserver` only if they are in the same namespace as the tenant, which is not the case.

2024-04-26 09:51 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy.yaml
> +        protocol: TCP
Thanks for catching this; yes. I audited the other `to:` stanzas as well to make sure they checked out.

2024-04-26 10:30 UTC, vladbologa requested changes

2024-04-26 10:30 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
> +secureTenantNetwork: false
Instead of hardcoding this value, you could set the value from the code here fleetshard/pkg/central/reconciler/reconciler.go:1730

And so you'd propagate the value from dp-terraform.

Otherwise this remains false when you set `secureTenantNetwork: true` via the Addon.

2024-04-26 10:44 UTC, ebensh commented on fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
> +secureTenantNetwork: false
Is this not what https://github.com/stackrox/acs-fleet-manager/pull/1767/files#diff-8b2c412ebc3fa158d46c2dfb0136cfef521abb4fb2dda0a77b403a32afd9c58eR1744 is doing?

2024-04-26 11:32 UTC, vladbologa commented on fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
> +secureTenantNetwork: false
Yes it is, I'll see myself out. :)

2024-04-26 19:32 UTC, vladbologa approved these changes

2024-04-28 07:13 UTC, merged