Initialise auth provider from fleetshard-sync
stackrox/acs-fleet-manager pull request #178
Opened 2022-07-06 15:59 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-07-08 09:39 UTC, SimonBaeumer requested changes
Great work @ivan-degtiarenko!

2022-07-08 09:39 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		ExtraUiEndpoints: []string{"localhost:8443"},
Is this because of the lack of correct exposure of Central?
Which implications does this have if we release it by accident?

2022-07-08 09:39 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		return "", errors.Errorf("No password present in %s secret. This should not be the case in Central instances installed via operator.", centralHtpasswdSecretName)
You can disable htpasswd, the short version of the error message is okay too.

```suggestion
		return "", errors.Errorf("no password present in %s secret.", centralHtpasswdSecretName)
```

2022-07-08 09:39 UTC, SimonBaeumer commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +        - name: CREATE_AUTH_PROVIDER
Does this configuration not break all current builds which were executed locally and change the development workflow by needing to set an additional environment variable?

2022-07-08 09:39 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +	// Acquire central address.
Comment duplicate function name

2022-07-08 09:39 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +	// Acquire central admin password.
Comment duplicates function name

2022-07-08 09:39 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		return acsErrors.NewErrorFromHTTPStatusCode(resp.StatusCode, "Failed to create auth provider for central %s", central.Metadata.Name)
Imho this code (line 48 - 71) can be extracted into its own package `central_client` to be re-usable. 
It is likely we need more API calls to Central in the future, having a package which allows us to quickly add an additional call with password auth is great.

2022-07-08 09:39 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +	if resp.StatusCode == http.StatusOK {
Is it really an http 200? ie. http 201 is `Created` which would be more correct.
Imho a check for `2xx` would be better here. StackRox has a helper function which can do exactly that.

2022-07-08 11:46 UTC, ivan-degtiarenko commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		ExtraUiEndpoints: []string{"localhost:8443"},
Correct, current `host` specified in spec is unreachable. 

The implication: if you have port-forward into Central/can access it on `localhost:8443`, you can log in if you have correct credentials.

2022-07-08 11:47 UTC, ivan-degtiarenko commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +        - name: CREATE_AUTH_PROVIDER
It's not required and set to `false` by default, leaving development workflow unchanged

2022-07-08 11:51 UTC, ivan-degtiarenko commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	// 3. OR Central request is in status "Ready" - meaning auth provider should've been initialised earlier
For now it's not, auth provider is created once and is saved to database.

If we ever decide to implement client secret rotation, we can change auth provider via `fleetshard-sync`, but then we would probably need to implement comparison of existing auth provider with the one coming to `fleetshard-sync`.

2022-07-11 07:31 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +func init() {
Yeah that makes sense. But why creating a package-wide variable if it can be in the scope of the function as it is only used once in the `http.Client` creation?
It is a variable initialization needing now a `var ()` block + an `init` function which could be just created before the `http.Client{}` creation in line 61.

2022-07-11 07:34 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	// 3. OR Central request is in status "Ready" - meaning auth provider should've been initialised earlier
Should the auth provider be non-editable in Central? Or the auth provider is always overwritten an idempotent.

Not for this PR but still a thing we need to take care of. In case a customer accidentally (or intentionally) changes the auth provider it is hard to recover if the auth provider is never re-created/fixed by fleetshard.
Also we don't have access to a production cluster.

This can be very frustrating that a customer might lock themselves out of the system.

2022-07-11 07:37 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	// 3. OR Central request is in status "Ready" - meaning auth provider should've been initialised earlier
I'll prefer the idempotent change, thus no changes to Central are necessary for now but still allows us to trigger updates which will fix the auth provider automatically.

2022-07-11 17:41 UTC, ivan-degtiarenko commented on fleetshard/pkg/centralreconciler/init_auth.go
> +			"issuer":        "https://sso.stage.redhat.com/auth/realms/redhat-external",
I'm not sure I get you.

The only two possible values are `https://sso.stage.redhat.com/auth/realms/redhat-external` and `https://sso.redhat.com/auth/realms/redhat-external`. Depending on whether we are in stage vs prod, fleet-manager will send either one or another issuer value to fleetshard-sync. 
This value would be unmodifiable for deployed Central instances.

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/init_auth.go
> +	address := fmt.Sprintf("https://%s.%s.svc.cluster.local:%d", centralServiceName, central.Metadata.Namespace, service.Spec.Ports[0].Port)
Hm, maybe we should use the name specifically here as well, as defined within [here](https://github.com/stackrox/stackrox/blob/master/image/templates/helm/stackrox-central/templates/_central_endpoints.tpl#L5)? In case of i.e. adding monitoring ports or other things to the service, we can't really hope that ordering stays the same.
To make things safer, we can check for name as well as targetPort.

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		return "", errors.Errorf("no password present in %s secret.", centralHtpasswdSecretName)
```suggestion
		return "", errors.Errorf("no password present in %s secret", centralHtpasswdSecretName)
```

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		return acsErrors.NewErrorFromHTTPStatusCode(resp.StatusCode, "Failed to create group for central %s", central.Metadata.Name)
```suggestion
		return acsErrors.NewErrorFromHTTPStatusCode(resp.StatusCode, "failed to create group for central %s", central.Metadata.Name)
```

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		return acsErrors.NewErrorFromHTTPStatusCode(resp.StatusCode, "Failed to create auth provider for central %s", central.Metadata.Name)
```suggestion
		return acsErrors.NewErrorFromHTTPStatusCode(resp.StatusCode, "failed to create auth provider for central %s", central.Metadata.Name)
```

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/init_auth.go
> +func CreateRHSSOAuthProvider(ctx context.Context, central private.ManagedCentral, client ctrlClient.Client) error {
Does it need to be made public? AFAICT its only used within the reconciler, so I don't see why we have to make it public.

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	if r.createAuthProvider && remoteCentral.RequestStatus != centralConstants.DinosaurRequestStatusReady.String() {
Just out of curiosity: we don't really plan to support anything like "changing owner of an existing instance", right? Cause this would imply that `3. OR Central request is in status "Ready"` to not be true anymore, as we would need to reconcile the auth provider and change the groups, specifically the one using the OwnerID, right?

2022-07-13 03:11 UTC, dhaus67 commented on fleetshard/pkg/centralreconciler/reconciler_test.go
> +		createAuthProvider: false,
nit: since `useRoutes` is skipped being explicitly set when false, maybe we should do the same with `createAuthProvider` or at the very least be consistent there.

2022-07-13 07:37 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	// 3. OR Central request is in status "Ready" - meaning auth provider should've been initialised earlier
> We still need to figure out how secret rotation will work then 

Is my understanding correct that it the use-cases we have are:
 - Update secret from API to rotate secrets
 - Disable editing from end users

Do you think the secret rotation will get to a special case for managed services in the UI?

2022-07-13 07:40 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +			"issuer":        "https://sso.stage.redhat.com/auth/realms/redhat-external",
Ah sorry, I confused some words.
All settings for the auth provider are passed from the fleet-manager to the fleetshard, why is the issuer URL not passed from fleet-manager?
In fleet-manager then make it configurable that a new image is not necessary on URL changes via an env var `RED_HAT_SSO_PROVIDER_ISSUER` or `RED_HAT_SSO_PROVIDER_ENDPOINT`.

2022-07-13 07:51 UTC, SimonBaeumer requested changes
@ivan-degtiarenko Changes look good to me. Most comments are around the central client, you can fix these in an additional PR if you prefer that to merge this PR.

2022-07-13 07:51 UTC, SimonBaeumer commented on fleetshard/pkg/central_client/client.go
> +	insecureTransport := http.DefaultTransport.(*http.Transport).Clone()
I've suggested @ivan-degtiarenko to do it inline.
Why would you move such a simple operation to an `init` function introducing package-wide variables?

2022-07-13 07:51 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +	err := client.Get(ctx,
The API call would work but the returned endpoint would not be accessible from outside the cluster I guess.

2022-07-13 07:51 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	if r.createAuthProvider && remoteCentral.RequestStatus != centralConstants.DinosaurRequestStatusReady.String() {
No, Central instances can not be transitioned between different customers currently.

2022-07-13 07:51 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +func sendGroupRequest(ctx context.Context, central private.ManagedCentral, groupRequest *storage.Group, address string, pass string) error {
This `sendGroupRequest` function can be part of the centralclient.

2022-07-13 07:51 UTC, SimonBaeumer commented on fleetshard/pkg/central_client/client.go
> +func SendRequestToCentral(ctx context.Context, requestBody interface{}, address string, pass string) (*http.Response, error) {
Add a small struct to the central client called `Client` which is initliazed with the endpoint URL.

```
type Client struct {
  address string
}

func NewCentralClient(endpoint string) *Client {
  return ...
}
```

After that all functions which send requests to some Central endpoint can be moved to the client to have a canonical location for Central requests.

2022-07-13 07:51 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/init_auth.go
> +		return acsErrors.NewErrorFromHTTPStatusCode(resp.StatusCode, "Failed to create auth provider for central %s", central.Metadata.Name)
This can also be added as a receiver function on the Central client.

2022-07-13 14:22 UTC, dhaus67 commented on fleetshard/pkg/central_client/client.go
> +	insecureTransport := http.DefaultTransport.(*http.Transport).Clone()
We've had this discussion in the past ([here](https://github.com/stackrox/stackrox/pull/706#discussion_r820515606)).
By sharing the transport, we will make use of connection pooling, as we use the same transport across multiple requests. If we were to re-create the transport for each request, we wouldn't benefit from this.

I don't really agree with the "package-wide variables" sentiment as an argument against it, since the package is so small and its anyways unexported (also, could be used for stubbing within tests if we really wanted to).

2022-07-15 12:48 UTC, ivan-degtiarenko commented on fleetshard/pkg/centralreconciler/init_auth.go
> +			"issuer":        "https://sso.stage.redhat.com/auth/realms/redhat-external",
That's what ROX-11619 is for :)

2022-07-15 13:58 UTC, ivan-degtiarenko commented on fleetshard/pkg/central_client/client.go
> +	// TODO: once certificates will be added, we probably will be able to replace with secure transport
Created https://issues.redhat.com/browse/ROX-11795

2022-07-16 18:24 UTC, ivan-degtiarenko commented on fleetshard/pkg/central_client/client.go
> +func SendRequestToCentral(ctx context.Context, requestBody interface{}, address string, pass string) (*http.Response, error) {
Sounds good. I also extended `Client` with some other repeating fields like `pass`, `central` and `httpClient`

2022-07-18 08:17 UTC, SimonBaeumer approved these changes

2022-07-18 08:17 UTC, SimonBaeumer commented on fleetshard/pkg/central/client/client.go
> +// reusing transport allows us to benefit from connection pooling
Thanks!

2022-07-18 08:29 UTC, SimonBaeumer commented
/approve

2022-07-18 08:44 UTC, merged