ROX-23252: Add emailsender deployment
stackrox/acs-fleet-manager pull request #1782
Opened 2024-05-03 21:54 UTC by kurlov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-05-06 09:13 UTC, johannes94 requested changes

2024-05-06 09:13 UTC, johannes94 commented on dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
> +              containerPort: 8080
This section is not strictly required but I think if it's there it should:
1. Expose correct default
2. List all ports the container uses

As of the current state of the code this is metrics on 9090 and the actual http server on 8080


```suggestion
          ports:
            - name: monitoring
              containerPort: 9090
            - name: server
              containerPort: 8080
```

2024-05-06 09:13 UTC, johannes94 commented on dp-terraform/helm/rhacs-terraform/values.yaml
> +  environment: ""
You might also want to expose replicas as a value to allow configuration of horizontal scaling here.

2024-05-16 07:34 UTC, kurlov commented on dp-terraform/helm/rhacs-terraform/templates/emailsender-rbac.yaml
> +  - apiGroups: [ "" ]
You are right, we don't need it ATM

2024-05-16 08:46 UTC, johannes94 approved these changes

2024-05-22 13:36 UTC, merged