ROX-23260: Add Rate Limiter Service
stackrox/acs-fleet-manager pull request #1867
Opened 2024-06-06 06:36 UTC by kurlov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-06-06 14:10 UTC, johannes94 commented on emailsender/config/config.go
> +	LimitEmailPerDayPerTenant int    `env:"LIMIT_EMAIL_PER_DAY_PER_TENANT" envDefault:"250"`
If I understand correctly the rate limiting currently is based on a "per Day" logic.

So there is 1 table entry per day, per tenant and we count the amount of emails send on this specific date.

With this logic we can send 250 emails per calendar day e.g
06/06/2024 form 00:00 to 23:59: 250 mails
07/07/2024: from 00:00 to 23:59: 250 mails

AWS on the other hand used a sliding 24h window for their limit, from their docs:
```
[Sending quota](https://docs.aws.amazon.com/ses/latest/dg/quotas.html)—The maximum number of emails that you can send in a 24-hour period. This quota is calculated on a rolling time period. Every time you try to send an email, Amazon SES determines the number of emails that you sent in the previous 24 hours. As long as the total number of emails that you have sent in the past 24 hours is less than this daily maximum, your send request is accepted and your email is sent.
```

With that if I've following scenario:
- 06/06/2024 12:00-23:59: 125 emails send
- 06/07/2024 00:00-11:59: 125 emails send

I'd reach the AWS limit but not our limit.

Did you consider also following the "rolling window" limitation?

2024-06-10 04:47 UTC, kurlov commented on emailsender/config/config.go
> +	LimitEmailPerDayPerTenant int    `env:"LIMIT_EMAIL_PER_DAY_PER_TENANT" envDefault:"250"`
You are right. Sliding window is more suitable here. Added this approach with 24 hours windows size. There is a room for improvements (e.g. use `unlogged` table or delete older than window_size records) but I would prefer to do it in the follow PR

2024-06-10 04:48 UTC, kurlov commented on emailsender/config/config.go
> +	LimitEmailPerSecond       int    `env:"LIMIT_EMAIL_PER_SECOND" envDefault:"14"`
Dropped perSecond limit and added a backoff in the separate PR https://github.com/stackrox/acs-fleet-manager/pull/1871

2024-06-10 04:49 UTC, kurlov commented on emailsender/config/config.go
> +	DatabasePassword          string `env:"DATABASE_PASSWORD" envDefault:"postgres"`
Added reading from files. I would like to keep reading from ENV for now for easier debugging. WDYT? I am also fine to drop it completely

2024-06-10 10:05 UTC, kurlov commented
/retest

2024-06-10 14:26 UTC, kurlov commented on emailsender/config/config.go
> +	LimitEmailPerSecond       int    `env:"LIMIT_EMAIL_PER_SECOND" envDefault:"14"`
Backoff PR is closed in favour of built-in backoff mechanism in aws sdk v2

2024-06-10 15:23 UTC, kurlov commented on emailsender/config/config.go
> +	LimitEmailPerSecond       int    `env:"LIMIT_EMAIL_PER_SECOND" envDefault:"14"`
Added backoff configuration to AWS client init

2024-06-11 07:51 UTC, johannes94 requested changes

2024-06-11 07:51 UTC, johannes94 commented on emailsender/pkg/db/connect.go
> +	connection, _ := commonDB.NewConnectionFactory(dbConfig)
If you wanted to modify connection pool configuration e.g. with the env config above, I think this would be the place to do this.

2024-06-11 07:51 UTC, johannes94 commented on emailsender/config/config.go
> +	MaxOpenConnections   int    `env:"DATABASE_MAX_CONNECTIONS" envDefault:"50"`
Also I think we'd have a better overview if we have a dedicated struct for those variables.
e.g:
```go
type Config struct {
  ...
  DB DBConfig
  ...
}

type DBConfig struct {
  Host string `env:"DATABASE_HOST" envDefault:"localhost"`
  Port int `env:"DATABASE_PORT" envDefault:"5432"`
  ...
}
```

2024-06-11 07:51 UTC, johannes94 commented on emailsender/pkg/db/connect.go
> +	return d.DB.AutoMigrate(&EmailSentByTenant{})
Not sure if we should use auto migrations, from experience its very convenient for dev but there's a higher risks of accidentally introducing breaking changes. Since we don't control what exactly is executed by the migration.

Since the data model is pretty straight forward, it might be ok, though. I'll leave it to you.

2024-06-11 07:51 UTC, johannes94 commented on emailsender/pkg/email/ratelimiter.go
> +func (r *RateLimiterService) Allow(tenantID string) bool {
Nit: because I think Allow does not communicate the intend of using that as a check.
```suggestion
func (r *RateLimiterService) IsAllowed(tenantID string) bool {
```

2024-06-11 07:51 UTC, johannes94 commented on emailsender/pkg/email/ratelimiter.go
> +func (r *RateLimiterService) Register(tenantID string) error {
```suggestion
func (r *RateLimiterService) PersistEmailSendEvent(tenantID string) error {
```

2024-06-11 23:08 UTC, kurlov commented on emailsender/config/config.go
> +	DatabaseHostFile     string `env:"DATABASE_HOST_FILE" envDefault:"localhost"`
Added default behaviour to reading from file and an explicit log message if reading was failed and plain envs will be used instead

2024-06-11 23:09 UTC, kurlov commented on emailsender/pkg/db/connect.go
> +	connection, _ := commonDB.NewConnectionFactory(dbConfig)
Yes you are right.  The`NewConnectionFactory` will set maxConnection value under the hood

2024-06-11 23:13 UTC, kurlov commented on emailsender/config/config.go
> +	MaxOpenConnections   int    `env:"DATABASE_MAX_CONNECTIONS" envDefault:"50"`
Also added DB CA cert file

2024-06-11 23:18 UTC, kurlov commented on emailsender/pkg/db/connect.go
> +	return d.DB.AutoMigrate(&EmailSentByTenant{})
I would like to use auto migration in the beginning.  The schema is really simple and GORM documentation claims that [unused columns will not be deleted.](https://gorm.io/docs/migration.html). Also, Email Service db data is basically a cache type of data. But we can reconsider it in the future

2024-06-12 00:06 UTC, kurlov commented
/retest

2024-06-12 00:55 UTC, kurlov commented
/retest

2024-06-12 06:22 UTC, johannes94 commented on emailsender/config/config.go
> +	DatabasePassword          string `env:"DATABASE_PASSWORD" envDefault:"postgres"`
Ok, that's fine for me.

2024-06-12 07:21 UTC, johannes94 commented on emailsender/config/config.go
> +	LimitEmailPerDayPerTenant int    `env:"LIMIT_EMAIL_PER_DAY_PER_TENANT" envDefault:"250"`
Yes, sounds good.

I think deletion of older records is definitely necessary. But that can be in a follow up PR.

2024-06-12 07:26 UTC, johannes94 approved these changes
Good work :) Only a minor comment.

2024-06-12 07:26 UTC, johannes94 commented on emailsender/cmd/app/main.go
> +	_ = email.NewRateLimiterService(dbConnection)
I presume this isn't used since you want to integrate this into emailhander later on? Can you add a TODO comment?

2024-06-12 08:02 UTC, kurlov commented
/retest

2024-06-12 15:04 UTC, merged