fix: emailsender auth on rosa
stackrox/acs-fleet-manager pull request #1942
Opened 2024-07-11 13:03 UTC by johannes94

## Description
Use a configurable jwks_uri independent from the openid discovery document for internal kubernetes authentication.

This proofs to be more reliable since every K8s distribution has `https://kubernetes.default.svc/openid/v1/jwks` for internal access to the jwks keys, while it seems that every distribution (crc, minikube, OSD, ROSA, colima) return different paths and access methods.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-07-11 14:11 UTC, johannes94 commented
/retest
Cluster creation failed

2024-07-12 07:20 UTC, johannes94 commented
/retest

2024-07-12 08:50 UTC, ebensh requested changes

2024-07-12 08:50 UTC, ebensh commented on emailsender/config/config.go
> +	jwksURL := fmt.Sprintf("%s/%s", c.k8sSvcURL, c.k8sJWKSPath)
Nit - won't this have an extra /?
`https://kubernetes.default.svc//openid/v1/jwks`

2024-07-12 08:50 UTC, ebensh commented on emailsender/config/config_test.go
> -func TestJWKSPathFromURL(t *testing.T) {
This test would've caught the extra / problem

2024-07-12 09:33 UTC, johannes94 commented on emailsender/config/config_test.go
> -func TestJWKSPathFromURL(t *testing.T) {
This was testing a deleted private method, but I've added a test to verify the new joining logic.

2024-07-12 09:33 UTC, johannes94 commented on emailsender/config/config.go
> +	jwksURL := fmt.Sprintf("%s/%s", c.k8sSvcURL, c.k8sJWKSPath)
Right good catch, one could say this was misconfiguration but I've added a method to make sure we don't produce paths like this.

2024-07-12 09:38 UTC, ebensh approved these changes

2024-07-12 11:30 UTC, merged