ROX-21530: Certificate Monitoring
stackrox/acs-fleet-manager pull request #1946
Opened 2024-07-15 14:45 UTC by aaa5kameric

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-07-22 12:55 UTC, ludydoo commented on fleetshard/main.go
> +	kubeconfigPath := certmonitorConfig.Kubeconfig
Please replace with `k8s.CreateK8sInterfaceOrDie()` (there is an example above with `k8s.CreateClientOrDie()`)

2024-07-22 12:55 UTC, ludydoo commented on fleetshard/main.go
> +	informedFactory := informers.NewSharedInformerFactory(clientset, time.Minute)
Please rename `informedFactory` to `informerFactory`

2024-07-22 12:55 UTC, ludydoo commented on fleetshard/main.go
> +		fmt.Printf("Error creating certificate monitor: %v\n", err)
Please replace this with `glog`

2024-07-22 12:55 UTC, ludydoo commented on fleetshard/main.go
> +		Kubeconfig: filepath.Join(homedir.HomeDir(), ".kube", "config"),
I believe this field can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +package certmonitor
Can you rename this file from `main.go` to `certmonitor.go` ?

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +import "C"
I think this import is not necessary

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +		fmt.Printf("Secret Error, got: %v\n", new)
I believe this can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +			fmt.Printf("failed to decode pem data on secret %s/%s/%s\n", secret.Namespace, secret.Name, dataKey)
This can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +			fmt.Printf("failed to decode certificate on secret %s/%s/%s\n", secret.Namespace, secret.Name, dataKey)
This can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +		fmt.Println("Certificates Expiry Date found:")
these two `fmt.Println` lines can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +		fmt.Printf("unexpected object: %v", obj)
This can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +	fmt.Printf("Handling Delete: %s,%s\n", secret.Namespace, secret.Name)
I think this print can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +		fmt.Printf("unexpected object: %v", obj)
I think this print can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +	fmt.Printf("Handling update: %s,%s\n", newsecret.Namespace, newsecret.Name)
I think this print can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +	}
I think this print can be removed

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +			fmt.Printf("failed to decode base64 data: %v", err)
I think this print can be removed, this would never really happen

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +		return
Perhaps this method can return an error

2024-07-22 12:55 UTC, ludydoo commented on internal/certmonitor/main.go
> +	fmt.Println("Synced and ready:")
I think this print can be removed

2024-07-22 12:56 UTC, ludydoo commented on internal/certmonitor/main.go
> +		return
e.g. return `fmt.Errorf(...)`

2024-07-22 12:56 UTC, ludydoo commented on internal/certmonitor/main.go
> +	informedfactory informers.SharedInformerFactory
I believe this field is unused and can be removed. Only `podInformer` seems to be used

2024-07-22 12:58 UTC, ludydoo commented on internal/certmonitor/main.go
> +		fmt.Printf("unexpected object: %v", oldObj)
this print can be removed

2024-07-22 13:01 UTC, ludydoo commented on internal/certmonitor/main.go
> +	}
Maybe you can exit early: 
```suggestion
Maybe you can exit early: 
```
        if oldSecret == nil || newSecret == nil {
            return
        }
        for oldKey := range oldsecret.Data {
	        if _, ok := newsecret.Data[oldKey]; !ok {
		        certificatesExpiry.DeletePartialMatch(prometheus.Labels{
			        labelSecretName:      newsecret.Name,
			        labelSecretNamespace: newsecret.Namespace,
			        labelDataKey:         oldKey,
		        })
	        }
        }
```

2024-07-22 13:03 UTC, aaa5kameric commented on internal/certmonitor/main.go
> +	informedfactory informers.SharedInformerFactory
for informedfactory, i used c.informedfactory right below it to startInformer, without it its an error.

But clientset I've taken out, it was from a previous version

2024-07-22 13:12 UTC, aaa5kameric commented on internal/certmonitor/main.go
> +		return
when I do this I get:
../main.go:76:10: too many return values
	have (error)
	want ()

2024-07-22 13:17 UTC, ludydoo commented on internal/certmonitor/main.go
> +		return
That's because you need to add `error` as the return type: 
```
func (c *certMonitor) StartInformer(stopCh <-chan struct{}) error { ... }
```

2024-07-22 13:17 UTC, ludydoo commented on internal/certmonitor/main.go
> +	informedfactory informers.SharedInformerFactory
ah right!

2024-07-22 13:34 UTC, aaa5kameric commented on internal/certmonitor/main/main.go
> +func main() {
delete

2024-07-23 15:35 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// findCertsFromInformer handles new/created or updated secrets and finds the cert within it
I think this method can be deleted (not used anymore)

2024-08-05 11:19 UTC, ludydoo requested changes

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +)
I believe this should go into `fleetshard/pkg/fleetshardmetrics/metrics.go` where all other metrics are defined (as well as the `const label...` below)

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// NamespaceGetter interface for retrieving namespaces on name
```suggestion
// NamespaceGetter interface for retrieving namespaces on name. Subset of `v1.NamespaceLister`
```

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +func NewCertMonitor(config *Config, informerFactory informers.SharedInformerFactory, podInformer cache.SharedIndexInformer, namespaceLister v1.NamespaceLister) (*certMonitor, error) {
```suggestion
func NewCertMonitor(config *Config, informerFactory informers.SharedInformerFactory, podInformer cache.SharedIndexInformer, namespaceGetter NamespaceGetter) (*certMonitor, error) {
```

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +	namespaceLister NamespaceGetter
```suggestion
	namespaceGetter NamespaceGetter
```

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +func (c *certMonitor) findCertsFromSecret(secret *corev1.Secret) {
Maybe you can rename to `processSecret`, so that the function name is more representative (`extracts, decodes, parses`)

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// findCertsFromSecret func extracts, decodes, parses certifications from a secret, and displays in Prometheus
```suggestion
// findCertsFromSecret func extracts, decodes, parses certificates from a secret, and populates prometheus metrics
```

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +			certificatesExpiry.DeletePartialMatch(prometheus.Labels{
Can you add a comment like
```suggestion
		// oldKey does not exist in the new secret hence deleting the metric for that namespace/secret/key combination
			certificatesExpiry.DeletePartialMatch(prometheus.Labels{
```

2024-08-05 11:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +	}
I think this block is not needed, since you're already deleting the whole `DeletePartialMatch` on secret Name/Namespace below.

```suggestion
```

2024-08-07 10:36 UTC, ludydoo commented on fleetshard/main.go
> +		os.Exit(1)
```suggestion
		glog.Fatalf("Error creating certificate monitor: %v", err)
```

2024-08-07 10:37 UTC, ludydoo commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +			Name: "acscs_certmonitor_certificate_expiration_timestamp",
```suggestion
			Name: metricsPrefix + "certificate_expiration_timestamp",
```

2024-08-07 10:37 UTC, ludydoo commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +			Help: "Expiry of certifications",
```suggestion
			Help: "Expiry of certificates",
```

2024-08-07 10:38 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// SelectorConfig struct for namespace or secret selection based on labels/name
```suggestion
// SelectorConfig represents a configuration to select a namespace or a secret by name or labelSelector. Only one of Name or LabelSelector can be specified.
```

2024-08-07 10:38 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// MonitorConfig struct for monitoring specific namespaces + secrets
```suggestion
// MonitorConfig represents a configuration for observing certificates contained in kubernetes secrets
```

2024-08-07 10:39 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// Config struct, overall configuration for the certificate monitoring
```suggestion
// Config represents the certificate monitor configuration
```

2024-08-07 10:39 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +	Kubeconfig   string          `json:"kubeconfig"`
```suggestion
```

2024-08-07 10:41 UTC, ludydoo commented on fleetshard/main.go
> +	go monitor.StartInformer(stopCh)
```suggestion
	if err := monitor.StartInformer(stopCh); err != nil {
	  glog.Fatalf("failed to start certMonitor: %v", err)
	}
```

2024-08-07 10:42 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// certMonitor struct is main struct for certificate monitoring
```suggestion
// certMonitor is the Certificate Monitor. It watches Kubernetes secrets containing certificates, and populates prometheus metrics with the expiration time of those certificates.
```

2024-08-07 10:43 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +func (c *certMonitor) StartInformer(stopCh <-chan struct{}) error {
I think this can be renamed to only `Start`

2024-08-07 10:43 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// StartInformer func starts to informer to monitor secrets + event handlers
```suggestion
// Start the certificate monitor
```

2024-08-07 10:43 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// NewCertMonitor func creates new instance of certMonitor
```suggestion
// NewCertMonitor creates new instance of certMonitor
```

2024-08-07 10:44 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// secretMatches func checks if secret matches in the monitor config
```suggestion
// secretMatches checks if a secret matches a monitor config
```

2024-08-07 10:44 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// processSecret func extracts, decodes, parses certificates from a secret, and populates prometheus metrics
```suggestion
// processSecret extracts, decodes, parses certificates from a secret, and populates prometheus metrics
```

2024-08-07 10:44 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// handleScretCreation func event handles new secret creations
```suggestion
// handleScretCreation handles secret creation events
```

2024-08-07 10:44 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// handleSecretUpdate func event handles secret updates
```suggestion
// handleSecretUpdate handles secret updates events
```

2024-08-07 10:44 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +	fmt.Printf("Handling Creation: %s,%s\n", secret.Namespace, secret.Name)
```suggestion
```

2024-08-07 10:45 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// handleSecretDeletion func event handles deletion of secrets
```suggestion
// handleSecretDeletion handles secret deletion events
```

2024-08-07 10:47 UTC, ludydoo commented on internal/certmonitor/certmonitor_test.go
> +			t.Errorf("erorrrr: %v", metrciValue)
```suggestion
			t.Errorf("error: %v", metricValue)
```

2024-08-07 10:49 UTC, ludydoo requested changes

2024-08-07 10:49 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// ValidateConfig func checks the validity of given config,  in 'Monitor'
```suggestion
// ValidateConfig checks the validity of Config
```

2024-08-07 10:49 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// validateMonitors func validates list of Monitor
```suggestion
// validateMonitors validates list of Monitor
```

2024-08-07 10:49 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// validateMonitor func validates single Monitor obj, including: 'Namespace' and 'Secret'
```suggestion
// validateMonitor validates a Monitor
```

2024-08-07 10:49 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +// validateSelectorConfig func validates selectorConfig obj
```suggestion
// validateSelectorConfig validates a SelectorConfig
```

2024-08-07 12:12 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +
```suggestion

```

2024-08-07 12:14 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +}
This method never returns an error

```suggestion
func NewCertMonitor(config *Config, informerFactory informers.SharedInformerFactory, podInformer cache.SharedIndexInformer, namespaceGetter NamespaceGetter) *certMonitor {
	return &certMonitor{
		informerfactory: informerFactory,
		podInformer:     podInformer,
		config:          config,
		namespaceGetter: namespaceGetter,
		metrics:         fleetshardmetrics.MetricsInstance(),
	}
}
```

2024-08-13 09:54 UTC, ludydoo requested changes

2024-08-13 09:54 UTC, ludydoo commented on fleetshard/main.go
> +								Key:      "rhacs.redhat.com/tenant",
Could you use the constant instead of hardcoded string? (from fleetshard/pkg/central/reconciler/reconciler.go)
```suggestion
								Key:      reconciler.TenantIDLabelKey,
```

2024-08-13 09:54 UTC, ludydoo commented on fleetshard/main.go
> +				},
All the namespace selectors are the same, can you introduce a variable (e.g. `tenantNamespaceSelector`)

2024-08-13 09:54 UTC, ludydoo commented on fleetshard/main.go
> +	if errs := certmonitor.ValidateConfig(*certmonitorConfig); len(errs) != 0 {
minor
```suggestion
	if errs := certmonitor.ValidateConfig(*certmonitorConfig); len(errs) > 0 {
```

2024-08-13 09:54 UTC, ludydoo commented on fleetshard/main.go
> +		glog.Fatalf("certmonitor validation error: %w", errs)
I think in this case it's 
```suggestion
		glog.Fatalf("certmonitor validation error: %v", errs)
```

2024-08-13 09:54 UTC, ludydoo commented on fleetshard/main.go
> +		glog.Fatalf("Error starting certmonitor monitor: %v\n", err)
```suggestion
		glog.Fatalf("Error starting certmonitor monitor: %v", err)
```

2024-08-13 14:25 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/gen/main.go
> +	builder.WriteString("// Code generated by fleetshard/pkg/central/reconciler/gen/certmonitor.go. DO NOT EDIT.\n")
I think this change can be removed

2024-08-14 07:15 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +}
@kovayur do you think this `Start` logic should be here, or in `fleetshard/main.go` ?

2024-08-14 07:16 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +	})
Can you move this into `func NewCertMonitor`?

2024-08-14 08:42 UTC, ludydoo approved these changes

2024-08-15 09:48 UTC, kovayur commented on fleetshard/pkg/k8s/client.go
> +func CreateInterfaceOrDie() kubernetes.Interface {
Is there any objective reason to introduce a client-go k8s client in addition to the existing controller-runtime client? 
I would stick with controller-runtime for consistency unless there was a justification for it.

2024-08-15 10:45 UTC, kovayur requested changes
Great work done @aaa5kameric! I have no objections to the idea of implementation, but there are a couple of questions about the lifecycle of the monitor and parsing of the TLS secret, otherwise just minor nitpicks.

2024-08-15 10:45 UTC, kovayur commented on fleetshard/main.go
> +	if err := monitor.Start(stopCh); err != nil {
The `stopCh` parameter does not serve its purpose because there is no stop signal. Perhaps it makes sense to move it to the monitor field and send the signal when calling the `monitor.Close` function (see the comment above).

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor_test.go
> +// verifyPrometheusMetricDelete func verifies that the promethues metric has actually been deleted (delete handle)
nit:
```suggestion
// verifyPrometheusMetricDelete func verifies that the prometheus metric has actually been deleted (delete handle)
```

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor_test.go
> +func verifyPrometheusMetricDelete(t *testing.T, namespace, secret, data_key string) {
```suggestion
func verifyPrometheusMetricDelete(t *testing.T, namespace, secret, dataKey string) {
```

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor_test.go
> +		}
```suggestion
	require.NoError(t, err)
	require.Equal(t, float64(0), testutil.ToFloat64(metric))
```

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor_test.go
> +func TestCertMonitor_secretMatches(t *testing.T) {
Good to see decent test coverage 👍

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +// handleScretCreation handles secret creation events
nit
```suggestion
// handleSecretCreation handles secret creation events
```

2024-08-15 10:45 UTC, kovayur commented on fleetshard/main.go
> +				Secret: certmonitor.SelectorConfig{ // pragma: allowlist secret
This means that we need to maintain the list of TLS secrets, i.e. make changes here every time TLS secrets in stackrox change. 
It might make sense to introduce a label for TLS secrets in stackrox that we can filter using a label selector.
We could go even further and implement a TLS certificate rotation logic in operator based on this label.
@aaa5kameric can you create a follow-up ticket for this please?
cc: @porridge

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +			continue
I don't think we should ignore the error here. Let's at least log it.

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +	for dataKey, dataCert := range secret.Data {
Not every `dataKey` is a certificate. For example, the cert key is not a certificate.
I guess it's safe to rely on the secret structure here, e.g. explicitly get `ca.pem` and `cert.pem` from `secret.Data`

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +	oldsecret, ok := oldObj.(*corev1.Secret)
nit
```suggestion
	oldSecret, ok := oldObj.(*corev1.Secret)
```

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +	newsecret, ok := newObj.(*corev1.Secret)
nit:
```suggestion
	newSecret, ok := newObj.(*corev1.Secret)
```

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +func (c *certMonitor) secretMatches(s *corev1.Secret, monitor MonitorConfig) bool {
This function is used in tests only. I suggest to move `secretMatches` and `objectMatchesSelector` to `certmonitor_test.go`

2024-08-15 10:45 UTC, kovayur commented on internal/certmonitor/certmonitor.go
> +}
Looks good to me

2024-08-15 11:21 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +	for dataKey, dataCert := range secret.Data {
This was intentional, e.g. to fail silently & grab everything that is a cert - because we might monitor other types of certificates in the future ?

2024-08-15 12:33 UTC, aaa5kameric commented on fleetshard/pkg/k8s/client.go
> +func CreateInterfaceOrDie() kubernetes.Interface {
maybe @ludydoo can answer this better, but if im not mistaken at the time we implemented a client go k8s client because in the fleetshard client.go file near the top there was original code utilizing client go k8s client and createClientorDie(). So to maintain consistency within the file with the original code, implementation of a client-go k8s client was employed. But also because of this placement my config and clientset work better and it was tied into my informeredFactory and secretInformer for watching and monitoring.

2024-08-15 13:15 UTC, ludydoo commented on fleetshard/pkg/k8s/client.go
> +func CreateInterfaceOrDie() kubernetes.Interface {
@kovayur that's because we need an Informer which is afaik only available with `kubernetes.Interface`

2024-08-15 13:19 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +			continue
Hm, I see 2 options:
- 1. Loop through all secret keys. Don't log non-certs
- 2. Loop through predefined keys. Log non-certs

2024-08-15 13:21 UTC, ludydoo commented on internal/certmonitor/certmonitor.go
> +func (c *certMonitor) secretMatches(s *corev1.Secret, monitor MonitorConfig) bool {
Actually I think not. The `handleSecretCreation` / `handleSecretUpdate` should be calling this method

2024-08-15 14:35 UTC, kovayur commented on fleetshard/pkg/k8s/client.go
> +func CreateInterfaceOrDie() kubernetes.Interface {
Understood, no objections.

2024-08-19 07:10 UTC, aaa5kameric commented on fleetshard/main.go
> +				Secret: certmonitor.SelectorConfig{ // pragma: allowlist secret
Here is the jira link, let me know if anything needs to be changed: https://issues.redhat.com/browse/ROX-25844

2024-08-20 07:50 UTC, kovayur approved these changes

2024-08-21 07:42 UTC, merged