WIP ROX-11414: Send routes statuses
stackrox/acs-fleet-manager pull request #197
Opened 2022-07-13 08:23 UTC by kovayur

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-07-18 08:31 UTC, SimonBaeumer requested changes
@kovayur Changes look LGTM. 
Requesting changes because of possible logic conflicts from another PR. Please connect to @ivan-degtiarenko because he has also updated the reconciler logic in https://github.com/stackrox/acs-fleet-manager/pull/178

2022-07-18 08:31 UTC, SimonBaeumer commented on fleetshard/pkg/k8s/route.go
> +func (s *RouteService) FindMtlsCanonicalHostname(ctx context.Context, namespace string) (string, error) {
```suggestion
func (s *RouteService) FindMTLSCanonicalHostname(ctx context.Context, namespace string) (string, error) {
```

2022-07-18 08:31 UTC, SimonBaeumer commented on fleetshard/pkg/k8s/route.go
> +type RouteService struct {
Please add a short description what the service does

2022-07-18 13:52 UTC, kovayur commented
/retest

2022-07-18 15:06 UTC, ivan-degtiarenko commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	if !changed && remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String() {
I think as long as this `if` is aligned with [this change](https://github.com/stackrox/acs-fleet-manager/pull/178/files#diff-8b2c412ebc3fa158d46c2dfb0136cfef521abb4fb2dda0a77b403a32afd9c58eR70), rebasing auth provider related changes should not be an issue.

2022-07-19 04:57 UTC, johannes94 requested changes

2022-07-19 04:57 UTC, johannes94 commented on fleetshard/pkg/k8s/route.go
> +type RouteService struct {
+1 for all exported functions and types in this package

2022-07-20 07:25 UTC, mtesseract commented on dev/env/defaults/cluster-type-infra-openshift/env
> +export CLUSTER_DNS_DEFAULT=$(oc get -n "openshift-ingress-operator" ingresscontrollers default -o=jsonpath='{.status.domain}' --ignore-not-found)
Is it required to use `oc` here?
If not, I have a suggestion: After https://github.com/stackrox/acs-fleet-manager/pull/210/files is merged you could use `try_kubectl` in place of `oc`. That would try to use either `kubectl` or `oc`, depending on what is available and it would fail gracefully with an error message in case none of thesse tools was found.

2022-07-20 12:32 UTC, kovayur commented on dev/env/defaults/cluster-type-infra-openshift/env
> +export CLUSTER_DNS_DEFAULT=$(oc get -n "openshift-ingress-operator" ingresscontrollers default -o=jsonpath='{.status.domain}' --ignore-not-found)
No, not required. Will fix in the next pr once #210 is merged.

2022-07-20 12:45 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	"github.com/stackrox/acs-fleet-manager/fleetshard/pkg/k8s"
Thanks, fixed. My IDE settings relied on gofmt rather than goimports. Fixed now.

2022-07-20 12:45 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	if !changed && remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String() {
Thanks, rebased

2022-07-20 12:46 UTC, kovayur commented on fleetshard/pkg/k8s/route.go
> +func (s *RouteService) FindMtlsCanonicalHostname(ctx context.Context, namespace string) (string, error) {
Fixed.

2022-07-21 06:44 UTC, johannes94 commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		statuses, err := r.getRoutesStatuses(ctx, namespace)
Ok, I think I was confused I though we were getting the routes for the overall status object, but we're also getting the status for the routes. So statuses means a different status then the status from the requests send to fleet-manager. Got it.

2022-07-21 06:49 UTC, johannes94 approved these changes
LGTM

2022-07-21 14:00 UTC, SimonBaeumer approved these changes
/approve

2022-07-21 14:18 UTC, merged