ROX-26039: Create tenant argoCd app
stackrox/acs-fleet-manager pull request #2009
Opened 2024-09-02 17:36 UTC by ludydoo

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-10-16 09:52 UTC, kovayur approved these changes
🔥

2024-10-16 12:25 UTC, johannes94 requested changes
I don't like being the "Process-driven block a PR because of formal issues guy", but for a change like this, I'd expect more information in the PR description. For instance how you've tested the changes and also a functional description of what you expect / not expect to work after this PR.

2024-10-16 12:25 UTC, johannes94 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			// This little part would only happen if we enable, then disable ArgoCD for a tenant
In my understanding this part would execute on every reconciliation where `remoteCentral.Spec.ArgoCd.Enabled != true`, am I wrong here? If so could you explain why?

Maybe the function would be NOOP in that case but it would go through this code path.

2024-10-16 12:31 UTC, ludydoo commented on fleetshard/config/config.go
> +	DefaultTenantArgoCdAppSourcePath    string `env:"TENANT_ARGOCD_APP_SOURCE_PATH_DEFAULT" envDefault:"tenant-resources"`
I named it default in the sense of it being the default if there are no per-tenant overrides. You are recommending dropping the DEFAULT here ?

2024-10-16 12:44 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			// This little part would only happen if we enable, then disable ArgoCD for a tenant
Not every reconciliation, only if the hashSum has been changed. 
This would run if 
1. ArgoCD enabled for a tenant
2. Then ArgoCD disabled for a tenant

This would basically clean up the ArgoCD application

2024-10-16 13:42 UTC, johannes94 commented on fleetshard/config/config.go
> +	DefaultTenantArgoCdAppSourcePath    string `env:"TENANT_ARGOCD_APP_SOURCE_PATH_DEFAULT" envDefault:"tenant-resources"`
For this specific env variables I'd recommend to make the naming consistent. The default should be either a prefix or a suffix, for instance: Env Variable: `TENANT_ARGOCD_APP_SOURCE_REF_DEFAULT` should be field  `TenantArgoCdAppSourceRefDefault` not `DefaultTenantArgoCdAppSourceRef`

For the `CentralReconciler` / `CentralReconcilerOptions` I don't see any logic for overriding that values on a per-tenant basis, so I'm questioning if this is going to be added in follow up PRs or if the "Default" prefix is unnecessary.

2024-10-16 13:42 UTC, johannes94 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			// This little part would only happen if we enable, then disable ArgoCD for a tenant
> Not every reconciliation, only if the hashSum has been changed.
True, forgot about that part.

Still I think this code path would run even if ArgoCD was never enabled for a tenant. Not only in the situation described above, which makes the comment misleading.

2024-10-16 14:28 UTC, ludydoo commented on fleetshard/config/config.go
> +	DefaultTenantArgoCdAppSourcePath    string `env:"TENANT_ARGOCD_APP_SOURCE_PATH_DEFAULT" envDefault:"tenant-resources"`
The ability to override the ArgoCD application source (repo/path/ref) will be added later

2024-10-16 14:29 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			// This little part would only happen if we enable, then disable ArgoCD for a tenant
Ah I see what you mean. Will change to
```
This little part handles the case where we enable, then disable ArgoCD for a tenant
```

2024-10-16 14:31 UTC, ludydoo commented on fleetshard/config/config.go
> +	DefaultTenantArgoCdAppSourcePath    string `env:"TENANT_ARGOCD_APP_SOURCE_PATH_DEFAULT" envDefault:"tenant-resources"`
I'll rename the env var to be consistent

2024-10-28 12:43 UTC, ludydoo commented
/retest

2024-10-29 06:42 UTC, ludydoo commented
/retest

2024-10-29 08:56 UTC, ludydoo commented
/retest

2024-10-30 08:16 UTC, ludydoo commented
/retest

2024-10-30 16:35 UTC, ludydoo commented
/retest

2024-10-31 06:24 UTC, ludydoo commented
/retest

2024-10-31 17:32 UTC, ludydoo commented
/retest

2024-11-04 13:25 UTC, johannes94 approved these changes

2024-11-04 13:25 UTC, johannes94 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	argoCdAppDeleted, err := r.ensureArgoCdApplicationDeleted(ctx, *remoteCentral)
Nit: you might want to guard this line with the argo enabled flag as well. But IIUC it would work as long as the respective CRD is available.

2024-11-08 10:25 UTC, kovayur commented on dev/env/scripts/bootstrap.sh
> +    kubectl create ns openshift-gitops || true
Shouldn't the namespace manifest be defined in `${MANIFESTS_DIR}/openshift-gitops` instead ?

2024-11-08 10:26 UTC, kovayur commented on dev/env/scripts/bootstrap.sh
> +"${GITROOT}/scripts/import_argocd_repo_secret.sh"
Instead of generating a secret you can put it to the `${MANIFESTS_DIR}/openshift-gitops` folder and change the line 62: 
```
chamber exec gitops -b secretsmanager -- apply "${MANIFESTS_DIR}/openshift-gitops"
```

`apply` supports `envsubst`. That's how the secrets propagation works in other components.

2024-11-12 12:35 UTC, kovayur approved these changes

2024-11-12 15:18 UTC, ludydoo commented
/retest

2024-11-12 17:00 UTC, ludydoo commented
/retest

2024-11-13 07:17 UTC, ludydoo commented
/retest

2024-11-14 08:02 UTC, merged