ROX-24112: cluster reassignment admin API
stackrox/acs-fleet-manager pull request #2053
Opened 2024-10-01 12:04 UTC by johannes94

## Description

This PR is the first of several PRs to enable migrating a tenant from on dataplane cluster to the other. It adds:
* A feature flag `RHACS_CLUSTER_MIGRATION`
* A admin API endpoint to be able to reassign the `cluster_id` column of a tenant in the DB via API

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-10-09 10:13 UTC, ebensh requested changes
LGTM, just some small nits; thanks for the cleanup along the way (renaming Dinosaur to Central) and making the review straightforward.

How did you feel about the amount of work to make a new API endpoint and change the cluster ID? It seems like a large change across many files, but was it fairly straightforward where to change what?

2024-10-09 10:13 UTC, ebensh commented on internal/dinosaur/test/integration/admin_test.go
> +			Owner:          "assigclusteruser1",
nit - assig?

2024-10-09 10:13 UTC, ebensh commented on internal/dinosaur/test/integration/admin_test.go
> +package integration
Is it worth adding a test for trying to move between clusters that do not match criteria (e.g. different MultiAZ)? I didn't see one in the cluster_placement_strategy and wasn't sure if it would go there or here

2024-10-09 13:23 UTC, johannes94 commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +func (d FirstReadyPlacementStrategy) AllMatchingClustersForCentral(central *dbapi.CentralRequest) ([]*api.Cluster, error) {
You're right sounds like that is more like a function that might be shared across multiple strategies. Moved it to a package function instead.

2024-10-09 13:23 UTC, johannes94 commented on internal/dinosaur/test/integration/admin_test.go
> +			Owner:          "assigclusteruser1",
Whoops. Fixed. :)

2024-10-09 13:23 UTC, johannes94 commented on internal/dinosaur/test/integration/admin_test.go
> +package integration
Hard to tell where to put them, I'd say if I add one it's gonna be here because it tests the entire API to DB flow.

I have a test with a region mismatch, essentially the logic is the same. Do you think I should add more edge cases to that test?

2024-10-09 13:27 UTC, johannes94 commented
> LGTM, just some small nits; thanks for the cleanup along the way (renaming Dinosaur to Central) and making the review straightforward.
> 
> How did you feel about the amount of work to make a new API endpoint and change the cluster ID? It seems like a large change across many files, but was it fairly straightforward where to change what?

It looks worse than it is. Essentially you're modifying the openapi doc, then most things get generate by `make generate`.

The actual manual changes are fairly simple:
- Add a HTTP handler.
- Route to that handler.
- Add a function to the dinosaurservice that orchestrates business logic.
- Done.

2024-10-09 13:57 UTC, johannes94 commented
/retest

2024-10-09 14:37 UTC, johannes94 commented
/retest

Cluster creation failed.

2024-10-10 04:50 UTC, johannes94 commented
/retest

2024-10-11 10:40 UTC, ebensh approved these changes

2024-10-14 09:11 UTC, merged