ROX-27073: add cluster migration e2e test
stackrox/acs-fleet-manager pull request #2127
Opened 2024-12-16 09:44 UTC by johannes94

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary
- [ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)
- [ ] Check AWS limits are reasonable for changes provisioning new resources
- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup
make verify lint binary test test/integration
```

2024-12-19 10:58 UTC, ebensh requested changes
Several nits, nothing major - the flow of the e2e test makes sense and is easy enough to read with the comments you provided throughout

2024-12-19 10:58 UTC, ebensh commented on .gitignore
> +cluster-list.json
Where do these come from / why can we not clean them up after the test?

2024-12-19 10:58 UTC, ebensh commented on e2e/dns/record_cleanup.go
> +package dns
Would waiting for "deleting" state instead of "deprovisioning" rely on the FM's cleanup of the routes instead of manually cleaning them up here? (sorry if missing something, not used to looking at the e2e tests as much)

2024-12-19 10:58 UTC, ebensh commented on e2e/e2e_suite_test.go
> +	waitTimeout           = testutil.GetWaitTimeout()
Just a meta-comment - adding the `testutil.` in a separate PR if possible would've made reviewing just the cluster migration part easier. It's fast enough to skim by but next time would recommend splitting into 2 PRs

2024-12-19 10:58 UTC, ebensh commented on e2e/e2e_test.go
> +			testutil.AssertDNSMatchesRouter(dnsRecordsLoader.CentralDomainNames, recordSets, &reencryptIngress)
:+1:

2024-12-19 10:58 UTC, ebensh commented on e2e/multicluster/multicluster_migration_test.go
> +	dpRegion        = "standalone"
nit - a unique value from dpCloudProvider

2024-12-19 12:38 UTC, johannes94 commented on .gitignore
> +cluster-list.json
Those files would be created and not cleaned up. So you can use them for debugging already, this is just the .gitignore to prevent those files from being commited and pushed to the repo.

2024-12-19 12:43 UTC, johannes94 commented on e2e/dns/record_cleanup.go
> +package dns
I'm not 100% sure about this. But I think FM would only start deleting the route records on `deleting` state.

We trigger a deletion and wait for deletion at the end of this test, which usually cleans up the records. 

This logic is intended as an additional measure on test failures. Because on failures we might be stuck somewhere in the usual reconciliation loop which can lead to a situation where the deletion lifecycle logic doesn't get executed. In a case like this we don't want to leak those resources.

2024-12-19 12:45 UTC, johannes94 commented on e2e/e2e_suite_test.go
> +	waitTimeout           = testutil.GetWaitTimeout()
Yes, I thought about splitting PRs as well along the way, decided to not do it since I only wanted very few changes. Then it grew over time to what you see now :) . I'll split it next time.

2024-12-19 12:55 UTC, johannes94 commented on e2e/testutil/testutil.go
> +func ObtainCentralRequest(ctx context.Context, client *fleetmanager.Client, id string, request *public.CentralRequest) error {
You're right. Its called that way because the private function I copied to `testuitl` was called like that before.

I changed it.

2024-12-19 12:57 UTC, johannes94 commented on e2e/multicluster/multicluster_migration_test.go
> +	dpRegion        = "standalone"
Do you mean dpCloudProvider should have a different value than dpRegion?

Unfortunately that's not so easy, because that's what we have for the cluster configurations all other tests do it like this as well.

2025-01-21 14:25 UTC, ebensh approved these changes
LGTM, thanks

2025-01-22 10:30 UTC, merged