ROX-10829: enable wrapcheck linter
stackrox/acs-fleet-manager pull request #217
Opened 2022-07-21 16:12 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-07-25 16:26 UTC, vladbologa commented
/test e2e

2022-07-25 17:18 UTC, vladbologa commented
/test e2e

2022-07-25 23:25 UTC, mtesseract requested changes
I am not through yet, though.

2022-07-25 23:25 UTC, mtesseract commented on fleetshard/pkg/testutils/k8s.go
>  		multiErr = multierror.Append(multiErr, t.ObjectTracker.Create(secretsGVR, newCentralTLSSecret(ns), ns))
I wasn't quite sure how to tackle this one, but in order to not loose context I was wondering if it would be better to not throw the `err` from the `Create` calls directly into the `multiErr`, but instead add wrapped errors (providing context as in l.75 above) to the multiErr.
WDYT?

2022-07-25 23:25 UTC, mtesseract commented on fleetshard/pkg/util/hash.go
> +		return [16]byte{}, fmt.Errorf("marshalling json: %w", err)
```suggestion
		return [16]byte{}, fmt.Errorf("marshaling JSON: %w", err)
```

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +		return nil, fmt.Errorf("unmarshalling routes: %w", err)
```suggestion
		return nil, fmt.Errorf("unmarshaling routes from JSON: %w", err)
```

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +		return fmt.Errorf("marshalling routes: %w", err)
```suggestion
		return fmt.Errorf("marshaling routes into JSON: %w", err)
```

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/clusters/ocm_provider.go
> +			return nil, fmt.Errorf("applying resources: %w", svcErr)
For me `"applying resources"` would be a better wrapping for errors at the caller site of `ApplyResources`. Here I would suggest something like 
```suggestion
			return nil, fmt.Errorf("retrieving sync set %s for cluster %s: %w", resources.Name, clusterSpec.InternalID, svcErr)
```

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/clusters/ocm_provider.go
> +		return nil, fmt.Errorf("creating SyncSet: %w", err)
```suggestion
		return nil, fmt.Errorf("creating SyncSet for cluster %q: %w", clusterID, err)
```

I don't know what spelling for sync set would be best (SyncSet, syncset, Syncset, Sync Set, sync set, sync-set, etc.), but I would suggest to use the same spelling in all error wrappings/log messages.

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/clusters/ocm_provider.go
> +			return nil, fmt.Errorf("updating SyncSet: %w", err)
```suggestion
			return nil, fmt.Errorf("updating SyncSet %q for cluster %q: %w", resourceSet.Name, clusterID, err)
```

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/clusters/standalone_provider.go
> +		return nil, fmt.Errorf("marshalling resource: %w", err)
```suggestion
		return nil, fmt.Errorf("marshaling resource %q into JSON: %w", resource.???, err)
```

Is it easy to get a kind & name combination or something like that for a generic `resource interface{}`?

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/clusters/standalone_provider.go
```suggestion
```

2022-07-25 23:25 UTC, mtesseract commented on internal/dinosaur/pkg/clusters/standalone_provider.go
> +		return nil, fmt.Errorf("unmarshalling data: %w", err)
```suggestion
		return nil, fmt.Errorf("unmarshaling data from JSON: %w", err)
```

2022-07-25 23:30 UTC, mtesseract commented
/retest

2022-07-26 07:57 UTC, vladbologa commented on fleetshard/pkg/fleetmanager/client.go
> +		return fmt.Errorf("marshalling status: %w", err)
I'd leave it with double L, because it's the more common spelling overall, and in this repo there's only 1 instance with single L.

2022-07-26 08:30 UTC, vladbologa commented on internal/dinosaur/pkg/clusters/ocm_provider.go
> +		return nil, fmt.Errorf("creating SyncSet: %w", err)
I think it's an OpenShift resource and it's spelt SyncSet

2022-07-26 15:47 UTC, vladbologa commented on internal/dinosaur/pkg/clusters/standalone_provider.go
> +		return nil, fmt.Errorf("marshalling resource: %w", err)
Actually it is, something like ("%T %v", resource, resource) would print the type and value. Should I do this?

2022-07-26 16:09 UTC, mtesseract commented on internal/dinosaur/pkg/services/data_plane_cluster.go
> +				return false, fmt.Errorf("getting FleetShard operator status: %w", err)
```suggestion
				return false, fmt.Errorf("parsing data plane cluster condition %q: %w", dataPlaneClusterStatusCondReadyName, err)
```

2022-07-26 16:13 UTC, mtesseract commented on internal/dinosaur/pkg/services/observatorium_service.go
> +	state, err := obs.observatorium.Service.GetDinosaurState(name, namespaceName)
It's not obvious to me if the `name/namespaceName` pair will end up in `err` -- if not, I would suggest to add it into the error message below.

Out of scope for this PR: I wonder if we really need the indirection of this function -- not clear to me what the rationale is behind having it.

2022-07-26 16:20 UTC, mtesseract commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return false, fmt.Errorf("checking configured quota cost: %w", err)
I have the impression that this is more about retrieving a summary of actually consumed quota, not so much about configured quota.

So, to me the message should read more like:
```suggestion
		return false, fmt.Errorf("retrieving quota costs: %w", err)
```

And, WDYT about checking what other information (see parameters of `GetQuotaCostsForProduct()` are missing from the error context and should hence be added to the error message?

2022-07-26 16:22 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +				return fmt.Errorf("reconciling deprovisioning cluster: %w", err)
This message should be added by the caller of this function, I think. I would suggest something like 
```suggestion
				return fmt.Errorf("updating status for cluster %s to %s: %w", cluster.clusterID, api.ClusterReady, err)
```

2022-07-26 16:23 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +	return updateStatusErr == nil, nil
we know it is `== nil` at this point, hence i find `return nil, nil` clearer.

2022-07-26 16:50 UTC, mtesseract requested changes

2022-07-26 16:50 UTC, mtesseract commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return fmt.Errorf("waiting for number of dinosaurs: %w", err)
I guess we can already use `central/centrals` in any new code that we add. I don't add a comment on the other occurrences of dinosaurs.

2022-07-26 16:50 UTC, mtesseract commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return dinosaur, nil, fmt.Errorf("waiting for dinosaur creation to be accepted: %w", err)
I think this should be `return nil, nil, ...` for clarity.

2022-07-26 16:50 UTC, mtesseract commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return dinosaur, fmt.Errorf("waiting for dinosaur to reach status: %w", err)
nil

2022-07-26 16:50 UTC, mtesseract commented on internal/dinosaur/test/mocks/fleetshardsync/fleetshard-sync.go
> +			return fmt.Errorf("retrieving ocmClient operator addon: %w", err)
suggestion: add `clusterID` and/or `AddonID` to the error message if the information is not enriched anywhere else (here and below).

2022-07-26 16:50 UTC, mtesseract commented on internal/dinosaur/test/mocks/fleetshardsync/fleetshard-sync.go
> +			return fmt.Errorf("updating CentralClusterStatus: %w", err)
I would do less camel-casing
```suggestion
			return fmt.Errorf("updating central status for cluster %s: %w", dataplaneCluster.clusterID, err)
```

2022-07-26 16:50 UTC, mtesseract commented on pkg/acl/access_control_list.go
> +		return fmt.Errorf("unmarshalling file contents: %w", err)
Looks to me like if unmarshalling fails than the error does not contain a reference to the invalid filename, is this correct? If so, the name should be added to the error here.

2022-07-26 16:50 UTC, mtesseract commented on pkg/api/cluster_types.go
> +		return fmt.Errorf("setting available central operator versions: %w", err)
Personally I like "retrieving/updating/..." more for user-facing messages than "getting/setting/...", but not critical for me at all.

2022-07-26 16:50 UTC, mtesseract commented on pkg/api/json.go
> +		return fmt.Errorf("unmarshalling json: %w", err)
does the context provide any information on what was attempted to unmarshall here?

2022-07-26 16:50 UTC, mtesseract commented on pkg/api/json.go
> +		return v, fmt.Errorf("marshalling json: %w", err)
same here (see above).

2022-07-26 16:50 UTC, mtesseract commented on pkg/api/json.go
> +		return nil, fmt.Errorf("marshalling json: %w", err)
unmarshalling.

2022-07-26 16:50 UTC, mtesseract commented on pkg/api/semverutil.go
> +		return 0, fmt.Errorf("comparing versions: %w", err)
the failure here is about parsing the version.

2022-07-26 16:50 UTC, mtesseract commented on pkg/api/semverutil.go
> +		return 0, fmt.Errorf("comparing versions: %w", err)
same (also, below are more of these). I think the messages you have introduced here would be more applicable on the caller site.

2022-07-26 16:50 UTC, mtesseract commented on pkg/auth/fleetshard_authz.go
> +		return fmt.Errorf("reading FleedShard AuthZ config: %w", err)
unmarshalling.

2022-07-26 16:58 UTC, vladbologa commented on internal/dinosaur/pkg/config/dataplane_cluster_config.go
>  			return errors.Errorf("The kubeconfig file %s does not exist", c.Kubeconfig)
Not sure what you mean. I replaced `os.IsNotExist` with `errors.Is(err, fs.ErrNotExist)` everywhere in the code, because `os.IsNotExist` is obsolete and should not be used in new code.

2022-07-26 17:03 UTC, vladbologa commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +	return updateStatusErr == nil, nil
`return true, nil` I think

2022-07-26 17:04 UTC, vladbologa commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return dinosaur, nil, fmt.Errorf("waiting for dinosaur creation to be accepted: %w", err)
it's not a pointer, so it can't be nil

2022-07-26 17:04 UTC, vladbologa commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return dinosaur, fmt.Errorf("waiting for dinosaur to reach status: %w", err)
same, not a pointer

2022-07-26 17:26 UTC, mtesseract requested changes

2022-07-26 17:26 UTC, mtesseract commented on pkg/client/iam/config.go
> +		return nil, fmt.Errorf("making GET request: %w", err)
```suggestion
		return nil, fmt.Errorf("executing HTTP GET request : %w", err)
```
Does the error reference the url? If not, I'd add it.

2022-07-26 17:26 UTC, mtesseract commented on pkg/client/observatorium/client.go
> +		return v, w, fmt.Errorf("executing POST request: %w", err)
I guess `return nil, nil, ...` would be clearer.

2022-07-26 17:26 UTC, mtesseract commented on pkg/client/observatorium/client.go
> +		return v, w, fmt.Errorf("executing range POST request: %w", err)
see above.

2022-07-26 17:26 UTC, mtesseract commented on pkg/server/logging/writer.go
> +		return fmt.Errorf("logging object: %w", merr)
```suggestion
		return fmt.Errorf("formatting object: %w", merr)
```

2022-07-26 17:26 UTC, mtesseract commented on pkg/server/logging/writer.go
> +		return i, fmt.Errorf("writing log body: %w", err)
does the "log" there make sense?

2022-07-26 17:26 UTC, mtesseract commented on pkg/server/logging/writer.go
> +		return "", fmt.Errorf("preparing request log: %w", err)
This is again about a formatting failure.

2022-07-26 17:26 UTC, mtesseract commented on pkg/server/logging/writer.go
> +		return "", fmt.Errorf("preparing response log: %w", err)
same.

2022-07-26 17:26 UTC, mtesseract commented on pkg/services/queryparser/query_parser.go
> +		return nil, fmt.Errorf("parsing sql string: %w", err)
```suggestion
		return nil, fmt.Errorf("unexpected EOF during parsing of database query: %w", err)
```

2022-07-26 17:26 UTC, mtesseract commented on pkg/shared/config.go
> +		return fmt.Errorf("reading config yaml file: %w", err)
problem here seems to be only unmarshalling.

2022-07-26 17:26 UTC, mtesseract commented on pkg/shared/config.go
> +		return "", fmt.Errorf("reading config file: %w", err)
I dunno, this function seems to be pretty generic, so I would drop the "config".

2022-07-26 17:26 UTC, mtesseract commented on pkg/services/authorization/authorization.go
> +		return false, fmt.Errorf("checking if user is valid: %w", err)
```suggestion
		return false, fmt.Errorf("retrieving accounts list: %w", err)
```

2022-07-26 17:26 UTC, mtesseract commented on pkg/shared/secrets/secrets.go
> +		return nil, fmt.Errorf("modifying secrets: %w", err)
```suggestion
		return nil, fmt.Errorf("retrieving paths to password fields: %w", err)
```

2022-07-26 17:26 UTC, mtesseract commented on pkg/shared/secrets/secrets.go
> +		return nil, fmt.Errorf("modifying secrets: %w", err)
unmarshalling error.

2022-07-26 17:26 UTC, mtesseract commented on pkg/shared/secrets/secrets.go
> +		return nil, fmt.Errorf("modifying secrets: %w", err)
marshalling error.

2022-07-26 17:26 UTC, mtesseract commented on pkg/shared/secrets/secrets.go
> +		return nil, fmt.Errorf("getting paths to password fields: %w", err)
I have suggested to move this to the caller. In that case some other error msg should be inserted here and below.

2022-07-26 17:26 UTC, mtesseract commented on pkg/services/account/account_service_impl.go
> +		return nil, fmt.Errorf("searching organizations: %w", err)
```suggestion
		return nil, fmt.Errorf("retrieving list of organizations: %w", err)
```

2022-07-26 17:26 UTC, mtesseract commented on pkg/quotamanagement/quota_management_list_config.go
> +		return fmt.Errorf("reading file: %w", err)
I think you can just use the pragma here for disabling the lint complain. I mean, this is basically what `shared.ReadFile` is already producing.

2022-07-26 17:26 UTC, mtesseract commented on pkg/environments/environment.go
> +		return nil, fmt.Errorf("creating env: %w", err)
I honestly don't know what to put here, but I wouldn't new what "creating env" means. Maybe "initializing dependency injection"?

2022-07-26 17:26 UTC, mtesseract commented on pkg/environments/environment.go
> +		return fmt.Errorf("creating services: %w", err)
Is "creating services" describing what went wrong here? I would have to lookup the docs of the relevant functions here.

2022-07-26 17:30 UTC, vladbologa commented on internal/dinosaur/pkg/migrations/20220114114500_add_centrals.go
> +				return fmt.Errorf("migrating: %w", err)
agree, I'll change

2022-07-26 17:35 UTC, vladbologa commented on pkg/client/observatorium/client.go
> +		return v, w, fmt.Errorf("executing POST request: %w", err)
I think also here they aren't pointers, so can't do `nil`

2022-07-26 17:35 UTC, vladbologa commented on pkg/client/observatorium/client.go
> +		return v, w, fmt.Errorf("executing range POST request: %w", err)
same, they are not pointers

2022-07-26 18:00 UTC, vladbologa commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return fmt.Errorf("waiting for number of dinosaurs: %w", err)
I'd suggest to change this when we change the surrounding code too...

2022-07-26 18:13 UTC, vladbologa commented on pkg/api/cluster_types.go
> +		return fmt.Errorf("setting available central operator versions: %w", err)
I think the error message should be 'marshalling' here though....

2022-07-26 20:19 UTC, vladbologa commented on pkg/shared/config.go
> +		return "", fmt.Errorf("reading config file: %w", err)
I'd keep it like this, it's less generic and so easier to search the source code for it

2022-07-26 20:30 UTC, vladbologa commented on pkg/quotamanagement/quota_management_list_config.go
> +		return fmt.Errorf("reading file: %w", err)
I don't think that's a good idea. I'd go for "reading quota management list config file". This way if you get a generic error from .ReadFile(), you can find it in the source code.

You could say that this could go in the caller, but the caller might not wrap errors, because the linter only looks at errors coming from external packages.

2022-07-26 20:55 UTC, mtesseract commented on internal/dinosaur/test/common/dinosaur_pollers.go
> +		return fmt.Errorf("waiting for number of dinosaurs: %w", err)
ok

2022-07-26 20:56 UTC, mtesseract commented on pkg/api/cluster_types.go
> +		return fmt.Errorf("setting available central operator versions: %w", err)
agreed

2022-07-26 21:07 UTC, mtesseract commented on pkg/client/observatorium/client.go
> +		return v, w, fmt.Errorf("executing POST request: %w", err)
Well, the first return value is an interface, hence it can be nil. This is how the Query function is implemented in the prometheus client library: https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/api.go#L855
It returns `nil` as first value in case of an error. We could do the same here. Regarding the `w` parameter, that is of type `type Warnings []string`, i.e. a slice and a slice has `nil` as its zero value, so that could also be nil.

2022-07-26 21:10 UTC, mtesseract commented on pkg/shared/config.go
> +		return "", fmt.Errorf("reading config file: %w", err)
Hmm, but have you seen that it is also used for reading files, which are not configuration files, e.g. https://github.com/stackrox/acs-fleet-manager/blob/vbologa%2FROX-10829-enable-wrapcheck-linter/fleetshard/pkg/fleetmanager/auth_rhsso.go#L51?

2022-07-26 22:33 UTC, mtesseract requested changes

2022-07-26 22:33 UTC, mtesseract commented on pkg/client/ocm/client.go
> +		return nil, fmt.Errorf("creating cluster authorization: %w", err)
describing what has just failed vs. describing what the current function is supposed to do.
Would you rather keep it this way?
same for the other two chqnges in this file.

2022-07-26 22:33 UTC, mtesseract commented on pkg/client/redhatsso/client.go
> +	return &serviceAccount, err == nil, nil
```suggestion
	return &serviceAccount, true, nil
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/config.go
> +		return fmt.Errorf("reading host value from file: %w", err)
```suggestion
		return fmt.Errorf("reading database host file: %w", err)
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/config.go
> +		return fmt.Errorf("reading port value from file: %w", err)
```suggestion
		return fmt.Errorf("reading database port file: %w", err)
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/config.go
> +		return fmt.Errorf("reading username value from file: %w", err)
```suggestion
		return fmt.Errorf("reading database username file: %w", err)
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/config.go
> +		return fmt.Errorf("reading password value from file: %w", err)
```suggestion
		return fmt.Errorf("reading database password file: %w", err)
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/config.go
> +		return fmt.Errorf("reading name value from file: %w", err)
```suggestion
		return fmt.Errorf("reading database name file: %w", err)
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/connection.go
> +		return fmt.Errorf("getting DB object: %w", sqlDBErr)
```suggestion
		return fmt.Errorf("getting DB connection: %w", sqlDBErr)
```

2022-07-26 22:33 UTC, mtesseract commented on pkg/db/connection.go
> +		return nil, fmt.Errorf("getting DB object: %w", sqlDBErr)
```suggestion
		return nil, fmt.Errorf("getting DB connection: %w", sqlDBErr)
```

2022-07-26 22:33 UTC, mtesseract commented on test/mocks/api_server.go
> +			return fmt.Errorf("marshalling AddOnnInstallation: %w", err)
```suggestion
			return fmt.Errorf("marshalling AddOnInstallation: %w", err)
```

2022-07-27 08:02 UTC, vladbologa commented on pkg/shared/config.go
> +		return "", fmt.Errorf("reading config file: %w", err)
right, there's no context here that suggests it's a config file. I don't know where I got that from

2022-07-27 08:08 UTC, vladbologa commented on pkg/api/semverutil.go
> +		return 0, fmt.Errorf("comparing versions: %w", err)
I forgot about these two

2022-07-27 08:20 UTC, vladbologa commented on internal/dinosaur/pkg/clusters/standalone_provider.go
> +		return nil, fmt.Errorf("marshalling resource of type %T with value %v into JSON: %w", resource, resource, err)
alright then I remove it

2022-07-27 13:32 UTC, vladbologa commented on pkg/api/json.go
> +		return fmt.Errorf("unmarshalling json: %w", err)
seems like a quite generic function, I don't think I can add additional context

2022-07-27 13:32 UTC, vladbologa commented on pkg/api/json.go
> +		return v, fmt.Errorf("marshalling json: %w", err)
same as above

2022-07-27 15:33 UTC, mtesseract requested changes
the "notes" are for me.

2022-07-27 15:33 UTC, mtesseract commented on pkg/client/redhatsso/client.go
> +		return nil, fmt.Errorf("getting service accounts: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building Subscription: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building ClusterAuthorizationResponse: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building Syncset: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building CloudProvier: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building CloudProviderList: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building CloudRegion: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building CloudRegionList: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building ClusterStatus: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building AddOnInstallation: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building AddOnInstallationList: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building Cluster: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building MachinePoolList: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building MachinePool: %w", err)
note

2022-07-27 15:33 UTC, mtesseract commented on test/mocks/api_server.go
> +		return nil, fmt.Errorf("building IdentityProvider: %w", err)
note

2022-07-27 15:41 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	return nil
oops good catch

2022-07-27 17:15 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	return nil
I think this latest version preserves the original behaviour, while also makes it clearer that we ignore the error from Create namespace (I wonder if that was intended? it's not really ensuring that the namespace exists)

2022-07-27 17:21 UTC, vladbologa commented on fleetshard/pkg/testutils/k8s.go
>  		multiErr = multierror.Append(multiErr, t.ObjectTracker.Create(secretsGVR, newCentralTLSSecret(ns), ns))
Could have something like this, WDYT?

```suggestion
		multiErr = multierror.Append(multiErr, errors.Wrap(t.ObjectTracker.Create(secretsGVR, newCentralTLSSecret(ns), ns), "creating central TLS secret"))
		multiErr = multierror.Append(multiErr, errors.Wrap(t.ObjectTracker.Create(routesGVR, newCentralRoute(ns), ns), "creating central route"))
		multiErr = multierror.Append(multiErr, errors.Wrap(t.ObjectTracker.Create(routesGVR, newCentralMtlsRoute(ns), ns), "creating central MTLS route"))		
```

2022-07-27 17:37 UTC, vladbologa commented on fleetshard/pkg/testutils/k8s.go
>  		multiErr = multierror.Append(multiErr, t.ObjectTracker.Create(routesGVR, newCentralMtlsRoute(ns), ns))
```suggestion
		multiErr = multierror.Append(multiErr, errors.Wrap(t.ObjectTracker.Create(secretsGVR, newCentralTLSSecret(ns), ns), "creating central TLS secret"))
		multiErr = multierror.Append(multiErr, errors.Wrap(t.ObjectTracker.Create(routesGVR, newCentralRoute(ns), ns), "creating central route"))
		multiErr = multierror.Append(multiErr, errors.Wrap(t.ObjectTracker.Create(routesGVR, newCentralMtlsRoute(ns), ns), "creating central MTLS route"))
```

could have something like this, WDYT?

2022-07-27 17:44 UTC, vladbologa commented on fleetshard/pkg/testutils/k8s.go
>  		multiErr = multierror.Append(multiErr, t.ObjectTracker.Create(routesGVR, newCentralMtlsRoute(ns), ns))
this suggestion needs importing `"github.com/pkg/errors"` btw

2022-07-27 17:49 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	return nil
nvm, you fixed this on `main` 👍

2022-07-27 19:42 UTC, mtesseract commented on fleetshard/pkg/testutils/k8s.go
>  		multiErr = multierror.Append(multiErr, t.ObjectTracker.Create(routesGVR, newCentralMtlsRoute(ns), ns))
Thanks for looking into this! But, I just realized that this is code for the test suite, which does not seem to be used in the production code, hence I would say that we shouldn't worry about the wrapping here. Let's keep this simple.

2022-07-27 20:58 UTC, mtesseract approved these changes
I think this is ready when CI is green.

2022-07-27 21:43 UTC, merged