ROX-11862: Match DNS name to the ADR
stackrox/acs-fleet-manager pull request #238
Opened 2022-07-28 09:07 UTC by kovayur

## Description
This PR aligns the routes creation implementation with URI scheme we decided to use in the ADR.
Previously there was a heuristic approach to determine a hostname using a prefix and subdomain. After this change, UI and data hostnames can be set separately on the fleetmanager with any pattern we want.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual
Tested manually on a dedicated OSD cluster

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-07-28 09:07 UTC, kovayur commented
Current dependencies on/for this PR:
* main
  * **PR #237** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/237" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #238** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/238" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/238?utm_source=stack-comment).

2022-07-29 11:56 UTC, johannes94 commented
The code changes look good to me. One thing I wanted to make sure is that we are aware of the impact of the change with the DataPlaneCentralStatusRoutes to an object instead of a list. Previously the concept was very generic and we could basically create all kind of different DNS names just by putting different routes in the request from fleetshard-sync to fleet-manager. Fleetshard-sync was aware of what routes should be created and fleet-managers job was just to create the corresponding CNAME records for that. This way only fleetshard-sync would have to change to register a new route and DNS name. The new approach is much easier to understand, since it is tailored exactly to our usecase. But we have the trade off that with the new approach if we'd like to add another route in the future we'd always have to change both fleet-manager and fleetshard-sync. What do you think about that?

2022-07-29 12:34 UTC, kovayur commented
Thanks for the thoughtful review @johannes94. I can share the concern and indeed it was a trade-off in favor of simplicity. Need to say that now if we need to add another route, we need to change not only the fleethard sync and the fleet-manager but also the Private API schema, which I don't really like.
On second thought, maybe something more flexible should be done here, I agree.

2022-08-01 07:30 UTC, johannes94 reviewed
Looks good. I'm going to test this together with #239 in our dev environment. If this works I'll approve.

2022-08-01 10:36 UTC, johannes94 requested changes

2022-08-01 10:36 UTC, johannes94 commented on internal/dinosaur/pkg/services/data_plane_dinosaur.go
> +	if routesErr := validateRouters(routesInRequest, dinosaur, clusterDNS); routesErr != nil {
This change led to routes not being stored, since the routes variable is never set. I'd suggest to remove the `routes` variable above and us `routesInRequest` in all function calls further down the line.

2022-08-01 11:25 UTC, kovayur commented on internal/dinosaur/pkg/services/data_plane_dinosaur.go
> +	if routesErr := validateRouters(routesInRequest, dinosaur, clusterDNS); routesErr != nil {
Right, thanks for checking! Fixed.

2022-08-01 11:47 UTC, johannes94 approved these changes

2022-08-01 15:07 UTC, kovayur commented
/retest

2022-08-02 09:56 UTC, merged