ROX-12012: Additional config for auth provider
stackrox/acs-fleet-manager pull request #246
Opened 2022-07-29 19:03 UTC by dhaus67

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-07-29 19:04 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #246** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/246" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/246?utm_source=stack-comment).

2022-07-30 19:30 UTC, ivan-degtiarenko requested changes
Also, could you test that org_id restriction works within created Central?

For that you would need to use the same identity to:
* send "create central" request to fleet-manager
* log in to central

2022-07-30 19:30 UTC, ivan-degtiarenko commented on fleetshard/pkg/central/reconciler/init_auth.go
> +			"disable_offline_access": "true",
Sorry, it looks like the ticket is misleading - the actual name of the field is `disable_offline_access_scope`:
https://github.com/stackrox/stackrox/blob/a539c76f0f3d50a42ad2e5bafc6b6e3b3e500e01/pkg/auth/authproviders/oidc/backend_impl.go#L37-L37

Would it be possible to ask you to fix it and verify that it actually works on the last released version of RHACS?
For that you need to:
* log in using sso.stage.redhat.com account
* Check that no offline tokens were created here: https://sso.stage.redhat.com/auth/realms/redhat-external/account/applications

2022-07-31 19:09 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/init_auth.go
> +			"disable_offline_access": "true",
I could have checked it as well 🥴 

Fixed the setting + verified that no offline token is created (adjusted the manual test steps in the description accordingly).

2022-08-01 08:46 UTC, ivan-degtiarenko approved these changes

2022-08-01 10:45 UTC, dhaus67 commented
/retest

2022-08-01 11:18 UTC, merged