ROX-12052: Routes on vanilla k8s
stackrox/acs-fleet-manager pull request #254
Opened 2022-08-01 16:47 UTC by kovayur

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-01 16:47 UTC, kovayur commented
Current dependencies on/for this PR:
* main
  * **PR #237** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/237" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #238** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/238" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #239** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/239" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #254** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/254" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/254?utm_source=stack-comment).

2022-08-04 16:23 UTC, vladbologa requested changes

2022-08-04 16:23 UTC, vladbologa commented on README.md
> +The process described in [operator documentation](https://github.com/stackrox/stackrox/tree/master/operator)
```suggestion
The process is described in [operator documentation](https://github.com/stackrox/stackrox/tree/master/operator)
```

2022-08-04 16:23 UTC, vladbologa commented on dev/env/manifests/ingress-router/route.crd.yaml
> +# See https://github.com/openshift/api/blob/master/route/v1/route.crd.yaml
Could we just get them with `curl` in the Makefile (or some equivalent approach), so that we don't duplicate these manifests in our repo?

2022-08-05 09:54 UTC, kovayur commented on dev/env/manifests/ingress-router/route.crd.yaml
> +# See https://github.com/openshift/api/blob/master/route/v1/route.crd.yaml
Thanks, it was an initial idea. Done as suggested.

2022-08-05 13:27 UTC, vladbologa requested changes

2022-08-05 13:27 UTC, vladbologa commented on scripts/ingress-router.sh
> +set -euo pipefail
You might want to not use `set -u`, because with it, the test for no arguments does not work as intended, and the script fails with `./ingress-router.sh: line 63: POSITIONAL_ARGS[@]: unbound variable`

```suggestion
set -eo pipefail
```

2022-08-05 13:54 UTC, vladbologa approved these changes

2022-08-05 14:51 UTC, merged