Add shellcheck pre-commit hook
stackrox/acs-fleet-manager pull request #259
Opened 2022-08-02 14:18 UTC by dhaus67

## Description

Inspired by [this PR](https://github.com/stackrox/acs-fleet-manager/pull/257) which fixed some shellcheck issues. This will introduce the shellcheck hook, ensuring all our scripts adhere to the same standard.

## Test manual

```
pre-commit run shellcheck --all-files # should succeed
```

2022-08-02 14:19 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #259** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/259" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/259?utm_source=stack-comment).

2022-08-02 14:21 UTC, dhaus67 commented
/retest

2022-08-02 14:31 UTC, mtesseract commented
you can read my thoughts.

2022-08-18 10:51 UTC, mtesseract requested changes

2022-08-18 10:51 UTC, mtesseract commented on .githooks/pre-commit
> +    # shellcheck disable=SC3024
Couldn't you get (properly) rid of this by using `#!/usr/bin/env bash` as she-bang instead of POSIX `sh`?
Any reason to stick with `sh`?

2022-08-18 10:51 UTC, mtesseract commented on dev/env/scripts/lib.sh
>      for i in $(seq "$seconds"); do
Wouldn't this be properly fixed by
```suggestion
    for _ in $(seq "$seconds"); do
```

2022-08-18 10:51 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +        server=$($KUBECTL run --rm -it alpine --quiet --image=alpine --restart=Never -- sh -c "echo $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" | tr -d '\r')
I think this is wrong. We need to interpolation within the pod, not outside?

2022-08-26 08:06 UTC, kovayur commented on scripts/fmcurl
> +curl -LH "Authorization: Bearer ${OCM_TOKEN}" http://localhost:8000/api/"${resource}" "$@" | jq .
```suggestion
curl -LH "Authorization: Bearer ${OCM_TOKEN}" "http://localhost:8000/api/${resource}" "$@" | jq .
```

2022-09-13 15:44 UTC, mtesseract commented
@dhaus67 Shall we try to get this merged?

2022-09-14 13:27 UTC, dhaus67 commented on .githooks/pre-commit
> +    # shellcheck disable=SC3024
No reason I'd be aware of - moved to bash.

2022-09-14 13:27 UTC, dhaus67 commented
@mtesseract Yeah, sorry. Lost track on this PR after PTO

2022-09-20 11:35 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +        server=$($KUBECTL run --rm -it alpine --quiet --image=alpine --restart=Never -- sh -c "echo $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" | tr -d '\r')
I believe the current state of the code is wrong:
```
server=$($KUBECTL run --rm -it alpine --quiet --image=alpine --restart=Never -- sh -c echo $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT | tr -d '\r')
 ```
 
 We need the single quotes to prevent early interpolation.

2022-09-20 11:36 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +        server=$($KUBECTL run --rm -it alpine --quiet --image=alpine --restart=Never -- sh -c "echo $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" | tr -d '\r')
I mean, as it was before?

2022-09-21 22:17 UTC, dhaus67 commented on dev/env/scripts/lib.sh
> +        server=$($KUBECTL run --rm -it alpine --quiet --image=alpine --restart=Never -- sh -c "echo $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" | tr -d '\r')
this is awkward. now it should be the correct command again (as in before).

2022-09-22 12:51 UTC, mtesseract approved these changes

2022-09-23 01:21 UTC, merged

2022-09-26 07:25 UTC, mtesseract commented
🎉