WIP: disable admin password after sso.redhat.com auth provider is ini…
stackrox/acs-fleet-manager pull request #265
Opened 2022-08-04 12:03 UTC by ivan-degtiarenko

…tialised

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-08 21:17 UTC, dhaus67 reviewed
I assume the issue discussed in the slack thread w.r.t. the update has been resolved, right?

2022-08-08 21:17 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if !changed && r.authInitStatus == AuthInitCompleted && remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String() {
Should we factor those out into separate helper functions instead of big if's? We do something similar in the image enricher with enrichtment context, I think it might be worthwhile here to make the intent clear (also, if there's anything else we may add in the future which makes this more complex).

2022-08-08 21:17 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/init_auth_status.go
> +type AuthInitStatus int
nit: do you think its worthwhile to expose this? I don't see any other usages and not sure where it'd make sense.

2022-08-09 07:41 UTC, SimonBaeumer submitted a review, later dismissed
Can you determine the necessary logic to setup the auth provider sequentially without a state machine?
A state machine adds a lot of complexity, especially if debugging a specific execution path.

Implementing it without a state machine could look like this:

 - Check if admin password is enabled -> create auth provider
 - Auth provider exists and admin password enabled -> disable admin password
 - Admin password disabled -> nothing to do

2022-08-09 07:41 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/init_auth_status.go
> +	CreateRhSso AuthInitStatus = iota
```suggestion
	CreateRHSSOAuthStatus AuthInitStatus = iota
```

2022-08-09 07:47 UTC, misberner requested changes
I think overall, this approach is not how a reconciler is supposed to work.

A reconciler has an input spec which gives rise to a desired state. The reconciler looks at the _actual_ state and performs changes to the effect that the actual state changes into the desired state.

A key concept is that the reconciler is, by itself, mostly stateless - the desired state should simply depend on the input spec, and the actions should only depend on the actual vs desired state. If we want any kind of stateful logic, this state has to be externalized to the actual (cluster) state, it cannot be kept in the in-memory state of the reconciler (what if the reconciler crashes and comes back up?)

I think this is, in part, already an issue with the existing code. Rather than having a `createAuthProvider` boolean field which is set to `false` after creation, the adequate setting should be `wantsAuthProvider` and should trigger the creation of an auth provider _if one does not yet exist_ (and if one exists with the wrong settings, fixes those).

I have no idea what would happen in the current code if the reconciler crashes and comes back up. Would it just try to create another auth provider with the same name and then fail? Would it always be stuck in `createAuthProvider == true`? In the current code, that might mean that while we set up the auth provider initially and then disable password generation, after a crash we would enable password generation again and it would remain enabled because we can't proceed past `CreateRhSso` due to creation failures.

2022-08-09 07:47 UTC, misberner commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		(&existingCentral).Spec = *central.Spec.DeepCopy()
```suggestion
		existingCentral.Spec = *central.Spec.DeepCopy()
```

2022-08-15 05:34 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #265** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/265" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/265?utm_source=stack-comment).

2022-08-15 11:04 UTC, misberner requested changes

2022-08-15 23:05 UTC, dhaus67 commented on fleetshard/pkg/central/client/client.go
> +// GetLoginAuthProviderResponse ...
Don't see why we wouldn't do this to be honest. I've changed it to use the respective proto definitions.

2022-08-15 23:11 UTC, dhaus67 commented on fleetshard/pkg/central/client/client.go
> +			glog.Warningf("Attempt to close GetLoginAuthProviders response failed: %s", err)
Used utils.IgnoreError (seems to be in line what we typically do within this code base / stackrox).

2022-08-15 23:15 UTC, dhaus67 commented on fleetshard/pkg/central/reconciler/init_auth.go
> +		return false, fmt.Errorf("retrieving central deployment resource from Kubernetes: %w", err)
Looking at other code, I'd say we use `errors.Wrap`, refactored it to use that.

2022-08-16 03:15 UTC, misberner requested changes

2022-08-16 03:15 UTC, misberner commented on fleetshard/pkg/central/client/client.go
> +		}
```suggestion
		marshaller := jsonpb.Marshaler{}
```
we're talking to a machine, no need for redundant information and pretty formatting

2022-08-16 03:15 UTC, misberner commented on fleetshard/pkg/central/client/client.go
> +		body = strings.NewReader(jsonString)
```suggestion
		jsonBytes, err := marshaller.Marshal(requestMessage)
		if err != nil {
			return nil, errors.Wrap(err, "marshalling new request to central")
		}
		body = bytes.NewReader(jsonBytes)
```
no need for string here

2022-08-16 03:15 UTC, misberner commented on fleetshard/pkg/central/client/client.go
> +	authProvider := &storage.AuthProvider{}
Please factor this out by:
1. rename `SendRequestToCentral` to `SendRequestToCentralRaw` (it might be useful eventually)
2. (re-)introduce `SendRequestToCentral` with an additional `responseOut proto.Message` parameter and returning a single `error` only. This method will call `SendRequestToCentralRaw`, and perform everything that this method does, only that it will not allocate a message in the highlighted line, but just use `responseOut`. If `responseOut` is `nil`, no unmarshaling should be performed (see below).

`SendAuthProviderRequest` then becomes:
```
func (c *Client) SendAuthProviderRequest(ctx context.Context, authProviderRequest *storage.AuthProvider) (*storage.AuthProvider, error) {
	var authProviderResponse storage.AuthProvider
	err := c.SendRequestToCentral(ctx, authProviderRequest, http.MethodPost, "/v1/authProviders", &authProviderResponse)
	if err != nil {
		return nil, err
	}
	return &authProviderResponse, nil
}
```

Gracefully handling `nil` `responseOut` arguments frees you from having to deal with closing response bodies for cases where you are not interested in them. For example:

```
func (c *Client) SendGroupRequest(ctx context.Context, groupRequest *storage.Group) error {
	resp, err := c.SendRequestToCentral(ctx, groupRequest, http.MethodPost, "/v1/groups", nil)
	if err != nil {
		return errors.Wrapf(err, "failed to create group for central %s/%s",
			c.central.Metadata.Namespace, c.central.Metadata.Name)
	}

	return nil
}
```

2022-08-18 10:25 UTC, misberner approved these changes
Please fix the response body leak before merging

2022-08-18 10:25 UTC, misberner commented on fleetshard/pkg/central/client/client.go
> +	if responseMessage != nil && resp.Body != nil {
I have no idea why my pending comment doesn't show up in review, but just in case it doesn't show up after submitting, please see my other comment regarding response body. This must always be closed.

2022-08-18 10:26 UTC, misberner commented on fleetshard/pkg/central/client/client.go
> +	if responseMessage != nil && resp.Body != nil {
OK GItHub just dropped the pending comment altogether -.- response bodies must always be closed because otherwise we leak resources. And they are always non-`nil` if `err == nil`

2022-08-18 14:23 UTC, dhaus67 commented on fleetshard/pkg/central/client/client.go
> +	if responseMessage != nil && resp.Body != nil {
Resolving in favor of the above comment.

2022-08-18 14:24 UTC, dhaus67 commented on fleetshard/pkg/central/client/client.go
> +	// Only required to close the response body if we plan on unmarshalling it. If no response message is set, we won't
Fixed this.

2022-08-18 21:11 UTC, misberner approved these changes

2022-08-19 14:39 UTC, dhaus67 commented
/retest

2022-08-19 16:10 UTC, merged