ROX-12072: Route update optimizations
stackrox/acs-fleet-manager pull request #267
Opened 2022-08-04 15:31 UTC by kovayur

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-04 15:31 UTC, kovayur commented
Current dependencies on/for this PR:
* main
  * **PR #267** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/267" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/267?utm_source=stack-comment).

2022-08-15 21:40 UTC, mtesseract commented
@kovayur , can you provide a brief description for this PR?

2022-08-17 16:40 UTC, kovayur commented
> @kovayur , can you provide a brief description for this PR?
@mtesseract thanks for pointing this out. I forgot to put a description, fixed now.

2022-08-23 07:11 UTC, kovayur commented
/retest

2022-08-23 14:58 UTC, mtesseract reviewed
Good job! just a few remarks.

2022-08-23 14:58 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if !centralReady || !centralTLSSecretFound {
Just to confirm, is it possible that `centralTLSSecretFound == false` and `centralReady == true` hold at the same time?

2022-08-23 14:58 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.useRoutes && !remoteCentralReady {
We are not able (currently) to correctly handle the case where `r.useRoutes` is modified, right?

2022-08-23 14:58 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		return nil, errors.Wrapf(err, "setting central reconcilation cache")
nit: adding the cluster ID?
```suggestion
		return nil, errors.Wrapf(err, "updating reconcilation cache for cluster %s", remoteCentral.Id)
```

2022-08-23 14:58 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> -	assert.Equal(t, "4", central.Annotations[revisionAnnotationKey])
We can keep the check for the revision being `4`, no?

2022-08-23 14:58 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> -	require.NoError(t, err)
Wondering if this could potentially lead to a flake in case the central is completely deleted unexpectedly fast?

2022-08-23 14:58 UTC, mtesseract commented on fleetshard/pkg/runtime/runtime.go
> +			glog.Errorf("Unexpected error occurred %s/%s: %s", central.Metadata.Namespace, central.Metadata.Name, err.Error())
```suggestion
			glog.Errorf("Unexpected error occurred for central %s/%s: %v", central.Metadata.Namespace, central.Metadata.Name, err.Error())
```

2022-08-24 08:10 UTC, SimonBaeumer requested changes

2022-08-24 08:10 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	remoteCentralReady := remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String()
Can you add to function to the managed central struct `IsReady`?

2022-08-24 08:10 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
>  	centralReady, err := isCentralReady(ctx, r.client, remoteCentral)
Can you rename this function to `isCentralDeploymentReady`? This function was not introduced in your pull request but could cause confiusion with the variable name `remoteCentralReady`.

2022-08-24 14:20 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	remoteCentralReady := remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String()
This is generated from OpenAPI, not sure what the best approach is here.

2022-08-24 14:25 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	remoteCentralReady := remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String()
We should look at the pre-commit configuration in that case. The working assumption there is that everything in those folders is auto-generated. Not sure if this assumption is also used in other places.

2022-08-24 15:27 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		return nil, errors.Wrapf(err, "setting central reconcilation cache")
This is already done by caller (runtime): 
```
			glog.Errorf("Unexpected error occurred for central %s/%s: %v", central.Metadata.Namespace, central.Metadata.Name, err.Error())
```

2022-08-24 15:29 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.useRoutes && !remoteCentralReady {
Not sure I understand the question. `r.useRoutes` is not expected to change at runtime.

2022-08-24 15:35 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> -	assert.Equal(t, "4", central.Annotations[revisionAnnotationKey])
You are right. Reverted.

2022-08-24 15:39 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> -	require.NoError(t, err)
Good point. I think this is currently not possible because we check the existence of the object on a next reconcile attempt.

2022-08-24 15:41 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if !centralReady || !centralTLSSecretFound {
Yes, it is possible. I'm going to rename `centralReady` => `centralDeploymentReady` to avoid confusion

2022-08-24 15:43 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.useRoutes && !remoteCentralReady {
Done

2022-08-24 15:44 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
>  	centralReady, err := isCentralReady(ctx, r.client, remoteCentral)
Yes, this makes sense. Done.

2022-08-24 15:56 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	remoteCentralReady := remoteCentral.RequestStatus == centralConstants.DinosaurRequestStatusReady.String()
Agree with @mtesseract, adding a new file to the autogenerated package may cause difficulties. For example, the package is [wiped on generation](https://github.com/stackrox/acs-fleet-manager/blob/main/Makefile#L396).
I extracted functions in the same file for now.

2022-08-24 21:22 UTC, mtesseract approved these changes

2022-08-24 21:22 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if !changed && r.wantsAuthProvider == r.hasAuthProvider && remoteCentralReady {
nit: I guess from a readability perspective it wouldn't be required to have a separate variable `remoteCentralReady`, since `isRemoteCentralReady(remoteCentral)` is easy to read as well and could be used inline.

2022-08-24 21:22 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.useRoutes && !remoteCentralReady {
Yeah, sorry, could have elaborated a little bit more. I was wondering what would happen if `useRoutes` is toggled and fleetshard-sync would be restarted. Probably not something that would occur in daily operations, but I was wondering from a data consistency perspective if in such a scenario routes (actual routes or empty routes) would need to be resent to fleet-manager.

2022-08-25 08:31 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.useRoutes && !remoteCentralReady {
I think it is part of a bigger problem I also raised before. At this moment we don't track stale resources on k8s cluster. 
I can imagine a case when fleetshard-sync was unavailable for some time and there were changes in the fleet manager, i.e. central was removed. The associated namespace with managed central will remain on the cluster even after fleetshard-sync becomes available.
I think we should track and alert such "stale" resources. Metrics may help us with that.

2022-08-25 13:40 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if !changed && r.wantsAuthProvider == r.hasAuthProvider && remoteCentralReady {
done

2022-08-25 14:28 UTC, SimonBaeumer approved these changes

2022-08-26 07:45 UTC, merged