Implement endpoint for updating central resource settings
stackrox/acs-fleet-manager pull request #291
Opened 2022-08-15 21:37 UTC by mtesseract

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-17 16:08 UTC, johannes94 requested changes
Good Job, left a few comments. One thing I encountered when executing e2e tests locally was that we need to set STATIC_TOKEN_ADMIN before running them. Would be nice if you could add it to `howto-run-e2e-tests.md`

2022-08-17 16:08 UTC, johannes94 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +			// TODO(mclasmeier): Do we need PresentDinosaurRequestAdminEndpoint?
Good question, I was about to comment something similar. I think we should have a dedicated type as input to the AdminCreate Endpoint and also probably return a dedicated response here. One reason is that the whole code base is separated into this different types for different APIs and it felt unusual that the new admin endpoints reuse types of other parts than the admin API. Second reason is that if we don't want to expose specific admin fields to the public API we would have to change it anyways. 3rd is if we change something for admin API, we also change the public API and we don't know for sure if tools or GUIs connecting to that API can handle the change without being modified.

2022-08-17 16:08 UTC, johannes94 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +	// Disabled this for now, since it is unclear as of now what our specific requirements
Nit: I like the YAGNI approach https://martinfowler.com/bliki/Yagni.html#:~:text=Yagni%20originally%20is%20an%20acronym,'t%20gonna%20need%20it%22. So I would just remove it, since we have it in the git history anyways if we really need it.

2022-08-17 16:08 UTC, johannes94 commented on internal/dinosaur/pkg/services/dinosaur.go
> +// Disabled this for now.
Same for this.

2022-08-17 21:47 UTC, mtesseract commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +			ValidateCentralSpec(ctx, &dinosaurRequest, convDinosaur),
done, thanks

2022-08-17 21:47 UTC, mtesseract commented on internal/dinosaur/pkg/services/dinosaur.go
> +// Disabled this for now.
done

2022-08-17 21:47 UTC, mtesseract commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
> +	// Disabled this for now, since it is unclear as of now what our specific requirements
removed it

2022-08-19 07:53 UTC, johannes94 approved these changes
LGTM except the comment. IMO we can merge and fix that in a follow up.

2022-08-19 07:53 UTC, johannes94 commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
>  func (h adminDinosaurHandler) Update(w http.ResponseWriter, r *http.Request) {
This endpoint return "null" as a response with a status code 200. Although the update of resources requirements works, "null" as a response indicates to me that something went wrong. Probably the reason is that the presenter used is not implemented.

2022-08-19 08:18 UTC, mtesseract commented on internal/dinosaur/pkg/handlers/admin_dinosaur.go
>  func (h adminDinosaurHandler) Update(w http.ResponseWriter, r *http.Request) {
Will do in a follow-up, thanks!

2022-08-19 08:18 UTC, merged