add fleetshard-sync metrics endpoint
stackrox/acs-fleet-manager pull request #323
Opened 2022-08-23 14:39 UTC by johannes94

## Description
This PR adds a metrics endpoint to the fleetshard-sync component. The endpoint serves default metrics for Go applications, as-well as custom defined metrics required to monitor our SLI/SLOs. By default the server listen to the address `:8081` and can be configured with env variable "FLEETSHARD_METRICS_ADDRESS"

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-30 10:09 UTC, stehessel commented on fleetshard/config/config.go
> +	MetricsAddress       string        `env:"METRICS_ADDRESS" envDefault:":8080"`
Why `8080`? Isn't 9090 the default Prometheus port?

2022-08-30 10:11 UTC, SimonBaeumer requested changes
Good job on the implementation!

I think collecting k8s error count does not give us much insights, instead collecting reconcile errors is a better indicator because k8s errors are often expected to inspect the cluster state (i.e. a resource was not found).

2022-08-30 10:11 UTC, SimonBaeumer commented on fleetshard/pkg/fleetshardmetrics/metrics_test.go
> +			resetMetrics()
Should this not be cleaned up after a test run instead of being required before?

```suggestion
			defer resetMetrics()
```

2022-08-30 10:11 UTC, SimonBaeumer commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +func registerCustomMetrics(r prometheus.Registerer) {
Why not introducing a singleton struct with receiver methods for this instead?
Accessibility is nearly the same but can offer cleaner interfaces for reconstructing/resetting metrics.

2022-08-30 10:11 UTC, SimonBaeumer commented on fleetshard/pkg/fleetshardmetrics/server.go
> +	server := &http.Server{Addr: address, Handler: mux}
```suggestion
	return &http.Server{Addr: address, Handler: mux}
```

2022-08-30 10:11 UTC, SimonBaeumer commented on fleetshard/pkg/fleetshardmetrics/metrics_test.go
> +func resetMetrics() {
This duplicates the initialization logic from `metrics.go`. Working with a singleton here is more clean (and still allows easy access) and gives a better interface to initialize.

2022-08-30 10:11 UTC, SimonBaeumer commented on fleetshard/pkg/fleetshardmetrics/server.go
> +	registry := prometheus.NewRegistry()
For my understanding: Is a prometheus registry a set of collector which represent a specific metric, i.e. the fleet-manager requests which can be incremented independently?

2022-08-30 10:32 UTC, stehessel commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +func registerCustomMetrics(r prometheus.Registerer) {
What do you think about prefixing the metrics? For example I think Central uses a `rox_central_*` prefix for most of its metrics.

2022-08-30 10:35 UTC, stehessel commented on fleetshard/config/config.go
> +	MetricsAddress       string        `env:"METRICS_ADDRESS" envDefault:":8080"`
Why did you go for `MetricsAddress` instead of `MetricsPort`?

2022-08-30 10:36 UTC, stehessel approved these changes
LGTM, just some minor comments 🚀

2022-08-31 12:32 UTC, johannes94 commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +func registerCustomMetrics(r prometheus.Registerer) {
Can we discuss this in more detail, so that I know i'm understanding correctly?

2022-08-31 12:32 UTC, johannes94 commented on fleetshard/pkg/fleetshardmetrics/metrics_test.go
> +func resetMetrics() {
I refactored the metrics initialization to drop the duplication here.

2022-08-31 12:32 UTC, johannes94 commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +func registerCustomMetrics(r prometheus.Registerer) {
added the prefix `acs_fleetshard_*`

2022-08-31 15:08 UTC, SimonBaeumer requested changes

2022-08-31 15:08 UTC, SimonBaeumer commented on fleetshard/pkg/fleetshardmetrics/metrics.go
> +func registerCustomMetrics(r prometheus.Registerer) {
I am referring to the Singleton pattern where only one instance of an object exists during the lifetime of the service.
To create a singleton the functions must be part of a struct (so having a receiver). This struct than is initialized only **once** by calling a constructor/factory function.

Example:

```
var (
  service MetricsService
  once     sync.Once
)

func initialize() {
  // init struct here
  service = &MetricsService{}
}

func Singleton() MetricsService {
  once.Do(initialize)
  return service
}
```

You can find several examples in the StackRox code base how to implement Singletons in Go.

2022-09-01 14:19 UTC, SimonBaeumer approved these changes
Good job @johannes94!

2022-09-02 09:10 UTC, johannes94 commented
/retest

2022-09-02 10:23 UTC, merged