[WIP] ROX-12155: Move RHSSO setup to a worker
stackrox/acs-fleet-manager pull request #334
Opened 2022-08-25 16:03 UTC by rukletsov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-25 20:52 UTC, misberner requested changes

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +	AuthConfig
```suggestion
	AuthConfig AuthConfig `json:"authConfig"`
```
You don't seem to want to use this as an embedded struct field anyway

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/services/dinosaur.go
> +		dinosaurConstants.DinosaurRequestStatusDeprovision.String(),
Is it intentional that `Deprovision` occurs both here and in `dinosaurDeletionStatuses`?

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/services/dinosaur.go
> +// require blocking operations (e.g., requesting a RHSSO client). Upon success,
```suggestion
// require blocking operations (as opposed to, e.g., requesting a RHSSO client). Upon success,
```

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/services/dinosaur.go
> +		// We can't provision this request, skip
So the status will never go into provisioning? What does that mean in practice?

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/services/dinosaur.go
> +		Where("idp_client_id != ''").
Shouldn't this be `==`?

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
> +	if err = k.dinosaurService.AcceptDinosaurRequest(dinosaur); err != nil {
Is it the normal procedure that workers call `AcceptDinsoaurRequest` directly? Just curious because there was no comparable call before

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +		if err := augmentWithAuthConfig(cr, k.centralConfig); err != nil {
```suggestion
		if err := k.augmentWithAuthConfig(cr); err != nil {
```
seems more fitting to turn that into a method?

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/services/dinosaur.go
> +	AcceptDinosaurRequest(dinosaurRequest *dbapi.CentralRequest) *errors.ServiceError
```suggestion
	// AcceptCentralRequest transitions CentralRequest to 'Preparing'.
	AcceptCentralRequest(centralRequest *dbapi.CentralRequest) *errors.ServiceError
```
Let's keep the dinosaur count monotonically decreasing

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/services/dinosaur.go
> +	ListDinosaursWithoutAuthConfig() ([]*dbapi.CentralRequest, *errors.ServiceError)
```suggestion
	ListCentralsWithoutAuthConfig() ([]*dbapi.CentralRequest, *errors.ServiceError)
```
same here

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +		if err := augmentWithAuthConfig(cr, k.centralConfig); err != nil {
Nvm, I see now why it isn't one.

2022-08-25 20:52 UTC, misberner commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	// TODO(alexr): Talk to RHSSO dynamic client API.
I think it would be nicer to factor out the "static config exists?" check to run outside of this function, and call the same function for static vs dynamically provisioned config

2022-08-26 09:28 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +		dinosaurConstants.DinosaurRequestStatusDeprovision.String(),
I believe so. `dinosaurManagedCRStatuses` is a collection of statuses that are used by `ListByClusterID()`, which sounds generic but apparently for some reason we're only interested in CentralRequests in some state. `ListByClusterID()` is only used to hand off work to fleetshard sync, so `DinosaurRequestStatusDeprovision` makes sense to me though I don't know how to verify which statuses are of interest to fleetshard sync.

2022-08-26 09:33 UTC, rukletsov commented on internal/dinosaur/pkg/api/dbapi/central_request_types.go
> +	AuthConfig
I'm not sure about this. Look how any non-basic type is represented as `api.JSON`, e.g., `Routes`. I definitely don't want to store `AuthConfig` as JSON here nor I fancy figuring out why we don't simply use nested structs.

So yeah, I want to embed this. Would you suggest dropping `AuthConfig` when accessing its fields?

2022-08-26 09:54 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +		// We can't provision this request, skip
My understanding of the fleet manager concept is that "workers" make updates to central requests, including status transitions. `PrepareDinosaurRequest()` is called from one of the worker that aims to transition some central requests into provisioning status. So what I think is going to happen here, every now and then `PrepareDinosaurRequest()` is called on a central request instance and is a no-op until after a different worker in `dinosaurs_auth_config.go` updates request's auth config.

2022-08-26 09:55 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +		Where("idp_client_id != ''").
🤦‍♂️

2022-08-26 09:59 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
> +	if err = k.dinosaurService.AcceptDinosaurRequest(dinosaur); err != nil {
That's what I picked up from other workers, e.g., [this](https://github.com/stackrox/acs-fleet-manager/blob/d3942c334d7b99e5b4167824d92bc538f698fa04/internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go#L107) and [this](https://github.com/stackrox/acs-fleet-manager/blob/d3942c334d7b99e5b4167824d92bc538f698fa04/internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go#L75).

However, I agree that state transitioning logic is hard to comprehend.

2022-08-26 10:02 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +	AcceptDinosaurRequest(dinosaurRequest *dbapi.CentralRequest) *errors.ServiceError
Hehe :). Yeah, I was on the fence here. I didn't spawn any dinosaurs in the newly created file, but here I'm not sure which strategy makes most sense: being consistent and 🪓 all dinosaurs at once or use the methodical one-dinosaur-at-a-time approach.

2022-09-02 11:25 UTC, misberner commented
/test all

2022-09-05 16:54 UTC, ivan-degtiarenko reviewed
Great work! Left some comments.

I'm trying to understand how partially moving work from `Preparing` to `Accepted` status(state) might affect the overall flow. The important question is: is there a difference between failing while in the `Accepted` state vs in the `Preparing` state?  Unfortunately, I don't have a concrete answer for now.

2022-09-05 16:54 UTC, ivan-degtiarenko commented on docs/legacy/feature-flags.md
> +  If set, every Central will have the **same** IdP config—likely not what you want
```suggestion
  If set, every Central will have the **same** IdP config — likely not what you want
```

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +// require blocking operations (deducing namespace or instance hostname). Upon
What do you consider blocking operation? `GetClusterDNS` can potentially end up in a request to OCM service, is it non-blocking?

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +	// There is no value in augmenting auth config for central requests beyond
Good thinking! I suggest we take it one step further and verify(not necessarily in this method) that there are no central requests without auth config in status provisioning and ready.

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
> +	if err = k.dinosaurService.AcceptCentralRequest(dinosaur); err != nil {
I think the name might be confusing: every central request passed down to `reconcileAcceptedDinosaur` is already accepted. Maybe something like `PreprocessCentralRequest`? I'm not so great at naming methods

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +		var augmentWithAuthConfigF func(r *dbapi.CentralRequest, centralConfig *config.CentralConfig) error
nit: I'm not sure whether it's a more idiomatic way compared to having a function with `if-else` inside.

Considering that's the result of @misberner suggestion, let's ask him :)

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	r.AuthConfig.ClientID = centralConfig.RhSsoClientID
Where do we save these modifications to the database?

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	glog.V(7).Infoln("static config found; no dynamic client will be requested from IdP")
Why it's `glog.V(7)` here while `glog.V(5)` above?

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	glog.V(7).Infoln("")
Even though this method will be rewritten when we will integrate with RH SSO API, let's log something meaningful here for now.

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	// TODO(alexr): Ideally this belongs in a config validation routine.
What's stopping us from adding this validation here:
https://github.com/stackrox/acs-fleet-manager/blob/5a987736238906fc86aecc51aa3a70b3828cb648/internal/dinosaur/pkg/config/central.go#L65-L65?

2022-09-05 16:54 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +package dinosaurmgrs
the filename does not reflect the fact this file contains `...Manager` code

2022-09-06 09:00 UTC, rukletsov commented on docs/legacy/feature-flags.md
> +  If set, every Central will have the **same** IdP config—likely not what you want
Generally, em-dash is not surrounded by spaces in English [1, 2].

[1] https://english.stackexchange.com/questions/214585/space-before-after-emdash-or-not
[2] https://www.merriam-webster.com/words-at-play/em-dash-en-dash-how-to-use

2022-09-06 09:03 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +// require blocking operations (deducing namespace or instance hostname). Upon
Every network operation can block. If `GetClusterDNS()` can block, it should be taken out of this function and put into a separate worker.

2022-09-06 09:05 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
> +	if err = k.dinosaurService.AcceptCentralRequest(dinosaur); err != nil {
I aligned method names with status names. From what I got from the code, on request in status `StatusX`, `X()` is called. I agree this is confusing, but in Rome do as the Romans do...

2022-09-06 09:13 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	r.AuthConfig.ClientID = centralConfig.RhSsoClientID
Yeah, a call to `dinosaurService.Update()` is missing — I'd like to get the read query work first : )

2022-09-06 11:00 UTC, misberner requested changes

2022-09-06 11:00 UTC, misberner commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		var augmentWithAuthConfigF func(r *dbapi.CentralRequest, centralConfig *config.CentralConfig) error
Hmm, is this really necessary? What benefit does it provide over calling `augmentWith(Static|Dynamic)Config` inline instead of assigning to this variable? You just need to declare `var err error` before the `if` statement.

2022-09-06 20:30 UTC, ivan-degtiarenko commented on docs/legacy/feature-flags.md
> +  If set, every Central will have the **same** IdP config—likely not what you want
Sorry for wasting your time on this, folks - it's not principal at all(should've marked with `nit`). If you feel like it looks nice, let's leave it as that

2022-09-06 20:34 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	glog.V(7).Infoln("static config found; no dynamic client will be requested from IdP")
I guess my question is more general: where do these numbers come from? Did you take some other piece of code as a reference to use numbers 5 and 7, or was it just a gut feeling?

I think it would be nice at some point to come up with a system which messages go to which level if it does not exist yet. Definitely not within this PR, but probably would be good to add it to our tech debt

2022-09-06 20:46 UTC, ivan-degtiarenko reviewed
Small batch of comments

2022-09-06 20:46 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		var augmentWithAuthConfigF func(r *dbapi.CentralRequest, centralConfig *config.CentralConfig) error
+1

2022-09-06 20:46 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
> +	if err = k.dinosaurService.AcceptCentralRequest(dinosaur); err != nil {
Fair enough, let's not rework this within this PR

2022-09-06 20:46 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +// require blocking operations (deducing namespace or instance hostname). Upon
I'm not sure about the separate worker - I would argue having a worker per remote call is too granular a separation of concern. I would say it would be more simple and clear to move this call to `Prepare...` function.

2022-09-08 14:28 UTC, rukletsov commented on docs/legacy/feature-flags.md
> +  If set, every Central will have the **same** IdP config—likely not what you want
Avoided em-dash and moved this to https://github.com/stackrox/acs-fleet-manager/pull/381.

2022-09-08 16:34 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		var augmentWithAuthConfigF func(r *dbapi.CentralRequest, centralConfig *config.CentralConfig) error
¯\_(ツ)_/¯

2022-09-09 15:36 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
> +	// TODO(alexr): Ideally this belongs in a config validation routine.
I think we could. It was not clear to me that it's a good place for verification but looking at other implementations of the interface, it probably is.

2022-09-12 17:32 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/config/central.go
> +			glog.Errorf("no issuer specified for static client_id %q;"+
+1

2022-09-12 17:37 UTC, ivan-degtiarenko approved these changes
One comment was left without an answer, otherwise LGTM

2022-09-12 17:37 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +// require blocking operations (deducing namespace or instance hostname). Upon
@rukletsov WDYT?

2022-09-12 18:20 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +// require blocking operations (deducing namespace or instance hostname). Upon
I think an explicit call per status transition is good regardless. Regarding separate workers... I don't think it matters much. Goroutines are cheap, so should be the workers. Whether having one worker per logical task or one per status transition — does not matter much because the whole worker concept is a bit of a miss here.

We can refactor later.

2022-09-12 18:23 UTC, rukletsov commented on internal/dinosaur/pkg/config/central.go
> +			glog.Warningf("no client_secret specified for static client_id %q;"+
No option here says or guarantees it's a code exchange, so the fact that client_secret is required as you mention in the comment is sort of non-local knowledge. However, I'm fine logging and returning an error here.

2022-09-12 18:25 UTC, rukletsov commented on internal/dinosaur/pkg/config/central.go
> +			glog.Errorf("no issuer specified for static client_id %q;"+
🤷‍♂️ this is not really fleet manager job to verify correctness of Central's config. It shall bypass what it gets, emitting advice where it thinks it might not be OK.

However, I don't have a strong opinion and will return error.

2022-09-12 18:27 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +var _ workers.Worker = &CentralAuthConfigManager{}
Yeah, it kinds is but we don't have to follow I think. Will adjust.

2022-09-12 18:39 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		if err := k.centralService.Update(cr); err != nil {
It should be fine call `Update()` if `augmentWithXYZAuthConfig()` is not written by Machiavelli but agree let's not do it.

2022-09-12 19:46 UTC, rukletsov commented on internal/dinosaur/pkg/config/central.go
> +			glog.Errorf("no issuer specified for static client_id %q;"+
Yeah, tests fall apart now because surely we didn't follow the practise in test...

2022-09-12 22:56 UTC, misberner approved these changes

2022-09-12 23:09 UTC, dhaus67 commented
/retest

2022-09-13 06:40 UTC, rukletsov commented
/retest

2022-09-13 07:15 UTC, merged