Delete leftover namespaces in down script
stackrox/acs-fleet-manager pull request #340
Opened 2022-08-29 13:24 UTC by mtesseract

## Description

When debugging issues in the e2e test suite it happens easily that we have to cleanup leftovers. In my opinion it makes sense to integrate this into `down.sh`.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-08-29 13:48 UTC, SimonBaeumer requested changes

2022-08-29 13:48 UTC, SimonBaeumer commented on dev/env/scripts/down.sh
> +central_namespaces=$($KUBECTL get namespace -o jsonpath='{range .items[?(@.status.phase == "Active")]}{.metadata.name}{"\n"}{end}' | grep '^rhacs-.*$')
Where is `$KUBECTL` var declared?

2022-08-29 13:54 UTC, mtesseract commented on dev/env/scripts/down.sh
> +central_namespaces=$($KUBECTL get namespace -o jsonpath='{range .items[?(@.status.phase == "Active")]}{.metadata.name}{"\n"}{end}' | grep '^rhacs-.*$')
https://github.com/stackrox/acs-fleet-manager/blob/mc%2Fdebug-e2e-local/dev/env/scripts/lib.sh#L89

2022-08-29 13:55 UTC, SimonBaeumer commented on dev/env/scripts/down.sh
> +central_namespaces=$($KUBECTL get namespace -o jsonpath='{range .items[?(@.status.phase == "Active")]}{.metadata.name}{"\n"}{end}' | grep '^rhacs-.*$')
Link is broken, but I see where it is coming from.
Should the `kubectl` in line 21 then be replaced?
https://github.com/stackrox/acs-fleet-manager/pull/340/files#diff-399711d07af14f32ea9544fecfd0cd1690b9505d0c21964c883a1b5f859fa3d8R21

2022-08-29 13:56 UTC, SimonBaeumer approved these changes

2022-08-29 13:56 UTC, SimonBaeumer commented on dev/env/scripts/down.sh
> +central_namespaces=$($KUBECTL get namespace -o jsonpath='{range .items[?(@.status.phase == "Active")]}{.metadata.name}{"\n"}{end}' | grep '^rhacs-.*$')
@mtesseract that was fast. 👍 Thank you!

2022-08-29 13:59 UTC, mtesseract commented on dev/env/scripts/down.sh
> +central_namespaces=$($KUBECTL get namespace -o jsonpath='{range .items[?(@.status.phase == "Active")]}{.metadata.name}{"\n"}{end}' | grep '^rhacs-.*$')
Sorry, was on the wrong (non-pushed) branch... 🤦

2022-08-29 14:58 UTC, mtesseract commented
/retest

2022-08-30 10:00 UTC, mtesseract commented
@SimonBaeumer I managed to introduce a bug in in this tiny PR: `grep` would fail with a non-zero exit code in case no such namespaces are found and due to `set -e` being active the script would be aborted immediately. The `|| true` seems to be the common practice for enforcing a success exit code irregardless of matches being found or not.

2022-08-30 10:13 UTC, SimonBaeumer commented
> @SimonBaeumer I managed to introduce a bug in in this tiny PR: `grep` would fail with a non-zero exit code in case no such namespaces are found and due to `set -e` being active the script would be aborted immediately. The `|| true` seems to be the common practice for enforcing a success exit code irregardless of matches being found or not.

Sounds good 👍

2022-08-30 10:18 UTC, merged