ROX-11993: Add architecture document
stackrox/acs-fleet-manager pull request #346
Opened 2022-08-30 04:34 UTC by kurlov

## Description

This document contains an overview about ACS Fleet Manager component. 
For compliance reasons the details interaction is not inserted directly but rather provided a link to miro dashboard.
The following sections are necessary for the appSRE AC (Acceptance Criteria):
- Technology stack
- Metadata
- Resource Capacity and Growth
- Data Continuity and Disaster Recovery
- Data Loss Impact

## Test manual

No need

2022-08-30 10:45 UTC, vladbologa requested changes
I left some suggestions that better phrase (imo) some sentences.

Also, since this architecture document is open, I wonder if it makes sense to link to internal documents that cannot be opened by people outside of the org.

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +   - It includes building an image from source and pushing it to the quay.io under appSRE organisation.
```suggestion
   - It includes building an image from source and pushing it to quay.io under the appSRE organisation.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +ACS Fleet Manager allows [Red Hat Cloud Console](https://console.redhat.com/) users to request and manage [ACS instance](https://github.com/stackrox/stackrox).
```suggestion
ACS Fleet Manager allows [Red Hat Cloud Console](https://console.redhat.com/) users to request and manage [ACS instances](https://github.com/stackrox/stackrox).
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +2. AppSRE JenkinsCI triggers Tekton pipeline for selected target namespaces.
```suggestion
2. The AppSRE JenkinsCI triggers a Tekton pipeline for the selected target namespaces.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +    It makes sense because saas.yml do not have any impact on image so there is no need to build a new one.
```suggestion
    It makes sense because `saas.yml` does not have any impact on the image, so there is no need to build a new one.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +There are two ACS grafana dashboard hosted on appSRE grafana instance:
```suggestion
There are two ACS Grafana dashboards hosted on the appSRE Grafana instance:
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +The number of running ACS Fleet Manager replicas can be configured via `REPLICAS` environment variable on [saas.yml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/ac
```suggestion
The number of running ACS Fleet Manager replicas can be configured via the `REPLICAS` environment variable in the [saas.yml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/cicd/saas.yaml) file on app-interface.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +There are factors which affect storage/database growth:
```suggestion
Factors which affect storage/database growth:
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +There are factor which affect CPU and memory usage:
```suggestion
Factors which affect CPU and memory usage:
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +- ACS Fleet Manager retains information for each ongoing request for provisioning/deleting ACS instance.
```suggestion
- ACS Fleet Manager retains information for each ongoing request for provisioning/deleting ACS instances.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +  - The AWS RDS instances is managed AppSRE team.
```suggestion
  - The AWS RDS instances are managed by the AppSRE team.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +- Ongoing ACS instance provisioning request might be lost.
```suggestion
- Ongoing ACS instance provisioning requests might be lost.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +- Ongoing ACS instance deleting request might be lost.
```suggestion
- Ongoing ACS instance deleting requests might be lost.
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +Losing data in ACS Fleet Manager due to a disaster only noticeably affects the displayed users ACS instances on https://console.redhat.com.
```suggestion
Losing data in ACS Fleet Manager due to a disaster only noticeably affects the displayed users of ACS instances on https://console.redhat.com. 
```

2022-08-30 10:45 UTC, vladbologa commented on docs/architecture/README.md
> +In that case the only option is to manually restore it using ACS Fleet Manager logs.
```suggestion
If there is a disaster that results in the database losing data, and lost data was recorded after the last backup, then the only option is to manually restore it using the ACS Fleet Manager logs.
```

2022-08-31 14:21 UTC, SimonBaeumer reviewed
Thanks @kurlov for the PR!

2022-08-31 14:32 UTC, kurlov commented on docs/architecture/README.md
> +- New commit in the main branch in the GitHub ACS Fleet Manager repository.
staging and production later

2022-08-31 14:38 UTC, kurlov commented
I've applied all suggestions in one commit just to not triggers full CI many times

2022-08-31 14:40 UTC, kurlov commented
I've just realised that I could use `add suggestion to batch` button instead  👀

2022-08-31 15:13 UTC, SimonBaeumer approved these changes

2022-09-01 09:47 UTC, vladbologa approved these changes

2022-09-01 11:52 UTC, merged

2022-09-01 12:02 UTC, porridge commented on docs/architecture/README.md
> +The number of running ACS Fleet Manager replicas can be configured via the `REPLICAS` environment variable in the [saas.yml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/ser
Do we finally have a clear picture of how work sharding works? Is any replica able to work on any pending work item? What is the reason for the leader election in that case?
I'm a little worried that our hack for the liveness probe is [still not solved](https://github.com/stackrox/acs-fleet-manager/pull/127) and that in fact the horizontal scaling has no impact on capacity, just failover reliability, so mentioning it here might be a source of confusion...

2022-09-01 12:05 UTC, porridge commented on docs/architecture/README.md
> +  - Both ACS Fleet Manager RDS resources are defined in app-interface repository ([prod](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/terraform/resources/acs-fleet-mana
```suggestion
  - Both ACS Fleet Manager RDS instances resources are defined in app-interface repository ([prod](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/terraform/resources/acs-fleet-manager/production/rds-pg14.yml) 
```
Assuming you mean "both instances", not "both resources"?

2022-09-01 12:11 UTC, porridge commented on docs/architecture/README.md
> +Requesting a new ACS Instance after data loss should not have any issue.
What if there is a name clash?
Should we mention here how to restore a record of an existing instance?