Configurable Tenant Defaults
stackrox/acs-fleet-manager pull request #349
Opened 2022-08-30 10:37 UTC by mtesseract

## Description

Rework resource defaulting: Instead of hard-coding the resource defaults, make them overwritable using environment variables.
Use the env package for unmarshalling directly into a corresponding struct.
Change the fleet-manager deployment in the test environment so that slimmer central tenants are created by default.

+ Some pre-commit fixes.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-09-13 15:43 UTC, mtesseract commented
@SimonBaeumer Any update here?

2022-09-19 19:23 UTC, johannes94 requested changes
Looks good to me at first glance. I'll approve as soon as I tested this and my requested changes were addressed.

2022-09-19 19:23 UTC, johannes94 commented on internal/dinosaur/pkg/defaults/default_scanner_spec.go
> +func PettyPrintScannerDefaults() []string {
Did you mean PrettyPrint... instead of `Petty`?

2022-09-19 19:23 UTC, johannes94 commented on internal/dinosaur/pkg/defaults/default_scanner_spec.go
> +func PettyPrintScannerDefaults() []string {
Apart from that, you could define a more generic function that takes an empty interface and a label and prints any object in that fashion instead of defining a function for scanner and central. The implementation itself would not differ much: (not tested)
```suggestion
func PettyPrintScannerDefaults(obj interface{}, label string) []string {
	bytes, err := json.MarshalIndent(obj, "", "  ")
	if err != nil {
		return nil
	}
	
	return append([]string{fmt.Sprintf("%s:", label)}, strings.Split(string(bytes), "\n")...)
}
```

2022-09-19 19:23 UTC, johannes94 commented on internal/dinosaur/pkg/defaults/default_central_spec.go
> +func PettyPrintCentralDefaults() []string {
```suggestion
func PrettyPrintCentralDefaults() []string {
```

2022-09-20 09:34 UTC, mtesseract commented on internal/dinosaur/pkg/defaults/default_scanner_spec.go
> +func PettyPrintScannerDefaults() []string {
Thanks!

2022-09-20 10:46 UTC, johannes94 commented on pkg/environments/environment.go
> +		glog.Errorf("Failed to pretty-print Central defaults: %v", err)
Nit: The 2 error handling/logging sections, look like a lot of duplication. I think we could also do it in a function instead.

2022-09-20 11:27 UTC, johannes94 approved these changes

2022-09-20 11:29 UTC, mtesseract commented on pkg/environments/environment.go
> +		glog.Errorf("Failed to pretty-print Central defaults: %v", err)
done

2022-09-20 11:54 UTC, merged