Avoid RHSSO in Central auth config for clarity
stackrox/acs-fleet-manager pull request #381
Opened 2022-09-08 14:11 UTC by rukletsov

## Description
Fleet manager config has several knobs mentioning "sso", "client secret", or alike in their names:
* `--observability-red-hat-sso-logs-client-id-file`
* `--redhat-sso-client-secret-file`
* `--ocm-client-secret-file`
* `--rhsso-client-secret-file`

`--redhat-sso-client-secret-file` and `--rhsso-client-secret-file` look particularly confusing. To avoid that, this PR aims to rename the latter (and those from the same `--rhsso-*` family) to `--central-idp-client-secret-file` (`--central-idp-*`).

Also mount entry for `rhsso-client-secret` in "templates/service-template.yml" is also removed — this seems incorrect.

## Checklist (Definition of Done)
- [ ] ~Unit and integration tests added~
- [x] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

## Test manual

CI run.

2022-09-08 23:22 UTC, dhaus67 commented on templates/service-template.yml
> +            - --central-idp-client-secret-file=/secrets/service/central.idp-client-secret
I'm not quite sure with this change to be honest.

We have the secrets that are defined within AppSRE vault (previously rhsso-client-secret). What's the source of truth here? Is it the AppSRE secret or the one here within the template?

Additionally, if you use the path `secrets/service/..`, you would be currently using the _fake-fleet-manager_ secret:
```yaml
          - name: service
            configMap:
              name: fake-fleet-manager-secret
...
...
            - name: service
              mountPath: /secrets/service
```
Is this something we actually desire? Shouldn't we use the `fleet-manager-credentials` for this?

Maybe this is obvious, but at the very least it is not to me 🥴

2022-09-08 23:32 UTC, dhaus67 commented on templates/service-template.yml
> +      central.idp-client-secret: badger
Probably something you would like to add `# pragma: allowlist secret`.

We have a pre-commit hook that detects secrets based on keywords and other things and stores meta-information within the `.secrets-baseline` file in the root of the repo. If we add the allowlist in-line, then entry won't be added to the file and doesn't create as much as noise in reviews + potential merge conflicts.

2022-09-09 00:32 UTC, ivan-degtiarenko requested changes
The renaming makes total sense to me. See comment about changing reference to mount

2022-09-09 00:32 UTC, ivan-degtiarenko commented on templates/service-template.yml
> +            - --central-idp-client-secret-file=/secrets/service/central.idp-client-secret
As the author of the changed line, I would say that it was working properly:
1. This line references to volume mount made here https://github.com/stackrox/acs-fleet-manager/blob/0df72de1d213168eccb38fc511cc5420cd9a3b83/templates/service-template.yml#L1002-L1003
2. This volume mount refers to volume created from secret `fleet-manager-central-rhsso-client-secret` here https://github.com/stackrox/acs-fleet-manager/blob/0df72de1d213168eccb38fc511cc5420cd9a3b83/templates/service-template.yml#L909-L912
3. `fleet-manager-central-rhsso-client-secret` is created in AppSRE envs from Vault value: https://gitlab.cee.redhat.com/search?search=fleet-manager-central-rhsso-client-secret&nav_source=navbar&project_id=13582&group_id=5301&search_code=true&repository_ref=master

2022-09-09 08:08 UTC, rukletsov commented on templates/service-template.yml
> +      central.idp-client-secret: badger
🤷‍♂️ I don't see pragmas in this section

2022-09-09 08:24 UTC, rukletsov commented on templates/service-template.yml
> +            - --central-idp-client-secret-file=/secrets/service/central.idp-client-secret
I see, thanks for detailed explanations, @ivan-degtiarenko.

I'm going to change the code here *without* touching appsre and vault parts (going on PTO next week). @ivan-degtiarenko, could I ask you to follow up and do:

* for both prod and stage, in [Vault](https://vault.devshift.net/ui/vault/secrets/app-interface/show/acs-fleet-manager) move `clientSecret` key from `central-rhsso-client-secret` folder to `central.idp-client-secret` in `acs-fleet-manager/{prod|stage}/service/credentials` for consistency with the code?
* update https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/namespaces to reflect the changes above (as per your search URL above)

2022-09-09 10:08 UTC, rukletsov commented on templates/service-template.yml
> +            - --central-idp-client-secret-file=/secrets/service/central.idp-client-secret
Thinking about this more, I concur that @dhaus67's suggestion makes most sense:
> Shouldn't we use the fleet-manager-credentials for this?

I've already *copied* the secret to https://vault.devshift.net/ui/vault/secrets/app-interface/show/acs-fleet-manager/stage/service/credentials (@ivan-degtiarenko please remove `stage/service/central-rhsso-client-secret` after this lands) and am trying to figure out how I can do that for prod.

Once Vault is updated, we can remove all mentions of `fleet-manager-central-rhsso-client-secret` in AppSRE (@ivan-degtiarenko please cover me here while I'm OOO).

2022-09-09 12:24 UTC, ivan-degtiarenko approved these changes
🚀

2022-09-09 15:11 UTC, merged