Fail if CENTRAL_IDP_CLIENT_SECRET is not set
stackrox/acs-fleet-manager pull request #403
Opened 2022-09-14 13:34 UTC by dhaus67

## Description

QoL change that will ensure we error out within the `init` function that is called when running `.openshift-ci/tests/e2e-test.sh` if `CENTRAL_IDP_CLIENT_SECRET` is not set.

If the variable is not set, central will be unable to start.

2022-09-14 13:35 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #403** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/403" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/403?utm_source=stack-comment).

2022-09-14 14:20 UTC, mtesseract requested changes

2022-09-14 14:20 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    if [[ -z "${CENTRAL_IDP_CLIENT_SECRET}" ]]; then
```suggestion
    if [[ -z "${CENTRAL_IDP_CLIENT_SECRET:-}" ]]; then
```

otherwise it would abort due to accessing an uninitialized variable. See:

```
$ bash -c 'source dev/env/scripts/lib.sh; init; if [[ -z "${NONEXISTANT}" ]]; then echo "is empty"; fi'
bash: NONEXISTANT: unbound variable
```

2022-09-14 15:00 UTC, mtesseract approved these changes

2022-09-15 02:06 UTC, dhaus67 commented
/retest

2022-09-15 02:45 UTC, dhaus67 commented
/retest

2022-09-15 13:47 UTC, dhaus67 commented
/retest

2022-09-15 18:12 UTC, mtesseract requested changes

2022-09-15 20:02 UTC, dhaus67 commented on dev/env/scripts/lib.sh
> +    done
🥴

2022-09-16 08:14 UTC, mtesseract approved these changes

2022-09-16 15:31 UTC, merged