Add git commit sha and tag to fleetshard-sync deployment
stackrox/acs-fleet-manager pull request #406
Opened 2022-09-15 09:29 UTC by SimonBaeumer

## Description
This PR adds the git commit SHA to the fleetshard-sync deployment.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

 - Manual testing

2022-09-15 11:42 UTC, ebensh requested changes
Looks good, couple questions and nits

2022-09-15 11:42 UTC, ebensh commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +GIT_COMMIT_HASH=$(git rev-parse HEAD)
Nit - please be consistent with naming (HASH vs SHA)

2022-09-15 11:42 UTC, ebensh commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +    "managed-service.rhacs.redhat.com/git-commit-sha": {{ .Values.fleetshardSync.gitCommitSHA }}
Is this consistent with labels exported by other ACS binaries, e.g. the Central set up by ACS Operator? It would be nice to have a single key for this across all deployments in the fleet to make simpler prometheus/grafana visualization

Edit: I assume this is the edit in the central reconciler annotation key. Is there any reason to add the managed-service namespace prefix on this here and diverge from other ACS deployments?

2022-09-15 12:14 UTC, SimonBaeumer commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +GIT_COMMIT_HASH=$(git rev-parse HEAD)
done

2022-09-15 12:16 UTC, SimonBaeumer commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +    "managed-service.rhacs.redhat.com/git-commit-sha": {{ .Values.fleetshardSync.gitCommitSHA }}
Typically we want to distinguish between annotations on different projects. For example on StackRox `platform.stackrox.io/---` is used as a key.

2022-09-15 14:23 UTC, SimonBaeumer commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +    "managed-service.rhacs.redhat.com/git-commit-sha": {{ .Values.fleetshardSync.gitCommitSHA }}
Removed the `managed-service.` to be consistent with already existent services.

2022-09-15 14:40 UTC, ebensh approved these changes

2022-09-15 15:32 UTC, merged

2022-10-05 13:43 UTC, stehessel commented
@SimonBaeumer I stumbled upon this change when trying to update the deployed version of fleetshard-sync. Maybe I'm missing something, but I think there is a fundamental flaw here because we add side effects to a declarative configuration. This results in a mismatch between the git hash of the actual deployed image in `fleetshardSync.image` and the hash of the HEAD on which the engineers happens to execute the script - which then ends up in `fleetshardSync.gitCommitSHA`. 

Can you maybe explain the reason behind this change in the first place? As is it seems kind of broken to me.

2022-10-05 16:13 UTC, stehessel commented
I think we can keep the git hash, but we need to make sure it actually corresponds to the one in the image.