wip
stackrox/acs-fleet-manager pull request #408
Opened 2022-09-15 13:21 UTC by stehessel

## Description

https://docs.google.com/document/d/1Vk-r97VokbhsHnZKcb8nAJO0M55NO9W0xtx0AQTavhA/edit

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-19 20:54 UTC, misberner requested changes
(note: lots of comments, I would recommend to read them all first before starting to implement any changes)

This is a great start! However, especially in the `runtime` implementation, I think there is a bit of restructuring that needs to happen to make it actually concurrency-correct (more below).

First thing, though, is that I would like this PR to be split into several smaller PRs, this will make the review process as well as iterating based on review comments much more tractable. My suggestion is:
- Separate PR for stylistic/formatting changes (`terraform_types.go` and `tools.go`). For smaller PRs I find it okay to sneak it in, but for PRs of that size (where scrolling in Chrome becomes noticeably slow for me), any kind of avoidable noise should be avoided.
- One PR for the main binary + Makefile stuff + runtime logic.
- One follow-up PR for the prometheus metrics

You could split it up even further. For example, main package/cobra scaffolding + makefile targets with noop logic firsts, then the runtime logic. Or a separate PR for the metrics registration side, and then one following up on the runtime logic PR to actually populate the metrics. However, no need to go to the extreme; as long as you can get to a size of not more than 500 lines (w/o generated code) per PR, I'm content.

The runtime logic is where I mostly see the issues. The use of contexts is somewhat inconsequential, and you definitely use more goroutines than would be needed. My suggestion would be to attempt to rewrite this with _as little concurrency as possible_. Most of things should happen sequentially in the "main" goroutine (i.e., the one in which `Run()` is called), and then you'll need some mechanism to asynchronously stop the execution. I've commented with more details in the `runtime.go` file.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	centralName, err := newCentralName()
I don't have anything too concrete in mind, but I'm sure in the future someone _might_ want to run several probes in parallel, and in this case, the probes have to have some names to distinguish them (e.g., pod names). I think that rather than calling the centrals `probe-<random>`, they should be called `probe-<probe name>-<random>`.

I also think that it would make sense to generate a new name in each iteration

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +				time.Sleep(r.config.RuntimeRunWaitPeriod)
Generally speaking, avoid `time.Sleep` in production code, as it is not sensitive to context cancellations. You can use `concurrency.WaitWithTimeout(ctxTimeout, r.config.RuntimeRunWaitPeriod)`, where a `true` return value indicates that `ctxTimeout` was cancelled.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	err = r.ensureCentralState(constants.CentralRequestStatusDeprovision.String())
Should this function not wait (with a certain timeout) until the central is actually deleted?

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	if r.centralState == nil {
`r.centralState` is written to within `Run()`, yet there is no explicit synchronization here, so it's not legal to call `Stop()` while `Run()` is running - which seems to defeat its purpose. In order to stop an asynchronous goroutine, you must use channels (or a context, a `concurrency.Signal` or something like that).

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +}
Reading the callsite `defer totalDurationTimer()()` makes it hard to see what's going on, both because the name isn't very descriptive, and also because of the double function call. I would propose to change it to
```suggestion
func recordElapsedTime(start time.Time) {
	metrics.MetricsInstance().ObserveTotalDuration(time.Since(start))
}
```
an then call it via `defer recordElapsedTime(time.Now())` (note that arguments to `defer`ed functions are evaluated eagerly)

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	r.centralState = &central
I think setting a `struct` field to an intermediate state is dangerous, given the number of goroutines. I haven't gone through that exercise, but I'm pretty sure one could create a race condition from that (note that a program is only concurrency-correct if its correct even when the scheduler is arbitrarily malicious, i.e., only explicit synchronizations matter, no real-time considerations, as a scheduler could keep a goroutine paused at an arbitrary point for an arbitrary amount of time).

I think it would be better as well as feasible to just pass the central state directly to the respective methods (you do need it out-of-band to realize `Stop`, but as written above, this will need to be changed anyway to just trigger a signal/write to a channel that is then handled in the main loop, where the local `centralState` variable is available if an iteration is currently in progress).

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	go r.pollCentral(ctxTimeout, isDone, targetState)
If you rewrite `pollCentral` to be fully sensitive to context cancellations (and that is possible), you do not need to run it in a goroutine.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	ctxTimeout, cancel := context.WithTimeout(context.Background(), r.config.RuntimePollTimeout)
Why do you use `context.Background()` here, given that at most callsites, there's a non-background parent context available that should be threaded through

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) pollCentral(ctx context.Context, isDone chan bool, targetState string) error {
Just a stylistic remark that will likely be obsolete after addressing comments: when passing channels between functions, it's common to be as specific as possible about the operations that will happen on them. Since this method only writes to the channel but will never read from it, one would write this as
```suggestion
func (r *Runtime) pollCentral(ctx context.Context, isDone chan<- bool, targetState string) error {
```

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +			isDone <- true
Note that generally speaking, unguarded (without an enclosing `select` with other alternative `case`s) writes to channel are deadlock-prone and should be avoided. They are only safe in limited circumstances, mostly when using buffered channels. The channel here is buffered, but it is created as such in a different function, and this method contains no method comment indicating that the channel _must_ be buffered.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +			isDone <- true
Concretely, if the channel wasn't buffered, and you would hit the `<-ctxTimeout.Done()` case in `ensureCentralState`, this goroutine would block forever.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) Run(isErr chan bool, sigs chan os.Signal, loop bool) {
I think this method signature unnecessarily breaks multiple aspects of abstraction:
1. `isErr` only seems to be used when `loop` is `false`, so maybe the non-`loop` case should be a separate method.
2. However, I do think that the loop case should not be handled at all. This type should only offer a method for a one-shot execution. Rather than weaving loop-or-not case distinction throughout this code, the loop execution should be built _on top of_ the one-shot execution.
3. `isErr` is a boolean, but what is the concrete error? With the above suggestion, you could rewrite this as `RunSingle(...) error`.
4. It seems that `sigs chan os.Signal` is overloaded/abused. You call `signal.Notify` on it. That instructs the Go runtime to write certain signals to this channel. However, in this method, you don't care about these signals - you never read from the channel. But you _close_ it when you're done. This is not what the channel is intended for, and could also lead to crashes: writing to a closed channel causes a panic. `signal.Notify` will still do what it's supposed to do after you close the channel. If a signal is delivered just after that happens, the Go runtime will attempt to write the received signal to the closed channel, which will result in a panic.

Concrete suggestions:
- Remove the `loop bool` parameter (and rename to `RunSingle`). Looping should be the responsibility of the caller (i.e., `pkg/cmd`), or, if you think that's adequate, a separate `RunLoop` method that calls `RunSingle`.
- Change this method (`RunSingle`) to return a concrete `error`.
- Take `sigs` and any reference to `os.Signal` out of the picture. Instead, pass a `ctx context.Context` as a general purpose cancellation mechanism. The caller can then cancel the context and call if a signal is received, a timeout expires, anything.

The one thing to consider, though, is that contexts typically don't go well together with clean shutdowns. A cancelled context basically instructs the method to return ASAP. Therefore, I think that cancellation on `SIGINT` or `SIGTERM` should still invoke `Stop()` (or `GracefulStop()`) rather than just cancelling the context.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/cmd/cmd.go
> +	isErr := make(chan bool, 1)
There are several issues with the asynchronous nature of this code. Please see my comments in `runtime.go`.

2022-10-19 20:54 UTC, misberner commented on probe/pkg/cmd/cmd.go
> +func Command() *cobra.Command {
`pkg/` is typically used for shared library code. The `cmd` package does not seem to fit that bill.

Also, per the [standard Go project layout](https://github.com/golang-standards/project-layout), the name `cmd` is commonly reserved for a _sibling_ directory of `pkg` that contains one directory for each binary. I.e., if you want to have `probe/pkg`, one would typically expect the `package main` in `probe/cmd/probe`.

2022-10-19 21:02 UTC, stehessel commented on dp-terraform/add-on/rhacs-terraform/api/v1alpha1/terraform_types.go
> +	Spec              TerraformSpec   `json:"spec,omitempty"`
This is just the result of a `make code/fix`. Yeah I can separate that out and add it to the pre-commit hook and CI.

2022-10-19 21:04 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	centralName, err := newCentralName()
Another thought: somewhere around here, you mention a write-ahead log for better cleanup. To be honest, that seems an unnecessarily complex solution to me. If you make the probe name part of the central name, a probe can easily discover "stray" central instances belonging to it that should be deleted. And even if a probe was abruptly deleted and is not coming back (at least not with that name), a probe supervisor could look at the list of running probes (with their names) and delete any orphaned central instances. And if the list of running probe names cannot easily be obtained, one could even (hex-)encode a creation timestamp in the central name, and have a janitor-like job delete centrals that are more than x minutes old.

A WAL would IMHO only make sense if the probe did something with a system that was _not_ declarative in nature.

2022-10-20 11:13 UTC, stehessel commented
Thank you Malte for the extensive review. This kind of review is quite valuable to me and probably others, so great job 👍 . Let me try to follow your recommendations starting with the PR break up. I'll probably keep this one for reference and start new ones.

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/metrics/metrics.go
> +// MetricsInstance return the global Singleton instance for Metrics
```suggestion
// MetricsInstance return the global Singleton instance for Metrics.
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/metrics/server.go
> +// NewMetricsServer returns the metrics server
```suggestion
// NewMetricsServer returns the metrics server.
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Wrapf(err, "Clean up: Deletion of Central instance %s failed", r.centralState.Id)
```suggestion
		return errors.Wrapf(err, "clean up: deletion of Central instance %s failed", r.centralState.Id)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Wrap(err, "Creation of Central instance failed")
```suggestion
		return errors.Wrap(err, "creation of Central instance failed")
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Errorf("Creation request to Central instance was not accepted: %s.", response.Status)
```suggestion
		return errors.Errorf("creation request to Central instance was not accepted: %s", response.Status)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Errorf("Central has wrong instance type. Expected %s, got %s.", fleetmanager.StandardInstanceType, r.centralState.InstanceType)
```suggestion
		return errors.Errorf("central has wrong instance type. Expected %s, got %s", fleetmanager.StandardInstanceType, r.centralState.InstanceType)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Wrapf(err, "Failed to create request for Central UI %s", r.centralState.Id)
```suggestion
		return errors.Wrapf(err, "failed to create request for Central UI %s", r.centralState.Id)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Wrapf(err, "Central UI of instance %s not reachable", r.centralState.Id)
```suggestion
		return errors.Wrapf(err, "central UI of instance %s not reachable", r.centralState.Id)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Errorf("Central UI %s did not respond with status OK. Got: %s", r.centralState.Id, response.Status)
```suggestion
		return errors.Errorf("central UI %s did not respond with status OK. Got: %s", r.centralState.Id, response.Status)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Wrapf(err, "Deletion of Central instance %s failed", r.centralState.Id)
```suggestion
		return errors.Wrapf(err, "deletion of Central instance %s failed", r.centralState.Id)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Errorf("Deletion request to Central instance %s was not accepted: %s.", r.centralState.Id, response.Status)
```suggestion
		return errors.Errorf("deletion request to Central instance %s was not accepted: %s", r.centralState.Id, response.Status)
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return "", errors.Wrapf(err, "Reading random bytes for unique central name")
```suggestion
		return "", errors.Wrapf(err, "reading random bytes for unique central name")
```

2022-10-20 16:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		return errors.Wrapf(ctxTimeout.Err(), "Central instance %s did not reach %s state", r.centralState.Id, targetState)
```suggestion
		return errors.Wrapf(ctxTimeout.Err(), "central instance %s did not reach %s state", r.centralState.Id, targetState)
```

2022-11-08 01:58 UTC, closed without merging