Add method to rhsso client to get token needed for dynamic client creation
stackrox/acs-fleet-manager pull request #414
Opened 2022-09-15 23:35 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-09-16 13:42 UTC, ivan-degtiarenko commented
Current dependencies on/for this PR:
* main
  * **PR #414** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/414" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #416** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/416" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/414?utm_source=stack-comment).

2022-09-16 15:38 UTC, dhaus67 approved these changes
Minor comment w.r.t function signature, otherwise 🚢

2022-09-16 15:38 UTC, dhaus67 commented on pkg/client/redhatsso/client.go
> +func (c *rhSSOClient) getToken(additionalScopes []string) (string, error) {
Use ellipsis so we don't have to pass an empty array to the function in `GetToken()`:
```suggestion
func (c *rhSSOClient) getToken(additionalScopes ...string) (string, error) {
```

2022-09-19 02:53 UTC, dhaus67 commented on pkg/client/redhatsso/client.go
>  	cachedToken, _ := c.getCachedToken(cachedTokenKey)
Re-reading through this:
Right now, if one were to use the _same_ client struct to call service account methods and then ACS OIDC client methods, you could potentially run into the issue that the cached token returned here will not have the scopes you require (i.e. `api.iam.acs`).
I'm not sure whether this is something actually going to happen (will we always have two different clients, is it even possible to use the same service account for both the ACS API and the "other" API?).
But, its still possible currently (and could lead to some interesting debugging if it ever occurs). We could do a quick fix for this by adding the `additionalScopes` to the `cachedTokenKey`, so we can be sure it's going to be a cached token with the correct scopes.

2022-09-19 02:54 UTC, dhaus67 requested changes
See the comment.

2022-09-19 10:42 UTC, rukletsov commented on pkg/client/redhatsso/client.go
>  	cachedToken, _ := c.getCachedToken(cachedTokenKey)
I don't think we should have multiple service accounts or tokens for a fleet manager instance, see https://chat.google.com/room/AAAAnbZRzRE/XWwTguzFnh8

2022-09-20 11:29 UTC, ivan-degtiarenko commented
/retest

2022-09-20 13:29 UTC, rukletsov requested changes

2022-09-20 13:29 UTC, rukletsov commented on pkg/client/redhatsso/client.go
> +func (c *rhSSOClient) GetAcsAPIToken() (string, error) {
I don't think we should have a separate call for this but rather extend `GetToken()` with the additional scopes we need.

2022-09-20 13:29 UTC, rukletsov commented on pkg/client/redhatsso/client.go
> +	return c.getToken("api.iam.acs")
Let's add `redhat-sso-additional-scopes` config parameter. This way we not only avoid hard-coding magic values but also avoid rebuilding code one SSO config changes.

2022-09-20 13:55 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/client.go
> +	return c.getToken("api.iam.acs")
That would make it necessary to ensure this config value is set up everywhere correctly, and we already suffer from too many config values.

Do you have reasons to think we would need to change the `scope` parameter value faster than via code change(that's the only benefit I see in adding this configuration parameter)?

2022-09-20 20:50 UTC, rukletsov commented on pkg/client/redhatsso/client.go
> +func (c *rhSSOClient) GetAcsAPIToken() (string, error) {
This is why we need to extract this as a config parameter : ). Why do we need the "multi-purpose general RH SSO client" path here? We're not editing the fleet manager template.

2022-09-20 21:01 UTC, rukletsov commented on pkg/client/redhatsso/client.go
> +	return c.getToken("api.iam.acs")
We suffer from poor config management and not from having too many values. Having some params hard coded, some called out as defaults, and some exposed is a nightmare.

I think that hard coded parameters almost always strike back. It's much cleaner to have all config for a component in one single place, this way it's easier to verify what's going on and why. Also, the scope name for dynamic client api sounds very temporary to me, I _hope_ we will need to change it soon.

Moreover, what I get from [this discussion](https://chat.google.com/room/AAAAnbZRzRE/XWwTguzFnh8):
* we might need to add at least one more scope soon
* having multiple claims is reasonable
* scope name for dynamic client API might change

So what are the drawbacks of *not* exposing scopes as a parameter?

2022-09-21 19:03 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/client.go
> +	return c.getToken("api.iam.acs")
> We suffer from poor config management and not from having too many values. Having some params hard coded, some called out as defaults, and some exposed is a nightmare.
> I think that hard-coded parameters almost always strike back. It's much cleaner to have all config for a component in one single place

I agree with that sentiment. The problem(and the only drawback) is that **at the moment** there is no component config in a single place - it's quite the opposite. For each config value in `fleet-manager` we might have:
* default hard-coded value in default config(see `NewDatabaseConfig` etc)
* hard-coded value in code for different stages(`NewStageEnvLoader` etc)
* `service-template` value of env variable(see https://github.com/stackrox/acs-fleet-manager/blob/92307d9034838e15231e2f730f106333f37e702c/templates/service-template.yml#L42-L44)
*  value assigned in Makefile(see https://github.com/stackrox/acs-fleet-manager/blob/92307d9034838e15231e2f730f106333f37e702c/Makefile#L704-L704)
* value set to env variable in [app-interface](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/cicd/saas.yaml)

IMHO, none of these places works(at least right now) as `one single place`. The simplest(and at the same time the most wrong) way to add  `redhat-sso-additional-scopes` config value in a single place would be to make it the default hard-coded value in the default config.  But that defeats the purpose of the exercise in the first place. Maybe you have a good solution for this in mind so we won't have to make changes across several files and repos.

> * we might need to add at least one more scope soon
> * having multiple claims is reasonable
> * scope name for dynamic client API might change

Thank you for referencing this discussion! I see where you are coming from now.
In all aforementioned cases, I don't see the rush that would make it necessary to change scopes via config value rather than in code. 
* From the discussion you mentioned, it seems that adding new scope will come with new functionality(and whether this functionality will be placed to the same client is a question for the discussion above).
* Not sure what case you mean by `having multiple claims is reasonable`
* `scope name for dynamic client API might change` - either way if done incorrectly(`api.iam.acs` is replaced with some other scope name without a grace period) this will break prod until a new value scope name value is used. 
If done correctly, switching from old scope name to new scope name will be a change in [app-interface deployment file](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/cicd/saas.yaml), and the difference will be that one change would be a config value change, when other would be a commit value change.


**tldr**: the drawback is exactly the one that you mentioned - configuration is split between several places in code, deployment files and environment config files. At the same time, it's not clear to me how using configuration value instead of re-deploying a new version will make our lives easier in the cases you mentioned.

2022-09-21 19:25 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/client.go
> +func (c *rhSSOClient) GetAcsAPIToken() (string, error) {
> Why do we need the "multi-purpose general RH SSO client" path here? 

What I meant is RH SSO client we can use for several purposes(create SA etc.) However, from the [discussion](https://chat.google.com/room/AAAAnbZRzRE/XWwTguzFnh8) you mentioned I can see there is no need to use minimal `scope` parameter as opposed to adding all scopes needed for client to function into the token call.

Let's keep the `GetToken()` call  with additional scopes instead of `GetAcsApiToken`. @dhaus67, do you have any concerns?

2022-09-21 20:46 UTC, dhaus67 commented on pkg/client/redhatsso/client.go
> +func (c *rhSSOClient) GetAcsAPIToken() (string, error) {
>I can see there is no need to use minimal scope parameter as opposed to adding all scopes needed for client to function into the token call.

Looking at the discussion, there's this sentence: `...it would be more ideal if the FM could scope itself so it would only have these scopes when they are necessary`

I don't really get the "no multi-purpose genereal RH SSO client" argument @rukletsov. If we already foresee that it's required in _some_ future, why not already add it? It saves us time once we _have_ to do it (i.e. once we create dynamic service accounts via RH SSO, which I'm _certain_ will come up if we have more than 1 dataplane cluster, and it's something within the scope of the dataplane CD efforts lead by Draco).

To keep you unblocked, you can remove the `GetAcsApiToken` one for the time being.

2022-09-21 20:50 UTC, dhaus67 approved these changes

2022-09-22 07:39 UTC, rukletsov commented on pkg/client/redhatsso/client.go
> +	return c.getToken()
So now we don't need `api.iam.acs` any more? I see it is added in https://github.com/stackrox/acs-fleet-manager/pull/416 but then you need to update PR title and description.

2022-09-26 10:41 UTC, misberner approved these changes
Much much nicer! Comments revolve mostly around naming and some restructuring suggestions

2022-09-26 10:41 UTC, misberner commented on e2e/e2e_auth_test.go
> +		TokenURL:     "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token",
Just out of curiosity, is there a reason we're using manual OAuth2 configuration instead of OIDC discovery via https://sso.redhat.com/auth/realms/redhat-external/.well-known/openid-configuration ? Is this inherited from the template?

2022-09-26 10:41 UTC, misberner commented on e2e/e2e_auth_test.go
> +			token, getTokenErr := oauth2Cfg.TokenSource(context.Background()).Token()
I would suggest to rewrite the entire function body as
```
token, err := oauth2Cfg.TokenSource(context.Background()).Token()
if err != nil {
  return retry.MakeRetryable(err)
}
accessToken = token.AccessToken
return nil
```

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/client.go
>  type SSOClient interface {
Just this be called `ServiceAccountsClient` (used as `redhatsso.ServiceAccountsClient`)?

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/client.go
> +	GetServiceAccount(clientID string) (*serviceaccountsclient.ServiceAccountData, bool, error)
Is `clientID` the official RHSSO parlance? For me `clientID` in the context of RHSSO refers to an OAuth2 client, so would belong to the dynamic client registration API.

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/client.go
> +	RegenerateClientSecret(id string) (serviceaccountsclient.ServiceAccountData, error)
Same question as above. Is this a "client secret" in the sense of oauth2?

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/sso_auth_http_client.go
> +func NewSsoAuthHTTPClient(scopes []string, realmConfig *iam.IAMRealmConfig) *http.Client {
```suggestion
func NewSSOAuthHTTPClient(scopes []string, realmConfig *iam.IAMRealmConfig) *http.Client {
```

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/client.go
> +	httpClient := NewSsoAuthHTTPClient([]string{}, realmConfig)
Why empty scopes?

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/client.go
> +	RegenerateClientSecret(id string) (serviceaccountsclient.ServiceAccountData, error)
The API call seems to call it `ServiceAccountSecret`. That seems to be a better wording especially since `Client` is overloaded (the containing interface is called `...Client`)

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/integration/client_test.go
> +	Expect(accounts).To(HaveLen(21))
Maybe `require` that prior to the test, there is exactly one service account.

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/integration/client_test.go
> +	serviceAccount, found, err := client.GetServiceAccount(serviceAccountList[5].GetClientId())
Why does this test create 20 service accounts to test lookup of a single one? 2 (maybe 3, to ensure that the server doesn't return the first or the last unconditionally) would suffice

2022-09-26 10:41 UTC, misberner commented on pkg/client/redhatsso/integration/client_test.go
> +	serviceAccount, found, err := client.GetServiceAccount(serviceAccountList[5].GetClientId())
Single service account suffices

2022-09-26 12:46 UTC, dhaus67 commented on pkg/client/redhatsso/integration/client_test.go
> +			ClientSecret:     *serviceAccount.Secret,
nit: add the pragma `pragma: allowlist secret`

2022-09-26 12:46 UTC, dhaus67 commented on pkg/client/redhatsso/integration/client_test.go
>  	Expect(*serviceAccount.Name).To(Equal("test_1"))
nit: using either `require` for the error to not have occurred or adding `Expect(serviceAccount).ToNot(BeNil())` with `require` would be good to here. Otherwise, in case you receive an error and the `serviceAccount` is nil, you'll get a nil-pointer panic here.

2022-09-26 12:46 UTC, dhaus67 commented on pkg/client/redhatsso/sso_auth_http_client.go
> +func NewSsoAuthHTTPClient(scopes []string, realmConfig *iam.IAMRealmConfig) *http.Client {
Additionally, this would also be better from consumer POV:
```suggestion
func NewSSOAuthHTTPClient(realmConfig *iam.IAMRealmConfig, scopes ...string) *http.Client {
```

2022-09-26 12:46 UTC, dhaus67 commented on pkg/client/redhatsso/integration/client_test.go
> +	initialServiceAccount := server.GetInitialServiceAccount()
why adding this `initialServiceAccount` to the mock server instead of just setting static client ID / secret in `getClient`?

It makes it hard to understand the tests and see that we expect 21 service accounts when we created 20 without reading the specifics of the mock server.

2022-09-30 01:20 UTC, ivan-degtiarenko commented on e2e/e2e_auth_test.go
> +		TokenURL:     "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token",
Correct, we inherited manual oauth2 configuration together with everything else SSO-related

2022-09-30 02:32 UTC, dhaus67 requested changes

2022-09-30 02:32 UTC, dhaus67 commented on pkg/client/redhatsso/sso_auth_http_client.go
> +		TokenURL:     fmt.Sprintf("%s%s", realmConfig.BaseURL, realmConfig.TokenEndpointURI),
`realmConfig.TokenEndpointURI` already contains the base url, see:
```go
	c.TokenEndpointURI = baseURL + "/auth/realms/" + c.Realm + "/protocol/openid-connect/token"
```

2022-09-30 02:32 UTC, dhaus67 commented on .secrets.baseline
> +    "pkg/client/redhatsso/api/api/openapi.yaml": [
This shouldn't be there, the hook explicitly ignores it 🤔 

Can you double check?

2022-09-30 02:32 UTC, dhaus67 commented on .secrets.baseline
> +    "pkg/client/redhatsso/client_test.go": [
I'd like to see those entries go away by using the pragmas.

Rebasing + merging will be a nightmare with these, so we should keep them to a minimum.

2022-09-30 03:09 UTC, ivan-degtiarenko commented on .secrets.baseline
> +    "pkg/client/redhatsso/client_test.go": [
The approach I usually took was - rebase, accept any version and then re-run `detect` command. 
Will try to use pragmas.

2022-09-30 03:15 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/sso_auth_http_client.go
> +		TokenURL:     fmt.Sprintf("%s%s", realmConfig.BaseURL, realmConfig.TokenEndpointURI),
I see. Do you think it makes sense to initialise `APIEndpointURI` in a similar manner? Or maybe rename it to `APIEndpointPath` to make it clear from the name that it needs to be appended to the base URL?

2022-09-30 03:19 UTC, dhaus67 commented on pkg/client/redhatsso/sso_auth_http_client.go
> +		TokenURL:     fmt.Sprintf("%s%s", realmConfig.BaseURL, realmConfig.TokenEndpointURI),
For consistency it would be better to check the occurrences of `APIEndpointURI` and instantiate it in a similar manner.

2022-09-30 07:38 UTC, rukletsov commented on pkg/client/redhatsso/client.go
> +	GetServiceAccount(clientID string) (*serviceaccountsclient.ServiceAccountData, bool, error)
This sounds to me like the implementation detail. We divorced authorization server and resource server despite they are represented by a single entity in the only known use case, RHSSO.

2022-09-30 15:12 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/sso_auth_http_client.go
> +		TokenURL:     fmt.Sprintf("%s%s", realmConfig.BaseURL, realmConfig.TokenEndpointURI),
From what I see in the IAM config: https://github.com/stackrox/acs-fleet-manager/blob/b459ccdf304e86aaae15ec51c07dbf79022e4fdf/pkg/client/iam/config.go#L66-L89, `APIEndpointURI` will have different values depending on whether it's internal or external SSO, so adding constant prefix wouldn't work.

For now changed how `TokenEndpointURI` is used in `sso_auth_http_client.go`

2022-10-03 14:43 UTC, ivan-degtiarenko commented
/retest

2022-10-03 15:39 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/client.go
> +	GetServiceAccount(clientID string) (*serviceaccountsclient.ServiceAccountData, bool, error)
@misberner as per conversation with CIAM, all CRUD operations in service accounts API should use `id` and not `clientId`.  So the name should reflect that :) I applied the change in https://github.com/stackrox/acs-fleet-manager/pull/416

2022-10-03 15:42 UTC, ivan-degtiarenko commented on pkg/client/redhatsso/client.go
> +	RegenerateClientSecret(id string) (serviceaccountsclient.ServiceAccountData, error)
So what it actually is is a client secret(used for "client credentials" flow) attached to the service account. So correct name would be `RegenerateServiceAccountClientSecret` 😞

2022-10-04 10:05 UTC, ivan-degtiarenko commented on .secrets.baseline
> +    "pkg/client/redhatsso/api/api/openapi.yaml": [
I think if you run `detect-secrets` manually, this entry is added.

2022-10-04 12:42 UTC, dhaus67 approved these changes

2022-10-04 13:38 UTC, rukletsov approved these changes

2022-10-06 14:32 UTC, ivan-degtiarenko commented
/retest

2022-10-06 16:30 UTC, ivan-degtiarenko commented
/retest

2022-10-06 17:37 UTC, dhaus67 commented
/retest

2022-10-06 21:27 UTC, merged