new cluster placement strategies
stackrox/acs-fleet-manager pull request #415
Opened 2022-09-16 12:08 UTC by johannes94

## Description
Implemented 2 cluster placement strategies for central:

- DefaultClusterPlacementStrategy
  - first cluster in Ready state that has SkipScheduling set to false for central
  - is enabled by default
- TargetClusterPlacementStrategy
  - allows to specify a command line flag `-dataplane-cluster-target`, if that flag is set centrals are placed 

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-09-19 18:40 UTC, johannes94 commented
/retest

2022-09-20 11:23 UTC, mtesseract commented
do you need additional reviewers here?

2022-09-22 09:16 UTC, johannes94 commented
> 

@mtesseract Yes, probably. I added you to the list :)

2022-09-22 13:58 UTC, mtesseract requested changes

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +	for _, cluster := range clusters {
I've been wondering if it might be a good idea to implement this filter as`FindClusterCriteria`, WDYT?

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +		if cluster.Status == api.ClusterReady && !cluster.SkipScheduling {
This could be implemented by extending `FindClusterCriteria`, WDYT?

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +func findAllClusters(c ClusterService) ([]*api.Cluster, error) {
Given the way how this function is used, shouldn't it rather be `findCluster` and return `(*api.Cluster, error)`?

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/services/clusters.go
> +		Where("cluster_id in (?)", clusterIds)
Is it correct that this function returns success even if some arbitrary `clusterIds` have been provided for which not a single cluster was found? At the same time the function returns error if `clusterIds` is empty.

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +	// TODO(addon): reactivate this, if required for cluster terraforming by fleet-manager
Is deactivating this code required?

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +	glog.Infof("Set skip_scheduling to true for clusters: %v", idsOfClusterToSkipScheduling)
```suggestion
	glog.Infof("Disabled scheduling for clusters %v", idsOfClusterToSkipScheduling)
```

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +			return []error{errors.Wrapf(err, "setting skip_scheduling for clusters: %v", idsOfClusterToSkipScheduling)}
```suggestion
			return []error{errors.Wrapf(err, "disabling scheduling for clusters %v", idsOfClusterToSkipScheduling)}
```

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +	var idsOfClusterToSkipScheduling []string
Question: What happens when I remove a cluster from the configuration (which has centrals allocated to it) so that the cluster will be marked as non-schedulable and later on I would like to reenable that cluster again by re-adding it to the configuration. I don't know what we are doing in this situation exactly (soft-deletion?), but would the re-added cluster would have `skip_schedulable=false`?

2022-09-22 13:58 UTC, mtesseract commented on internal/dinosaur/pkg/migrations/20220916000000_add_skip_scheduling_to_clusters.go
> +			err := tx.Migrator().DropTable(&Cluster{})
I would have expected something like `DropColumn()` here?

2022-09-23 08:15 UTC, johannes94 commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +func findAllClusters(c ClusterService) ([]*api.Cluster, error) {
I've removed the entire function, because I'm now using FindClusterByID in the TargetClusterPlacementStrategy. My initial reasoning for this function was to remove duplicated code in both PlacementStrategy implementation. No that TargetClusterPlacementStrategy is not using FindAllClusters this is not necessary.

2022-09-23 11:15 UTC, johannes94 commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +	var idsOfClusterToSkipScheduling []string
It was not set to false, but I only had to change a single line in cluster_mgr.go to get it fixed.
The expected behaviour now is:

- If the cluster is in the config file and not in the DB the entry will be created with skip_scheduled `false`
- If the cluster is in the DB but not in the config file and it has centrals scheduled to it, it sets skip_scheduled to `true`
- If the cluster in in the DB and you add it to the config file after skip_scheduled was set to `true` it will update to `false` on fleet-manager restart

2022-09-23 12:54 UTC, mtesseract reviewed
Basically one question/concern.

2022-09-23 12:54 UTC, mtesseract commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +	if cluster != nil {
nit: I would expect a function `FindClusterByID` to return some kind of not-found error in case the cluster could not be looked up. In that case you wouldn't need the additional check for `cluster != nil` here.

2022-09-23 12:54 UTC, mtesseract commented on internal/dinosaur/pkg/services/clusters.go
> +		SkipScheduling: criteria.SkipScheduling,
I have a concern here: If I understand this code correctly, then in L291 an SQL is assembled based on `clusterDetails`. Wouldn't the addition of `SkipScheduling` change the existing behaviour of this function such that previously any `SkipScheduling` setting would have been ignored (it did not exist) and from now on `FindCluster` would only return clusters with `skip_scheduling == false` if this flag is not set in the find criteria. In other words, clusters which are not schedulable will not be returned irregardless of wether schedulability is configured in the find criteria. Is this correct? And if so, is it expected / are all callers of `FindCluster()` happy with this?

2022-09-23 13:17 UTC, johannes94 commented on internal/dinosaur/pkg/services/cluster_placement_strategy.go
> +	if cluster != nil {
The implementation of FindClusterByID was like this, I don't want to change it because it could involve changing a lot of other code parts calling this method.

2022-09-23 13:30 UTC, johannes94 commented on internal/dinosaur/pkg/services/clusters.go
> +		SkipScheduling: criteria.SkipScheduling,
Looks to me like the way gorm works a boolean value that is false would not be included in the query: https://gorm.io/docs/query.html#Struct-amp-Map-Conditions

So the filtering would be completely ignored here, I changed it back to the loop for filtering.

2022-09-26 08:22 UTC, merged