Implement augmentWithDynamicAuthConfig
stackrox/acs-fleet-manager pull request #425
Opened 2022-09-20 01:18 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-09-20 01:18 UTC, ivan-degtiarenko commented
Current dependencies on/for this PR:
* main
  * **PR #414** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/414" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #416** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/416" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #425** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/425" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/425?utm_source=stack-comment).

2022-09-20 15:19 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +	name := fmt.Sprintf("rhacs-central-idp-%s", r.Name)
```suggestion
	name := fmt.Sprintf("acsms-%s", r.Name)
```

Per [openapi spec](https://sso.dev.redhat.com/auth/realms/redhat-external/apis/openapi.yaml), name is limited to 50 chars, so let's be (1) frugal with extras and (2) truncate the name in rhsso client to avoid unnecessary `400`s.

2022-09-20 15:19 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +	r.AuthConfig.Issuer = centralConfig.CentralIDPIssuer
This is not good: there is no guarantee `CentralIDPIssuer` is set in case of dynamic config. We should be able to assemble this here or—better—get from `iam`.

2022-09-20 15:19 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		return fmt.Errorf("cannot create OIDC client when no host provided for %s/%s", r.Namespace, r.Name)
Maybe this is still WIP, but we shouldn't error out here. Instead, we should somehow express that we depend on DNS to be already set, which may be as simple as "do nothing" (you probably will need to change the signature or the flow to express this).

2022-09-21 23:59 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		return fmt.Errorf("cannot create OIDC client when no host provided for %s/%s", r.Namespace, r.Name)
Added filtration within `ListCentralsWithoutAuthConfig` method

2022-10-04 15:52 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +		Where("host != ''")
Is that a good signal that DNS has been set up? This is the instance-independent part of the URL, e.g., `acs-stage.rhcloud.com`. I see that `GetUIHost()` relies on it but could you please confirm and leave a comment specifying our _intent_ (ensure this instance already got DNS provisioned) and why it is satisfied by this check (e.g., "host is only set when blah...").

2022-10-04 15:52 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		return errors.Wrapf(err, "failed to create dynamic client for %s/%s", r.Namespace, r.Name)
```suggestion
		return errors.Wrapf(err, "failed to create RHSSO dynamic client for %s/%s", r.Namespace, r.Name)
```

2022-10-05 05:11 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/dinosaur.go
> +		Where("host != ''")
AFAIU:
1. DNS provisioning is happening **after** central becomes ready in `fleetshard-sync`
https://github.com/stackrox/acs-fleet-manager/blob/ivan%2Fuse-acs-api/internal/dinosaur/pkg/services/data_plane_dinosaur.go#L82-L82
https://github.com/stackrox/acs-fleet-manager/blob/ivan%2Fuse-acs-api/internal/dinosaur/pkg/services/dinosaur.go#L844-L851

2. That does not bother us, since we don't have a requirement for the authentication to work before DNS records are ready.  What can satisfy us is being able to get **correctly generated UI host name** aka call `GetUIHost()`

2022-10-05 18:11 UTC, dhaus67 requested changes
Since this is the "last" PR in the PRs for dynamic client registration, can we also perform a manual E2E test here that will ensure we can create a central using a dynamically created OIDC client within the auth provider configuration, and also login to that specific central?

I know we don't currently have the proper E2E tests, but it would also be worthwhile once we have change all of this to ensure our E2E tests are also _using_ the dynamic OIDC client generation. You should achieve this by simply changing [the respective templates here](https://github.com/stackrox/acs-fleet-manager/tree/main/dev/env/manifests/fleet-manager) and setting the correct values in the CI vault.

2022-10-05 18:11 UTC, dhaus67 commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +		return errors.Wrapf(err, "failed to create RHSSO dynamic client for %s/%s", r.Namespace, r.Name)
Based on the discussion [in this thread](https://github.com/stackrox/acs-fleet-manager/pull/460#discussion_r987548913), I'd favor us being consistent throughout the workers and use `r.Id`.

2022-10-05 18:11 UTC, dhaus67 commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +func NewCentralAuthConfigManager(centralService services.DinosaurService, realmConfig *iam.IAMRealmConfig, centralConfig *config.CentralConfig) *CentralAuthConfigManager {
Shouldn't we use here `iam.Config` and later use it as such:
```
dynamicClientsAPI := dynamicclients.NewDynamicClientsAPI(iamConfig.RedhatSSORealm)
```
Maybe I don't understand our dependency injection good enough, but what would actually be the `realmConfig` injected?

2022-10-05 18:46 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
>  // no auth config.
```suggestion
// no auth config. For central requests without host set, we cannot compute
// redirect_uri and hence cannot set up auth config.
```

2022-10-05 18:46 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +		// We cannot call dynamic clients API without correct UI host.
"dynamic clients API" is not a thing here; please remove in favor of the suggestion above.

2022-10-05 18:46 UTC, rukletsov commented on internal/dinosaur/pkg/services/dinosaur.go
> +		Where("host != ''")
Sounds good, thanks!

2022-10-05 18:46 UTC, rukletsov commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +func NewCentralAuthConfigManager(centralService services.DinosaurService, realmConfig *iam.IAMRealmConfig, centralConfig *config.CentralConfig) *CentralAuthConfigManager {
➕

2022-10-06 13:29 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
> +	dynamicClientData, _, err := apiClient.CreateAcsClient(context.Background(), api.AcsClientRequestData{
For me `context.Background()` is more reasonable as I don't expect workers to take context from anywhere(since they are running independently of request flow).

2022-10-06 14:31 UTC, ivan-degtiarenko commented
@dhaus67 I will do the manual test as you described.

Regarding CI: I will branch out to the experiment and see which RHSSO we use in CI and whether CI works with dynamic clients. I think it makes sense to start using dynamic clients in CI when "delete" PR is merged so as not to produce orphaned clients.

2022-10-07 00:51 UTC, ivan-degtiarenko commented
Manual test is successful ✅

2022-10-07 01:14 UTC, dhaus67 approved these changes

2022-10-07 10:13 UTC, rukletsov commented
/retest

2022-10-07 10:19 UTC, rukletsov approved these changes
🚢 it modulo CI.

2022-10-07 10:54 UTC, merged