ROX-12747: Refactor the fleet manager client
stackrox/acs-fleet-manager pull request #430
Opened 2022-09-21 20:38 UTC by dhaus67

## Description

Currently, we have a single, manually written client within `fleetshard/pkg/fleetmanager` that is used to interact with fleet manager.

Initially, it was only used within fleeshard, hence also the location. Over time, the usages have grown to include the E2E tests.

Within the context of writing the probe service, we'd like to re-use this client as well. However, the current location as well as the client per-se seem unfortunate to use off-the-shelve.

This PR aims to improve this situation by doing the following:
- Move the client and auth to a generally-purpose-fit location, specifically `pkg/client/fleetmanager`.
- Create a wrapper around the three generated OpenAPI clients for the admin, public, private API of fleet manager.
- Create a transport that injects the bearer token based on the auth type, re-use the transport in a custom HTTP client within the client wrapper / OpenAPI clients.
- Improve the configuration of the different auth types by adding an options pattern, but keeping the possibility to configure them via environment variables.

What's left and will be done within a follow-up PR:
The usage of this client in combination with the RH SSO auth type currently implies the following: the usage of the token-refresher. Originally thought of as a egress proxy for fleetshard-sync that will inject the auth information 
within requests to central, but modified to write to a file for local development. This is something completely undesired and we should change. This will be done in a follow-up, removing the need for the token-refresher and doing 
the client-credentials grant within the auth type. This way, the existing fleetshard-sync deployment will lose another dependency and component to fail (token-refresher) and all new services that may depend on this client 
(probe-service) will not suffer by having to use the token-refresher sidecar.

## Test manual

- see the e2e tests, they should be working as expected :-)

2022-09-21 20:39 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #430** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/430" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/430?utm_source=stack-comment).

2022-09-22 09:47 UTC, misberner requested changes
Thanks for making this change!

2022-09-22 09:47 UTC, misberner commented on pkg/client/fleetmanager/client.go
> +		return resp, errors.Wrap(err, "round trip error")
```suggestion
		return resp, err
```
The wrap does not provide any value whatsoever. If the linter insists on it, it needs to be suppressed at this point

2022-09-22 09:47 UTC, misberner commented on pkg/client/fleetmanager/client.go
> +		return resp, errors.Wrap(err, "round trip error")
I guess you can change the entire thing to `return c.transport.RoundTrip(req)`

2022-09-22 09:47 UTC, misberner commented on pkg/client/fleetmanager/auth.go
> +	factory, exists := authFactoryRegistry[t]
Move this line and the `exists` check to the very top of the function

2022-09-22 09:47 UTC, misberner commented on pkg/client/fleetmanager/auth.go
> +	return authTypes
```suggestion
	sort.Strings(authTypes)
	return authTypes
```
Better to have a consistent order

2022-09-22 09:47 UTC, misberner commented on pkg/client/fleetmanager/auth.go
> +// setBearer is a helper to set a bearer token as authorization header on the http.Request.
This looks out of place in this file at this point. Maybe move it to a file `auth_token_common.go`?

2022-09-22 09:47 UTC, misberner commented on fleetshard/pkg/runtime/runtime.go
> +	auth, err := fleetmanager.NewAuth(config.AuthType, fleetmanager.WithOptionFromEnv())
Why this change? You are breaking the functional property of `NewRuntime` of depending only on the input by suddenly and surprisingly taking _some_ fraction of the config options from the environment, with no way for the user to inject something here, requiring `Setenv` calls in tests where previously merely setting a struct field had sufficed. This is particularly confusing as, as far as I understand, `config.Config` is already intended to be populated from env vars.

I think it would be much nicer to allow setting this via `config.Config` fields.

2022-09-22 09:47 UTC, misberner commented on fleetshard/pkg/runtime/runtime.go
> +		clusterID:   config.ClusterID,
Why does the `Runtime` now have a single specific `clusterID`?

2022-09-22 15:32 UTC, dhaus67 commented on fleetshard/pkg/runtime/runtime.go
> +		clusterID:   config.ClusterID,
Previously, the manually written client had the `clusterID` from the `config.Config` injected as a struct member.

Now, since we use the generated one, we don't have this as a member anymore. Since the client is used throughout different places (e.g. `runtime.Start, runtime.handleReconcileResult`) I've added this as a field in the struct.

Not sure there's a better place / way to inject this, felt most natural to me.

2022-09-27 12:03 UTC, dhaus67 commented
/retest

2022-09-29 10:15 UTC, misberner requested changes

2022-09-29 10:15 UTC, misberner commented on openapi/fleet-manager-private-admin.yaml
> +  '/api/rhacs/v1/admin/centrals/db/{id}':
Again, how is backwards-compatibility ensured here?

2022-09-29 10:15 UTC, misberner commented on pkg/client/fleetmanager/auth.go
> +func NewAuth(t string, opts ...AuthOption) (Auth, error) {
I find this factory function to be a bit weird. Allowing the type `t` to be dynamic is somewhat undermined by requiring the option for the concrete provider to be spelled out at compile time. Indeed, it seems like this is only invoked with either _all_ the provider-specific `With...` options, or with `WithOptionFromEnv()`. However, even `WithOptionFromEnv` in my view conceals a little bit too much the nature of this function: the environment is required to contain _all_ the options for the various auth provider types, or at least the one the user had in mind when specifying `t` (which may or may not come from the environment).

To emphasize the fact that options and `t` are decoupled, I would propose to export the `option` struct (call it `Options`), make it the second argument (no varargs), add a function `func OptionsFromEnv() Options` or a method `func (o *Options) PopulateFromEnv()`, and get rid of the `With...` option setters.

If you think about it, the individual `With...` options are useless. Either I am specifying all of them anyway, or I am specifying a single one because I statically know `t` when calling `NewAuth`. But if I statically know, e.g., that I want to instantiate an `RHSSO` authenticator, I would better use a `NewRHSSOAuth(opts RhSsoOption) (Auth, error)`, which would be less error-prone.

2022-09-29 12:45 UTC, rukletsov commented on openapi/fleet-manager-private-admin.yaml
> +  '/api/rhacs/v1/admin/centrals/db/{id}':
I agree with the thinking in general. Here I think we can cut that corner still:
* we have exactly 0 users (so let's ship this quick 😛)
* SP does not promise API stability
* nor SP promises flawless communication between fleet manager and fleetshard sync (not to mention again there is exactly 0 requests per day)

2022-09-29 13:14 UTC, dhaus67 commented on pkg/client/fleetmanager/auth.go
> +func NewAuth(t string, opts ...AuthOption) (Auth, error) {
Yeah, I agree. I wasn't initially sure whether I wanted to keep the factory as-is or split it up to be more "static".

I've chosen now to do the following:
- Create `NewAuth` with which you can specify the type and a _single_ option as parameter.
- Create additional functions that allow to create a _specific_ auth type (e.g. `NewRHSSOAuth`), which take in the _specific_ option as parameter (e.g. `RHSSOOption`).
- Create a helper `OptionFromEnv` that will re-use env settings to populate an option struct.

2022-09-29 13:14 UTC, dhaus67 commented on openapi/fleet-manager-private-admin.yaml
> +  '/api/rhacs/v1/admin/centrals/db/{id}':
The only thing that changed here was aligning the spec to the actual implementation.

The spec specified the endpoint to be `api/rhacs/v1/admin/db/centrals/..`, but the actual implementation is `api/rhacs/v1/admin/centrals/db/..`, which was not correct and never working.

I skipped anything related to backwards compatibility due to:
- This is fixing a broken spec, wich specified a wrong endpoint.
- The admin API is not used by neither fleetshard-sync nor UI (only referenced in the runbook).

2022-09-29 13:14 UTC, dhaus67 commented on internal/dinosaur/pkg/routes/route_loader.go
> +	adminCentralsRouter := adminRouter.PathPrefix("/centrals").Subrouter()
So, admin API is not used by either UI nor fleetshard sync.

The only reference we currently have is [within this runbook](https://github.com/stackrox/acs-managed-service-runbooks#changing-resources-configuration-of-a-production-central-tenant) where I'd create a PR once this is approved and merge both simultaneously.

I can still do the exercise of creating a backwards-compatible API path, but feel like the actual value is quite small since the API is not used in any component other the runbook.

2022-09-29 14:04 UTC, misberner approved these changes

2022-09-29 14:04 UTC, misberner commented on internal/dinosaur/pkg/routes/route_loader.go
> +	adminCentralsRouter := adminRouter.PathPrefix("/centrals").Subrouter()
Sounds good, I thought that this API was in use

2022-09-29 14:04 UTC, misberner commented on openapi/fleet-manager-private-admin.yaml
> +  '/api/rhacs/v1/admin/centrals/db/{id}':
SG

2022-09-29 19:57 UTC, merged