ROX-12742: rename "dinosaur" to "central" in error messages and logs
stackrox/acs-fleet-manager pull request #436
Opened 2022-09-22 13:38 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-09-22 14:52 UTC, dhaus67 requested changes
Blocking on one comment that highlights a non-backward compatible change.

Otherwise, LGTM! I'd say we prefer to merge this PR over [pull/434](https://github.com/stackrox/acs-fleet-manager/pull/434) since the latter will probably take more review cycles and is up for additional splitting.

2022-09-22 14:52 UTC, dhaus67 commented on internal/dinosaur/pkg/services/data_plane_dinosaur.go
> +	dinosaurUpdating         string         = "CentralUpdating"
I think those will be a bit more involving for refactor.

If you look at their reference (e.g. [here](https://github.com/stackrox/acs-fleet-manager/blob/main/internal/dinosaur/pkg/services/data_plane_dinosaur.go#L158)), they are compared against the [dbapi.DataPlaneCentralStatus.Conditions[].Reason](https://github.com/stackrox/acs-fleet-manager/blob/main/internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go#L20), which as the name suggest is stored within the DB.

We have two options for this:
- Skip refactoring this value altogether and keep the original value for now (incl. a TODO marker to refactor in the future)
- Add a migration similar to [this one](https://github.com/stackrox/acs-fleet-manager/blob/main/internal/dinosaur/pkg/migrations/202209141000_add_central_auth_lease_type.go). Within the migration, we should rename all the previous values `DinosaurOperatorUpdating/DinosaurUpdating` to their new values `CentralOperatorUpdating/CentralUpdating`.

I'd prefer the migration + renaming, but it's up to you. Either way it's probably best suited to do this in a separate PR so its more explicit.

2022-09-22 16:37 UTC, vladbologa commented on internal/dinosaur/pkg/services/data_plane_dinosaur.go
> +	dinosaurUpdating         string         = "CentralUpdating"
Thanks for reviewing! I will do the migration in a separate PR, I agree that it makes more sense that way.

2022-09-23 11:31 UTC, dhaus67 approved these changes

2022-09-23 13:35 UTC, merged