Ensure log entries point to relevant code lines
stackrox/acs-fleet-manager pull request #450
Opened 2022-09-27 16:41 UTC by rukletsov

## Description
https://github.com/stackrox/acs-fleet-manager/pull/419 introduced wrappers around glog calls. This is a bit unfortunate because:
* the codebase now uses `glog.*` and `log.*` variants
* log entries created via wrappers will point wrapper code and not the actual caller, e.g.: `E0927 11:29:48.933799       1 log.go:36] Unexpected error occurred ...`, as observed in [ROX-12836](https://issues.redhat.com/browse/ROX-12836)

This PR:
* reduces the number of wrappers to support only the custom verbosity case
* skips one extra stack frame to account for the wrapper

## Checklist (Definition of Done)
- [ ] ~Unit and integration tests added~
- [ ] ~Documentation added if necessary~
- [ ] CI and all relevant tests are passing
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

## Test manual

TODO(alexr): Carry out a manual test

2022-09-27 16:50 UTC, dhaus67 reviewed
Need to run good old `go mod tidy` to add the missing go.sum entry.

2022-09-27 16:50 UTC, dhaus67 commented on fleetshard/pkg/log/log.go
> -func Info(args ...interface{}) {
Why not keep the wrapper and instead use `glog.Info/Error/WarningDepth` within the wrappers function?

Right now it feels weird to _know_ when to use what: `glog` for "normal" logging and `log` for debug logging - I'd rather have it consistent: either using `glog` all the time or the wrapper (in this case `log`).

2022-09-27 23:18 UTC, misberner requested changes

2022-09-27 23:18 UTC, misberner commented on fleetshard/pkg/log/log.go
> +	msg := fmt.Sprintf(format, args)
Careful, this passes a *single* argument of type `[]interface{}` to `Sprintf`. So `Debugf("%s %s", "foo", "bar")` will print as `"[foo bar] %!s(MISSING)"`. What you want is `args...`.

2022-09-27 23:18 UTC, misberner commented on fleetshard/pkg/log/log.go
> +	// Note that `Verbose.InfoDepth()` is unavailable in "golang/glog" at the
This hardly seems to justify the fork. What you want is
```
if glog.V(debugLogLevel) {
  msg := fmt.Sprintf(format, args)
  glog.InfoDepth(1, msg)
}
```

That's because `fmt.Sprintf` potentially has non-trivial performance implications (e.g., rendering of a larger struct).

2022-09-27 23:18 UTC, misberner commented on fleetshard/pkg/log/log.go
> -func Info(args ...interface{}) {
I agree with Daniel that it's weird to have `glog.Info..` for most stuff, and then `log.Debug` for debug levels. Is it really that much effort to write the extra `V(...)`? Is the worry a lack of consistency in verbosity levels?

2022-09-28 15:37 UTC, rukletsov commented on fleetshard/pkg/log/log.go
> +	msg := fmt.Sprintf(format, args)
This is embarrassing.

2022-09-28 15:38 UTC, rukletsov commented on fleetshard/pkg/log/log.go
> -func Info(args ...interface{}) {
I went down a bunch of rabbit holes so I actually think wrappers are not that necessary. Updated the PR.

2022-09-28 17:37 UTC, misberner approved these changes

2022-09-30 08:05 UTC, mtesseract commented
/retest

2022-10-04 09:16 UTC, SimonBaeumer commented
Thanks for fixing this @rukletsov. Did not recognized that the reported source file changed.

2022-10-04 09:17 UTC, SimonBaeumer approved these changes

2022-10-04 10:59 UTC, merged