ROX-12650: Update Helm resources in central reconciler
stackrox/acs-fleet-manager pull request #465
Opened 2022-10-04 12:27 UTC by vladbologa

## Description
Currently Helm resources are not updated in the fleetshard-sync reconciliation loop, they are only created if they don't exist.

This change would update Helm resources if a new fleetshard-sync version is deployed (the resources are currently embedded in the binary,
so they can only change with a binary update).

This PR is replacing https://github.com/stackrox/acs-fleet-manager/pull/411

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

Only did manual testing so far, because I'm not sure yet if the implemented behaviour is acceptable.

Set up a local cluster with `colima`, then:
- ran the operator outside the cluster (with `make install run` from `stackrox/operator`)
- ran the bootstrap script: `INSTALL_OPERATOR=NO INSTALL_OLM=NO ./dev/env/scripts/bootstrap.sh`
- started the services with `INSTALL_OPERATOR=NO ./dev/env/scripts/up.sh`
- make a central request to fleet-manager with `./scripts/create-central.sh`

Then to test that updating of the chart resources works:
- added annotation to `egress-proxy`
- simulated an update of `fleetshard-sync` with `kubectl -n acsms rollout restart deployment fleetshard-sync`
- checked that `egress-proxy` is updated (via logs, also checked that the annotation that I added was removed)

The current behaviour is as follows:
- chart resources are embedded in the `fleetshard-sync` binary, so they can only change when a new binary is deployed
- chart resources are installed on the first run of `Reconcile`, or, if they exist, they are updated. After the central is ready, they are no longer updated, unless the Central objects changes. 
They are also updated if `fleetshard-sync` is restarted (so in case a new version of `fleetshard-sync` is installed, the updated chart resources *will* be installed - which is what I think 
we're trying to achieve) 
- changes (manual or made by other controllers) to the chart resources will be lost if `fleetshard-sync` is updated or restarted, but also if the Central is changed (is this acceptable for 
now?)
- I think it's not likely to have hot update loops right now, because if the managed Central is ready and not changed (see line 84) the `Reconcile` function just exits

2022-10-04 12:33 UTC, vladbologa commented
/test all

2022-10-04 13:37 UTC, SimonBaeumer commented
**Testing notes:**
 - Does a second reconcile upgrade the resources? Helm should not upgrade resources which are in their final state.

**Behaviour:**
> chart resources are installed on the first run of Reconcile

This not tied to the first Reconcile run but for the chart installation. If the chart is installed it can only be upgraded or deleted.
Additionally if that reconcile run failed according to the description for installation would not happen.

> They are also updated if fleetshard-sync is restarted
why should the resources be upgraded on every fleetshard restart?

> changes (manual or made by other controllers) to the chart resources will be lost if fleetshard-sync is updated or restarted, but also if the Central is changed (is this acceptable for
now?)
Yes, the resources are managed by fleetshard. If fleetshard updates these resources changes made manually are reverted.
The same applies if a Pod or ReplicaSet is manually edited but managed by a Deployment.

> I think it's not likely to have hot update loops right now, because if the managed Central is ready and not changed (see line 84) the Reconcile function just exits
What is a "hot update loop"?

2022-10-04 13:57 UTC, SimonBaeumer requested changes
Thanks for taking on this @vladbologa.
Added some comments in the code.

2022-10-04 13:57 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		glog.Infof("Creating object %s/%s", obj.GetNamespace(), obj.GetName())
Reducing verbosity in production systems by setting `V(10)`:

```suggestion
		glog.v(10).Infof("Creating object %s/%s", obj.GetNamespace(), obj.GetName())
```

2022-10-04 13:57 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			glog.Infof("Updating object %s/%s", obj.GetNamespace(), obj.GetName())
```suggestion
			glog.V(10).Infof("Updating object %s/%s", obj.GetNamespace(), obj.GetName())
```

2022-10-04 14:40 UTC, vladbologa commented
@SimonBaeumer To make things clearer, in this current implementation I mostly made the installation / upgrading of chart resources to follow the behaviour of Central CRs. But probably also that one is not truly correct.

Let's follow the happy path for now. If you create a central, on the first run of Reconcile you get something like this:

```
I1004 14:17:55.305674       1 runtime.go:103] Received 1 centrals
I1004 14:17:55.306263       1 runtime.go:113] Start reconcile central rhacs-ccu40kof57v001t0og50/test-central-1
I1004 14:17:55.755537       1 reconciler.go:468] Creating object rhacs-ccu40kof57v001t0og50/egress-proxy-config
I1004 14:17:55.847913       1 reconciler.go:468] Creating object rhacs-ccu40kof57v001t0og50/egress-proxy
I1004 14:17:55.862879       1 reconciler.go:468] Creating object rhacs-ccu40kof57v001t0og50/egress-proxy
I1004 14:17:55.872082       1 reconciler.go:468] Creating object rhacs-ccu40kof57v001t0og50/egress-proxy
I1004 14:17:55.885786       1 reconciler.go:201] Creating central rhacs-ccu40kof57v001t0og50/test-central-1
I1004 14:17:55.898309       1 reconciler.go:205] Central rhacs-ccu40kof57v001t0og50/test-central-1 created
```

Then every 10 seconds, until the Central is ready, there's this:
```
I1004 14:18:55.455700       1 runtime.go:103] Received 1 centrals
I1004 14:18:55.455874       1 runtime.go:113] Start reconcile central rhacs-ccu40kof57v001t0og50/test-central-1
I1004 14:18:55.650730       1 reconciler.go:455] Updating object rhacs-ccu40kof57v001t0og50/egress-proxy-config
I1004 14:18:55.750160       1 reconciler.go:455] Updating object rhacs-ccu40kof57v001t0og50/egress-proxy
I1004 14:18:55.760350       1 reconciler.go:455] Updating object rhacs-ccu40kof57v001t0og50/egress-proxy
I1004 14:18:55.849530       1 reconciler.go:455] Updating object rhacs-ccu40kof57v001t0og50/egress-proxy
I1004 14:18:55.859002       1 reconciler.go:208] Update central rhacs-ccu40kof57v001t0og50/test-central-1
```

So the chart resources will be updated several times. I don't think this has side effects, because we're installing the same objects. The same happens (and happened before) to Centrals.

After the central is ready, there will be no more updates, due to this check at the beginning of `Reconcile`:
```
	if !changed && r.wantsAuthProvider == r.hasAuthProvider && isRemoteCentralReady(remoteCentral) {
		return nil, ErrCentralNotChanged
	}
```

The hash of the central object is stored in memory. Which is why if `fleetshard-sync` is restarted, `changed` will be false and it'll do another Update of both Central and the chart resources.

I could store the hashes of the rendered chart resources in memory, like we do for centrals, and then I think I could avoid doing needless updates.

2022-10-04 14:58 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			err := r.client.Update(ctx, obj)
> Can you add a protection to the update call that not every time the update is called? I.e. with a hash in an annotation like @misberner described before.

I'm considering 2 possibilities now:
1. We save the hash of the applied resources in-memory, like we do for Centrals. This will prevent manual modifications, and could cause hot update loops, and will also cause one extra update when `fleetshard-sync` is restarted.
2. If I understood correctly what @misberner was suggesting, I would apply the resource and then store the hash as an annotation. Then on reconcile, I would compare the hash of the resources that come with the `fleetshard-sync` binary and update only if they are different. This can happen IMO only when a new version of `fleetshard-sync` is deployed.

So option (1) would not allow manual or external modifications to the resources. Option (2) would allow manual or external modifications, and would not perform an upgrade unless there's a new version of the chart resources.

Does (2) sound like indeed the one we want? There could also be a variation of (2) where `fleetshard-sync` could update the resources even if the hash annotation says we shouldn't, if the object is in a failed state. I'm open to suggestions here if I'm missing something.

> Also you described in you PR description that the `egress-proxy` now has an annotation. I could not find it. Can you point me to it?

That's just a manual annotation I added during manual testing, to verify that the object was updated. (i.e. by checking that the annotation disappears)

2022-10-05 15:43 UTC, SimonBaeumer commented
> I could store the hashes of the rendered chart resources in memory, like we do for centrals, and then I think I could avoid doing needless updates.

Why in memory if we can apply on the resource instead?
The reason for the Central hash to be in memory is that we can avoid the Reconcile there, here we can skip resources on a resource level.

2022-10-07 14:47 UTC, SimonBaeumer requested changes

2022-10-07 14:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			err := r.client.Update(ctx, obj)
As discussed offline, no need to implement an update protection here. If an upgrade is necessary we will fix it.
Hot reconcile loops don't affect here as the Reconcile is triggered based on changes on the Central object received from the fleet-manager.

2022-10-07 14:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.hasChartResources {
I don't understand this here?
Also it introduces state in the reconciler which because it introduces dependencies between independent Reconcile runs.

2022-10-07 14:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	// resources are normally not updated once installed
But the resources should be updated no?
This seems like a misunderstanding between us, my understanding was that resources are always updated if a Helm update is necessary.

2022-10-07 14:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	chart, err := charts.LoadChart(testdata, "testdata/tenant-resources")
Testing looks very good, thanks for implementing it!

2022-10-07 14:57 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if r.hasChartResources {
I was trying to avoid updating the helm chart several times. But perhaps you are right and this just complicates things. I removed it.

2022-10-07 15:03 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	// resources are normally not updated once installed
I don't think they should be updated, but also nothing bad happens if they are.
The resources are installed the first time `Reconcile` is called for this Central. Then whenever `Reconcile` is called again, if the central has been changed or is not ready yet, they will be updated.

Imo they should only be updated when fleetshard-sync restarts (because it might be a newer version). So that's what I was trying to achieve here. But I removed it, if it just complicates the logic by adding state.

2022-10-13 09:14 UTC, SimonBaeumer approved these changes

2022-10-13 10:16 UTC, merged