Minor improvements to terraform script
stackrox/acs-fleet-manager pull request #468
Opened 2022-10-05 13:38 UTC by dhaus67

## Description

This PR will bring minor improvements to the terraform script:
- Skip with execution if CLUSTER_ID is empty. Previously, this was undetected and installed the chart, which lead to a CrashLoopBackOff from fleetshard-sync when an incorrect cluster name was provided (e.g. typo).
- Make sure the script is callable from a _different_ directory. Previously, it was only callable when navigating to `dp-terraform/helm`.

## Checklist (Definition of Done)

~~- [ ] Unit and integration tests added~~
~~- [ ] Documentation added if necessary~~
- [ ] CI and all relevant tests are passing
~~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~

## Test manual

```
# Temporarily add `--dry-run` to the Helm invocation.

./dp-terraform/helm/terraform_cluster.sh stage invalid-name

# Observe the error message and no Helm dry-run.

./dp-terraform/helm/terraform_cluster.sh stage acs-stage-dp-01

# Observe no error message and the helm dry-run output.

```

2022-10-05 13:39 UTC, dhaus67 commented
Current dependencies on/for this PR:
* main
  * **PR #468** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/468" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/468?utm_source=stack-comment).

2022-10-05 13:48 UTC, stehessel approved these changes

2022-10-05 14:44 UTC, dhaus67 commented
/retest

2022-10-05 15:23 UTC, dhaus67 commented
/retest

2022-10-05 15:27 UTC, dhaus67 commented
/retest

2022-10-05 15:51 UTC, dhaus67 commented
/retest-required

2022-10-05 19:12 UTC, johannes94 requested changes

2022-10-05 19:12 UTC, johannes94 commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    if [[ -z "${CLUSTER_ID}" ]]; then
I noticed that we could reduce duplication for this by getting the CLUSTER_ID and checking it above the case statement since the executed command is the same for both environments.

2022-10-06 22:27 UTC, dhaus67 commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +    if [[ -z "${CLUSTER_ID}" ]]; then
Moved both this + the check for the OCM login being correct below the select statements.

2022-10-07 07:36 UTC, johannes94 approved these changes

2022-10-08 02:58 UTC, dhaus67 commented
/retest

2022-10-08 03:07 UTC, merged