ROX-13018: Load secrets from Parameter Store on CI / Local deployment
stackrox/acs-fleet-manager pull request #477
Opened 2022-10-10 16:01 UTC by kovayur

## Description
This PR adds loading from the Parameter Store on dev / local environment.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-10 16:01 UTC, kovayur commented
Current dependencies on/for this PR:
* main
  * **PR #477** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/477" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/477?utm_source=stack-comment).

2022-10-10 16:26 UTC, kovayur commented
/test all

2022-10-13 03:38 UTC, dhaus67 approved these changes
Just as a note: the manual test step you describe in the PR currently does not apply, right? This PR doesn't have the documentation, so not really sure how the whole setup and configuration was done but I suppose we find out in the other PRs 😜

2022-10-13 03:38 UTC, dhaus67 commented on e2e/README.md
> +  RHSSO_SERVICE_ACCOUNT_CLIENT_ID=$(bw get username 028ce1a9-f751-4056-9c72-aea70052728b) RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET=$(bw get password 028ce1a9-f751-4056-9c72-aea70052728b) \
Might be worthwhile to have a link at the top of this README to `docs/development/howto-run-e2e-tests.md`, this way people know this doc exists in the first place.

2022-10-13 09:11 UTC, SimonBaeumer requested changes
Please add documentation how chamber is used here. If the code is merged would mean that an undocumented change is in main and may break development environments.

Please also document that `chamber` must be installed in the README.md getting started guide.

2022-10-13 09:11 UTC, SimonBaeumer commented on dev/env/defaults/00-defaults.env
> +export CHAMBER_DEFAULT=chamber
What does this env variable do?

2022-10-13 09:11 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +  local chamber="${CHAMBER:-$CHAMBER_DEFAULT}"
Why not expecting "chamber" in the path directly? I don't understand the env var here

2022-10-13 13:22 UTC, kovayur commented
Documentation added in #485

2022-10-13 13:27 UTC, kovayur commented on dev/env/scripts/lib.sh
> +  local chamber="${CHAMBER:-$CHAMBER_DEFAULT}"
This allows to override the executable.
Might be helpful in case when we want to override executable or add extra parameters, for example:
```
# .envrc
export CHAMBER="aws-vault exec dev -- chamber" 
```
Such style is used pretty often in our scripts, i.e. `$KUBECTL` or  `$DOCKER`.

2022-10-13 13:28 UTC, kovayur commented on dev/env/defaults/00-defaults.env
> +export CHAMBER_DEFAULT=chamber
This is the default path to an executable.

2022-10-13 15:39 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +  local chamber="${CHAMBER:-$CHAMBER_DEFAULT}"
@SimonBaeumer
This style serves two purposes:
1. As @kovayur already pointed out, the user has full control over overwriting stuff, for example `export DOCKER=$PWD/.rancher-desktop/bin/docker`.
2. On the other hand this allows for smarter defaulting logic, which is not constant, but could be influenced by the cluster type for instance. So, for example, when it is an openshift cluster, then `OPENSHIFT_MARKETPLACE_DEFAULT=true` is automatically set. For example, when the current kubernetes cluster is named "colima", then `DOCKER_DEFAULT="colima nerdctl -- -n k8s.io"`, so that using `$DOCKER ...` you can directly build images for the kubernetes cluster. This is for example picked up in the Makefile.

2022-10-13 15:40 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +  local chamber="${CHAMBER:-$CHAMBER_DEFAULT}"
You can find all sorts of cluster-specific defaulting logic in `dev/env/defaults/cluster-type-*`.

2022-10-13 15:46 UTC, mtesseract requested changes

2022-10-13 15:46 UTC, mtesseract commented on .openshift-ci/tests/e2e.sh
> +if [[ -z "$STATIC_TOKEN" ]]; then
The variable `$STATIC_TOKEN` is referenced in a manifest (`manifests/fleet-manager/01-fleet-manager-secrets.yaml`). Therefore I would suggest to move these kind of checks somewhere here https://github.com/stackrox/acs-fleet-manager/blob/main/dev/env/scripts/lib.sh#L91.

Because, it is completely supported here to, for example, use the `up.sh` or even `apply` script directly to apply something in `dev/env/manifests`. When you move the check into `lib.sh` the user using `up.sh` or `apply` would also see this error message, not only the user using `e2e.sh` (or `up.sh`).

2022-10-13 16:32 UTC, kovayur commented on .openshift-ci/tests/e2e.sh
> +if [[ -z "$STATIC_TOKEN" ]]; then
As stated in the description, `STATIC_TOKEN` now used only in e2e tests. For deployment, the RHSSO auth type is always used.

2022-10-13 16:33 UTC, kovayur commented on e2e/README.md
> +  RHSSO_SERVICE_ACCOUNT_CLIENT_ID=$(bw get username 028ce1a9-f751-4056-9c72-aea70052728b) RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET=$(bw get password 028ce1a9-f751-4056-9c72-aea70052728b) \
Thanks, done in #485

2022-10-13 16:35 UTC, kovayur commented on .openshift-ci/tests/e2e.sh
> +if [[ -z "$STATIC_TOKEN" ]]; then
With that in mind, I think it's the right place.

2022-10-14 10:09 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +  local chamber="${CHAMBER:-$CHAMBER_DEFAULT}"
Thanks for the clarification @mtesseract and @kovayur!

2022-10-14 11:24 UTC, mtesseract commented on .openshift-ci/tests/e2e.sh
> +if [[ -z "$STATIC_TOKEN" ]]; then
I see, thanks. I've still been wondering if that should be in `e2e.sh` or in the `Makefile`, in the `test/e2e` target.
I mean, would be good to also see a friendly error message about this var being undefined when using `make test/e2e` or even `ginkgo ... ./e2e/...` directly.
Related: could we define **the** supported/primary way of executing the e2e test suite (or is it just me who is unsure about this, as I see several different ways of executing it)?

2022-10-14 11:26 UTC, mtesseract approved these changes

2022-10-14 12:01 UTC, merged