ROX-13018: Automate Parameter Store toolset installation
stackrox/acs-fleet-manager pull request #492
Opened 2022-10-14 09:53 UTC by kovayur

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-14 09:53 UTC, kovayur commented
Current dependencies on/for this PR:
* main
  * **PR #477** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/477" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #485** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/485" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #492** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/492" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/492?utm_source=stack-comment).

2022-10-14 11:16 UTC, mtesseract requested changes

2022-10-14 11:16 UTC, mtesseract commented on Makefile
> +	GOBIN=${LOCAL_BIN_PATH} $(GO) install github.com/segmentio/chamber/v2@v2.10.12
If I understand this right then you are planning to make the `dev/env/scripts/*` dependant on `chamber`, is this correct? Maybe it would make sense to add this `LOCAL_BIN_PATH` to `PATH` in `dev/env/scripts/lib.sh::init` so that the scripts these tools in path automatically? (Would allow, e.g. to use these scripts directly, without make)

2022-10-14 11:16 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    if [[ ! $credentials_exist ]]; then
why not

```suggestion
    if ! aws-vault list --credentials | grep "${profile}"; then
```

2022-10-14 11:16 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    if [[ ! $credentials_exist ]]; then
In any case, I guess something like
```
grep "^${profile}$"
```

would be more reliable (depending on the precise output of the tool).

2022-10-14 11:16 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    chamber="aws-vault exec ${profile} -- chamber"
nit: I guess, if the user would accidentally store a value containing a whitespace in `AWS_VAULT_PROFILE`, then this would probably fail with some usage error.
```suggestion
    chamber="aws-vault exec '${profile}' -- chamber"
```

2022-10-17 10:12 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    chamber="aws-vault exec ${profile} -- chamber"
I've just checked, with single quotes it doesn't work, but works with a whitespace

2022-10-17 10:15 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    if [[ ! $credentials_exist ]]; then
> why not

If I inline, I should suppress the output, with variable it looks cleaner IMHO.

> In any case, I guess something like

Thanks, added

2022-10-17 10:16 UTC, kovayur commented on Makefile
> +	GOBIN=${LOCAL_BIN_PATH} $(GO) install github.com/segmentio/chamber/v2@v2.10.12
Reworked. Now the executable should always be in `PATH`. The scripts can now be used directly, without make

2022-10-17 10:16 UTC, kovayur commented on .openshift-ci/tests/e2e-test.sh
> +make prepare/dev
Reverted

2022-10-17 12:29 UTC, SimonBaeumer requested changes

2022-10-17 12:29 UTC, SimonBaeumer commented on Makefile
> +	@cd $(TOOLS_DIR) && $(GO) install github.com/segmentio/chamber/v2
Why is it necessary to change the directory before installing the tool?

From `go help install` it seems to be installed into `$GOROOT/bin`, `$GOBIN` or `$GOTOOLDIR`:

```
Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set. Executables in $GOROOT
are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.
```

2022-10-17 12:29 UTC, SimonBaeumer commented on Makefile
> +script-tools: $(CHAMBER_BIN) $(AWS_VAULT_BIN)
```suggestion
install-dev-tools: $(CHAMBER_BIN) $(AWS_VAULT_BIN)
```

2022-10-17 12:29 UTC, SimonBaeumer commented on dev/env/scripts/lib.sh
> +  if [ "$use_aws_vault" = true ]; then
nit: consistency. I prefer `[[ ]]` because it has more features for string matching.

```suggestion
  if [[ "$use_aws_vault" = true ]]; then
```

2022-10-17 12:29 UTC, SimonBaeumer commented on tools/go.mod
> +module github.com/stackrox/acs-fleet-manager/tools
Why adding a separate `go.mod` file here?

2022-10-17 12:42 UTC, mtesseract requested changes

2022-10-17 12:42 UTC, mtesseract commented on dev/env/defaults/cluster-type-colima/env
> +export ENABLE_EXTERNAL_CONFIG_DEFAULT="true"
Q: Do I understand this correctly that we want these two settings for basically all local installations but not for remote installations (infra, OpenShift CI)?

2022-10-17 12:42 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    make -s -C "$GITROOT" script-tools
nit, just a possible performance improvement:
We could check for something like:
```
if [[ ! ( -x "${GITROOT}/tools/chamber" && -x "${GITROOT}/tools/other-tool" ... ) ]]; then
   make ...
fi
```

2022-10-17 12:42 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +  local use_aws_vault="${USE_AWS_VAULT:-$USE_AWS_VAULT_DEFAULT}"
I think it would be more in line with the current structure to do
```
export USER_AWS_VAULT=${USE_AWS_VAULT:-$USE_AWS_VAULT_DFAULT}
```
in the init functions where all the other such variables are created and defaulting is applied. And then just refer to `$USE_AWS_VAULT` here instead of introducing a different indirection `$use_aws_vault` -- or am I missing something here?

2022-10-17 12:42 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    local profile="${AWS_VAULT_PROFILE:-$AWS_VAULT_PROFILE_DEFAULT}"
Same for this.

2022-10-17 12:42 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    if [[ ! $credentials_exist ]]; then
Why not something like
```suggestion
    if [[ ! aws-vault list --credentials | grep -q "^${profile}$" ]]; then
```
?
Otherwise you are kind of throwing away the exit code (`|| true`) which exactly encodes this control boolean, no?

2022-10-17 12:42 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    chamber="aws-vault exec ${profile} -- chamber"
```suggestion
    chamber="aws-vault exec '${profile}' -- chamber"
```

2022-10-17 12:42 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    chamber="chamber"
Wouldn't you need to make sure that this `tools/` directory is in `PATH` somewhere?

2022-10-17 12:42 UTC, mtesseract commented on docs/development/setup-test-environment.md
> +2. Set up a test cluster using [one of the supported](#Cluster setup) types
nit, in order to keep future PRs small(er), I usually like to use
```
1. ...
1. ...
1. ...
```
instead if enumerating by hand.

2022-10-17 12:42 UTC, mtesseract commented on tools/go.mod
> +go 1.17
Didn't we move to go 1.18?

2022-10-17 14:11 UTC, kovayur commented on Makefile
> +	@cd $(TOOLS_DIR) && $(GO) install github.com/segmentio/chamber/v2
This is for using a separate `go.mod` for tools

2022-10-17 14:15 UTC, kovayur commented on Makefile
> +script-tools: $(CHAMBER_BIN) $(AWS_VAULT_BIN)
Here I wanted to point out that this target is intended for **scripts**. I wouldn't call `chamber` as a dev tool because it should be used in all the environments in the target state.

2022-10-17 14:29 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    make -s -C "$GITROOT" script-tools
My idea was to keep the tools versions in the `tools/go.mod`. Tools themselves are installed in `$GOPATH/bin`.

`make script-tools` will install them only if:
1. They doesn't exist
2. Version update

In other cases it will skipped: `make: Nothing to be done for 'script-tools'.` (`-s` suppresses this output)
Your suggestion duplicates (1) and breaks (2).

2022-10-17 14:43 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    if [[ ! $credentials_exist ]]; then
`!` changed to `-z`. 
Here I'm checking the command output.
`|| true` is required so that no failure occurs when the pipe command (`grep`) returns a non-zero exit code.

2022-10-17 14:47 UTC, kovayur commented on tools/go.mod
> +go 1.17
Not in acs-fleet-manager yet, eager to do it :)

2022-10-17 14:48 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    local profile="${AWS_VAULT_PROFILE:-$AWS_VAULT_PROFILE_DEFAULT}"
Done.

2022-10-17 14:48 UTC, kovayur commented on dev/env/scripts/lib.sh
> +  local use_aws_vault="${USE_AWS_VAULT:-$USE_AWS_VAULT_DEFAULT}"
Done.

2022-10-17 14:48 UTC, kovayur commented on dev/env/scripts/lib.sh
> +  if [ "$use_aws_vault" = true ]; then
Fixed

2022-10-17 15:01 UTC, kovayur commented on tools/go.mod
> +module github.com/stackrox/acs-fleet-manager/tools
I think it makes sense to minimise the number of dependencies in the root go.mod file which become available from the  source code. Same approach exists in stackrox (`tools/linters/go.mod`).
Also, by separating tools, `tools/go.sum` wouldn’t be updated as frequently as root `go.sum`. It means that re-installation of tools will occur less frequently when we call tool installation targets.

2022-10-17 15:34 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +    chamber="chamber"
ah, could have seen that, thanks.

2022-10-17 15:42 UTC, kovayur commented on dev/env/scripts/lib.sh
> +    if [[ ! $credentials_exist ]]; then
You are right. Fixed. Thanks for the detailed explanation.

2022-10-17 21:11 UTC, mtesseract approved these changes

2022-10-18 12:48 UTC, SimonBaeumer approved these changes

2022-10-24 12:11 UTC, mtesseract approved these changes
lgtm.
Just have two smaller comments, feel free to discard.

2022-10-24 12:11 UTC, mtesseract commented on scripts/external_config.sh
> +        return
Not really abou this line.

Am I right in that nowhere in this file is a log emitted informing the user which chamber/aws-vault mode is being active? There are three different scenarios, as I understand it:

* external config is disabled
* external config is enabled and aws vault is enabled
* external config is enabled and aws vault is disabled

WDYT about printing this out somewhere? Could be that I just haven't found it...

2022-10-24 17:51 UTC, kovayur commented on scripts/external_config.sh
> +#!/bin/bash
Fixed

2022-10-24 17:51 UTC, kovayur commented on scripts/external_config.sh
> +        return
Added diagnostic log in the `up.sh`

2022-10-24 17:52 UTC, kovayur commented on scripts/external_config.sh
> +        echo "Error: Unable to resolve one of the following environment variables: AWS_SESSION_TOKEN, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY.
Because it does not source `lib.sh`. I've extracted `log` and `die` to the `scripts/lib/log.sh` for reusing it in `external_config` and therefore, the terraforming script

2022-10-25 08:45 UTC, mtesseract commented on dev/env/scripts/lib.sh
> -    GITROOT_DEFAULT=$(git rev-parse --show-toplevel)
Why did you remove this?
This is exported, so I don't know from the top of my head if this has unintended side-effects.

2022-10-25 09:18 UTC, mtesseract commented on dev/env/scripts/lib.sh
> +source "$GITROOT/scripts/lib/log.sh"
```suggestion
# shellcheck source=/dev/null
source "$GITROOT/scripts/lib/log.sh"
```

2022-10-25 09:18 UTC, mtesseract commented on dev/env/scripts/up.sh
> +source "${GITROOT}/scripts/lib/external_config.sh"
```suggestion
# shellcheck source=/dev/null
source "${GITROOT}/scripts/lib/external_config.sh"
```

2022-10-25 11:54 UTC, merged