ROX-12429 Support debugging deployed Fleet components via VSCode
stackrox/acs-fleet-manager pull request #507
Opened 2022-10-19 11:19 UTC by mtesseract

## Description

This PR adds functionality for debugging fleet-manager and fleetshard-sync in VSCode while they are running as deployed Pods in the Kubernetes test environment.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-21 15:20 UTC, johannes94 requested changes
LGTM after the requested changed are done

2022-10-25 09:54 UTC, mtesseract commented on .vscode/launch.json
> +        {
added

2022-10-25 09:54 UTC, mtesseract commented on Makefile
> +	DOCKER_CONFIG=${DOCKER_CONFIG} $(DOCKER) build -t $(IMAGE_REF) -f . Dockerfile.hybrid
fixed

2022-10-25 11:12 UTC, johannes94 approved these changes
LGTM

2022-10-25 20:15 UTC, merged