ROX-12076: Probe service for blackbox monitoring [1/3]
stackrox/acs-fleet-manager pull request #518
Opened 2022-10-25 04:14 UTC by stehessel

This is the first batch of changes for the probe service. It encompasses the Makefile, Dockerfile and the underlying cli and config setup.

See https://github.com/stackrox/acs-fleet-manager/pull/408 for the preceding PR. I'm planning (at least) two follow up PRs for the runtime logic and the metrics logic.

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-25 12:39 UTC, stehessel commented on probe/cmd/cmd.go
> +				time.Sleep(config.RuntimeRunWaitPeriod)
@misberner I didn't understand your point of avoiding `time.Sleep`. Can you comment if this is appropriate here? The purpose is to wait some time in between probe runs.

2022-10-25 16:28 UTC, SimonBaeumer requested changes
Added some comments, the overall approach to me looks good.

Summarized:
- Cancellation is created for each probe run, this is not necessary
- Packages need a bit restructuring
-  Replacing the loop with `concurrency.NewRetryTicker`

2022-10-25 16:28 UTC, SimonBaeumer commented on probe/config/config_test.go
> +	t.Setenv("FLEET_MANAGER_ENDPOINT", "http://127.0.0.1:8888")
Please use the envisolator to avoid side-effects in unit tests.
The acs-fleet-manager repo can import the stackrox env isolator: https://github.com/stackrox/acs-fleet-manager/blob/4ce487d2ad2ce453580d0fb6e71a743f257bec94/fleetshard/pkg/central/reconciler/proxy_test.go#L16-L16

2022-10-25 16:28 UTC, SimonBaeumer commented on probe/cmd/cmd.go
> +				time.Sleep(config.RuntimeRunWaitPeriod)
`time.Sleep` can't be cancelled because it does not return a channel which you can select on.

As the probe polls like the fleetshard-sync why not using the `concurrency.RetryTicker` which takes care of cancellation, retries etc?

2022-10-25 16:28 UTC, SimonBaeumer commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) RunSingle(ctx context.Context) error {
Imho the endless loop created should be wrapped in the runtime, the runtime calls a package to execute the probe.
The `probe` package could implement a function `Execute` which executes a single probe run. The probe does not need to know whether it is called from a user once, in a for-loop or from a REST/gRPC endpoint.

I think you implemented it nearly and only small changes necessary:

- Rename `runtime` to `probe` (or something which fits)
- Move `for {}` endless loop from `cmd/` pkg to a runtime package
- Move cancellation to composition root in cmd package (or something else which is "above" a layer above runtime)

2022-10-25 16:28 UTC, SimonBaeumer commented on probe/cmd/cmd.go
> +	}
I think this should called from outside the for loop. In this implementation every probe call setups up the listeners again which makes it inefficient.
This implementation needs refactors if multiple go routines are started and need cancellation.

2022-10-25 16:53 UTC, dhaus67 commented on probe/main.go
> +		panic(err)
We should call `glog.Fatalf` here instead of relying on panic.

2022-10-25 16:56 UTC, dhaus67 commented on probe/cmd/cmd.go
> +				time.Sleep(config.RuntimeRunWaitPeriod)
Or, if the `concurrency.RetryTicker` doesn't fit your use-case, you can simply use `time.Ticker` with the specified timeout (we have references on how to use it within the stackrox repo, e.g. [a watcher for k8s config map changes](https://github.com/stackrox/stackrox/blob/d653406651df4331a714839ec2c0a23a93425c64/pkg/k8scfgwatch/poll_watcher.go#L33-L47)).

2022-10-26 00:06 UTC, stehessel commented on probe/config/config_test.go
> +	t.Setenv("FLEET_MANAGER_ENDPOINT", "http://127.0.0.1:8888")
`t.Setenv` already restores the environment after the test, so I think this is unnecessary. Or does the env isolator have another purpose?

2022-10-26 03:10 UTC, stehessel commented on probe/cmd/cmd.go
> +				time.Sleep(config.RuntimeRunWaitPeriod)
Went with the `RetryTicker`.

2022-10-26 03:11 UTC, stehessel commented on probe/README.md
> +```
done

2022-10-26 03:12 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) RunSingle(ctx context.Context) error {
Tried to follow the suggestion. Can you take another look?

2022-10-26 03:14 UTC, stehessel commented on probe/Dockerfile
> +CMD ["/stackrox/probe", "start"]
done

2022-10-26 03:14 UTC, stehessel commented on probe/cmd/cmd.go
> +			if len(args) > 0 {
done

2022-10-26 03:14 UTC, stehessel commented on probe/main.go
> +		panic(err)
done

2022-10-26 06:01 UTC, dhaus67 requested changes

2022-10-26 06:01 UTC, dhaus67 commented on probe/internal/cli/cli.go
> +				}
This doesn't currently work with the way the function is currently implemented.

Right now, we call `runtime.Start` which in turn will start a `concurrency.RetryTicker`. We will return any error within start. Since that will not produce an error, we will never actually receive an error here.

Now, if within the retry ticker, any error occurs, the retry ticker will be stopped (which can be retrieved from running `ticker.Stopped()`.
However, this will not be propagated to this go routine, and we do not have a channel which we use to indicate any issues that _may_ have occurred during execution.

For me, the best would be the following:
- Share the code for handling context cancellation, errors, and interrupt signal from both `run` / `start`.
- Improve the existing go routine inline you created for the `run` part, specifically:
```go
go func() {
  select {
    case runResult <- runtime.RunSingle(ctxTimeout):
    case ctxTimeout.Done():
  }
}()
```
This way we ensure the go routine won't be blocking when the context timeout was hit before an error got returned from `RunSingle`.

I'm not sure whether it's required to prepare the current code to allow the execution of multiple go routines instead of the single `probe.Execute()` (e.g. splitting up the probes into multiple sub-routines?), but this is probably something we can iterate upon once we desire it.

2022-10-26 06:08 UTC, dhaus67 commented on probe/config/config_test.go
> +	t.Setenv("FLEET_MANAGER_ENDPOINT", "http://127.0.0.1:8888")
I don't think we need to re-use `envisolator` anymore. This was something we had prior go1.17 (where [t.Setenv](https://pkg.go.dev/testing#T.Setenv) only has been added) and mimics the behavior of `t.Setenv` (with the caveat that `t.Setenv` only works for non-parallel tests compared to `envisolator`).

2022-10-26 09:25 UTC, misberner commented on probe/config/config_test.go
> +	t.Setenv("FLEET_MANAGER_ENDPOINT", "http://127.0.0.1:8888")
Yeah, `envisolator` shouldn't be used any more. And `envisolator` also does not work for parallel tests, at least it doesn't do the right thing.

2022-10-26 10:53 UTC, stehessel commented on probe/cmd/probe/main.go
> +	}()
Indeed this looks a bit weird, I can remove them.

2022-10-26 10:56 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +			return 0, errors.Wrap(err, "failed to execute single probe run")
> As exit condition, the ticker currently will only exit [if the error is deemed as non-recoverable error.](https://github.com/stackrox/stackrox/blob/74c227af5798d3dbc93ec7b2cefe847fe266b855/pkg/concurrency/retry_ticker.go#L101-L104).

But isn't this exactly what we want? I.e. if the probe fails with a non-recoverable error then fail the service, otherwise just register a failed run in the metrics and continue with the next run?

2022-10-26 11:22 UTC, stehessel commented on probe/internal/cli/cli.go
> +				}
> Share the code for handling context cancellation, errors, and interrupt signal from both run / start.

Can you be more explicit? I'm not sure how to share the code because we want to do different things:
* In run we always want to fail on every error.
* In start we want to continue the loop on most errors.

2022-10-26 11:41 UTC, SimonBaeumer commented on probe/config/config_test.go
> +	t.Setenv("FLEET_MANAGER_ENDPOINT", "http://127.0.0.1:8888")
Did not know that, thanks for the input!

2022-10-26 11:55 UTC, SimonBaeumer approved these changes

2022-10-26 11:55 UTC, SimonBaeumer commented on probe/internal/cli/cli.go
> +			case err := <-runResult:
Is `err == nil` the success case in a single probe run? If yes, I think the success case is not handled here? 🤔

2022-10-26 11:55 UTC, SimonBaeumer commented on probe/pkg/runtime/runtime.go
> +			return 0, errors.Wrap(err, "failed to execute single probe run")
+1, the probe should continue running after an error in the probe occurred. 
@stehessel would a failed probe run trigger an alert (in a later implementation)?

2022-10-26 11:55 UTC, SimonBaeumer commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) RunSingle(ctx context.Context) error {
Yes, looks very good, nice!

One small nit-pick: The `RunSingle` is not necessary as it wraps only the `probe.Execute`. The `probe run` can call `probe.Execute` directly.
This way the runtime's responsibility is to guarantee the continuous execution of probe runs, the probe pkg is responsible for executing the probe.

2022-10-26 12:01 UTC, stehessel commented on probe/internal/cli/cli.go
> +			case err := <-runResult:
If `err == nil`, then `errors.Wrap(err, ...)` is also `nil`.

2022-10-26 12:05 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) RunSingle(ctx context.Context) error {
After the next step (adding the actual probe logic) it will be necessary, because `runtime` will also set up the fleet manager client etc.

2022-10-26 12:06 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +			return 0, errors.Wrap(err, "failed to execute single probe run")
Yeah you are right, I think we need an error channel for `start` as well, but it should only be filled with non recoverable errors.

2022-10-26 12:14 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) RunSingle(ctx context.Context) error {
I think there may have been some conflicting advice from both Simon and me in the respective review round, so before iterating further, it might be good to agree on an approach first. We need:
1. a way to run a single probe execution
2. a way to run probe executions in a loop
3. a way to (cleanly) terminate an ongoing (single) probe execution, e.g., for `^C` in oneshot mode
4. a way to terminate the loop execution

I think it's a no-brainer that 2 should be based upon 1. I think I initially suggested to pull 2 out of `runtime`, but if there's a separate `probe` component, I think it makes sense to have the loop be part of runtime. In general I agree with Simon that the portion in `cmd` should contain as little logic as possible.

Furthermore, I think 3 and 4 should be the same thing from a caller's perspective. When a stop is requested, the single execution can return a special kind of error, and the loop just terminates. Or, the stop facility triggers a signal/cancels a context that is both used to abort a single execution, but also checked before starting a new loop iteration.

The bottom-line is, I think that there shouldn't be a `Stop()` method that only works in conjunction with `Start()`, because the use case of stopping execution is not tied to the loop mode only. For this reason, I think that one-shot and loop execution should have a uniform signature and both be synchronous, rather than differing in whether or not they take a context and whether or not they are asynchronous.

2022-10-26 12:23 UTC, dhaus67 commented on probe/internal/cli/cli.go
> +				}
I think my main point is that I don't expect `RunSingle` or `Start` to have different function signatures.

Additionally, there are still conditions where we want to error out, e.g. as you mentioned above when the ticker could not be started.

So, for me it would be best to share this between both commands (creating the runtime, starting the routine that will _either_ do the one-shot or start the loop, react on signals and act upon them (e.g. stop the runtime, exit the progam). I don't think we should treat those differently conceptually, so I do think its possible to share the code for both.

2022-10-26 12:57 UTC, stehessel commented on probe/internal/cli/cli.go
> +var errInterruptSignal error = errors.New("received interrupt signal")
Hmm my IDE uses `gofumpt`, which is a bit stricter and removes the variable block as opposed to `gofmt`. I'd prefer use `gofumpt` formatting, but I can disable it if there are already established conventions like this one.

2022-10-26 13:10 UTC, stehessel commented on probe/internal/cli/cli.go
> +			ctxTimeout, cancel := context.WithTimeout(context.Background(), runtime.Config.RuntimeRunTimeout)
The probe timeout in the loop case currently comes from the `RetryTicker`, which calls its function with a timeout context, which is then also passed to `RunSingle`.

2022-10-26 13:16 UTC, stehessel commented on probe/internal/cli/cli.go
> +			defer signal.Stop(sigs)
You are right, I think this can be removed.

2022-10-26 13:31 UTC, stehessel commented
> I looked at the docs, and if I am not mistaken, the "retry" in the name refers to the fact that a back-off strategy is applied on failures. I.e., you can have different waiting intervals after successful and failed executions, and also have the interval after a failed execution change dynamically based on how many executions have failed in a row. Nifty, but I'm not sure if that is what Stephan wants/needs?

The backoff is definitely not needed here.

2022-10-26 13:47 UTC, SimonBaeumer commented on probe/internal/cli/cli.go
> +			case err := <-runResult:
Uh, did not know that. Today I learned. 🧑‍🏫

2022-10-26 13:55 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) RunSingle(ctx context.Context) error {
Alright, let me summarize:
* We need the 4 types of execution/termination you mentioned. Just to add some more example cases:
  - a single probe run is cleanly terminated upon any error, like a context timeout (`Config.RuntimeRunTimeout`) or on `^C`.
  - in one-shot mode, the program will exit with non-zero exit code upon any error.
  - in loop mode, a recoverable error like context timeout during the probe run does not cancel the loop. It just cleans up the current run and waits for the next one.
  - in loop mode, a non-recoverable error like `^C` cleans up, cancels the loop and the program will exit with non-zero exit code.

Implementation:
* `Start` (loop) and `RunSingle` (one-shot) are part of the runtime package.
* `Start` and `RunSingle` have the same signature, take a context and run in the main go routine. The context is passed further down to the probe package, which will do the requests to fleet manager.
* `Start` calls `RunSingle` internally.
* The interrupt and error handling is done in a separate function, which is run in a separate go routine.

Did I miss anything or misunderstand the proposal?

2022-10-26 17:38 UTC, stehessel commented on probe/pkg/probe/probe.go
> +	time.Sleep(5 * time.Second)
Thanks, I see now. I thought: But it does exit on timeout?!

2022-10-26 17:43 UTC, stehessel commented on probe/config/config_test.go
> +func TestSingleton_Success(t *testing.T) {
Tbh I copied this part from the fleetshard config code. Agreed the name doesn't make sense here, I'll change it.

2022-10-26 17:53 UTC, stehessel commented
I refactored the code such that:

* `runtime.Start` and `runtime.RunSingle` have identical signatures and are now synchronously run on the main go routine.
* The interrupt handling has been factored out into a separate function.
* The `RetryTicket` has been removed in favor of regular `time.Ticker`.
* Smaller changes based on the nit comments.

2022-10-26 18:42 UTC, misberner commented on probe/cmd/probe/main.go
> +		glog.Info("Unable to set logtostderr to true.")
just curious - where would we log this to, given the failure reason?

2022-10-26 18:42 UTC, misberner commented on probe/pkg/probe/probe.go
> +	ErrNotRecoverable = errors.New("not recoverable error")
Hmm, this is a bit of an antipattern as this doesn't say _what_ the error actually is. An error should always be or contain a cause. I saw that you are planning to wrap it (using `errors.Is` for checking), but the _fundamental_ error should always be an error condition, not a label we attach to some other error condition.

2022-10-26 18:42 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +		ctxErr = errors.Wrap(ctxErr, "probe context cancelled")
Also nitpicking here, but given that you didn't call `cancel()`, it is more likely the context timed out/exceeded its deadline rather than being cancelled (this is of course possible if the parent context was canceled).

2022-10-26 18:42 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) Start(ctx context.Context) error {
I would call this `RunLoop` or `RunForever` to emphasize the analogy to `RunSingle`

2022-10-26 18:42 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	if ctxErr := ctxTimeout.Err(); ctxErr != nil {
I would avoid this check:
- if the probe finished successfully (`err == nil`) just before the context expired, there's no reason to return an error.
- if the probe hit an error _other_ than context expiration, this error is most likely to be more relevant for understanding the failure condition; i.e., if `err != nil`, `err` should not be masked.
- if the probe hits a timeout/context cancellation, `Execute` should return `ctxTimeout.Err()` anyway.

2022-10-26 18:42 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) CleanUp() error {
The unfortunate reality is that `CleanUp` will also perform blocking operations, and thus should also receive `context.Context` parameter. This also means you need a second "cleanup" timeout. It also means that when the context is cancelled, you won't be able to exit right away (that's why I initially said I would prefer an asynchronous call to `Stop()` being made rather than a context being cancelled, as the former does not suggest responsiveness - but no need to change it now).

You can add the context param when you start doing something here, but just as a heads-up.

2022-10-26 18:42 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) CleanUp() error {
Separate question: is `Runtime` the right place for `CleanUp`? Since `probe` does the setup, shouldn't it also do the cleanup?

2022-10-26 19:05 UTC, stehessel commented on probe/cmd/probe/main.go
> +		glog.Info("Unable to set logtostderr to true.")
glog defaults to logging to temporary files. See https://pkg.go.dev/github.com/golang/glog#section-documentation.

2022-10-26 19:12 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +func (r *Runtime) CleanUp() error {
I was planning that `runtime.CleanUp` calls not yet existing functions in `probe` to do the actual clean up work (just passing the fleet manager client and so on). If `runtime.CleanUp` turns out unnecessary I can remove it in favor of `probe.CleanUp`.

2022-10-26 19:19 UTC, stehessel commented on probe/pkg/probe/probe.go
> +	ErrNotRecoverable = errors.New("not recoverable error")
Tbh I don't know yet what unrecoverable error we even expect from the probe run (other than `^C`, which is handled by the parent context). So probably it makes sense to removes this now and revisit with a specific error at hand, which we want to cancel the loop.

2022-10-27 01:35 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +			glog.Warning(err)
```suggestion
			if err := r.RunSingle(ctx); err != nil {
			        glog.Warning(err)
			}
```

2022-10-27 01:35 UTC, dhaus67 commented on probe/internal/cli/cli.go
> +	return &CLI{runtime}, nil
nit (to keep consistency with runtime.New()):
```suggestion
	return &CLI{runtime: runtime}, nil
```

2022-10-27 01:35 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +}
```suggestion
```

2022-10-27 01:35 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +	defer r.CleanUp()
I saw @misberner's comment suggesting to change this later on - specifically making the call to `r.CleanUp()` async and expose e.g. a concurrency.Signal indicating whether cleanup has been finalized. So I can assume it's a TODO for later on?

Irrespective of the changes to be made, it's probably still worthwhile to use `defer utils.Should(r.CleanUp())` instead of ignoring the error from `r.CleanUp()` here.

2022-10-27 01:35 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +			return errors.Wrap(ctx.Err(), "probe context invalid")
I think this qualifies as a nit, albeit it would be quite nice to have proper error and log messages on using the interrupt:

Right now, if you would cancel the loop, you would receive the following logs and error message:
```log
^CE1027 03:23:49.503328    3184 cli.go:81] received SIGINT signal, shutting down ...
Error: probe context invalid: context canceled
F1027 03:23:49.503399    3184 main.go:27] probe context invalid: context canceled
```

I thought we initially had plans to use a specific error for this, which is currently unused: `probe/internal/cli.errInterruptSignal`.

Additionally, things get even more confusing when you interrupt the loop when you are currently _within the probe run_:
```log
^CE1027 03:28:16.125293    3330 cli.go:81] received SIGINT signal, shutting down ...
I1027 03:28:16.125347    3330 probe.go:19] probe run has ended
I1027 03:28:16.125360    3330 runtime.go:69] probe resources have been cleaned up
W1027 03:28:16.125368    3330 runtime.go:50] probe run failed: probe run expired: context canceled
Error: probe context invalid: context canceled
```
This will now yield a `probe run expired` error. Reason for this is due to the way `concurrency.WaitWithTimeout` is handling the `ctx.Done` signal. It will return `true`, resulting in us assuming the context deadline was exceeded. Instead, we should check if `errors.Is(ctx.Err(), context.Cancelled)` and handle this to return our "special" interrupt error.

Shall we make it more clear and re-use`probe/internal/cli.errInterruptSignal` _iff_ the context was cancelled? If not, we should remove it since its unused anyways.

2022-10-27 02:23 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +	defer r.CleanUp()
Yeah I'll do this in the next iteration, want to get this one done to avoid moving target.

2022-10-27 02:26 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +			glog.Warning(err)
done

2022-10-27 02:26 UTC, stehessel commented on probe/internal/cli/cli.go
> +	return &CLI{runtime}, nil
done

2022-10-27 02:28 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +			return errors.Wrap(ctx.Err(), "probe context invalid")
I added the check to the interrupt handler in `runtime` since this is where we cancel the context.

2022-10-27 15:49 UTC, misberner approved these changes
I think especially the cleanup portion needs some more thinking, but that will probably be easier once it has a real implementation behind this, so no objections against merging this as-is for now.

2022-10-27 15:49 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +	defer utils.Should(r.CleanUp())
`utils.Should` should only be used when you think that an `error` can only occur because of a programming error. I think cleaning up can fail for a variety of reasons (ACSMS down?) that are not programming errors.
```suggestion
	defer r.CleanUp()
```

2022-10-27 15:51 UTC, dhaus67 approved these changes

2022-10-27 18:59 UTC, merged