Add Kubernetes Label to Tenant Namespaces
stackrox/acs-fleet-manager pull request #519
Opened 2022-10-25 09:07 UTC by mtesseract

## Description

In multiple places we have now logic for retrieving the set of all tenant namespaces by doing some grep-work on `kubectl get ns` output of some sort.

Would be nicer and more robust to have a dedicated label for this.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-25 10:10 UTC, SimonBaeumer requested changes
Very good idea @mtesseract!

2022-10-25 10:10 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) createTenantNamespace(ctx context.Context, namespace *corev1.Namespace) error {
I think this does not update existing namespace right?

2022-10-25 10:11 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	namespace.Labels["rhacscs/type"] = "tenant"
```suggestion
	namespace.Labels["rhacs.redhat.com/tenant"] = ""
```

2022-10-25 10:30 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) createTenantNamespace(ctx context.Context, namespace *corev1.Namespace) error {
that's correct. I thought it would be ok to not implement update logic to keep it simple and instead do a one-time adjustment to the existing namespaces manually.

2022-10-25 10:35 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	namespace.Labels["rhacscs/type"] = "tenant"
Changed.

2022-10-25 14:36 UTC, SimonBaeumer approved these changes

2022-10-25 20:21 UTC, mtesseract commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) createTenantNamespace(ctx context.Context, namespace *corev1.Namespace) error {
@johannes94 I think you mean "If this is rolled out before LA [...]", right?

Do we agree that his change is ok to merge before LA and that it is acceptable to deal with updating tenant namespaces manually until then?

@SimonBaeumer I don't quite follow. What is your point exactly with the bash scripts?

2022-10-26 07:15 UTC, johannes94 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) createTenantNamespace(ctx context.Context, namespace *corev1.Namespace) error {
Yes I mean LA 👍 

> I am wondering if that is a use-case - applying a bash script to adjust existing instances instead of implementing an update logic in the operator which is only executed once.

I'd prefer a declarative approach, e.g fleetshard-sync has a state it wants the namespaces/resources in general to be, including labels and annotations, and makes sure it gets all resources to that state.

2022-10-26 07:41 UTC, merged

2022-10-26 12:00 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) createTenantNamespace(ctx context.Context, namespace *corev1.Namespace) error {
@johannes94 agree, declarative is better. It's the nature of operators to do it programmatically which makes it more complex, the bash script would be a duck-tape solution.

@mtesseract +1 on merging + manual adjustments of labels.