ROX-12076: Probe service - add clients [2]
stackrox/acs-fleet-manager pull request #532
Opened 2022-10-30 23:55 UTC by stehessel

## Description

Follow up to PR #518. This adds the fleet manager client and http client including mocks for tests.

## Checklist (Definition of Done)

- [x] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] ~Evaluated and added CHANGELOG.md entry if required~
- [x] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [x] CI and all relevant tests are passing
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-30 23:55 UTC, stehessel commented
Current dependencies on/for this PR:
* main
  * **PR #532** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/532" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #533** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/533" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/532?utm_source=stack-comment).

2022-11-02 12:54 UTC, SimonBaeumer approved these changes

2022-11-02 12:54 UTC, SimonBaeumer commented on probe/pkg/fleetmanager/client.go
> +// Client is an interface for the fleetmanager client.
```suggestion
// Client is a wrapper interface for the fleetmanager client.
```

2022-11-02 12:54 UTC, SimonBaeumer commented on probe/pkg/fleetmanager/client.go
> +type Client interface {
+1, this is a very good idea to have a mock for the client!

Could you add an interface check to have compile time checks for the interface implementation? 
See: https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance

I think this package can be moved to `pkg/` in general where we maintain a shared client between all components.
Something like `pkg/fleetmanager/client`

2022-11-02 12:54 UTC, SimonBaeumer commented on probe/pkg/fleetmanager/client.go
> +	client, err := fleetmanager.NewClient(config.FleetManagerEndpoint, auth, fleetmanager.WithUserAgent("probe-service"))
```suggestion
	client, err := fleetmanager.NewClient(config.FleetManagerEndpoint, auth, fleetmanager.WithUserAgent("fleet-manager-probe-service"))
```

2022-11-02 14:20 UTC, stehessel commented on probe/pkg/fleetmanager/client.go
> +	client, err := fleetmanager.NewClient(config.FleetManagerEndpoint, auth, fleetmanager.WithUserAgent("probe-service"))
done

2022-11-02 14:20 UTC, stehessel commented on probe/pkg/fleetmanager/client.go
> +type Client interface {
done

2022-11-02 15:36 UTC, dhaus67 approved these changes
Just minor nit's, otherwise LGTM 🚀

2022-11-02 15:49 UTC, SimonBaeumer commented on probe/pkg/fleetmanager/client.go
> +package fleetmanager
I think you can either omit the client part from `pkg/client/fleetmanager` or reversing it to `.../fleetmanager/client`.
This is because this makes the code explorable, a package "client" is very generic and without context (fleet-manager, fleetshard) not a useful information.

2022-11-02 16:30 UTC, misberner requested changes

2022-11-02 16:30 UTC, misberner commented on probe/pkg/fleetmanager/client.go
> +package fleetmanager
+1 on that `pkg/fleetmanager/client` would be a less surprising way to structure the packages

2022-11-02 16:30 UTC, misberner commented on probe/pkg/httpclient/client.go
> +	retryClient := retryablehttp.NewClient()
How do you know that the default retry settings from a third-party library make sense for this use case?

2022-11-02 16:30 UTC, misberner commented on probe/pkg/httpclient/client_mock.go
> +func NewMockClient(fn RoundTripFunc) *http.Client {
I would generally avoid placing test-only functions in regular packages. Maybe put this in `probe/pkg/httpclienttest` or `probe/pkg/httpclient/testutils` or so.

2022-11-02 17:11 UTC, stehessel commented on probe/pkg/fleetmanager/client.go
> +package fleetmanager
I followed the existing structure with different clients placed in `pkg/client/*`. Are you suggesting to refactor the whole structure in https://github.com/stackrox/acs-fleet-manager/tree/main/pkg/client to `pkg/*/client` (for fleetmanager and other clients)? That seems way out of scope to me for this PR. If you mean just the new fleet manager interface in `pkg/fleetmanager/client`, that I can do.

With `.../fleetmanager/client` do you mean reversing it to `probe/pkg/fleetmanager/client`? That I could also do.

2022-11-02 17:14 UTC, stehessel commented on probe/pkg/httpclient/client.go
> +	retryClient := retryablehttp.NewClient()
I took a quick peak at the implementation in my IDE and it seemed reasonable to me. I can pin the retry config if you prefer.

2022-11-02 22:59 UTC, stehessel commented on probe/pkg/httpclient/client_mock.go
> +}
Removed

2022-11-03 02:59 UTC, misberner approved these changes

2022-11-03 02:59 UTC, misberner commented on probe/pkg/httpclient/client.go
> +	retryClient := retryablehttp.NewClient()
I think the question was indirectly targeted at something else: why are those settings good -> what qualifies "good" settings -> what problems do "good" settings solve, therefore: what made you believe that we need intra-request-level retry? Not having looked at the library, I'm assuming now (for good reasons) that this only applies to `GET` (and maybe `HEAD`, but irrelevant) requests, and only to 5xx and transport-level failures. I didn't check the PR 3 line-by-line, but I would assume that only polling/wait-for-ready/wait-for-$status requests are GET request. However, these are retried anyway (as multiple requests) by the probe code. If we think that intermittent failures are a real risk, not retrying intra-request does not seem to hurt much, and retrying intra-request cannot help with the type of requests (mutating ones) where a single failure means the entire probe run fails anyway.

I guess you could argue that in case of a transient failure condition, the intra-request retry would happen quicker than just waiting for the next poll. But there's little reason to assume that this quicker retry is necessary - the status changing to the value we are waiting for is not any more likely after a transport/5xx failure than it is after a 2xx response with an undesired value, and yet we don't retry quickly after the latter.

Long story short: no objection to keeping it. Maybe we should even use it everywhere. But it does introduce complexity and makes things a tad bit less predictable.

2022-11-03 02:59 UTC, misberner commented on pkg/client/fleetmanager/client.go
>  var _ http.RoundTripper = (*authTransport)(nil)
+1 to omitting the comment

2022-11-03 02:59 UTC, misberner commented on probe/pkg/fleetmanager/client.go
> +package fleetmanager
IMHO no need to refactor `pkg/client`. I'm a bit confused if the structure has changed now or if I just misread simon's PR, but the current structure seems fine to me.

2022-11-03 13:01 UTC, stehessel commented on probe/pkg/httpclient/client.go
> +	retryClient := retryablehttp.NewClient()
Alright fair enough. Let me remove the library and add explicit retries as you suggest in PR [3].

2022-11-07 13:53 UTC, stehessel commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/532?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: WSxW0jmiiYoVqUGHV0ml

2022-11-07 13:54 UTC, merged