ROX-12076: Probe service - probe requests [3]
stackrox/acs-fleet-manager pull request #533
Opened 2022-10-30 23:55 UTC by stehessel

## Description

Follow up to PR #518. This adds the primary probe package.

Notable changes:
 * Hopefully better use of tickers and contexts.
 * The clean up routine has been moved to the probe package.
 * The clean up is now done in a separate go routine, while the main routine is blocked by a `concurrency.Signal`.
 * Probes are now named via config parameters. The `ProbeName` can be injected with the K8s pod name on deployment.
 * Instead of passing the state of the current probe run for central deletion back the clean up routine, the probe
   requests the list of currently owned centrals from fleet manager. It then iterates over this list and deletes
   the centrals owned by this instance of the probe. The clean up loop is currently executed sequentially, but
   could be optimized by running it concurrently in the future.
 * Added tests to cli and runtime package to test interrupt and timeout handling.

## Checklist (Definition of Done)

- [x] Unit and integration tests added
- [x] Added test description under `Test manual`
- [ ] ~Evaluated and added CHANGELOG.md entry if required~
- [x] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [x] CI and all relevant tests are passing
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

## Test manual

Tested the probe against a dev data plane cluster.

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-10-30 23:55 UTC, stehessel commented
Current dependencies on/for this PR:
* main
  * **PR #532** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/532" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #533** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/533" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/533?utm_source=stack-comment).

2022-11-02 15:07 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +				glog.Infof("central instance %s is in `%s` state", currentCentral.Id, targetState)
```suggestion
				glog.Infof("central instance %s is in %q state", currentCentral.Id, targetState)
```

2022-11-02 15:08 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +	glog.Info("finished clean up of probe resources")
nit:
```suggestion
	glog.Info("finished attempting clean up of probe resources")
```

2022-11-02 15:17 UTC, dhaus67 commented on probe/pkg/probe/probe_test.go
> +				assert.ErrorContains(t, err, tc.errContains, "expected an error during probe run")
I'm not a fan of these string checks within errors. Ideally, we would do an error comparison here (e.g. `assert.ErrorIs()`.

Unless its really critical, I would favour dropping the specific error check via string and instead simply check for an error being returned, in the lack of absence of concrete error types.

2022-11-02 15:18 UTC, dhaus67 commented on probe/pkg/probe/probe_test.go
> +				assert.NoError(t, err, "failed to create central")
You probably want those to be switched and a `required`. If you were to receive an unexpected error in `probe.CreateCentral`, you would get `central == nil` which would lead to a panic when accessing `central.Status`.
```suggestion
				require.NoError(t, err, "failed to create central")
				assert.Equal(t, constants.CentralRequestStatusReady.String(), central.Status, "central not ready")

```

2022-11-02 15:23 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		ctxCleanup, cancel := context.WithTimeout(context.Background(), r.Config.ProbeCleanUpTimeout)
nit:
```suggestion
		cleanupCtx, cancel := context.WithTimeout(context.Background(), r.Config.ProbeCleanUpTimeout)
```

2022-11-02 15:24 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +	ctxTimeout, cancel := context.WithTimeout(ctx, r.Config.ProbeRunTimeout)
```suggestion
	probeRunCtx, cancel := context.WithTimeout(ctx, r.Config.ProbeRunTimeout)
```

2022-11-02 15:28 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		cleanupDone.Wait()
```suggestion
		select {
		        case <-cleanupCtx.Done():
		            // You probably want to catch the cleanup context being done here as well and log it, otherwise you will not catch it with the blocking call on `cleanupDone.Wait()`.
		        case <- cleanupDone.Done():
		           // The concurrency.Signal does expose this handy `Done()` function, which is a channel that will be closed if the signal was triggered.
		}
```

2022-11-02 15:32 UTC, dhaus67 commented on probe/pkg/runtime/runtime_test.go
> +			assert.Equal(t, 1, len(tc.mockFMClient.DeleteCentralByIdCalls()), 1, "must delete central for clean up")
Otherwise, you would have an index out of bounds panic in l.73 in case `tc.mockFMClient.DeleteCentralByIdCalls() == 0`
```suggestion
			require.Equal(t, 1, len(tc.mockFMClient.DeleteCentralByIdCalls()), 1, "must delete central for clean up")
```

2022-11-02 15:35 UTC, dhaus67 commented on probe/pkg/runtime/runtime_test.go
> +func TestRunSingle(t *testing.T) {
It would be great to additionally have a test case which tests the behavior upon a timeout within the Cleanup section.

I feel like this would require additional work to make the code better testable, meaning defining an interface for `Probe` and generating mocks for that, ensuring that runtime depends on the interface etc.

2022-11-02 15:52 UTC, stehessel commented on probe/pkg/probe/probe.go
> +		central := centralList.Items[i]
This doesn't work because of `&central` below, which does not work if `central` is part of the loop scope.

2022-11-02 15:53 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +		central := centralList.Items[i]
Ah, I missed that, disregard this one then.

2022-11-02 16:03 UTC, stehessel commented on probe/pkg/runtime/runtime_test.go
> +func TestRunSingle(t *testing.T) {
This could be tested by putting a timeout into a mocked `GetCentralsFunc`, but it's probably a better idea to do the testing improvement you mentioned. That way we would have to deal with a mocked fleetmanager client in `runtime_test.go` and `cli_test.go` at all.

2022-11-02 16:44 UTC, stehessel commented
> 1. Avoiding creating an infinite number of probe Centrals

This is already covered by a finite quota for the probe service account. I don't think we need to add additional logic to the probe or fleet manager.

> 2. Testing the probe

I would suggest to add a `probe run` against the stage fleet manager to the CI pipeline. But I would do that as a follow up.

2022-11-02 18:34 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +		cleanupDone.Wait()
I'm fine with this change, just curious: This is what I expect to happen in case the `CleanUp` context expires:
* The context sensitive requests return with context exceeded error.
* This leads to `CleanUp` returning and signalling `cleanupDone` because of the `defer` statement.
* This then ends the blocking `cleanupDone.Wait` call.

Is there any scenario where the signal is not triggered in the defer and we would dead lock without this change?

2022-11-02 23:04 UTC, stehessel commented on probe/pkg/runtime/runtime_test.go
> +func TestRunSingle(t *testing.T) {
Added a test that times out in `CleanUp`.

2022-11-03 09:59 UTC, misberner requested changes

2022-11-03 09:59 UTC, misberner commented on probe/pkg/probe/probe.go
> +	centralList, _, err := p.fleetManagerClient.GetCentrals(ctx, nil)
There's a 15m timeout for cleaning up, yet we give up immediately if fleet manager spits out an error. This seems a bit odd to me. I would have expected cleaning up to work like a reconciliation loop: attempting the same sequence of steps (list - filter - delete - wait for deleted) over and over again, until we either have confirmation that all centrals are gone, or the timeout expires.

2022-11-03 09:59 UTC, misberner commented on probe/pkg/probe/probe.go
> +	if err := p.pingURL(ctx, centralRequest.CentralUIURL); err != nil {
So, expanding on my [comment from the previous PR](https://github.com/stackrox/acs-fleet-manager/pull/532/files#r1012019030) a bit: I see now that there are no explicit retries here in the surrounding logic. I wonder, though, if relying on HTTP client-level retries makes sense, for three different reasons:
1. absence of logging. While the client attempts to ping central, nothing will be printed on the console. I think it would be helpful to log intermediate attempts.
2. lack of control. I think we're _expecting_ that the first few attempts will fail, because the image will need to be pulled, central will need to be initialized before marking itself ready, router configs will need to be updated etc. To me, 4 retries with a 1 sec minimum seem very low. Not sure what the exponential base and the jitter are, but naively, it looks like we might give up after as little as ~10-15s. That is not enough for image pull + central startup, generally speaking. Somewhat related: the retry parameters, especially the point at which to give up, are not related to the overall probe execution timeout at all. While there certainly is some value in detecting error conditions that won't resolve themselves automatically, I would say that, in the absence of any such condition, we should keep retrying until the time budget is exhausted.
3. adequacy of retry policy. The default retry policy by the library makes sense when assuming we are interacting with an established system, but I'm not sure whether it's lenient enough to deal with a system that is just in the process of starting up. For example, race conditions when provisioning routes might be an issue. DNS resolution failures are retriable, and when an OpenShift router gets hit on a route that it doesn't know, it sends a 503 (service unavailable), which is also retriable. However, among the non-retriable errors are certificate validation errors. And I think such an error _could_ occur spuriously because the `CentralUIURL` is the _external_ URL, not the one corresponding to a route's default DNS (`<route>-<namespace>.apps.<cluster DNS>`). A 503 does not help in this context if it's sent back with an invalid certificate (matching `*.apps.<cluster DNS>`, whereas we'd need `*.acs.rhcloud.com` or so). It's of course good to not re-invent the wheel when it comes to deciding whether an HTTP failure is retriable or not, but I do suspect that some customizations are needed.

Have you done any extended tests of running the probe? If so, and you observed no flakes, maybe these concerns are unwarranted. However, I do think they should be addressable in a fairly complete fashion by using techniques you've already used elsewhere in the probe logic, namely explicit retries with a ticker.

2022-11-03 13:05 UTC, stehessel commented on probe/pkg/probe/probe.go
> +	return fmt.Sprintf("%s-%s-%s", p.config.ProbeNamePrefix, p.config.ProbeName, rndString), nil
My intention was to use Kubernetes `valueFrom` to set `ProbeName` to the pod name of the probe. Afaik this does not allow further string formatting, so to keep the `probe-` I added the prefix.

2022-11-03 13:55 UTC, stehessel commented on probe/pkg/probe/probe.go
> +	if err := p.pingURL(ctx, centralRequest.CentralUIURL); err != nil {
I have not seen any flakes so far. Note that the probe already ensures that the Central is "ready", although I'm not exactly sure how that is determined wrt to the errors you mentioned. But I'm fine with switching to an explicit ticker based retry.

2022-11-03 21:06 UTC, stehessel commented on probe/pkg/probe/probe_test.go
> +package probe
@SimonBaeumer I added more tests wrt timeouts in `probe_test.go` in [4e8c2a0](https://github.com/stackrox/acs-fleet-manager/pull/533/commits/4e8c2a0b7dfb445d6a7c1cfd7e9b6209a9d98d5d).

2022-11-04 00:21 UTC, misberner requested changes
I think a few refactorings would really help readability, but overall the approach looks good. Thanks for all the effort iterating on this!

This is probably the last review I will be able to provide. Feel free to simply dismiss my review once you have addressed the changes.

2022-11-04 00:21 UTC, misberner commented on probe/pkg/probe/probe.go
> +	return fmt.Sprintf("%s-%s-%s", p.config.ProbeNamePrefix, p.config.ProbeName, rndString), nil
It doesn't allow string formatting directly, but a little-known property of K8s env vars is that they actually allow [variable substitution](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/). Hence, you could do
```
env:
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: PROBE_NAME
  value: "probe-$(POD_NAME)"
```
Note that the order is crucial, variables must be defined before being referenced.

I don't want to say you _should_ be using something like the above, but it _is_ possible.

2022-11-04 00:21 UTC, misberner commented on probe/pkg/probe/probe.go
> +				continue
I think it would be good for readability to factor the code under the `case <-ticker.C` branch out into a separate function.

2022-11-04 00:21 UTC, misberner commented on probe/pkg/probe/probe.go
> +				continue
Actually, it might be worthwhile factoring out also the outer loop into a `retryUntilSucceeded(ctx context.Context, fn func(context.Context) error, interval time.Duration)` or so.

2022-11-04 00:21 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +		cleanupDone := concurrency.NewSignal()
It isn't entirely clear to me why `CleanUp` runs in a goroutine and you use a signal here, given that `CleanUp` takes in a context and thus should respect context cancellations. I _suspect_ that the motivation is ensuring that the deferred cleanup does not run for longer than `ProbeCleanUpTimeout`, regardless of whether `CleanUp` is well-behaved (i.e., respecting context cancellations) or not. If this is the case, there should be a comment here motivating the goroutine/signal approach.

2022-11-04 00:21 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +			defer cleanupDone.Signal()
This is a deferred call in a goroutine launched from a deferred func. I think factoring one of those functions out would be a good change.

2022-11-04 00:21 UTC, misberner commented on probe/pkg/runtime/runtime.go
> +		cleanupCtx, cancel := context.WithTimeout(context.Background(), r.Config.ProbeCleanUpTimeout)
I think I said this in a previous PR already, but it is a bit unfortunate that `RunSingle` now deliberately disrespects the `ctx` passed to it due to cleanup. I don't have a good solution, though

2022-11-04 01:17 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +		cleanupDone := concurrency.NewSignal()
Maybe I misunderstood your previous comments, but I thought that you and @dhaus67 were explicitly asking for the go routine/signal approach for the clean up function. That's why I used it here, however to my understanding, the new `context.Background()` would be sufficient as well.

2022-11-04 01:21 UTC, stehessel commented
> I think a few refactorings would really help readability, but overall the approach looks good. Thanks for all the effort iterating on this!
This is probably the last review I will be able to provide. Feel free to simply dismiss my review once you have addressed the changes.

Thank you as well Malte, for putting in a lot of effort to give a detailed review. I learned quite a lot, and I think it will be worth it in the end.

2022-11-04 02:24 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +			defer cleanupDone.Signal()
done

2022-11-04 02:24 UTC, stehessel commented on probe/pkg/probe/probe.go
> +				continue
Done, also for the other retry-type functions.

2022-11-04 06:45 UTC, dhaus67 approved these changes
Thanks for addressing all the feedback and iterating over all the comments!

Just minor comments from my side, otherwise LGTM.

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +			errReturn = cleanupCtx.Err()
I haven't seen the usage of named return parameters in combination with go routine as such here - will this actually lead to the `context cancelled / context deadline exceeded` error being returned from `RunSingle` here?

Either way, probably nice to have a comment describing this here, it wasn't not totally obvious to me at first sight.

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +				glog.Warning(err)
Should we log the error here or silently ignore it?
Currently, we do log every error in `cleanUpFunc` and the default error we return pretty much doesn't say a lot (`central clean up not successful`).
I know that it's not necessarily given that this function knows the details of the passed `fn` - so either we should stop logging within `cleanUpFunc` and propagate the whole error context and log it here, or silently ignore here and log within `cleanUpFunc`.

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +	ensureFunc := func(context.Context) error {
Can we factor this out to a separate function instead of a inline function?

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +	}
Can we factor this out to a separate function instead of a inline function?

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe.go
> +			if response != nil && response.StatusCode == http.StatusNotFound {
I suppose in case `response != nil` you also want to close the response body.

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/runtime/runtime.go
> +		cleanupDone := concurrency.NewSignal()
I think the previous iteration had neither context nor signal - I suppose that's the misunderstanding here and where the suggestions came from (at the very least I can speak for the suggestions I made).

I think we now doubled up on the way the function should behave - we have the context cancellation _and_ the signal approach.

I personally like the signal approach more for these cleanup tasks, however, since you already implemented it, you can also keep the context cancellation and remove the signal part.

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe_test.go
> +			testName: "timeout on context deadline exceeded",
```suggestion
			testName: "create central times out",
```

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe_test.go
> +			testName: "timeout on context deadline exceeded",
```suggestion
			testName: "central deletion times out",
```

2022-11-04 06:45 UTC, dhaus67 commented on probe/pkg/probe/probe_test.go
> +			testName: "timeout on context deadline exceeded",
```suggestion
			testName: "clean up times out",
```

2022-11-04 12:59 UTC, stehessel commented on probe/pkg/runtime/runtime.go
> +			errReturn = cleanupCtx.Err()
The return is not assigned from the goroutine, but just from a deferred function. So yeah it should return the context error. However on second look, I this might not be such a good idea in case `Execute` already returned an error, because then we are overwriting that. So I think just logging the clean up error would be better.

2022-11-04 13:09 UTC, stehessel commented on probe/pkg/probe/probe.go
> +			if response != nil && response.StatusCode == http.StatusNotFound {
The OpenAPI client always closes the body, that's why I removed it here.

2022-11-07 13:02 UTC, SimonBaeumer approved these changes

2022-11-07 13:53 UTC, stehessel commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/533?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: WSxW0jmiiYoVqUGHV0ml

2022-11-07 15:15 UTC, merged