WIP: add cloud account id to API, database and AMS call
stackrox/acs-fleet-manager pull request #535
Opened 2022-10-31 12:06 UTC by ivan-degtiarenko

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Evaluated and added CHANGELOG.md entry if required
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-11-05 01:26 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	if err := q.verifyCloudAccountInAMS(dinosaur, orgID); err != nil {
We should only do something with the cloud accounts if the billing model is `marketplace`. Note that the billing model is determined via `getAvailableBillingModelFromDinosaurInstanceType` automagically by fleet manager. This is taken from the Kafka implementation, but I'm not a big fan of that. I can imagine in the future we will also add the billing model as an explicit request parameter. In any case, for `standard` billing model (e.g. yearly subscriptions, sold via regular Red Hat sales) we should just ignore the cloud account id.

2022-11-05 01:34 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	}
I would probably write this as such to avoid the `&&`s. But feel free to ignore, I think this is personal taste.

```suggestion
	if dinosaur.CloudAccountID == "" {
	  if len(cloudAccounts) != 0 {
		return errors.CloudAccountIDNotSetupProperly("Request cloud account is not setup even though organization has cloud accounts")
	  }
	  return nil
}
```

2022-11-05 01:40 UTC, stehessel commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	for _, ca := range cloudAccounts {
This would be much nicer to write in Python 😅 . Not sure if there is a more elegant way in golang though

2022-11-05 01:43 UTC, stehessel commented on pkg/errors/errors.go
> +func CloudAccountIDNotSetupProperly(reason string, values ...interface{}) *ServiceError {
Maybe `InvalidCloudAccountID` is a better name? `NotSetupProperly` sounds weirdly informal.

2022-11-05 01:49 UTC, stehessel commented
LGTM overall. The situation with the billing model is a bit unfortunate, because currently we don't really make this distinction in the UI. Right now I think it's probably best to favour `marketplace` over `standard` billing model if both exist, such that we don't run into the situation where a cloud account id is selected in the UI, but the quota is registered with a `standard` billing model. As mentioned in the future it might make sense to make the billing model explicitly part of the request, as well as show a selection of billing model to the user in the UI.

2022-11-14 13:17 UTC, SimonBaeumer requested changes

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return errors.NewWithCause(svcErr.Code, svcErr, "Error getting cloud accounts")
Can you log the cloud account IDs requested here please?

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return errors.CloudAccountIDNotSetupProperly("Request cloud account is not setup even though organization has cloud accounts")
Can you log the cloud account IDs requested here please?

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	for _, ca := range cloudAccounts {
Is the loop necessary because AMS returns all customer's cloud accounts? Can't we request an account by providing provider + ID?

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +						ca, _ := v1.NewClusterAuthorizationResponse().Allowed(true).Subscription(&sub).Build()
Can you rename `ca` to `cloudAccount`? ca is an abbreviation used to often for certificate authority.

```suggestion
						cloudAccount, _ := v1.NewClusterAuthorizationResponse().Allowed(true).Subscription(&sub).Build()
```

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	for _, ca := range cloudAccounts {
Can you rename `ca` to `cloudAccount`? ca is an abbreviation used to often for certificate authority.

```suggestion
	for _, cloudAccount := range cloudAccounts {
```

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +						sub.Status("Active")
Can you add constants for the string fields here?
Is it worth adding constants for the`sub.Status` field in a non-test package? 🤔

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +			name: "cloud account id in request is empty while cloud_accounts response is not",
Can you also write what is expected?

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +							panic("unexpected error")
Use `require.NoError(err)` instead

2022-11-14 13:17 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +			name: "cloud account id in request does not match cloud_accounts response",
```suggestion
			name: "cloud account id in request does not match ids in cloud_accounts response",
```

2022-11-15 23:23 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +	for _, ca := range cloudAccounts {
@SimonBaeumer unfortunately, AMS API does not allow for this level of granularity, see how  [GetCustomerCloudAccounts](https://github.com/stackrox/acs-fleet-manager/blob/ivan%2Frox-12153-add-aws-account-central-request/pkg/client/ocm/client.go#L606-L628) is implemented

2022-11-15 23:36 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return errors.NewWithCause(svcErr.Code, svcErr, "Error getting cloud accounts")
Not sure what you mean by cloud account IDs requested - here we request all cloud account IDs for organization

2022-11-15 23:39 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +						ca, _ := v1.NewClusterAuthorizationResponse().Allowed(true).Subscription(&sub).Build()
Here `ca` stands for `clusterAuthorization` - should we change to `cloudAuthorizationResponse`?

2022-11-16 00:04 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +						sub.Status("Active")
I extracted this subscription into a separate method.

> Is it worth adding constants for the sub.Status field in a non-test package

considering it is used twice within this repo, I wouldn't bother

2022-11-16 07:47 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return errors.NewWithCause(svcErr.Code, svcErr, "Error getting cloud accounts")
Ah okay, makes sense. Would you think it is useful to log the orgId?

2022-11-16 07:48 UTC, SimonBaeumer commented on internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
> +						ca, _ := v1.NewClusterAuthorizationResponse().Allowed(true).Subscription(&sub).Build()
Good suggestion, +1 for `cloudAuthorizationResp`

2022-11-16 07:48 UTC, SimonBaeumer approved these changes

2022-11-16 19:10 UTC, ivan-degtiarenko commented on internal/dinosaur/pkg/services/quota/ams_quota_service.go
> +		return errors.NewWithCause(svcErr.Code, svcErr, "Error getting cloud accounts")
Counter-proposal: maybe we can add `orgID` to error? Our HTTP handlers should log all errors with HTTP code between 400 and 499

2022-11-16 21:17 UTC, stehessel approved these changes

2022-11-18 22:21 UTC, merged