Provision RDS instances and clusters
stackrox/acs-fleet-manager pull request #542
Opened 2022-11-03 16:21 UTC by vladbologa

- ROX-13158: Sync CRDs with the stackrox repo
- Update Central CR to latest version
- Add DB field to Central CR
- DB Provisioning
- Move code to db.go
- * Generate passwords * Deprovision DBs on Central deletion * Siupport DB provisioning resuming, if fleetshard restarts

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Evaluated and added CHANGELOG.md entry if required
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-11-04 15:26 UTC, vladbologa commented
/test all

2022-11-04 15:43 UTC, vladbologa commented
/test all

2022-11-07 16:52 UTC, vladbologa commented
/test all

2022-11-08 18:55 UTC, vladbologa commented
/test e2e

2022-11-16 18:03 UTC, vladbologa commented
/test all

2022-11-17 17:28 UTC, vladbologa commented
/test all

2022-11-17 18:45 UTC, vladbologa commented
/test all

2022-11-17 18:53 UTC, vladbologa commented
/test all

2022-11-17 20:02 UTC, vladbologa commented
/test all

2022-11-17 21:15 UTC, vladbologa commented
/test all

2022-11-18 14:28 UTC, vladbologa commented
/test all

2022-11-21 08:44 UTC, vladbologa commented
/test all

2022-11-21 10:12 UTC, vladbologa commented
/test all

2022-11-22 21:04 UTC, vladbologa commented
/test all

2022-11-22 22:32 UTC, vladbologa commented
/test all

2022-11-23 08:27 UTC, vladbologa commented
/retest required

2022-11-24 10:51 UTC, vladbologa commented on fleetshard/pkg/central/rdsclient/rdsclient.go
> +	for {
I want to check if this can be rewritten using event subscriptions (instead of polling for the state every 10 seconds).

2022-11-24 10:52 UTC, vladbologa commented on fleetshard/pkg/central/rdsclient/rdsclient.go
> +		Region: aws.String(awsRegion),
passing of the credentials is missing here

2022-11-24 10:55 UTC, porridge commented on fleetshard/pkg/central/rdsclient/rdsclient.go
> +	for {
I'd be cautious against adding too much AWS-specific code at this point, given:
- this might be a premature optimization,
- the possibility of having to support other cloud providers in the future, who might not have an events mechanism.

2022-11-24 17:07 UTC, vladbologa commented
/test all

2022-11-24 17:54 UTC, vladbologa commented
/test all

2022-11-26 09:57 UTC, vladbologa commented
/test all

2022-11-28 10:42 UTC, ebensh requested changes

2022-11-28 10:42 UTC, ebensh commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			glog.Infof("Deprovisioning RDS database cluster.")
I think this is swapped with the message below - first we delete the instance, then the cluster

2022-11-28 10:42 UTC, ebensh commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			glog.Infof("Deprovisioning RDS database instance.")
Flipped here

2022-11-28 10:42 UTC, ebensh commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +// EnsureDBProvisioned is a blocking function that makes sure that an RDS database was provisioned for a Central
In runtime.go:134 this is provided ctx.Background(), and it looks like we don't ensure a timeout anywhere; this means the reconcile for this Central could get stuck and never recover, correct?

Should we at least ensure a timeout is present on the AWS API call? (or in the larger runtime.go set a timeout on the context there)

2022-11-28 11:09 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +// EnsureDBProvisioned is a blocking function that makes sure that an RDS database was provisioned for a Central
Right, I forgot to write a TODO about this, and then I forgot about it entirely. I'll look into it now.

2022-11-28 14:26 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +// EnsureDBProvisioned is a blocking function that makes sure that an RDS database was provisioned for a Central
I think I prefer setting a timeout in runtime.go, even though that will change behaviour unrelated to this ticket. But if someone has a strong reason not to do it, I'll move it to the AWS API call.

2022-11-28 15:00 UTC, SimonBaeumer commented
@vladbologa Can you describe the overall approach in the PR description? If possible highlighting areas which are more critical?

2022-11-28 16:12 UTC, vladbologa commented
/test e2e

2022-11-29 08:51 UTC, SimonBaeumer requested changes

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return "", fmt.Errorf("unexpected number of DB instances: %v", err)
I would assume that in this case `err` is `nil` no?
Would it be more useful to print the returned DB instances instead?

```
"unable to determine DB instances, found more than 1 instance. Instances: ...."
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	}
WDYTH about moving these to the function call directly?
Temporary variables are helpful to me if the execution path gets too long and bloated, in this case to me it created an indirection which was a bit harder to create a mental mapping on.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		result, err := c.rdsClient.DescribeDBInstances(dbInstanceQuery)
```suggestion
		dbInstanceStatuses, err := c.rdsClient.DescribeDBInstances(dbInstanceQuery)
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceResult, err := c.rdsClient.DescribeDBInstances(dbInstanceQuery)
Here as well like described (below or above :D), I like the effort of creating temporary variables for readability, in this case though it creates a mental mapping overhead for readers of the code in a simple execution path.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		dbInstanceStatus := *result.DBInstances[0].DBInstanceStatus
Can you use the `clusterStatus` for L197-L206? Looks like duplicate code on a first glance.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	return err == nil
This check looks not accurate. If `err` contains a network related error it does not says anything about the existence of the database but would return `false` here.
Instead a specific `not exist-err` should be checked or the amount of db instances returned.

Also in other cases you verified that only 1 DB instance is returned from the query, here the check is not done. Is there a reason? 🤔

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	_, err := c.rdsClient.DescribeDBClusters(dbClusterQuery)
See below feedback on `instanceExists`. I think it is not sufficient to only check for an error if a cluster exists.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceID := centralNamespace + dbInstanceSuffix
I think coupling the namespace name is not a good idea. If the namespace schema changes our database names need a migration as well.
If you want to refer to the `rhacs-<instance-id>` model I think a function which compiles it explicitly is better to avoid side effects in later refactorings.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			glog.Infof("Deprovisioning RDS database instance.")
I think this log info is meaningless because it lacks context which database is provisioning.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			//TODO: do not skip taking a final DB snapshot
Is this a requirement? If yes please create a ticket for it.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +				return false, fmt.Errorf("deleting DB cluster: %v", err)
```suggestion
				return false, errors.Wrap(err, "deleting DB cluster")
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return false, fmt.Errorf("getting DB cluster status: %v", err)
```suggestion
			return false, errors.Wrap(err, "getting DB cluster status")
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +				return false, fmt.Errorf("deleting DB instance: %v", err)
```suggestion
				return false, errors.Wrap(err, "deleting DB instance")
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return false, fmt.Errorf("getting DB instance status: %v", err)
```suggestion
			return false, errors.Wrap(err, "getting DB instance status")
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		// cluster does not exist, create it
Can be removed, comment is redundant to if-case.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		glog.Infof("Provisioning RDS database cluster.")
Log message lacks context, please add DB cluster name. 
Is it a useful information? Don't we only need that information in case a provisioning failed?

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	if !c.clusterExists(clusterID) {
Can you change the check to an early return?

```
if c.clusterExists(clusterID) {
    return nil
}

// Logic to create DB cluster
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	if !c.instanceExists(instanceID) {
Here also an early return to reduce n-path complexity.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	awsRegion        = "us-east-1" // TODO: this should not be hardcoded
I second the TODO, can you make it configurable?

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			// TODO: delete cluster if instance cannot be created?
Why? Shouldn't the reconciler just retry to create a new instance?
If the timeout is reached our operations team gets notified because of a failed provisioning.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return fmt.Errorf("creating DB instance: %v", err)
```suggestion
			return errors.Wrap(err, "creating DB instance")
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		return "", fmt.Errorf("ensuring DB instance %s exists in cluster %s: %v", instanceID, clusterID, err)
```suggestion
		return "", errors.Wrapf(err, "ensuring DB instance %s exists in cluster %s", instanceID, clusterID)
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		return "", fmt.Errorf("ensuring DB cluster %s exists: %v", clusterID, err)
```suggestion
		return "", errors.Wrapf(err, "ensuring DB cluster %s exists", clusterID)
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	err := c.ensureDBClusterCreated(ctx, clusterID, centralNamespace, centralDbSecretName)
You can move the err and ensure call into the if-statement directly.

```
if err := c.ensureDBClusterCreated(ctx, clusterID, centralNamespace, centralDbSecretName); err != nil {
    // ...
}
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	err = c.ensureDBInstanceCreated(instanceID, clusterID)
Can be moved the if case directly.

```
if err := c.ensureDBInstanceCreated(instanceID, clusterID); err != nil {
    // ....
}
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		return "", fmt.Errorf("getting cluster status: %v", err)
```suggestion
		return "", errors.Wrap(err, "getting cluster status")
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/dbprovisioningclient.go
> +package dbprovisioning
The naming is duplicate of the package name. To me the package would look something like this:

```
cloudprovider/
  dbclient.go         // has interface
  awsclient/
    rds.go
```

`dbprovisioning` sounds overly specific to me which would make all other queries related to instance management not being located here.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/dbprovisioningclient.go
> +	EnsureDBProvisioned(ctx context.Context, name, passwordSecretName string) (string, error)
Docs should be on the interface, i.e. if the call is blocking.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +		assert.Fail(t, "Ready condition not found in conditions", status.Conditions)
Why not printing a message in `assert.Equal` if the assert failed? There is no need to call `assert.Fail` manually here

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	if readyCondition, ok := conditionForType(status.Conditions, conditionTypeReady); ok {
```suggestion
readyCondition, ok := conditionForType(status.Conditions, conditionTypeReady)
require.True(t, ok)
assert.Equal(t, "True", readyCondition.Status, "Ready condition not found in conditions", status.Conditions)
```

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, "1", central.GetAnnotations()[revisionAnnotationKey])
Why do you assert the revision? `Reconcile` is called once.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, testutils.CentralCA, route.Spec.TLS.DestinationCACertificate)
Why verifying so many properties on the created route?

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	_, ok := secret.Data["password"]
I think an assertion is missing that the DB password is not empty.

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	managedDBProvisioningClient.On("EnsureDBProvisioned", mock.Anything, mock.Anything, centralDbSecretName).Return("connectionString", nil)
Can you add a meaningful example of a connection string with example data?

2022-11-29 08:51 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.NotNil(t, statusDeletion)
Should this be a check on a specific status?

2022-11-29 12:41 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +				return fmt.Errorf("creating Central DB secret: %v", err)
I replaced %v with %w, because it's the preferred way in Go 1.13+ here and in all other places.

2022-11-29 12:44 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/dbprovisioningclient.go
> +package dbprovisioning
Done, I think your naming suggestion is much better.

2022-11-29 12:50 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return "", fmt.Errorf("unexpected number of DB instances: %v", err)
I checked the docs and it's not possible to get more than 1 instances if you search by name (there must be an exact match). And if the instance is not found, the `DescribeDBInstances` will fail. So I removed this check entirely.

2022-11-29 12:52 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		glog.Infof("Provisioning RDS database cluster.")
I think it's useful to see exactly when we called the AWS API to provision / deprovision databases and instances.

2022-11-29 12:56 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		result, err := c.rdsClient.DescribeDBInstances(dbInstanceQuery)
Done

2022-11-29 12:56 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		// cluster does not exist, create it
Done

2022-11-29 13:07 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	if !c.clusterExists(clusterID) {
Done

2022-11-29 13:07 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	if !c.instanceExists(instanceID) {
Done

2022-11-29 13:07 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			// TODO: delete cluster if instance cannot be created?
Agreed, I removed this comment.

2022-11-29 13:16 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		time.Sleep(10 * time.Second)
The time is 8-10 minutes... With a 10 sec delay we're making about 50 requests to AWS.

2022-11-29 13:18 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	}
`DescribeDBInstances` / `DescribeDBClusters` belong to the `aws-sdk-go` package. I could make a wrapper function, to make the code easier to follow.

2022-11-29 13:23 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/dbprovisioningclient.go
> +	EnsureDBProvisioned(ctx context.Context, name, passwordSecretName string) (string, error)
Done

2022-11-29 13:51 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			glog.Infof("Deprovisioning RDS database instance.")
Fixed.

2022-11-29 13:52 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			//TODO: do not skip taking a final DB snapshot
Tbh not sure, will have to check. I think it should be a requirement, otherwise if a Central is deleted by mistake, it will not be possible to recover it to its most recent state.

2022-11-29 13:56 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, testutils.CentralCA, route.Spec.TLS.DestinationCACertificate)
These checks were copied over from the `TestReconcileCreate` test.

I thought I should do all the checks from that test (+ the DB checks), to make sure there were no side-effects (i.e. causing unrelated features to stop working).

2022-11-29 14:07 UTC, kovayur requested changes

2022-11-29 14:15 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			secret = &corev1.Secret{
Done

2022-11-29 14:34 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	return err == nil
You're right, fixed.

I got tricked by the function doc, which only lists `ErrCodeDBClusterNotFoundFault` as possible error codes, but that doesn't account for network related errors etc.

2022-11-29 14:36 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	awsRegion        = "us-east-1" // TODO: this should not be hardcoded
I'd leave it for another PR, because we only support this region anyway atm. If I don't hardcode it here, I'd have to hardcode it somewhere in the upper layers. Should I do that?

2022-11-29 18:44 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceID := centralNamespace + dbInstanceSuffix
I agree, this was a hack from the original demo that somehow stayed, but now it's not easy to get rid of.

I have now refactored the RDS client to remove references to namespaces (I was using them to name the clusters & instances, but also to retrieve the password secret - functionality which does not belong here). 

But then I noticed that we don't have the `instance-id` anywhere in fleetshard, except for the namespace. Possible solutions:

1.  keep using the namespace for now, create a ticket to remove coupling to namespace (I suppose we can assume the namespaces will be stable short-medium term)
2. propagate the `CentralID` from fleet-manager to fleetshard (requires internal API changes)
3. generate the DB name and store it (in etcd?) I would prefer not to do this, I want to avoid keeping state, and instead having deterministic names for the DB.

WDYT? I'd go for 1, followed by 2.

2022-11-29 19:07 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.NotNil(t, statusDeletion)
This code was part of the original `TestReconcileDelete`, which I duplicated and added the DB-related checks. I think you wrote these asserts. :)

2022-11-29 19:12 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +		assert.Fail(t, "Ready condition not found in conditions", status.Conditions)
I did not write this code. There is the original test `TestReconcileCreate`, I added `TestReconcileCreateWithManagedDB` which is similar to the original one, but uses the Managed DB and has some extra checks. Same goes for several other comments here.

2022-11-30 08:26 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		time.Sleep(10 * time.Second)
Can we than use 1 min? 🤔 
If the provisioning misses the first attempt it needs at leat 20 Minutes which would result in a timeout and a pager notification.

2022-11-30 08:29 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return "", fmt.Errorf("unexpected number of DB instances: %v", err)
I think the check should not removed than, it is always possible to have an error in AWS SDK. If Go tries to access an invalid index the application crashes.
See: https://go.dev/play/p/-IfKZQJVojL

2022-11-30 08:31 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	}
Initializing the struct in the function call is what I've tried to describe. That would be independent of the aws sdk, the caller has full control over it:

```
_, err := c.rdsClient.DescribeDBClusters(&rds.DescribeDBClustersInput{
    DBClusterIdentifier: aws.String(clusterID),
})
```

2022-11-30 08:32 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceResult, err := c.rdsClient.DescribeDBInstances(dbInstanceQuery)
It is about the `dbInstanceQuery`. Sorry my comment was not explicit enough.

2022-11-30 08:38 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		time.Sleep(10 * time.Second)
I'm not sure I understand. This is just the time interval between two AWS calls. Additionally there's a 15 minute timeout  for the `Reconcile` function.

What is it that causes the Pager notification? If there's no status reported from fleetshard -> Fleet Manager in 20 minutes? Or if there's no running Central in 20 minutes?

2022-11-30 08:39 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceID := centralNamespace + dbInstanceSuffix
> propagate the CentralID from fleet-manager to fleetshard (requires internal API changes)

Option 2 sounds the best to me. Imho follow-up PR is okay, a TODO with the ticket number to it is sufficient.

2022-11-30 08:40 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	}
Ah ok, I actually made this change. See rds.go:197 (describeDBInstance) and rds.go:209(describeDBCluster)

2022-11-30 08:40 UTC, SimonBaeumer commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			//TODO: do not skip taking a final DB snapshot
Please remove the TODO if it is not necessary. We should not keep the database after deletion, so I suspect that this is a requirement.
Can you check with Doron?

2022-11-30 08:42 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +		assert.Fail(t, "Ready condition not found in conditions", status.Conditions)
Interesting, no need to tackle it in this PR.

2022-11-30 08:44 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, testutils.CentralCA, route.Spec.TLS.DestinationCACertificate)
We also have e2e tests. No strong feelings on having too many assertions here, just wanted to be cautiousness about them because it creates unnecessary noise in CI logs.
Maybe reducing the amount of assertions is fine here? Do you expect any side effects except the route not being created? 🤔

2022-11-30 08:46 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.NotNil(t, statusDeletion)
Okay, then we can do better than my old me here 🥳 
Please let us not use "copied the code" as an excuse to keep logic which we can do simply better now. Also this means the author of the copied code did not fully understood the assertion itself as well. We are all stuck in the past😱

2022-11-30 08:47 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, testutils.CentralCA, route.Spec.TLS.DestinationCACertificate)
> These checks were copied over from the TestReconcileCreate test.

As I read it again I have strong feelings. Copying code and leaving the state is not good if we know it already better. Let's spent the time on housekeeping. 🧹

2022-11-30 09:03 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, testutils.CentralCA, route.Spec.TLS.DestinationCACertificate)
I don't expect any sides effects, but I don't want to test only for things that I expect. There might be side effects in the future for who knows what reason.

I think the test for "Central creation" should be just as thorough as the test for "Central creation with Managed DB". I don't think that duplicated code in tests is as bad as in production code, but we could also factor some things out.

2022-11-30 09:08 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.NotNil(t, statusDeletion)
I agree, but I couldn't resist pointing it out, sorry. 😂

2022-11-30 09:28 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			//TODO: do not skip taking a final DB snapshot
We don't keep the database. It's a snapshot stored on S3, with a retention period of 30 days (set with BackupRetentionPeriod).

2022-11-30 11:24 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			return "", fmt.Errorf("unexpected number of DB instances: %v", err)
Done.

2022-11-30 11:24 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceResult, err := c.rdsClient.DescribeDBInstances(dbInstanceQuery)
Done.

2022-11-30 15:53 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	instanceID := centralNamespace + dbInstanceSuffix
Done

2022-11-30 15:53 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +			//TODO: do not skip taking a final DB snapshot
Added a Jira ticket in the TODO.

2022-11-30 15:54 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +	awsRegion        = "us-east-1" // TODO: this should not be hardcoded
Done, added ticket number.

2022-11-30 15:58 UTC, vladbologa commented on fleetshard/pkg/central/dbprovisioning/rdsprovisioningclient.go
> +		dbInstanceStatus := *result.DBInstances[0].DBInstanceStatus
Done

2022-11-30 16:44 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.Equal(t, "1", central.GetAnnotations()[revisionAnnotationKey])
The revision value is set by the reconciler, so this checks that the value is correct.

2022-11-30 20:46 UTC, vladbologa commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
> +              value: "$MANAGED_DB_SECRET_ACCESS_KEY"
Done.

2022-11-30 20:46 UTC, vladbologa commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
> +              value: "$MANAGED_DB_SESSION_TOKEN"
Done.

2022-11-30 22:48 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.NotNil(t, statusDeletion)
Actually the status is checked the following lines...

2022-11-30 22:48 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	if readyCondition, ok := conditionForType(status.Conditions, conditionTypeReady); ok {
Done

2022-11-30 22:48 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	managedDBProvisioningClient.On("EnsureDBProvisioned", mock.Anything, mock.Anything, centralDbSecretName).Return("connectionString", nil)
Done

2022-12-01 07:42 UTC, vladbologa commented
/test e2e

2022-12-01 09:53 UTC, SimonBaeumer requested changes
Good job @vladbologa!

2022-12-01 09:53 UTC, SimonBaeumer commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +		// this should never happen (DescribeDBInstances should return either 1 instance, or ErrCodeDBInstanceNotFoundFault)
+1000, defensive programming!

2022-12-01 09:53 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.True(t, len(password) > 0)
There are pre-defined existing assertion (asset.NotEmpty could work too):

```suggestion
	assert.Len(t, len(password) > 0)
```

2022-12-01 09:53 UTC, SimonBaeumer approved these changes

2022-12-01 10:13 UTC, ebensh approved these changes
LGTM, let's get it in and test it out further

2022-12-01 10:15 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	assert.True(t, len(password) > 0)
`Len` doesn't work in this case (it compares against an exact value), I changed to `NotEmpty`

2022-12-01 10:27 UTC, kovayur approved these changes
LGTM. Just a few small remarks on unit testing. Can be fixed in the following PRs.

2022-12-01 10:27 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.ErrorContains(t, err, "InvalidClientTokenId")
nit: Shouldn't we test here with AWS mocked services instead of real?

2022-12-01 10:27 UTC, kovayur commented on fleetshard/pkg/testutils/dbclient.go
> +type DBProvisioningClientMock struct {
nit: shouldn't we use `moq` to generate mocked implementations?

2022-12-01 10:28 UTC, kovayur commented
Good job @vladbologa 🚀 !

2022-12-01 10:31 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +	require.ErrorContains(t, err, "InvalidClientTokenId")
actually I used the real one on purpose for this test, but maybe it's not good practice if a unit test depends on external services

2022-12-01 10:58 UTC, merged