ROX-12871: add release-version to Makefile
stackrox/acs-fleet-manager pull request #565
Opened 2022-11-09 09:53 UTC by johannes94

## Description
To make it easier to get a release version string I added a Makefile target. I also updated the CHANGELOG.md to list the 2022-11-08.1.3060ea1 Release, since it wasn't done during release.

## Checklist (Definition of Done)

~- [ ] Unit and integration tests added~
~- [ ] Added test description under `Test manual`~
~- [ ] Evaluated and added CHANGELOG.md entry if required~
~- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~
~- [ ] CI and all relevant tests are passing~
~- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~
~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

## Test manual

```
# To run tests locally run:
make release-version
```

2022-11-09 10:19 UTC, kovayur commented on Makefile
> +REVISION ?= 1
Shouldn't we start with `0` WDYT @SimonBaeumer @johannes94 ?

2022-11-09 10:19 UTC, kovayur approved these changes

2022-11-14 12:51 UTC, SimonBaeumer commented on Makefile
> +REVISION ?= 1
1 is fine, zero seems odd on an incremental number if a first release was done.

2022-11-14 12:52 UTC, SimonBaeumer requested changes

2022-11-14 12:52 UTC, SimonBaeumer commented on Makefile
> +	@echo "$(release_date).$(REVISION).$(release_commit)"
How do you increment the revision? I would guess you need to parse at the existing git tags for a given date no?

2022-11-16 16:03 UTC, johannes94 commented on Makefile
> +	@echo "$(release_date).$(REVISION).$(release_commit)"
For now I though setting eg. `REVISION=2 make release-version` is sufficient, but I can invest some more time to do it with parsing if you like.

2022-11-16 16:04 UTC, SimonBaeumer commented on Makefile
> +	@echo "$(release_date).$(REVISION).$(release_commit)"
Parsing please, automate everything ⚙️

2022-11-22 13:51 UTC, johannes94 commented on Makefile
> +	@echo "$(release_date).$(REVISION).$(release_commit)"
Done.

2022-11-23 08:16 UTC, johannes94 commented
/retest

2022-11-23 08:17 UTC, SimonBaeumer approved these changes

2022-11-23 08:42 UTC, merged