Implement runtime
stackrox/acs-fleet-manager pull request #59
Opened 2022-05-29 18:42 UTC by SimonBaeumer

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-05-30 14:18 UTC, kovayur approved these changes

2022-05-30 14:18 UTC, kovayur commented on fleetshard/pkg/runtime/runtime.go
> +func (r *Runtime) Start() error {
To me the reconciler now has too many responsibilities. It handles not only the reconciliation with the k8s cluster, now it also handles the locks and updates the status.

How about keeping it synchronous with the same signature and handle the parallelisation and sending the statues by the caller (`Runtime`)?

How about this (not tested, just sharing the idea):
```
func (r *Runtime) Start() error {
	ticker := concurrency.NewRetryTicker(func(ctx context.Context) (timeToNextTick time.Duration, err error) {
		startedAt := time.Now()

		list, err := r.client.GetManagedCentralList()
		if err != nil {
			glog.Errorf("Failed to list central", err)
			return 0, err
		}

		results := make(chan reconcileResult)
		reconciler := centralreconciler.NewCentralReconciler(r.k8sClient, r.client)
		statusesMap := make(map[string]private.DataPlaneDinosaurStatus)

		for _, remoteCentral := range list.Items {
			remoteCentral := remoteCentral
			go func() {
				status, err := reconciler.Reconcile(context.Background(), remoteCentral)
				if err != nil {
					glog.Errorf("failed to reconcile central %s: %s", remoteCentral.Metadata.Name, err)
				}
				results <- reconcileResult{
					id:     remoteCentral.Id,
					status: status,
				}
			}()
		}

		for i := 0; i < len(list.Items); i++ {
			result := <-results
			if result.status != nil {
				statusesMap[result.id] = *result.status
			}
		}

		_, err = r.client.UpdateStatus(statusesMap)
		if err != nil {
			glog.Errorf("failed to update statuses %s: %s", err)
		}

		return r.nextTick(startedAt), nil
	}, 10 * time.Minute, backoff)

	return ticker.Start()
}

func (r *Runtime) nextTick(startedAt time.Time) time.Duration {
	duration := time.Now().Sub(startedAt)
	return max(0, 30 * time.Second - duration)
}

func max(a, b time.Duration) time.Duration {
	if a > b {
		return a
	}
	return b
}

type reconcileResult struct {
	id     string
	status *private.DataPlaneDinosaurStatus
}
```

2022-05-30 15:56 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		return errors.New("Reconciler still busy, wait until current reconciliation has stopped.")
`wait until ...` sounds like a blocking operation.

```suggestion
		return errors.New("Reconciler still busy, skipping reconciliation attempt.")
```

2022-05-31 08:31 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +func (r *Runtime) Start() error {
> handles the locks

Yes, it is by intention to be safe to call. The reconcile can now called as often as it want without running into unsafe operations (i.e. parallel reconciles on the same Central instance).
This makes it more convenient in our use-case due to the polling mechanism.
Handing the locking in the reconcile itself also allows us triggering the reconcile from other sources, like kube events, too.

> and updates the status

Why do you consider sending the status updates to the fleet-manager should not be done in the reconciler?
The reconciler takes care of the end-to-end deployment/upgrade flow of a central. 
The only reason not sending the updates from the reconcile would be if status should not be reported to a fleet-manager.

> handle the parallelisation and sending the statues by the caller (Runtime)?

Updates see above.
Handling parallelisation by the runtime would mean the reconcile function allows parallel execution by default only prevented by the runtime.
With this approach the caller is responsible to implement guarding logic to not run into race-conditions on the reconcile.

2022-05-31 08:34 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +func (r *Runtime) Start() error {
Starting the reconcile from the runtime in a goroutine imho can make sense. 
The idea for the reconciler was to have only one instance which can receive from multiple sources - to prevent parallel reconciles it should only ever exists one reconciler per Central.

For our use-cases now likely to be too complex.

2022-05-31 08:35 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +	reconcilers       reconcilerCache
Good catch.
If a central instance is deleted it should be cleaned up from this map. Wouldn't call it cache anymore though, `Registry` would be a better term.

2022-05-31 08:36 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		return errors.New("Reconciler still busy, wait until current reconciliation has stopped.")
done

2022-05-31 13:10 UTC, mtesseract reviewed
Partial review.

2022-05-31 13:10 UTC, mtesseract commented on fleetshard/pkg/runtime/runtime.go
> +		glog.Infof(string(resp))
Is it useful to output the response with Info severity in case `err != nil`?

2022-05-31 13:27 UTC, mtesseract requested changes

2022-05-31 13:27 UTC, mtesseract commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	blocked            *int32
The name `blocked` seems to correspond to a single variant of the above enum, namely `BlockedStatus`. I'd suggest to rename this field to something like `status` or `blockingStatus`.

2022-05-31 13:27 UTC, mtesseract commented on fleetshard/pkg/centralreconciler/reconciler.go
> +func (r CentralReconciler) ReceiveCh() chan *private.ManagedCentral {
nit: I find it a bit misleading that the exported getter here carries "Receive" in its name, while the actual user of this function (the runtime) uses it for *sending* something.

2022-05-31 13:28 UTC, SimonBaeumer commented on dev/scripts/ffm_curl.sh
> +#!/usr/bin/env bash
Moved the `dev/scripts` to the `scripts/` dir and remove `ffm_curl.sh`

2022-05-31 13:38 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +type reconcilerRegistry map[string]*centralreconciler.CentralReconciler
Added a small comment. With that being said most of the things need more docs and polishing

2022-05-31 13:39 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +		glog.Fatal("failed to create fleetmanager client", err)
Return the error now and exit on the caller with `glog.Fatal`

2022-05-31 13:39 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +		glog.Infof(string(resp))
This needs more polishing, edit a To Do comment

2022-05-31 13:41 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +func (r CentralReconciler) ReceiveCh() chan *private.ManagedCentral {
Good catch, renamed to `InputChannel`

2022-05-31 14:42 UTC, mtesseract approved these changes

2022-05-31 14:54 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +type ReconcilerResult struct {
`ReconcileResult`?

2022-05-31 14:54 UTC, kovayur commented on fleetshard/pkg/runtime/runtime.go
> +			reconciler.InputChannel() <- &central
Instead of using `resultCh` and `inputCh` why don't just call the `Reconcile` function in a goroutine here:

```
for _, central := range list.Items {
	if _, ok := r.reconcilers[central.Metadata.Name]; !ok {
		r.reconcilers[central.Metadata.Name] = centralreconciler.NewCentralReconciler(r.k8sClient, r.client, central, r.reconcilerResultCh)
	}

	reconciler := r.reconcilers[central.Metadata.Name]
	go func() {
		status, err := reconciler.Reconcile(context.Background(), central)
		r.handleResult(central, status, err)
	}()
}
```

Initaly I thought about an asynchronous [pipeline](https://go.dev/blog/pipelines) which consists of 2 stages:
1) Perform reconciliation and return the status to the `runtime`
2) Report the status to the fleet manager

But after reading about how it can be implemented in go I ended up with this. 
I think that's even simpler. What do you think?

2022-05-31 14:56 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +type ReconcilerResult struct {
done

2022-05-31 16:25 UTC, merged