ROX-13593: Add tenant ID as a k8s label
stackrox/acs-fleet-manager pull request #627
Opened 2022-12-01 03:21 UTC by stehessel

## Description

## Checklist (Definition of Done)

- [x] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] ~Evaluated and added CHANGELOG.md entry if required~
- [ ] ~Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~
- [x] CI and all relevant tests are passing
- [x] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] ~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~

## Test manual

2022-12-01 03:22 UTC, stehessel commented
Current dependencies on/for this PR:
* main
  * **PR #617** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/617" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #627** <a href="https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/627" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/acs-fleet-manager/627?utm_source=stack-comment).

2022-12-01 17:08 UTC, 0x656b694d commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
Why label and not annotation?

2022-12-01 20:50 UTC, stehessel commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
I think it fits a bit better semantically because it identifies the resources. It's also more useful than an annotation because you can do something like `kubectl get pods -l tenant=xxx`. Not a big deal, but why not use it.

2022-12-05 09:33 UTC, SimonBaeumer requested changes

2022-12-05 09:33 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
+1 for label. Labels are used for identification, whereas annotations define different meta data and sometimes modify a pods behaviour (i.e. a controller).


Suggestion: being more explicit in the annotation key:

```suggestion
	tenantIDLabelKey          = "rhacs.redhat.com/tenant-id"
```

2022-12-05 09:33 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	namespace.Labels[tenantIDLabelKey] = ""
The `rhacs.redhat.com/tenant` had a different use-case. It was to select all namespaces for tenants, independent of the actual tenant configuration.
Please do not delete this, some queries require it.

Please add a new label and keep the `rhacs.redhat.com/tenant` label as it is.

2022-12-05 09:33 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +				tenantIDLabelKey:      remoteCentral.Id,
WDYTH about setting the tenant-id label also on the namespace?

2022-12-05 10:35 UTC, 0x656b694d commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
Well, ok, I can see a potential use case to find pods in multi-tenant setup one day.
This ID is going to modify central pods behavior. I'll need to update the backend, once we agree on the naming.
@SimonBaeumer, please expand how the similar namespace label is used, why cannot the name be the same?

2022-12-05 12:11 UTC, stehessel commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	namespace.Labels[tenantIDLabelKey] = ""
But currently it's just an empty label, I don't really get it. Couldn't you still query all namespaces via `kubectl get namespaces -l rhacs.redhat.com/tenant`, even if each label value would be the actual id? Can you maybe post the query that you have in mind?

2022-12-05 12:12 UTC, stehessel commented on fleetshard/pkg/central/reconciler/reconciler.go
> +				tenantIDLabelKey:      remoteCentral.Id,
I would rather set the `rhacs.redhat.com/tenant` on the namespace to the actual id.

2022-12-05 14:21 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	namespace.Labels[tenantIDLabelKey] = ""
> But currently it's just an empty label, I don't really get it.

Empty labels and annotation are often used in Kubernetes to identify something. The existence of the label is equal to `rhacs.redhat.com/tenant=true`.

> Couldn't you still query all namespaces via kubectl get namespaces -l rhacs.redhat.com/tenant, even if each label value would be the actual id?

I am honestly not sure if referencing a label without the value works in this scenario, never tried it. 

>  Can you maybe post the query that you have in mind?

The query you mentioned is what I have in mind: `kubectl get namespaces -l rhacs.redhat.com/tenant`
As discussed in a thread above with @0x656b694d: https://github.com/stackrox/acs-fleet-manager/pull/627#discussion_r1039659277

2022-12-05 14:23 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	namespace.Labels[tenantIDLabelKey] = ""
Referencing the label name with values works as well:

```
❯ k get ns -l "kubernetes.io/metadata.name"
NAME              STATUS   AGE
default           Active   12d
kube-system       Active   12d
kube-public       Active   12d
kube-node-lease   Active   12d
stackrox          Active   11d
test1             Active   21s
❯ k get ns -l "kubernetes.io/metadata.name=test1"
NAME    STATUS   AGE
test1   Active   23s
```

2022-12-05 14:33 UTC, stehessel commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
But you don't have to specify the value to query for the existence of the label.

2022-12-05 14:38 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
>But you don't have to specify the value to query for the existence of the label.

That's correct.

@stehessel Are you worried about the number of labels on an k8s object? 🤔

2022-12-05 14:43 UTC, stehessel commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
In this case yes (well not really worried, just a bit baffled). I see no reason for two tenant identifier labels.

2022-12-05 15:45 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	tenantIDLabelKey          = "rhacs.redhat.com/tenant"
Agree, let's use `rhacs.redhat.com/tenant` then.

2022-12-05 15:47 UTC, SimonBaeumer submitted a review, later dismissed
Please add the tenant ID to the namespace labels and ready to 🚢

2022-12-07 09:12 UTC, 0x656b694d approved these changes
LGTM

2022-12-07 12:34 UTC, merged