[fleetshard] Add central removal logic to the reconciler
stackrox/acs-fleet-manager pull request #63
Opened 2022-05-30 11:42 UTC by kovayur

## Description
Add central removal logic to the reconciler

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-02 07:54 UTC, johannes94 approved these changes
Looks good.

2022-06-03 14:06 UTC, SimonBaeumer requested changes
Nice @kovayur, Looks already very good!

2022-06-03 14:06 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +func (r CentralReconciler) getOwnedPVCs(central *v1alpha1.Central) ([]*v1.PersistentVolumeClaim, error) {
You can list the PVCs by the `app.kubernetes.io/component: central` label and delete all of them.
Filtering the PVC for the owner-ref in our case does not work reliable because the operator removes its owner ref after a deletion on the CR is triggered to prevent k8s garbage collection cleaning it up.

2022-06-03 14:06 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	}
new line pls

2022-06-03 14:06 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		if err := r.deleteCentralPVC(pvc); err != nil {
Why extracting it in its own function for a simple delegation in an obvious call?

2022-06-03 14:06 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	return r.client.Delete(context.Background(), namespace)
Does this work?
```suggestion
	return r.client.Delete(context.Background(), &v1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
	})
```

2022-06-03 14:06 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		return deletedStatus(), nil
Is this call only made until all resources were removed for a given Central?

2022-06-07 07:55 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		return errors.Wrapf(err, "get central PVCS %s/%s", central.GetName(), central.GetNamespace())
Fixed.

2022-06-07 07:55 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +			tmp := item
Removed.

2022-06-07 07:57 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +func (r CentralReconciler) getOwnedPVCs(central *v1alpha1.Central) ([]*v1.PersistentVolumeClaim, error) {
This obstacle was already taken into account, but anyway the implementation was changed according to your suggestion.

2022-06-07 07:57 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	}
Added more newlines here and below.

2022-06-07 07:59 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		if err := r.deleteCentralPVC(pvc); err != nil {
To align with another function calls inside this function, like: `r.getCentralPVCs`, `r.deleteCentralCR` and `r.deleteNamespace`.

Anyway, inlined.

2022-06-07 07:59 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	return r.client.Delete(context.Background(), namespace)
Inlined as suggested.

2022-06-08 07:08 UTC, SimonBaeumer commented on README.md
> +# Golang 1.17+
A lower version might not work because some symbols are not supported by <Go 1.17 or libs don't exists.

2022-06-08 07:16 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +func (r CentralReconciler) deleteCentralCR(central *v1alpha1.Central) error {
Can you make all functions context aware and pass it from the highest function?

2022-06-08 07:49 UTC, kovayur commented on Makefile
> +.PHONY: fleet-manager
Right, without this `make binary` simply doesn't work for me

2022-06-08 07:51 UTC, kovayur commented on README.md
> +# Golang 1.17+
Yes, this is the requirement came after importing stackrox as a dependency. I just missed this occurrence in the docs last time.

2022-06-08 07:57 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +func (r CentralReconciler) deleteCentralCR(central *v1alpha1.Central) error {
Done.

2022-06-10 07:42 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +	watch, err := r.watchNamespace(ctx, central.GetNamespace())
A watch here is dangerous I think as it starts an async process and could block the goroutine for a long time, especially if something goes wrong.

Instead let's align this with kube's controller recommendation to only use synchronous code.
You can check for the deletion timestamp and re-check on every reconcile if all resources were cleaned up. 
If everything was cleaned up the status update is reported to the Fleet-Manager.

2022-06-13 20:10 UTC, SimonBaeumer requested changes
Two last things to address, then LGTM.
Do you plan to address the e2e-test in separate PR?

2022-06-13 20:10 UTC, SimonBaeumer commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		deleted = deleted && crDeleted
The `&&` is not necessary, just returning `crDeleted` if it is `false` should be enough.
If `deleted` was once set to false all other `&&` calls evaluate to `false` too.

2022-06-13 20:10 UTC, SimonBaeumer commented on fleetshard/pkg/k8s/client.go
> +	k8sClient, err := ctrlClient.NewWithWatch(config, ctrlClient.Options{
Can the `NewWithWatch` be reverted?

2022-06-14 09:15 UTC, kovayur commented on fleetshard/pkg/centralreconciler/reconciler.go
> +		deleted = deleted && crDeleted
Done.

2022-06-14 09:15 UTC, kovayur commented on fleetshard/pkg/k8s/client.go
> +	k8sClient, err := ctrlClient.NewWithWatch(config, ctrlClient.Options{
Reverted.

2022-06-14 13:53 UTC, SimonBaeumer approved these changes
LGTM!

2022-06-14 13:57 UTC, merged