Mc/fleet shard to image
stackrox/acs-fleet-manager pull request #64
Opened 2022-05-30 12:05 UTC by mtesseract

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-05-31 08:31 UTC, mtesseract commented on Makefile
> +BUILD_IMAGE := quay.io/stackrox-io/apollo-ci:$(shell sed 's/\s*\#.*//' BUILD_IMAGE_VERSION)
There must have been some misunderstanding here.

Never said that it is *necessary* to use apollo-ci. My thinking here has been that this building mechanism is easy to copy straight from stackrox and that it would potentially provide us with a more future-proof solution.

But, I don't have strong feelings on this -- at least for now we can easily get away with `GOOS=linux GOARCH=amd64`.

2022-05-31 09:04 UTC, porridge requested changes
I don't think we should be treating the fleet manager image as a bag for all our binaries.
Let's use a different image for that.

2022-05-31 09:11 UTC, mtesseract commented
> I don't think we should be treating the fleet manager image as a bag for all our binaries. Let's use a different image for that.

That PR was based on a Slack discussion. @SimonBaeumer @porridge

2022-05-31 12:01 UTC, porridge approved these changes
Discussed on slack, we'll go ahead with this debt for now.

2022-05-31 12:15 UTC, porridge commented
Perhaps create a ticket and add a TODO to create another image? @mtesseract

2022-05-31 13:35 UTC, SimonBaeumer requested changes

2022-05-31 13:35 UTC, SimonBaeumer commented on Makefile
>  	$(GO) build ./cmd/fleet-manager
Can you add a separate command to build the fleet-manager independently?

2022-05-31 13:44 UTC, SimonBaeumer requested changes

2022-05-31 15:23 UTC, mtesseract commented on Makefile
>  	$(GO) build ./cmd/fleet-manager
ok

2022-06-01 07:31 UTC, SimonBaeumer requested changes

2022-06-01 07:33 UTC, mtesseract commented on BUILD_IMAGE_VERSION
> +stackrox-build-0.3.35
thanks, yes

2022-06-01 07:34 UTC, mtesseract commented on Makefile
> +
done

2022-06-02 06:49 UTC, SimonBaeumer approved these changes

2022-06-02 06:49 UTC, SimonBaeumer commented on secrets/db.host.internal-docker
> +kubernetes.docker.internal
Should this file be here?

2022-06-02 07:20 UTC, mtesseract commented on secrets/db.host.internal-docker
> +kubernetes.docker.internal
Yes, required for configuring our services so that they are able to talk to a postgres on the host system.
It is a bit unfortunate in my opinion that `fleet-manager` and `fleetshard-sync` in their current form cannot by configured using environment variables, instead most settings are read from config *files*. (Or is there a way that I have overlooked so far?)

2022-06-02 07:31 UTC, mtesseract commented on Makefile
> +	GOOS=linux GOARCH=amd64 $(GO) build $(GOARGS) -o fleetshard-sync ./fleetshard
Thank you! I was looking for something like this, but didn't find it immediately. 
In case somebody is interested, here is the manual for this piece of Makefile functionality: https://www.gnu.org/software/make/manual/make.html#Target_002dspecific

2022-06-02 07:32 UTC, mtesseract commented on Makefile
> +	GOOS=linux GOARCH=amd64 $(GO) build $(GOARGS) -o fleetshard-sync ./fleetshard
Changed, will proceed with merging.

2022-06-02 07:34 UTC, merged