Add option to enable performance insights
stackrox/acs-fleet-manager pull request #643
Opened 2022-12-06 19:54 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Evaluated and added CHANGELOG.md entry if required
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-12-07 13:43 UTC, ebensh approved these changes

2022-12-07 13:44 UTC, ebensh commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +	dbMinCapacity           = 0.5
Maybe specify units here - vCPU? Days?

2022-12-07 13:48 UTC, kovayur commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
> +              value: "$MANAGED_DB_PERFORMANCE_INSIGHTS"
Aren't we going to include this parameter to the helm chart as well?

2022-12-07 14:01 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +	dbMinCapacity           = 0.5
It's ACUs - Aurora Capacity Unit
1 ACU = 1 vCPU + 2GB RAM

Should it be like `dbMinCapacityACU`? and a comment describing the acronym?

2022-12-07 14:01 UTC, vladbologa commented on dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
> +              value: "$MANAGED_DB_PERFORMANCE_INSIGHTS"
yes, doing that now

2022-12-07 14:25 UTC, kovayur requested changes
Pls add `MANAGED_DB_PERFORMANCE_INSIGHTS` parameter to the helm chart and enable it

2022-12-08 08:25 UTC, kovayur requested changes
All good except the small typo

2022-12-08 08:25 UTC, kovayur commented on dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
> +          value: { { .Values.fleetshardSync.managedDB.performanceInsights | quote } }
```suggestion
          value: {{ .Values.fleetshardSync.managedDB.performanceInsights | quote }}
```

2022-12-08 12:13 UTC, merged