ROX-13911: Add RDS provisioning integration test
stackrox/acs-fleet-manager pull request #680
Opened 2022-12-15 15:02 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Evaluated and added CHANGELOG.md entry if required
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-12-15 15:33 UTC, kovayur commented on .github/workflows/ci.yaml
> +    environment: dev
nit:
```suggestion
    environment: development
```
to be aligned with another environment names.

2022-12-15 15:33 UTC, kovayur commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
Don't we want to make a separate test suite for RDS instead of introducing a skip flag? I think it will be cleaner + we could run RDS tests in parallel with the main suite in another action.

2022-12-15 15:39 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
Yes, that was my original plan. I'd like to get this one pass first, and then I'll look into that.

2022-12-15 17:51 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
Done.

2022-12-15 18:52 UTC, vladbologa commented on .github/workflows/rds.yaml
> +          AWS_RDS_DB_SUBNET_GROUP_NAME: ${{ secrets.AWS_RDS_DB_SUBNET_GROUP_NAME }}
@kovayur Is it possible to get these from the parameter store? I manually stored them as secrets in the GitHub development environment, for now.

2022-12-16 09:39 UTC, kovayur commented on .github/workflows/rds.yaml
> +          AWS_RDS_DB_SUBNET_GROUP_NAME: ${{ secrets.AWS_RDS_DB_SUBNET_GROUP_NAME }}
Yes, it is possible. In fact, they already should present in the Parameter Store.

2022-12-20 09:44 UTC, kovayur requested changes
Good job @vladbologa, just a few minor remarks

2022-12-20 09:44 UTC, kovayur commented on .github/workflows/rds.yaml
> +          source "scripts/lib/external_config.sh"
```suggestion
          set -euo pipefail
          source "scripts/lib/external_config.sh"
```

2022-12-20 09:44 UTC, kovayur commented on .github/workflows/rds.yaml
> +          export AWS_AUTH_HELPER="none"
nit: move to `env` section?

2022-12-20 09:44 UTC, kovayur commented on .github/workflows/rds.yaml
> +          export PATH=${PATH}:$GOPATH/bin
nit: I understand that it was inspired by `ci.yaml` but is it really necessary?

2022-12-20 09:44 UTC, kovayur commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
As far as I understand, you can add move `rds_test.go` under `/test` subdirectory to be excluded by `make test` target:
```
go list ./... | grep -v /test
```

2022-12-20 15:06 UTC, vladbologa commented on .github/workflows/rds.yaml
> +          export PATH=${PATH}:$GOPATH/bin
Looks like it's not, removed.

2022-12-20 15:06 UTC, vladbologa commented on .github/workflows/rds.yaml
> +          export AWS_AUTH_HELPER="none"
Done.

2022-12-20 15:14 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
I'm also using unexported types from the `awsclient` package in these tests, so if I'm moving this file in a new directory (e.g. `awsclient/test/integration`) I won't have access to them.

So I'd rather keep this as is, unless you have another idea how to fix this.

2022-12-21 09:20 UTC, kovayur approved these changes

2022-12-21 09:20 UTC, kovayur commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
IMO an **integration** test should not use internal package types, this indicates that we are mixing test kinds (unit vs integration). Perhaps we could use the aws client to make sure the DB is (de)provisioned. It would have been a more "fair" test. Nevertheless, I don't want to block this PR, perhaps this should be left as food for thought.

2022-12-21 10:22 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	if os.Getenv("RUN_RDS_TESTS") != "true" {
I agree and I also thought about it, but the alternative is not perfect either... Basically I'd have to copy the `instanceExists` and `clusterExists` functions from awsclient into the test package.

2022-12-21 10:34 UTC, merged