Increase resource limits and requests
stackrox/acs-fleet-manager pull request #723
Opened 2023-01-13 20:49 UTC by connorgorman

## Description

Up for debating the increases in requests, but the limits should be more near to what we expect customers to run in production

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Evaluated and added CHANGELOG.md entry if required
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-01-19 13:13 UTC, SimonBaeumer requested changes
@connorgorman Do you have any concerns about limiting the resources to lower than recommended?
So far we did not hit any issues, i.e. with hack-fest deploying >70 instances.
The secured clusters were very small in these scenarios.

2023-01-19 13:13 UTC, SimonBaeumer commented on internal/dinosaur/pkg/defaults/default_scanner_spec.go
> +	CPURequest    resource.Quantity `env:"CPU_REQUEST"    envDefault:"100m"`
The requests for CPU are so low because it reserves CPU resources. We hit a problem when too many instances are deployed to the cluster that the cluster run out of resources, even though the CPU usage was < 40%.
For now the idea is that instances with higher resource requirements are scaled manually vertically.

2023-05-03 21:26 UTC, connorgorman commented
@SimonBaeumer I am seeing quite a few timeout: context deadline exceeded errors when contacting the database. Also, there seems to be a decent amount of throttling. I've removed the requests, but increased the limits so that customers can at least get a core of resources

2023-05-03 22:09 UTC, kylape commented
You could take care of https://issues.redhat.com/browse/ROX-16657 and bump memory request to `1Gi`.  We'll need to make sure we are ready to increase node count on our clusters in the likely event that ACS instances will not be able to be scheduled due to lack of allocatable memory.

2023-05-03 22:11 UTC, connorgorman commented
@kylape I had initially adjusted the requests in this PR, but there were concerns that we weren't utilizing the cluster enough

2023-05-04 03:48 UTC, kylape commented
I think when customers start using the cloud service for production
workloads, the average central will likely use more resources.

On Wed, May 3, 2023 at 17:12 Connor Gorman ***@***.***> wrote:

> @kylape <https://github.com/kylape> I had initially adjusted the requests
> in this PR, but there were concerns that we weren't utilizing the cluster
> enough
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/stackrox/acs-fleet-manager/pull/723#issuecomment-1533819328>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHEIJ6JTO64BTMVA4P7SXDXELJ3NANCNFSM6AAAAAAT2ZYJKY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-04 08:13 UTC, SimonBaeumer commented
We can increase the resources but need an additional alert for memory and CPU requests exceeding cluster capacity. 
Added a ticket for this: https://issues.redhat.com/browse/ROX-16884

2023-05-04 18:41 UTC, kylape commented
let me try to sum up all the things

* Need to bump memory and cpu limits because things are slow
* This increases risk of evictions, so bump up cluster node count
* Evictions trigger incidents - this should be fixed by modifying the alert rule
* Evictions can also be reduced by increasing memory request, but this risks scheduling issues, especially at the point when requests are raised across the fleet

2023-05-04 18:42 UTC, kylape approved these changes

2023-05-04 18:47 UTC, merged

2023-05-05 09:30 UTC, porridge commented on internal/dinosaur/pkg/defaults/default_scanner_spec.go
> +	CPURequest    resource.Quantity `env:"CPU_REQUEST"    envDefault:"100m"`
FTR, we had [an alert today](https://redhat-internal.slack.com/archives/C055YVB53M5) where the 0.005 core request might have been at least a contributing factor.