enable setting operator versions in dataplane config file
stackrox/acs-fleet-manager pull request #73
Opened 2022-05-30 19:54 UTC by johannes94

## Description
In order to get a central resource in fleet manager to transition from `accepted` to `provisioning` you have to set available operator version for a cluster. Until now it was expected that this would be done by fleet shard components with a PUT request to `/api/rhacs/v1/<cluster-id>/status` when they are deployed and ready on the data plane cluster. Since we're bringing the clusters in manually, it makes sense to also allow setting this configuration with the `dataplane-cluster-configuration.yaml` file. When using the new introduced configuration (see [dataplane-cluster-configuration-dockerdesktop.yaml](dev/config/dataplane-cluster-configuration-dockerdesktop.yaml)) the cluster will be in `ready` state and have an operator version available, thus there is no further preparation necessary to start with proper central reconciliation.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-05-30 22:31 UTC, mtesseract reviewed
Looking good to me, just have minor stylistic remarks and two questions:

First: Do we have an idea already on how a dinosaur operator would look like? I was under the impression that we don't know yet what kind of operator components we need on the dataplane clusters.

Second: I understand that this change allows to register a new cluster in `ready` state with a certain dinosaur operator version being set. Somewhere in the comments for this PR I would have expected some remark along the lines of saying that when registering clusters in `ready` state it is your own responsibility to also make sure you have set up the claimed operator version on the dataplane cluster, because this is nothing the fleet-manager would do for you (right?).

Does this make sense?

2022-05-30 22:31 UTC, mtesseract commented on dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
> +      dinosaur_versions:
Personally I would prefer getting rid of these occurrences of "dinosaurs" incrementally.

2022-05-30 22:31 UTC, mtesseract commented on internal/dinosaur/pkg/config/dataplane_cluster_config.go
> +	AvailableDinosaurOperatorVersions []api.DinosaurOperatorVersion `yaml:"available_dinosaur_operator_versions"`
There might have been discussions around this which I have missed, but especially for things like public struct fields I would prefer avoiding the "dinosaur" terminology.

2022-05-30 22:31 UTC, mtesseract commented on dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
> +#- This list is ordered, any new cluster should be appended at the end.
What exactly does it mean for list being ordered? What would happen if a new cluster is inserted at the beginning or in the middle?

2022-05-31 06:31 UTC, johannes94 commented on dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
> +#- This list is ordered, any new cluster should be appended at the end.
Tbh. I don't know. The content of this file was copied from the dataplane-cluster-configuration-minikube.yaml. I did not check all the comments when I was working on this.

2022-05-31 06:32 UTC, johannes94 commented on internal/dinosaur/pkg/config/dataplane_cluster_config.go
> +	AvailableDinosaurOperatorVersions []api.DinosaurOperatorVersion `yaml:"available_dinosaur_operator_versions"`
You're right that makes sense. I'm going to change that.

2022-05-31 06:36 UTC, ebensh commented on dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
> +#- This list is ordered, any new cluster should be appended at the end.
I believe this *may* be a way to detect removal of a cluster to trigger deprovisioning and deletion - addition should happen at the end, but **I haven't confirmed this in code**.

2022-05-31 06:39 UTC, ebensh requested changes

2022-05-31 06:39 UTC, ebensh commented on internal/dinosaur/pkg/config/dataplane_cluster_config_test.go
>  	c := ManualCluster{}
I can't add on line 34 but I'd expect the test to verify that the available operator version is indeed 0.1.0

2022-05-31 07:54 UTC, johannes94 commented on internal/dinosaur/pkg/config/dataplane_cluster_config_test.go
>  	c := ManualCluster{}
Added some verification here in last commit.

2022-05-31 07:55 UTC, johannes94 commented on internal/dinosaur/pkg/config/dataplane_cluster_config.go
> +	AvailableDinosaurOperatorVersions []api.DinosaurOperatorVersion `yaml:"available_dinosaur_operator_versions"`
Changed dinosaur occurrences as far as it made sense in context of this PR.

2022-05-31 08:53 UTC, ebensh approved these changes

2022-05-31 09:46 UTC, mtesseract approved these changes

2022-05-31 10:24 UTC, merged

2022-05-31 10:36 UTC, mtesseract commented on internal/dinosaur/pkg/workers/clusters_mgr.go
> +		}
Thanks for the hint!