managed central first proposal for data
stackrox/acs-fleet-manager pull request #74
Opened 2022-05-31 10:52 UTC by johannes94

## Description
Add additional data to configure ManagedCentral's in fleet-manager

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-05-31 11:40 UTC, SimonBaeumer reviewed
Currently we expect that the user can only set a name for the instance from the UI.
All other data is enriched by fleet-manager.

Thus a separation between data sourced by fleet-manager and user makes sense.

**Data from user:**

 - Name
 - Availability Zone / Region (later, we start with `us-east-1` for MVP, EMEA is added later)
 - Additional CAs (later for private PKIs)


**Data from FleetManager:**

 - instance / tenant name
 - TLS certificates
 - Resource limits (for development at first)
 - Subscriptions / Service level
    - Scaling config
    - Resource limits
 - DB configuration for RDS (skip for now, inline comment is okay, add to gaps)
 - DNS name for Central
 - central version
 - deletion timestamp


I would suggest to start with this. Ignoring namespace for now.
After the initial data is implemented and the fleet-shard runtime merged we can start implementing the production configuration implementation.

2022-06-02 07:34 UTC, kovayur commented on internal/dinosaur/pkg/presenters/manageddinosaur.go
> +const defaultCentralRequestMemory = "1Gi"
NIT: combine to a const block?

2022-06-02 07:37 UTC, SimonBaeumer requested changes
Nice!
Some small comments but looks good from my side!

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/api/openapi.yaml
> +          - central-owner1
Why was this changed?

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/api/openapi.yaml
> +                cpu: 1000m
Can you reduce CPU request to 250m and memory to 250Mi? 
This setting would always consume one CPU core for central

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/api/openapi.yaml
> +                  cpu: 500m
Can you reduce this to 250m?

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/api/openapi.yaml
> +                  memory: 500Mi
Can you reduce this to 100Mi?

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
> +	AdditionalCAs []ManagedCentralAllOfSpecAdditionalCAs `json:"additionalCAs,omitempty"`
Let's remove the additionalCA until we need them after MVP.

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/presenters/manageddinosaur.go
> +const defaultCentralRequestMemory = "1Gi"
Use this syntax instead:
```
const (
  defaultCentralRequestMemory = "1Gi"
  defaultCentralRequestCpu = "1000m"
  ...
)
```

2022-06-02 07:37 UTC, SimonBaeumer commented on internal/dinosaur/pkg/api/private/api/openapi.yaml
> +    ManagedCentral_allOf_spec_additionalCAs:
Remove additionalCA

2022-06-02 09:34 UTC, kovayur commented on internal/dinosaur/pkg/api/private/api/openapi.yaml
> +    ManagedCentral_allOf_spec_additionalCAs:
No objections, was just curious.

2022-06-02 09:38 UTC, kovayur approved these changes
Looks good!

2022-06-03 13:50 UTC, SimonBaeumer approved these changes

2022-06-07 09:07 UTC, merged