ROX-13666: Create non-privileged RDS DB user
stackrox/acs-fleet-manager pull request #748
Opened 2023-01-23 10:08 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Evaluated and added CHANGELOG.md entry if required
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-01-23 11:55 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
With a non-privileged account, Central tries to install the `pg_stat_statements` extension but fails.

As a workaround, I'm creating the `central_active` DB right after AWS provisions the DB (see the function above), and I'm using the `rds_superuser` account to install the extension.

We generally don't want to use to use `rds_superuser`, as it's bad practice. 

@dashrews78 @c-du do you have any objections to this workaround? One problem is that hardcoding the DB name (central_active) is fragile.

2023-01-23 12:10 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +		" WITH NOSUPERUSER INHERIT CREATEDB NOREPLICATION VALID UNTIL 'infinity' PASSWORD '"+userPassword+"'")
@dashrews78 @c-du Does Central still need `CREATEDB`, if we create `central_active` before providing the DB to Central?

From glancing at the source code, I think it might still need to create `central_backup` and `central_restore` DBs. Are those actually created in ACSCS? AWS is also taking daily snapshots of our DBs, btw.

2023-01-23 12:18 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +		" WITH NOSUPERUSER INHERIT CREATEDB NOREPLICATION VALID UNTIL 'infinity' PASSWORD '"+userPassword+"'")
It still needs it for upgrade/rollback.  in an upgrade it will create things like `central_previous` and `temp` potentially.  Backup and restore are currently hiddeen for ACSCS

2023-01-23 12:22 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
That particular extension is at the server level and reports on all databases.  So I think if you installed that on the `postgres` database before creating the database and/or `central_active` that may solve the problem.  It will exist when central tries to mess with it upon getting the connection and thus not try to re-enable it.  In theory.

2023-01-23 12:41 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
I tried installing it on `postgres`, but Central was still failing when creating the extension. The way I could get it work was to create `central_active` (with Central as owner) and then installing the extension into `central_active` using the superuser account.

2023-01-23 12:42 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +		" WITH NOSUPERUSER INHERIT CREATEDB NOREPLICATION VALID UNTIL 'infinity' PASSWORD '"+userPassword+"'")
If that is something we want to handle differently for ACSCS in the future we can probably explore that, but for now we need that permission

2023-01-23 12:44 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
we may need a ticket to look at that from a central code perspective on when we do that extension install.  This could cause issues if customers try to us any external installation.

2023-01-23 12:59 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
It would be best if Central does not attempt to install extensions in ACSCS at all. For `pg_stat_statements` we're good (due to `IF NOT EXISTS`, which is also used by Central). But if other extensions are added, they would cause failures in Central (unless they are added via `fleetshard-sync` as well).

2023-01-23 13:22 UTC, vladbologa commented
/test all

2023-01-23 14:19 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
This might require more thought and coordination.  We will have to think through what to do if we need a new extension and it is not installed in the target database for managed services and potentially for other external databases.  We are also going to have to investigate and analyze if we have access to the data in the extension if it was installed more globally.

2023-01-23 19:46 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
I did some more tests, but it seems a user really needs to be a member of the `rds_superuser` role in order to create extensions, except for a small subset of "trusted" extensions:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.Extensions.Trusted

Even if we were to continue using `rds_superuser` in ACSCS, it's still not a guarantee that an extension created by Central on vanilla Postgres would work on RDS. Only some extensions are supported:
https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-13x

Regarding your last point, I found this in the [Postgres docs](https://www.postgresql.org/docs/current/pgstatstatements.html):
> When pg_stat_statements is active, it tracks statistics across all databases of the server. To access and manipulate these statistics, the module provides views pg_stat_statements and pg_stat_statements_info, and the utility functions pg_stat_statements_reset and pg_stat_statements. These are not available globally but can be enabled for a specific database with CREATE EXTENSION pg_stat_statements.

2023-01-23 20:55 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
I took a quick look, and best I can tell we currently are not using those views.  I'm sure there is useful info we may want to include as metrics at some point but until then one could make the argument that we could eliminate that for ACSCS or perhaps put it behind a debug type flag in general.  @c-du @connorgorman thoughts?

2023-01-24 11:06 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
Even if we remove this particular extension creation from Central, we should still decide who's responsible for creating them in general.

I'd argue that on ACSCS the responsibility of installing extensions should fall on `fleetshard-sync`, because it is the one that provisions and manages the DB, and has access to the superuser account. So I don't think it's wrong that `fleetshard-sync` creates the `central_active` DB and installs extensions. This approach would fit also with multi-tenancy, where `fleetshard-sync` would create separate accounts in the same DB for each Central.

2023-01-24 11:12 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
Not going to disagree with that.  It makes a lot of sense, but I worry about the upgrade case considering how it currently works.  What happens when you copy a database that has extensions enabled that you didn't have permissions to enable?  Restore is different for ACSCS so I'm not too worried about that case.

2023-01-24 13:18 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
That's a very good point, I'll have to try that.

2023-01-26 18:49 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
yes I 100% agree with that statement.  I'm not entirely sure how to solve that, however, other than "knowing" that if I add an extension, I need to coordinate.  I'm open to suggestions.

2023-01-27 16:36 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	_, err = db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
An idea would be to have some CI tests in the stackrox repo, that would use a non-root user (ideally a user created using this code from acs-fleet-manager).

2023-01-30 12:37 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +func (r *CentralReconciler) noPrivilegedCentralDBUserExists(ctx context.Context, remoteCentralNamespace string) bool {
rename to `nonPrivilegedCentralDBUserExists`

2023-01-30 14:29 UTC, SimonBaeumer requested changes

2023-01-30 14:29 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbNonPrivilegedUserName = "rhacs_central"
```suggestion
	dbCentralUserName = "rhacs_central"
```

2023-01-30 17:20 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbUserType, exists := secret.Annotations[dbUserTypeAnnotation]
To the first question: legacy Centrals are migrated too, see the line below (if the annotation does not exist, it's assumed that this is a master password, and the new user will be created).

To the second question: in theory it's nil-safe (we always add the managed-by annotation), but I should have checked for nil nevertheless.

2023-01-30 17:28 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +const centralDBName = "central_active"
If / when we have multi-tenancy, we'll have to adapt this code.

I suppose in that case we'll have to create a DB here in `fleetshard-sync`, create a user that can *only* access that DB and not the others, and pass it to Central.

But as long as there's no support for that in Central or ACSCS, I'd leave this as is.

2023-02-02 14:55 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +	return fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=%s",
`AsConnectionStringWithPassword()` is used to connect from `fleetshard-sync`
`AsConnectionString()` is used to create a connection string without the passport, in order to pass it to Central (via the Central CR).

This is why there are two versions of this function. I could unexport `asConnectionStringWithPassword()`, so that it's not mistakenly used outside of this package (and so leaking the password in plaintext in a connection string).

2023-02-03 09:03 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbinit.go
> +const centralDBName = "central_active"
@vladbologa Wouldn't it just adding the UUID to the database names, i.e. `central_active_<UUID>`? It seems like low effort, saving later lots of migration work, no?

2023-02-03 11:14 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +const centralDBName = "central_active"
This is a very good idea, to simplify future migration to multi-tenancy.

But unfortunately I don't think it's low effort because:
- we need to implement support in Central, as a prerequisite
- we need to migrate the databases of legacy Centrals

Should open a new ticket for this.

2023-02-06 09:48 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
This logic can be moved into `ensureCentralDBSecretExists`. If the secret does not exist a new secret is created, thus ensured the secret is there.

In L525 is looks like the previously generated password is read from the cluster again. This can also be omitted if `ensureCentralDBSecretExists` guarantees to persist the secret in k8s.

2023-02-06 09:55 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	if err != nil {
Done.

2023-02-06 09:56 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +func createUser(ctx context.Context, db *sql.DB, userName, userPassword string) error {
Renamed to `createNonPrivilegedUser`

2023-02-06 09:56 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		return false
Done.

2023-02-06 09:57 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbUserType, exists := secret.Annotations[dbUserTypeAnnotation]
Added nil-check.

2023-02-06 09:57 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	if err := r.ensureCentralDBSecretExists(ctx, remoteCentralNamespace); err != nil {
Done.

2023-02-06 09:57 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	err = r.updateCentralDBSecret(ctx, remoteCentralNamespace, dbUserTypeCentral, dbCentralPassword)
Done.

2023-02-06 09:59 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbCentralPassword, err := random.GenerateString(25, random.AlphanumericCharacters)
Done, but `random.GenerateString(25, random.AlphanumericCharacters)` is still duplicated (once for master pass, once for Central pass). Should I make this line into a standalone function?

2023-02-06 10:01 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbinit.go
> +	err = initializeNonPrivilegedUser(ctx, db, userName, userPassword)
Done

2023-02-06 10:01 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbNonPrivilegedUserName = "rhacs_central"
Done

2023-02-06 10:19 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
Consider the following case:
1. the master password is generated and stored in the secret
2. we use the AWS API to create the DB, with this password
3. this operation takes about ~10 minutes, let's assume that fleetshard restarts or the context expires during this time
4. when we reach this point again, if we generate a new password we won't know the DB password anymore (because we already used the previous password to start the DB provisioning)

If I were to move the logic into `ensureCentralDBSecretExists` then there would be situations where the password that we give as parameter would not be stored, which is not a good API in my opinion.

BTW, there's a difference between the logic for the master pass and the one for the central pass:
- master password is stored **once** before everything else, so we don't lock ourselves out of the DB
- central password is stored after everything is done; if storing fails, we still have the master password and can recreate another central password (so this step can be attempted multiple times)

2023-02-06 10:31 UTC, dashrews78 commented on fleetshard/pkg/central/postgres/dbinit.go
> +const centralDBName = "central_active"
FWIW, this is my general thought on how we may handle the multi-tenancy when we get there.

2023-02-07 13:46 UTC, SimonBaeumer requested changes

2023-02-07 13:46 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	}
That makes sense. I think it is not worth to abstract this function given the use-case here.

2023-02-07 13:46 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbCentralPassword, err := random.GenerateString(25, random.AlphanumericCharacters)
Yes, please. The duplication here is the domain logic, the generation of the password itself to avoid.

2023-02-07 14:59 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +	dbCentralPassword, err := random.GenerateString(25, random.AlphanumericCharacters)
Done

2023-02-07 15:14 UTC, SimonBaeumer approved these changes

2023-02-07 15:21 UTC, merged