Remove timeout log messages
stackrox/acs-fleet-manager pull request #779
Opened 2023-01-30 15:40 UTC by SimonBaeumer

## Description
Delete it reconcile timeout log messages. Not required because reconcilers already print multiple log messages to indicate that they are running.
Removed wake up channel because it is not used.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-02-01 09:52 UTC, vladbologa requested changes

2023-02-01 09:52 UTC, vladbologa commented on Makefile
> -deploy/dev-fast: GOOS=linux
is this deleting your prev PR?

2023-02-01 14:18 UTC, SimonBaeumer commented on Makefile
> -deploy/dev-fast: GOOS=linux
Yes, was an accident. Not sure how it happend, maybe I've made a mistake during rebase. 🤔

2023-02-01 14:39 UTC, kurlov approved these changes

2023-02-02 09:19 UTC, vladbologa approved these changes

2023-02-02 09:30 UTC, merged