ROX-15242 - Reduce fleetshard and fleet-manager log noise
stackrox/acs-fleet-manager pull request #785
Opened 2023-02-01 09:43 UTC by SimonBaeumer

## Description

Clean up logs. Added logger to only log if the given integer value had changed.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-02-15 17:19 UTC, vladbologa commented on fleetshard/pkg/runtime/runtime.go
> +		logger.InfoChangedInt32(&reconciledCentralCountCache, "Received central count changed: received %d centrals")
What do you think about also removing the log on line 142? We could move it in reconciler.go, and only print it if the Central needs to be reconciled.

That line probably makes up more than 99% of our fleetshard-sync logs.

2023-02-22 13:28 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +		logger.InfoChangedInt32(&reconciledCentralCountCache, "Received central count changed: received %d centrals")
done

2023-02-22 13:41 UTC, vladbologa requested changes

2023-02-22 13:41 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +
I think logging here will still result in many log messages, should be after line 113 to have effect.

2023-02-22 13:41 UTC, vladbologa commented on fleetshard/pkg/runtime/runtime.go
> +	"github.com/stackrox/acs-fleet-manager/pkg/logger"
please move to the section below

2023-02-22 14:27 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +
And one more thing here, is it ok to log `remoteCentral.Metadata.Name`? It's customer data, and I remember that when I wanted to tag the DB instances with the name, we decided not to do it.

2023-02-22 14:38 UTC, johannes94 commented on fleetshard/pkg/runtime/runtime.go
> +	"github.com/stackrox/acs-fleet-manager/pkg/logger"
+1, usually the formatter should fix that. Don't know why it doesn't.

2023-02-22 14:38 UTC, johannes94 commented on fleetshard/pkg/central/reconciler/reconciler.go
> +
Not sure about if we should remove the name, but adding the ID would be good since this is most important to filter for logs of a specific tenant.

2023-02-22 14:53 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +
The namespace already contains the Id, but it would be better to replace `Namespace` with `Id`.

2023-02-22 16:26 UTC, vladbologa commented on fleetshard/pkg/runtime/runtime.go
> +		logger.InfoChangedInt32(&reconciledCentralCountCache, "Received central count changed: received %d centrals")
This doesn't seem to work as expected, here are some logs from my local machine:

```
I0222 16:18:02.130817       1 runtime.go:126] Received central count changed: received %d centrals0
I0222 16:19:32.236458       1 runtime.go:126] Received central count changed: received %d centrals0
I0222 16:19:32.236553       1 reconciler.go:107] Start reconcile central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:19:32.277767       1 reconciler.go:285] Creating central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:19:32.298116       1 reconciler.go:289] Central rhacs-cfr40h6og40g01q0bb50/test-central-1 created
I0222 16:19:42.247972       1 runtime.go:126] Received central count changed: received %d centrals0
I0222 16:19:42.248036       1 reconciler.go:107] Start reconcile central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:19:42.267968       1 reconciler.go:291] Update central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:19:52.259769       1 runtime.go:126] Received central count changed: received %d centrals0
I0222 16:19:52.259844       1 reconciler.go:107] Start reconcile central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:19:52.285547       1 reconciler.go:291] Update central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:20:02.266983       1 runtime.go:126] Received central count changed: received %d centrals0
I0222 16:20:02.267147       1 reconciler.go:107] Start reconcile central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:20:02.296243       1 reconciler.go:291] Update central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:20:12.277558       1 runtime.go:126] Received central count changed: received %d centrals0
I0222 16:20:12.277622       1 reconciler.go:107] Start reconcile central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:20:12.294873       1 reconciler.go:291] Update central rhacs-cfr40h6og40g01q0bb50/test-central-1
I0222 16:20:22.290589       1 runtime.go:126] Received central count changed: received %d centrals0
```

2023-02-23 16:45 UTC, vladbologa reviewed
Removing my "Request changes" review to not block this PR while on PTO.

2023-02-27 15:02 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +
Convinced. I'll create a follow-up PR to this to keep the changes small.

2023-02-27 15:03 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +		logger.InfoChangedInt32(&reconciledCentralCountCache, "Received central count changed: received %d centrals")
Fixed

2023-02-27 15:25 UTC, SimonBaeumer commented
/retest

2023-02-27 15:26 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +
Follow up PR: https://github.com/stackrox/acs-fleet-manager/pull/856

2023-03-01 14:56 UTC, johannes94 approved these changes
LGTM

2023-03-29 12:45 UTC, SimonBaeumer commented
/retest

2023-04-25 11:09 UTC, merged