Provide docker compose environment for local testing for fleet-manager & fleetshard-sync
stackrox/acs-fleet-manager pull request #79
Opened 2022-06-01 11:31 UTC by mtesseract

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-03 14:13 UTC, SimonBaeumer requested changes
Can you add a README in the `dev/docker-compose` dir with simple commands how to use this setup?

2022-06-03 14:13 UTC, SimonBaeumer commented on Dockerfile
> +
Why was this change necessary?

2022-06-03 14:13 UTC, SimonBaeumer commented on dev/env/docker-compose/config/dataplane-cluster-configuration.yaml
> +  - name: docker-desktop # Uncomment if using docker-desktop
```suggestion
  - name: docker-compose # Uncomment if using docker-desktop
```

2022-06-06 21:50 UTC, mtesseract commented on Dockerfile
> +
With this change in place docker compose can also take care of building images. In the `docker-compose.yaml` the image to use for `fleet-manager` and `fleetshard-sync` is provided in terms of a `Dockerfile`, hence `docker compose`  tries to build the image using `docker build`. But this requires the `Dockerfile` to be self-contained.

Previously `docker build` using our `Dockerfile` simply picked up the two application binaries in the top-level directory (asuming that they are built for the correct target platform!) and included them in the image. This process required the two relevant binaries being built ahead of time using something like `make binary`, this is -- as far as I can tell - incompatible with what `docker compose` requires.

Besides satisfying this requirement for `docker compose` I also think that this approach is generally more reliable since it guarantees that the correct binaries are copied into the image -- good for build reproducibility.

2022-06-07 14:17 UTC, mtesseract commented on dev/env/docker-compose/config/dataplane-cluster-configuration.yaml
> +  - name: docker-desktop # Uncomment if using docker-desktop
changed

2022-06-08 07:28 UTC, SimonBaeumer requested changes

2022-06-08 07:28 UTC, SimonBaeumer commented on Dockerfile
> +RUN go mod download
It is recommended to use `go mod tidy`. This downloads dependencies and removes deps which are not necessary.

```suggestion
RUN go mod tidy
```

2022-06-08 07:28 UTC, SimonBaeumer commented on Dockerfile
> +RUN make clean binary
This might run the targets in parallel.

```
RUN make clean && make binary
```

2022-06-08 07:28 UTC, SimonBaeumer commented on dev/env/docker-compose/README.md
> +Either source `dev/env/.envrc` or use `direnv` for loading this environment automatically.
Can you directly document the recommended behaviour as a list of commands?
It is more convenient to follow the doc with commands to execute and not taking my own decisions whether I should use `source` or `direnv`.

A small comment `# ...` which explains the reason of a command above it is enough.


Example: 

```
# Docker is required to be running

# Stop running postgres instances:
$ make -C $(git rev-parse --show-toplevel) db/teardown

# Set environment
$ cd acs-fleet-manager/env && direnv

# Spin up environment and build
$ docker compose up --build

# To tear down environment run:
$ docker compose down

# To additionally delete the postgres volume run:
$ docker compose down -v
```

2022-06-08 07:32 UTC, mtesseract commented on Dockerfile
> +RUN make clean binary
Yes, but I doubt that this is the desired behaviour in this case. (Potentially) deleting previous build artifacts needs to come strictly before creating the same build artifacts.

2022-06-08 07:37 UTC, mtesseract commented on Dockerfile
> +RUN go mod download
Not an expert on Golang build tools and procedures here, but can you quote a source for this claim?
My sources are:
* (the official Docker manual)[https://docs.docker.com/language/golang/build-images/]
* (Medium article)[https://petomalina.medium.com/using-go-mod-download-to-speed-up-golang-docker-builds-707591336888]
* (Codefresh article)[https://codefresh.io/docs/docs/learn-by-example/golang/golang-hello-world/]
among others.

The worry I am having regarding "go mod tidy" is that it can, as a side-effect, modify `go.sum`, which would render a given repo as dirty. If, as we do in StackRox, image tags are derived from Git revision information, this would produce undesired behaviour, I guess.

2022-06-08 08:07 UTC, mtesseract commented on dev/env/docker-compose/README.md
> +Either source `dev/env/.envrc` or use `direnv` for loading this environment automatically.
Done.

2022-06-09 13:43 UTC, kovayur reviewed
Good job! Left just a few clarifying questions. Looking forward to trying docker-compose in action!

2022-06-09 13:43 UTC, kovayur commented on dev/env/docker-compose/docker-compose.yaml
> +version: "3"
Wouldn't it be more convenient to have this file in the root directory?

2022-06-09 13:43 UTC, kovayur commented on dev/env/docker-compose/config/dataplane-cluster-configuration.yaml
> +---
Can't we reuse the existing config files in the `$GITROOT/config` directory?

2022-06-09 13:57 UTC, SimonBaeumer commented on Dockerfile
> +RUN go mod download
Yeah, a lot of docs point to `go mod download` 

`go mod tidy` ensures that the dependencies match the source. If `go.sum` changed after running `go mod tidy` the build should ideally fail because dependencies are out of date.
In stackrox builds often failed because of `go mod download` because deps were out of sync.

Compare docs between [tidy](https://go.dev/ref/mod#go-mod-tidy) and [download](https://go.dev/ref/mod#go-mod-download).

I can't find the github discussion anymore though on this topic...

2022-06-10 07:50 UTC, SimonBaeumer approved these changes

2022-06-23 14:25 UTC, closed without merging