Add operator install script
stackrox/acs-fleet-manager pull request #806
Opened 2023-02-10 13:11 UTC by SimonBaeumer

## Description
Add operator install script to install and upgrade the operator independently of the setup scripts.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

 - run scripts

2023-02-10 13:21 UTC, vladbologa approved these changes

2023-02-13 08:50 UTC, kovayur requested changes

2023-02-13 08:50 UTC, kovayur commented on dev/env/scripts/bootstrap.sh
> +    ./install_operator.sh
Pls call using the full path, it will not work when I call the bootstrap script from the root folder for example (or using `make`)

2023-02-15 10:16 UTC, SimonBaeumer commented on dev/env/scripts/bootstrap.sh
> +    ./install_operator.sh
The other scripts are called locally too and it works. Removed the `./` though and call it like `apply`.

2023-02-15 10:31 UTC, kovayur approved these changes
LGTM!

2023-02-15 11:00 UTC, merged