ROX-13913: Verify RDS certificates in Postgres connections
stackrox/acs-fleet-manager pull request #827
Opened 2023-02-16 16:18 UTC by vladbologa

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-02-17 07:48 UTC, kovayur reviewed
Thanks @vladbologa, this looks good. Just a couple of remarks.

2023-02-17 07:48 UTC, kovayur commented on Dockerfile
> +ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /usr/local/share/ca-certificates/aws-rds-ca-global-bundle.pem
Either need to copy this line for `standard` or move it to `build` and `COPY --from build <cert-file>` for both `debug` and `standard`.

2023-02-17 07:48 UTC, kovayur commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) asConnectionForFleetshard() string {
Do we need to specify pem here if we run `update-ca-trust` after adding a certificate in the `Dockerfile`?

2023-02-17 07:50 UTC, kovayur commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		additionalCa, err := os.ReadFile(postgres.RDSCertificatePath)
How about caching it?

2023-02-17 09:26 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) asConnectionForFleetshard() string {
I'm not sure, I will try. But I think it's preferable like this, so that only RDS servers are accepted.

2023-02-17 09:27 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		additionalCa, err := os.ReadFile(postgres.RDSCertificatePath)
Makes sense, when there are many Centrals it'll keep reading this file.

2023-02-20 09:34 UTC, SimonBaeumer requested changes

2023-02-20 09:34 UTC, SimonBaeumer commented on Dockerfile
> +ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /rds_ca/aws-rds-ca-global-bundle.pem
Does this call fail when a 404 or 500 is returned?

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +var rdsCertificateData []byte
```suggestion
var (
  once sync.Once
  rdsCertificateData []byte
)
```

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +	rdsCertificatePath = caPath + "aws-rds-ca-global-bundle.pem"
Why so many spaces between the constant definitions?

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) AsConnectionStringForCentral() string {
This is leaky abstraction. The caller of the function is exposed in the method signature. How should someone use this function if they don't use it from Central?
`AsConnectionStringWithCertificateAuth`

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) asConnectionStringForFleetshard() string {
```suggestion
func (c DBConnection) asConnectionStringWithPasswordAuth() string {
```

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +	rdsCertificatePath = caPath + "aws-rds-ca-global-bundle.pem"
Can you add information that this is used to trust AWS RDS instances? (not authentication)

```suggestion
	rdsCertificatePath = caPath + "aws-rds-ca-global-bundle.pem"
```

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +	once.Do(func() {
Certificates changing at runtime are not updated anymore and require a Pod restart to be read.
Is this safe to use here?

2023-02-20 09:34 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			glog.Warningf("Could not read RDS CA bundle: %v", err)
Can you rename the function t o`GetRDSCACertificates`? The error message is more descriptive than the function name.
If you find a better way to not have so many uppercases it would be cool as in my suggestion😆

2023-02-20 09:35 UTC, SimonBaeumer commented on fleetshard/pkg/central/postgres/dbconnection.go
> +var rdsCertificateData []byte
not sure if my suggestion is valid go style

2023-02-20 10:21 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) AsConnectionStringForCentral() string {
"Central" is not the caller of the function. This function generates a connection string that is to be used by Central, and you can't / shouldn't use it for something else (e.g. it includes the path where Central stores its CA certificates in the `sslrootcert` field)

2023-02-20 10:23 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) asConnectionStringForFleetshard() string {
Naming them `AsConnectionStringWithCertificateAuth` / `asConnectionStringWithPasswordAuth` implies to me that one uses passwords, and the other doesn't (which is not true). They both use passwords and certificates, except that in the case of Central we don't include the password (it's shared via a secret), in case of Fleetshard we put it in the connection string (because it's the same process).

2023-02-20 10:27 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +	once.Do(func() {
These certificates cannot change at runtime, they are included in the image so they can only change when we deploy a new fleetshard image.

2023-02-20 10:30 UTC, vladbologa commented on Dockerfile
> +ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /rds_ca/aws-rds-ca-global-bundle.pem
Building of the image fails if this file can't be downloaded.

2023-02-20 10:50 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +			glog.Warningf("Could not read RDS CA bundle: %v", err)
Oh that's how I also wanted to name it, and changed my mind because of all the caps. 😄

2023-02-20 11:20 UTC, vladbologa commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		additionalCa, err := os.ReadFile(postgres.RDSCertificatePath)
Done

2023-02-20 11:20 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +	rdsCertificatePath = caPath + "aws-rds-ca-global-bundle.pem"
Done

2023-02-20 11:21 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +var rdsCertificateData []byte
Done

2023-02-20 11:22 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) AsConnectionStringForCentral() string {
I guess the underlying problem is that I'm hardcoding the path of the `sslrootcert`. If I make the paths configurable I could make these functions more generic like before.

2023-02-20 13:32 UTC, vladbologa commented on fleetshard/pkg/central/postgres/dbconnection.go
> +func (c DBConnection) AsConnectionStringForCentral() string {
Working on cleaning this up a bit

2023-02-22 08:33 UTC, SimonBaeumer approved these changes

2023-02-22 08:59 UTC, merged