Add e2e tests
stackrox/acs-fleet-manager pull request #85
Opened 2022-06-02 14:09 UTC by SimonBaeumer

## Description

Add a simple e2e testing suite to run locally. See `e2e/README.md` for instructions.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Documentation added if necessary
- [ ] CI and all relevant tests are passing

## Test manual

TODO: Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2022-06-03 11:56 UTC, mtesseract requested changes

2022-06-03 11:56 UTC, mtesseract commented on e2e/README.md
> +$ ./scripts/setup-dev-env.sh
I know, not strictly speaking the scope of this PR, but a script with `dev` in its name should probably live somewhere under `dev`.

2022-06-03 11:56 UTC, mtesseract commented on e2e/README.md
> +$ ./scripts/setup-dev-env.sh
This step also requires the dataplane config to be in a specific state. I am getting:

```
E0603 13:18:01.337506   23631 environment.go:119] unable to read configuration files: standalone cluster with ID: 1234567890abcdef1234567890abcdef, and Name minikube not in kubeconfig context
F0603 13:18:01.337521   23631 cmd.go:21] Unable to initialize environment: unable to read configuration files: standalone cluster with ID: 1234567890abcdef1234567890abcdef, and Name minikube not in kubeconfig context
```

2022-06-03 11:56 UTC, mtesseract commented on e2e/README.md
> +$ make fleetshard/build
Looks like this is getting removed in https://github.com/stackrox/acs-fleet-manager/pull/63/files, `make fleetshard-sync` instead should work.

2022-06-03 11:56 UTC, mtesseract commented on e2e/README.md
> +$ OCM_TOKEN=$(ocm token) ./fleetshard-sync
Now requires more settings in the environment.

2022-06-03 11:56 UTC, mtesseract commented on e2e/cleanup.sh
> +docker stop fleet-manager-db && docker rm fleet-manager-db
Just an idea: Since you are hard-coding this to docker, how about then depending on `docker compose` for the setup?
Feels a bit like we are duplicating things here (bootstrapping, storage, cleanup) -- it is all built into docker compose, even image building.

2022-06-03 11:56 UTC, mtesseract commented on e2e/e2e_test.go
> +	var _ = Describe("new", func() {
```suggestion
	var _ = Describe("new central", func() {
```

2022-06-03 11:56 UTC, mtesseract commented on e2e/e2e_test.go
> +			It("should create central in managed cluster", func() {
Why "in managed cluster"? Isn't this more like "in dedicated namespace"?

2022-06-03 11:56 UTC, mtesseract commented on fleetshard/README.md
>  $ make fleetshard/build
See above.

2022-06-03 11:56 UTC, mtesseract commented on fleetshard/README.md
>  $ ./scripts/create-central.sh
Probably also a candidate for moving into `dev/`?

2022-06-03 11:56 UTC, mtesseract commented on fleetshard/pkg/fleetmanager/client.go
>  	return ioutil.ReadAll(resp.Body)
`io.ReadAll`

2022-06-07 15:21 UTC, SimonBaeumer commented on e2e/README.md
> +$ ./scripts/setup-dev-env.sh
> This step also requires the dataplane config to be in a specific state.

Yes, it currently supports only minikube. If we want to support other platforms the config should be configurable.

> I know, not strictly speaking the scope of this PR, but a script with dev in its name should probably live somewhere under dev.

No, all our local scripts are under `scripts`. We can later change it again.

2022-06-07 15:21 UTC, SimonBaeumer commented on e2e/README.md
> +$ make fleetshard/build
done

2022-06-07 15:21 UTC, SimonBaeumer commented on e2e/README.md
> +$ OCM_TOKEN=$(ocm token) ./fleetshard-sync
done

2022-06-07 15:22 UTC, SimonBaeumer commented on e2e/e2e_test.go
> +			It("should create central in managed cluster", func() {
Done

2022-06-07 15:22 UTC, SimonBaeumer commented on fleetshard/README.md
>  $ make fleetshard/build
Done

2022-06-07 15:22 UTC, SimonBaeumer commented on fleetshard/README.md
> +$ OCM_TOKEN=$(ocm token) ./fleetshard-sync
Done

2022-06-07 15:23 UTC, SimonBaeumer commented on fleetshard/README.md
>  $ ./scripts/create-central.sh
No, we have local setup scripts in `scripts/`

2022-06-07 15:24 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/client.go
> +	respBody, err := ioutil.ReadAll(resp.Body)
done

2022-06-07 15:24 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/client.go
> +	fmt.Println(string(all))
removed

2022-06-07 15:25 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/client.go
>  	return ioutil.ReadAll(resp.Body)
removed

2022-06-07 15:52 UTC, mtesseract commented
Integrate it in CI?

2022-06-08 07:23 UTC, johannes94 requested changes
Going to approve as soon as resp.Body comment is addressed.

2022-06-08 07:23 UTC, johannes94 commented on fleetshard/pkg/fleetmanager/client.go
> +	err = c.unmarshalResponse(resp.Body, result)
Looks like resp.Body for all requests made in this file is never closed. Might make sense to add it to the unmarshalResponse function.

2022-06-08 07:57 UTC, SimonBaeumer commented on fleetshard/pkg/fleetmanager/client.go
> +	err = c.unmarshalResponse(resp.Body, result)
Good catch, fixed it

2022-06-08 08:06 UTC, juanrh commented on scripts/setup-dev-env.sh
> +setup_db_container=$?
We can still do this without losing `set -e`

```bash
set -e
success=0
ls asdsa || success=$?
$ echo $success
1
```

2022-06-08 08:21 UTC, johannes94 approved these changes
Looks good.

2022-06-08 08:25 UTC, SimonBaeumer commented on e2e/cleanup.sh
> +docker stop fleet-manager-db && docker rm fleet-manager-db
Good point, added!

2022-06-08 09:41 UTC, merged