ROX-15155: Add ACS Operator installation
stackrox/acs-fleet-manager pull request #871
Opened 2023-03-08 10:12 UTC by kurlov

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-03-08 11:02 UTC, kurlov commented
/test all

2023-03-14 15:30 UTC, johannes94 requested changes

2023-03-14 15:30 UTC, johannes94 commented on fleetshard/pkg/runtime/runtime.go
> +	err := r.upgradeOperator()
Do I understand correctly that this should only be executed once during fleetshard-sync startup?

After we merge this the fleetshard-sync in this version will be deployed to stage and it's going to try install the operator this way. Are we at a point where we want to replace the old way of installing the operator, if so we need to:

- Uninstall the old OLM resources on the stage data plane cluster
- Change the terraforming script for data plane so that it won't reinstall the operator through OLM
- Do the same to prod on the next release

If we don't want that yet, one option would be to put this behind a feature flag (e. g. through an ENV variable) and work on improving it until we are at a point where we want to replace the old installation method.

2023-03-14 15:30 UTC, johannes94 commented on fleetshard/pkg/central/operator/upgrade.go
> +			obj.SetNamespace(operatorNamespace)
I'm not sure about this. I don't think every resource should get a namespace attribute. For example the CRDs that are also part of the referenced helm chart are not namespace scoped.

2023-03-14 15:30 UTC, johannes94 commented on fleetshard/pkg/central/operator/upgrade.go
> +	operatorImage     = "quay.io/rhacs-eng/stackrox-operator:3.73.1"
In case we bring this to prod, I'd like this to be configurable so that we don't have to build a new fleetshard-sync image if we need to change the operator image.

Also current operator version deployed to prod is `3.74.0` so this should be the default.

2023-04-03 08:15 UTC, SimonBaeumer requested changes
Reviewed it, please add a feature flag like @johannes94 suggested.
I am still testing it locally, but need to fix my setup first.

2023-04-03 08:15 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +func (u *ACSOperatorManager) Upgrade(ctx context.Context) error {
Can you refactor this with Malte's implementation in the reconciler?

2023-04-03 08:15 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade_test.go
> +	// check Operator Deployment exists
Can you validate the image reference in the deployment?
This is missing but crucial for the successful deployment.

2023-04-04 04:15 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/platform.stackrox.io_centrals.yaml
> +apiVersion: apiextensions.k8s.io/v1
I think we decided that it's fair trade considering that CRDs don't change often

2023-04-04 04:17 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
> +  name: rhacs-operator-controller-manager
`ServiceAccount` is assigned in the [deployment yaml](https://github.com/stackrox/acs-fleet-manager/blob/c71e5b3947313e5b62add131bda5b341394589ed/fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml#L121)

2023-04-04 14:03 UTC, kurlov commented
/test e2e

2023-04-05 13:40 UTC, johannes94 approved these changes
LGTM, except the RoleBinding, but we can add this if we need it further down the line. I'll approve for now since this is feature flagged anyways.

2023-04-05 14:21 UTC, merged