ROX-16205: Add Operator Version label to Centrals
stackrox/acs-fleet-manager pull request #909
Opened 2023-03-29 13:05 UTC by kurlov

## Description
Add an Operator Version label to Central instances. It will be used for Canary Upgrades.

Additional note: [k8s Label, selector, and annotation conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#label-selector-and-annotation-conventions)

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

2023-04-05 09:51 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		labels := central.ObjectMeta.Labels
Does this need a nil check ? 
```
e.g.
if labels == nil { labels = map[string]string{} } 
```

2023-04-05 09:53 UTC, ludydoo commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +			EgressProxyImage: "registry.redhat.io/openshift4/ose-egress-http-proxy:defaultOperatorVersion-for-test",
was this rename intentional?

2023-04-05 14:01 UTC, SimonBaeumer requested changes
What is the value of this PR? 
It applies the default operator version, but what does it change?
The label should be dervied the `remoteCentral` variable because the version is different for very tenant.
The default version will be applied from fleet-manager to central instances.

2023-04-11 22:01 UTC, kurlov commented on fleetshard/pkg/central/reconciler/reconciler_test.go
> +			EgressProxyImage: "registry.redhat.io/openshift4/ose-egress-http-proxy:defaultOperatorVersion-for-test",
Nope 😄

2023-04-18 07:36 UTC, SimonBaeumer approved these changes
As discussed offline with @kurlov, @ludydoo and @johannes94 we agreed this can be merged as an intermediate step.

2023-04-18 13:17 UTC, merged