ROX-15941: Run multiple operators from FSS
stackrox/acs-fleet-manager pull request #951
Opened 2023-04-13 15:54 UTC by kurlov

## Description
Make FSS able to run multiple ACS Operator versions.
Each operator version has it's own deployment.
The metrics service and ServiceAccount can be shared between multiple versions.
For the sake of simplicity, there are two versions installed on startup before reconciler run.

The next steps are:
- fetch operators versions from FM
- installed desired versions on ticker base manner (similar to centrals reconcile)
- cleanup redundant operator versions

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-04-14 07:28 UTC, kurlov commented
/test e2e

2023-04-14 08:15 UTC, SimonBaeumer requested changes
Nice, the implementation looks overall very good to me!
Some minor changes and the PR can be merged 🚢

2023-04-14 08:15 UTC, SimonBaeumer commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		err := charts.InstallOrUpdateChart(ctx, obj, r.client)
Can you extract this refactoring into a separate PR?

2023-04-14 08:15 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +	return Image{s[0], s[1]}
The images are later received as user input. Can you add validation here?

2023-04-14 08:53 UTC, kurlov commented on fleetshard/pkg/central/charts/charts.go
> +func InstallOrUpdateChart(ctx context.Context, obj *unstructured.Unstructured, client ctrlClient.Client) error {
Yes, I would like to do it in the separate PR

2023-04-14 08:54 UTC, kurlov commented on fleetshard/pkg/runtime/runtime.go
> +	// TODO: delete redundant operators
The versions which no longer needed. There is no ACS instance which needs this version so we should drop such operator

2023-04-14 11:54 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
> +operatorImage:
Would it make sense to keep the `operator` key, so that we could put all configuration for the operator deployment under this key?
For example
```
operator:
  tag: ...
  repository: ...
  resources: ...
  centralLabelSelector: ...
```

2023-04-14 11:59 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade.go
> +		if obj.GetNamespace() == "" && obj.GetKind() != crdKind {
Is this to ensure that all objects have a namespace? If yes, there might be some object kinds that are not namespaced scoped, such as Namespace, ClusterRole, ClusterRoleBinding, PersistentVolume.

2023-04-14 15:37 UTC, kurlov commented on fleetshard/pkg/central/charts/charts.go
> +func InstallOrUpdateChart(ctx context.Context, obj *unstructured.Unstructured, client ctrlClient.Client) error {
probably worth to add in https://github.com/stackrox/acs-fleet-manager/pull/954

2023-04-14 15:37 UTC, kurlov commented on fleetshard/pkg/runtime/runtime.go
> +	for _, image := range operatorImages {
Sounds great!

2023-04-14 15:37 UTC, kurlov commented on fleetshard/pkg/central/reconciler/reconciler.go
> +		err := charts.InstallOrUpdateChart(ctx, obj, r.client)
opened https://github.com/stackrox/acs-fleet-manager/pull/954

2023-04-14 15:38 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +	return Image{s[0], s[1]}
I've change the implementation and added a check if there is no tags at all

2023-04-14 15:39 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +		if obj.GetNamespace() == "" && obj.GetKind() != crdKind {
It's a naive approach. If object does not have namespace then it will be ignored and will take no affect

2023-04-14 15:43 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade.go
> +	}
Should this be an error? e.g. for new clusters where there are no Centrals installed

2023-04-14 15:44 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade.go
> +			glog.V(10).Infof("Updating object %s/%s", obj.GetNamespace(), obj.GetName())
```suggestion
			glog.V(10).Infof("Updating %s %s/%s", obj.GetKind(), obj.GetNamespace(), obj.GetName())
```

2023-04-17 12:42 UTC, SimonBaeumer approved these changes

2023-04-17 12:42 UTC, SimonBaeumer commented on fleetshard/pkg/runtime/runtime.go
> +	// TODO: delete redundant operators
```suggestion
	// TODO: delete unused operator versions
```

2023-04-17 14:20 UTC, johannes94 requested changes
LGTM, except the concern with the repository value.

2023-04-18 06:17 UTC, porridge requested changes
I will look at the code in a moment, but I think this piece of description is not accurate:
> ~Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~

Please accurately document the rollout and rollback procedure from the release engineer's PoV.

2023-04-18 06:36 UTC, porridge requested changes

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
>            image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
Shouldn't this version be a parameter? Or do you assume it will be OK to upgrade this in all running operators when the newest one bumps the version?

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
Overall, what is the plan for keeping this file in sync with the upstream operator releases? Who, when and how copies the changes across the repos?

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ $tag | trunc 29 }}
I think we should abort if `$tag` is longer. Silent truncation means the versions would clash if we cut off the trailing part (which is the part most likely to actually differ between versions).

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +			glog.Errorf("failed to parse image %s", img)
Shouldn't this cause an error to be returned?

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +	val, err := parseRepositoryAndTags(images)
`val` is not terribly informative... how about:
```suggestion
	operatorSettings, err := parseRepositoryAndTags(images)
```

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +		if obj.GetNamespace() == "" && obj.GetKind() != crdKind {
Why single out the CRD kind, then?

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +				return fmt.Errorf("failed to update object %s/%s of type %s %w", key.Namespace, key.Name, obj.GetKind(), err)
Perhaps not in scope of this PR, but the kubectl convention is to separate the resource type and name with a slash (`pods/web-pod-13je7`), rather than namespace and name :thinking:

2023-04-18 06:36 UTC, porridge commented on fleetshard/pkg/runtime/runtime.go
> +	glog.Infof("Install Operators: %s", strings.Join(operatorImages, ", "))
```suggestion
	glog.Infof("Installing Operators: %s", strings.Join(operatorImages, ", "))
```

2023-04-18 16:08 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +	}
Yes, it's about the case when we passed some tags and none of them were able to be parsed and applied

2023-04-18 17:56 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
>            image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
Good point. I added a TODO for this

2023-04-18 17:58 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
CRDs will be downloaded directly from the main stackrox repository.
But I don't have a good solution for deployment. There will be an alert for failed operator start which could help to spot if deployment is incorrect for particular version

2023-04-18 18:17 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ $tag | trunc 29 }}
Added random string to the end of deployment name

2023-04-18 18:17 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +			glog.Errorf("failed to parse image %s", img)
I am not sure, I think it's better to keep parsing instead of canceling whole process

2023-04-18 18:20 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +			s := strings.Split(img, ":")
yes, you are right. I thought that we don't need such feature and all images relieved from FM should have the same repository. But it's not complex to handle different repositories

2023-04-19 08:44 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +		if obj.GetNamespace() == "" && obj.GetKind() != crdKind {
Only CRDs should not have namespace. Deployment, Service and ServiceAccount should be in the operator namespace

2023-04-19 09:25 UTC, ludydoo commented on fleetshard/README.md
> +Fleetshard-sync service is able to manager installation/update
typo
```suggestion
Fleetshard-sync service is able to manage installation/update
```

2023-04-19 09:25 UTC, ludydoo commented on fleetshard/README.md
> +and it effectively represents an operator that is installed on cluster
minor:
```suggestion
and it effectively represents an operator that is installed on the cluster
```

2023-04-19 09:25 UTC, ludydoo commented on fleetshard/README.md
> +1. Redeploy Fleetshard-syn with disabled `FEATURE_FLAG_UPGRADE_OPERATOR_ENABLED` environment variable
minor:
```suggestion
1. Redeploy Fleetshard-sync with `FEATURE_FLAG_UPGRADE_OPERATOR_ENABLED=false` environment variable
```

2023-04-19 09:25 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 }}-{{ randAlphaNum 10 | lower }}
minor:
```suggestion
  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 | lower }}-{{ randAlphaNum 10 | lower }}
```

2023-04-19 09:29 UTC, porridge commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 }}-{{ randAlphaNum 10 | lower }}
Just a quick thought - doesn't using random strings cause all deployments to be replaced on every run? I don't think we want that. Why not just fail on longer tags? I don't think we'll ever need them :thinking:

2023-04-19 09:34 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 }}-{{ randAlphaNum 10 | lower }}
@porridge I agree. Also since the "tag" is our "unique" key to install operator versions, we don't need a random suffix

2023-04-19 11:39 UTC, johannes94 commented on fleetshard/pkg/central/operator/upgrade.go
> +			s := strings.Split(img, ":")
Ok, I think we'll need it to be able to switch between downstream/upstream images. Would you mind adding it in this PR or are you going to create a follow up PR. If so please add a comment so that we don't forgot about this.

2023-04-19 13:57 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +			s := strings.Split(img, ":")
It's added, now we can use operators from different registries

2023-04-19 14:26 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 }}-{{ randAlphaNum 10 | lower }}
I've changed it in a way that long tags will be ignored. My only concern is that we probably should not return an error if there is one too long tag version but instead keep parsing the next image. I am not 100% sure about it though.

Let's assume that we have received two operator images for deployment. One is fine and another is too long to be the suffix for deployment. Should we cancel both deployment or only one with long version?

2023-04-19 14:36 UTC, johannes94 approved these changes

2023-04-19 14:36 UTC, johannes94 commented on fleetshard/pkg/central/operator/upgrade.go
> +			s := strings.Split(img, ":")
I'd suggest to add a check that there actually are 2 elements in the slice after you run strings.Split() before accessing the array (otherwise we might get a panic if the string is malformed). This usually won't happen but better safe than sorry. I'll approve and leave it to you if you want to add this.

2023-04-19 15:52 UTC, porridge commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 }}-{{ randAlphaNum 10 | lower }}
I don't think we should be silently ignoring requests to install a problematic operator. These cases always make me think of a compiler which just ignores the statements that it didn't understand, because it wants to be robust and produce a program that works "mostly" :-)

2023-04-20 08:51 UTC, porridge requested changes

2023-04-20 08:51 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +			glog.V(10).Infof("Updating %s/%s", obj.GetKind(), obj.GetName())
Let's keep the namespace in the message, it might be extremely useful for debugging. Similar below.

2023-04-20 08:51 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +				glog.Errorf("tag version %s contains more than %d characters and cannot be used as a deployment suffix", tag, maxOperatorDeploymentSuffixLength)
```suggestion
				glog.Errorf("Tag version %s contains more than %d characters and cannot be used as a deployment suffix.", tag, maxOperatorDeploymentSuffixLength)
```

2023-04-20 08:51 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +			glog.Errorf("failed to parse image %s", img)
I don't think we should be silently discarding malformed image specs. Better to fail early and loud (but perhaps collect all errors from the parsing and return them together).

2023-04-20 08:51 UTC, porridge commented on fleetshard/pkg/runtime/runtime.go
>  		return fmt.Errorf("operator upgrade: %w", err)
```suggestion
		return fmt.Errorf("ensuring initial operator installation failed: %w", err)
```

2023-04-20 08:51 UTC, porridge commented on fleetshard/README.md
> +In Openshift console go to `Operators -> OperatorHub -> Advanced Cluster Security for Kubernetes`
Isn't this something that the terraforming helm chart should be doing?
Speaking of this, shouldn't this PR also remove the `acs-operator.yaml` from that chart? Otherwise there will be a conflict on rollout, no?

2023-04-20 20:17 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +  name: rhacs-operator-controller-manager-{{ .tag | trunc 10 }}-{{ randAlphaNum 10 | lower }}
I added fail fast on parsing images

2023-04-20 20:17 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +func parseOperatorImages(images []string) ([]chartutil.Values, error) {
Sounds nice! Implemented parsing in a way that it ignores duplicates

2023-04-20 20:18 UTC, kurlov commented on fleetshard/README.md
> +2. Delete existing ACS Operator deployment(s)
Good point

2023-04-20 20:22 UTC, kurlov commented on fleetshard/README.md
> +In Openshift console go to `Operators -> OperatorHub -> Advanced Cluster Security for Kubernetes`
I aded an alternative approach with helm chart.
I also added a TODO to disable operator subscription installation. There is a feature flag so we should remove `acs-operator.yaml` only when `FEATURE_FLAG_UPGRADE_OPERATOR_ENABLED` is turned on. That's clumsy 😞

2023-04-21 07:14 UTC, porridge requested changes

2023-04-21 07:14 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
> +## TODO disable operator installation when FSS runs with FEATURE_FLAG_UPGRADE_OPERATOR_ENABLED=true
Can you file a task for the flag flip and change the format to `TODO(ROX-NNNN): `? Also in other such places.

2023-04-21 07:14 UTC, porridge commented on fleetshard/README.md
> +2. Delete the Operator’s ClusterServiceVersion.
There is also the `OperatorGroup`. Perhaps just advise setting `acsOperator.enabled` to `false`? But now that you pointed out this functionality is behind a feature flag, it's OK to delay the rollout/rollback considerations to the PR that flips the flag.

2023-04-21 07:14 UTC, porridge commented on fleetshard/README.md
> +In Openshift console go to `Operators -> OperatorHub -> Advanced Cluster Security for Kubernetes`
Um, I don't think a simple `helm template -s templates/acs-operator.yaml --values values.yaml` will work. We depend on the values `--set` by the terraforming script, so I would just advise to re-terraform with `acsOperator.enabled`.

2023-04-21 07:14 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +			glog.V(10).Infof("Updating %s/%s", obj.GetKind(), obj.GetName())
> Similar below.

The cases below were not addressed AFAICT?

2023-04-21 07:14 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +		if obj.GetNamespace() == "" && obj.GetKind() != crdKind {
So what's up with this one?

2023-04-21 14:38 UTC, kurlov commented on fleetshard/README.md
> +In Openshift console go to `Operators -> OperatorHub -> Advanced Cluster Security for Kubernetes`
Added re-terraform step. `acsOperator.enabled` is enabled by default

2023-04-21 14:39 UTC, kurlov commented on dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
> +## TODO disable operator installation when FSS runs with FEATURE_FLAG_UPGRADE_OPERATOR_ENABLED=true
I think we should keep `acs-operator.yaml` for some time after enabling FSS operator installation. So I added two TODOs. One is for disabling operator installation in terraform script. Another is to drop `acs-operator.yaml` completely

2023-04-21 14:42 UTC, kurlov commented on fleetshard/README.md
> +2. Delete the Operator’s ClusterServiceVersion.
`OperatorGroup` looks generic. I am not sure we should delete it. Also, OLM documentation for removing operator does not mention `OperatorGroup` neither

2023-04-25 09:23 UTC, porridge requested changes
I think we're getting there!

2023-04-25 09:23 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
> +## TODO ROX-16646: drop acs-operator.yaml template
```suggestion
## TODO(ROX-16646): drop acs-operator.yaml template
```

2023-04-25 09:23 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
> +# TODO ROX-16645: set acsOperator.enabled to false
```suggestion
# TODO(ROX-16645): set acsOperator.enabled to false
```

2023-04-25 09:23 UTC, porridge commented on dp-terraform/helm/rhacs-terraform/test.sh
> +# TODO ROX-16645: set acsOperator.enabled to false
```suggestion
# TODO(ROX-16645): set acsOperator.enabled to false
```

2023-04-25 09:23 UTC, porridge commented on fleetshard/README.md
> +2. Delete the Operator’s ClusterServiceVersion.
Not sure what you mean by "generic"... This is an `OperatorGroup` specific to our installation of the ACS operator via OLM. If we are getting rid of the `Subscription` then we absolutely should also clean up the `OperatorGroup`.

2023-04-25 09:23 UTC, porridge commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +              value: {{ $.Values.operator.centralLabelSelector }}
I must be missing something... we're deploying multiple controllers but they all share the same central label selector? :thinking:
Also, I don't see it being set anywhere. Is this dead code?

2023-04-25 09:23 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +	crdKind           = "CustomResourceDefinition"
Delete unused const?

2023-04-25 09:23 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +	maxOperatorDeploymentSuffixLength = 29
I'm a little concerned that if someone changes the prefix length in the helm chart, they will not know to update this magic number here. How about passing the whole name from go code into the chart instead?

2023-04-25 09:23 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +			tag := strs[1]
```suggestion
			repo, tag := strs[0], strs[1]
```
Then using `repo` below instead of `strs[0]` is a bit neater.

2023-04-25 09:23 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +		if strings.Contains(img, ":") {
It would be a bit more idiomatic to:
```suggestion
		if !strings.Contains(img, ":") {
					return nil, fmt.Errorf("failed to parse image %s", img)
		}
```
and de-dent the other branch. You might even be able to drop this in favor of just the `Split` call which should DTRT in case of missing ":"?

2023-04-25 09:29 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +              value: {{ $.Values.operator.centralLabelSelector }}
This probably needs to be something like
```suggestion
              value: "rhacs.redhat.com/version={{ .tag | lower }}"
```

2023-04-25 09:34 UTC, ludydoo reviewed
Just as a general question:

I see that you modified the helm chart so that we install multiple operators from the same helm release. Did you consider that each operator could also be its own helm release?

I'm wondering what would be the pros and cons of both approaches. 

Approach 1 (this PR)
- Fleetshard sync aggregates all desired installed operator versions
- Passes this list to the helm values in the `.operator.images`
- Helms installs multiple operator deployments from the same helm release through a loop

Approach 2
- Fleetshard sync aggregates all desired installed operator versions
- Would create 1 helm release for each operator version
- Helm installs 1 operator deployment for each helm release


Approach 1 Pros: 
- Simpler logic
- Probably that helm would remove superfluous versions itself
- Can use shared resources (e.g. metrics service?)

Approach 1 Cons:
- Not as configurable as 1 operator per release
- We are more coupled between operator charts of different versions. 

Approach 2 Pros:
- Each operator can be configured, e.g. resources more easily, RBAC, etc. 
- Each operator installation is "independent" (its own helm release). Less coupling

Approach 2 Cons:
- More complex logic to sync/reconcile the operators to update, add, delete

thoughs @stackrox/draco  ?

2023-04-25 13:23 UTC, SimonBaeumer commented on fleetshard/pkg/central/operator/upgrade.go
> +	maxOperatorDeploymentSuffixLength = 29
This is a hard kubernetes label. Ideally the Fleet-Manager API forbids image names >29characters. If this limit is not enforced on fleetshard, fleetshard cannot apply the Helm chart.

2023-04-25 13:35 UTC, SimonBaeumer commented
@ludydoo The first implementation in @kurlov PR was installing it with custom Helm installations for each version. After a discussion it was changed to the current approach for simplicity for the cons you've listed in "Approach 2 Cons":

> More complex logic to sync/reconcile the operators to update, add, delete

I prefer Approach 1 more because only one Helm chart release is applied which feels more natural and causes less side-effects, i.e. accidental overwrites of resources because they are applied multiple times.
Changing the operator installation is relatively easy later in production because it does not affect the SLA.
I am suggesting moving on with the one Helm chart implementation.

2023-04-25 13:40 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +              value: {{ $.Values.operator.centralLabelSelector }}
or 
```suggestion
              value: {{ substr 0 64 (lower (printf "rhacs.redhat.com/version=" $.Values.operator.centralLabelSelector)) }}
```

2023-04-25 13:48 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +              value: {{ $.Values.operator.centralLabelSelector }}
@porridge I added this bit (CENTRAL_LABEL_SELECTOR) a few weeks ago, as I assumed that there would be 1 helm release per operator. But as @SimonBaeumer explained, it was actually decided to use 1 helm release for all operators.

2023-04-25 13:51 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade.go
> +			if _, used := uniqueTags[tag]; !used {
would that mean that the operator cannot install two images from different repositories with the same tag ? Why not just check the uniqueness based on the repository + tag instead ?

2023-04-25 14:00 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade.go
> +	maxOperatorDeploymentSuffixLength = 29
Perhaps we could consider
- having fleetshard sync compute the suffix, and pass it as an additional parameter in the `images`. eg. `images: [{repository: foo, tag: bar, suffix: foobar}]`. 
- using a hash of the repository + tag in the deployment suffix, so that we can install operators from different repositories that have the same tag. 
- creating a distinct namespace per operator `operator-<repository>-<version>`

2023-04-25 14:05 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade_test.go
> +		"fail if image does contain colon": {
Should this be supported ? 

```suggestion
		"should accept images from multiple repositories with the same tag": {
			images: []string{"repo1:tag","repo1:tag"},
			expected: []map[string]string{
				{"repository":"repo1", "tag": "tag"},
				{"repository":"repo2", "tag": "tag"},
			},
		},
		"fail if image does contain colon": {
```

2023-04-25 14:08 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +            {{- if $.Values.operator.centralLabelSelector -}}
```suggestion
            {{- if $.Values.operator.centralLabelSelector -}}
```

2023-04-25 14:08 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
>              {{- end }}
```suggestion
            {{- end }}
```

2023-04-27 14:25 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +	maxOperatorDeploymentSuffixLength = 29
I like the idea to pass full name from FSS.

2023-04-27 14:26 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +		if strings.Contains(img, ":") {
I like it

2023-04-27 14:27 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +			if _, used := uniqueTags[tag]; !used {
You are right, I've changed the implementation

2023-04-27 14:31 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
>  operator:
Not sure about this, but consider renaming `images` to `operators`, or `deployments` such as 
```
deployments:
- operator:
    image:
      repository: foo
      tag: bar
    resources: {}
  kubeProxy:
    resources: {}
 ...
```

2023-04-28 07:40 UTC, kurlov commented on fleetshard/README.md
> +2. Delete the Operator’s ClusterServiceVersion.
I was wrong. I thought that OperatorGroup is shared between different operators, but it's not and it's safe to delete it. I've added instructions about it

2023-04-28 07:41 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
>  operator:
I agree, but I would prefer to do it in the separate PR where more fields will be added

2023-04-28 08:03 UTC, ludydoo commented on fleetshard/pkg/central/operator/upgrade.go
> +			uniqueTags[repo+tag] = true
This is minor, but consider
- Renaming `uniqueTags` to `uniqueImages` or something similar, as this suggests that it only holds `tags`.
- very minor: `uniqueTags := map[string]struct{}` rather than `uniqueTags := map[string]bool`

2023-04-28 08:04 UTC, ludydoo commented on fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
> +            {{- if $.Values.operator.centralLabelSelector -}}
I think this still needs to be removed

2023-04-28 10:33 UTC, porridge approved these changes
LGTM overall, some nitpicks inline and +1 to those from @ludydoo

2023-04-28 10:33 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +			return nil, fmt.Errorf("failed to parse image %s", img)
```suggestion
			return nil, fmt.Errorf("failed to parse image %q", img)
```
similarly below

2023-04-28 10:33 UTC, porridge commented on fleetshard/pkg/central/operator/upgrade.go
> +		if len(operatorDeploymentPrefix+"-"+tag) > maxOperatorDeploymentNameLength {
Nit: you're replicating the concatenation that also happens in the chart. It would be more robust to just pass the concatenated name to the chart, as it makes it impossible for these two operations ever get out of sync and cause trouble.

2023-04-28 14:22 UTC, kurlov commented on fleetshard/pkg/central/operator/upgrade.go
> +			uniqueTags[repo+tag] = true
Renamed, but `bool` is used because `true` is  inserted for every unique image

2023-04-28 14:33 UTC, kurlov commented on fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
> +  deploymentPrefix: rhacs-operator-controller-manager
I dropped `-controller` part

2023-04-28 16:43 UTC, kurlov commented
/test e2e

2023-04-28 21:57 UTC, merged