ROX-13692: create final snapshot for tenant db
stackrox/acs-fleet-manager pull request #994
Opened 2023-04-27 13:26 UTC by johannes94

## Description
This PR changes the central tenant DB deletion for RDS so that it always creates a final snapshot this is required in order to restore the tenant in case it has been deleted accidentally by a customer, an engineer or an error in the code.

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary

## Test manual

Adding test case and running rds tests locally and in CI.

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-04-28 10:24 UTC, johannes94 commented
/retest

2023-04-28 11:06 UTC, kovayur reviewed
Do we have any retention rules for the final snapshot?

2023-04-28 11:06 UTC, kovayur approved these changes

2023-05-02 09:16 UTC, vladbologa requested changes

2023-05-02 09:18 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
>  		// TODO(ROX-13692): do not skip taking a final DB snapshot
there's also another TODO that needs to be removed at line 169

2023-05-02 09:45 UTC, vladbologa requested changes

2023-05-02 09:45 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	snapshotExists, err := waitForFinalSnapshotToExist(deleteCtx, rdsClient, clusterID)
I think the test is leaking the final snapshots, am I right?

2023-05-02 09:45 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> -		// exit early if cluster is marked as deleting
This code was added to avoid CI flakes, see:
https://github.com/stackrox/acs-fleet-manager/pull/838

Deleting a DB occasionally takes a very long time, and it doesn't bring much benefit to wait (we're basically testing AWS, not our code).

But if this is really needed to check the snapshots, we'll have to increase the timeouts for this test.

2023-05-02 09:45 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +func waitForFinalSnapshotToExist(ctx context.Context, rdsClient *RDS, clusterID string) (bool, error) {
Could this be called before `waitForClusterToBeDeleted`?

Doesn't AWS first create the snapshot and then delete the cluster? If so, we could reverse the order, and also not wait for the cluster to be completely deleted.

2023-05-02 11:13 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
>  		// TODO(ROX-13692): do not skip taking a final DB snapshot
Thanks, removed the TODOs.

2023-05-02 11:15 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	snapshotExists, err := waitForFinalSnapshotToExist(deleteCtx, rdsClient, clusterID)
It is, I though about a scheduled job for in Github Actions that queries RDS and deletes `*-final` snapshots after a retention period. This job could also cleanup the DBs created in this test, or I could add a delete to this implementation. WDYTH?

2023-05-02 11:16 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> -		// exit early if cluster is marked as deleting
The snapshot is not created until a few seconds after the cluster is no longer listed in the RDS API. So unfortunately this is necessary to check that snapshots are created.

2023-05-02 11:17 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +func waitForFinalSnapshotToExist(ctx context.Context, rdsClient *RDS, clusterID string) (bool, error) {
No AWS first deletes the cluster, a few seconds after it disappears from the cluster list the snapshot is listed.

2023-05-02 11:18 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> -		// exit early if cluster is marked as deleting
Which timeout setting are you referring to?

2023-05-02 11:33 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	snapshotExists, err := waitForFinalSnapshotToExist(deleteCtx, rdsClient, clusterID)
I'd also delete them here, even if we have the GHA job. There's no reason to pay for storage for all these snapshots.

2023-05-02 11:46 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +	snapshotExists, err := waitForFinalSnapshotToExist(deleteCtx, rdsClient, clusterID)
Added a defer call to try and delete the snapshot.

2023-05-02 12:04 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> -		// exit early if cluster is marked as deleting
There are several, and we need to increase them all (I'd suggest doubling the values): 

- `awsTimeoutMinutes = 15` in `rds_test.go:20`
- `-timeout 30m` in `Makefile:329`
- `timeout-minutes: 35` in the `rds.yaml:70`

Anyway if we do this, we'll have another long running (and possibly still flaky) test in addition to the E2E one.

2023-05-02 14:18 UTC, johannes94 commented
@kovayur @vladbologa Follow up PR with github action to cleanup final snapshots: https://github.com/stackrox/acs-fleet-manager-aws-config/pull/77

2023-05-02 14:24 UTC, johannes94 commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> -		// exit early if cluster is marked as deleting
Incremented all timeouts by 15 minutes. During my tests in this PR I noticed no failures because of timeouts. Nevertheless I increased it by 15 minutes because at some point the timeout was very close to actually trigger.

2023-05-02 15:48 UTC, vladbologa commented
/test e2e

2023-05-02 16:12 UTC, vladbologa approved these changes

2023-05-02 16:12 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
> +				DBClusterSnapshotIdentifier: aws.String(fmt.Sprintf("%s-%s", clusterID, "final")),
```suggestion
				DBClusterSnapshotIdentifier: getFinalSnapshotID(clusterID),
```

2023-05-02 16:12 UTC, vladbologa commented on fleetshard/pkg/central/cloudprovider/awsclient/rds.go
> +	if !skipFinalSnapshot {
Nit: I think we can just remove this `skipFinalSnapshot` parameter completely.

2023-05-02 17:55 UTC, vladbologa commented
/test e2e

2023-05-03 08:59 UTC, vladbologa approved these changes

2023-05-04 05:35 UTC, merged