Add admin API client
stackrox/acs-fleet-manager pull request #998
Opened 2023-04-28 09:55 UTC by SimonBaeumer

## Description

## Checklist (Definition of Done)

- [ ] Unit and integration tests added
- [ ] Added test description under `Test manual`
- [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)
- [ ] CI and all relevant tests are passing
- [ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`
- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.
- [ ] Add secret to app-interface Vault or Secrets Manager if necessary

## Test manual

**TODO:** Add manual testing efforts

```
# To run tests locally run:
make db/teardown db/setup db/migrate
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> OCM_ENV=development
make verify lint binary test test/integration
```

2023-05-03 20:53 UTC, kurlov approved these changes
Looks great! Just few nitpicks which totally fine to ignore

2023-05-03 20:53 UTC, kurlov commented on internal/dinosaur/pkg/cmd/admin/centrals/cmd.go
> +	apiErrorMsg = "%s Admin Central failed: To fix this ensure you are authenticated, fleet-manager endpoint is configured and reachable. Status Code: %s."
Nitpicking:
- let;'s use `%q` for command name to highlight that it's a name
- should Admin be lowercase?

2023-05-03 20:53 UTC, kurlov commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +	staticTokenEnvVar           = "STATIC_TOKEN"
I think it's better to reuse const from `auth_static_token.go` to avoid potential mismatch in the future
https://github.com/stackrox/acs-fleet-manager/blob/fc0f2be99a1d2929606cf984754fa2e857acb7cf/pkg/client/fleetmanager/auth_static_token.go#L10

2023-05-04 07:46 UTC, SimonBaeumer commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +	staticTokenEnvVar           = "STATIC_TOKEN"
This constant does not fit here because it describes the name of the authentication method and not the env variable's name.
Nevertheless the constant can be used for the initialization of the clients to reduce duplicate code. 
The environment variable names are hardcoded in struct tags and only accessible via reflection.

2023-05-04 10:55 UTC, johannes94 requested changes

2023-05-04 10:55 UTC, johannes94 commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +// AuthenticatedClientWithStaticToken returns a rest ocmClient to the fleet-manager using a static token.
```suggestion
// AuthenticatedClientWithStaticToken returns a rest client for fleet-manager API using a static OCM token for authentication.
```

I'm still struggling with calling this an ocmClient. In my opinion OCM is an API/CLI tool we depend on. If something is called ocmClient, I expect it to have the sole purpose of helping me communicate with the OCM API. But this is returning a client for fleet-manager API with a preconfigured `STATIC_TOKEN` that should be set to a valid static token for ocm.

2023-05-04 10:55 UTC, johannes94 commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +	if fleetManagerEndpoint == defaultFleetManagerEndpoint {
I don't think we should have this in the code base, because it seems to be an error that only occured on you local system setup.

2023-05-04 10:55 UTC, johannes94 commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +// AuthenticatedClientWithOCM returns a rest ocmClient to the fleet-manager and receives the OCM refresh token.
Same as stated above, I wouldn't call this an ocmClient. It's a fleet-manager client using OCM to obtain a valid authentication token from OCM using an OCM refresh token

2023-05-08 11:57 UTC, SimonBaeumer commented on internal/dinosaur/pkg/cmd/admin/centrals/cmd.go
> +	apiErrorMsg = "%s Admin Central failed: To fix this ensure you are authenticated, fleet-manager endpoint is configured and reachable. Status Code: %s."
Changed admin to lower case.

> let's use %q for command name to highlight that it's a name

I don't think so, %q is used whenever a value can be empty to indicate that something is variable. In this case it is a static word templated.

2023-05-08 11:58 UTC, SimonBaeumer commented on internal/dinosaur/pkg/cmd/admin/centrals/list.go
> +func NewListCommand() *cobra.Command {
No hard opinion. Your suggestion is more readable, used it.

2023-05-08 11:58 UTC, SimonBaeumer commented on internal/dinosaur/pkg/cmd/admin/centrals/update.go
> +func NewUpdateCommand() *cobra.Command {
removed the upgrade command from this PR.

2023-05-08 11:58 UTC, SimonBaeumer commented on internal/dinosaur/pkg/cmd/admin/centrals/update.go
> +package centrals
removed the upgrade command from this PR.

2023-05-08 12:47 UTC, SimonBaeumer commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +// AuthenticatedClientWithOCM returns a rest ocmClient to the fleet-manager and receives the OCM refresh token.
renamed

2023-05-08 12:52 UTC, johannes94 commented on internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
> +	if fleetManagerEndpoint == defaultFleetManagerEndpoint {
For me it works with following setup:
```
# run local fleet-manager in a local shell
./fleet-manager serve

# run the CLI command as fast as possible in another shell
OCM_TOKEN=$(ocm token --refresh) ./fleet-manager central create --name=test1 --region=standalone --provider=standalone

# same for admin commands
RHOAS_TOKEN=$(rhoas authtoken) ./fleet-manager admin centrals list
```

2023-05-08 13:15 UTC, johannes94 requested changes
Good work 👍 just two more things to consider from my side:

- removing the 5 sec sleep before merging or make it not default
- `admin centrals` for admin CLI command vs `central` for non-admin, I'd prefer plural for both

2023-05-08 16:51 UTC, merged